### ISSUE TITLE
v1.2.0 released, Changelog still talking about 1.1.3

### ISSUE THREAD

**Issue by rubroboletus** [kubernetes-sigs/aws-ebs-csi-driver#1000]
**Is your feature request related to a problem?/Why is this needed**
I'm always frustrated when new release appears, mentions Changelog for list of changes and in Changelog is ZERO about that version. Is it possible to really list changes before making release?

/feature

**Describe the solution you'd like in detail**
Is it possible to really list changes before making release?

**Describe alternatives you've considered**
Put changes to Releases page when making a release.

**Comment by AndyXiangLi** [comment]
Hi @rubroboletus, we understand that. Release changelog is available in the release branch before the image build/publish (branch release-1.2 in this case). And once image build/publish completed, we will merge the changelog back to master branch. As the image build/publish may take hours, it may introduce confusion during this gap.
