### ISSUE TITLE
Documentation discrepancies between github.com and kubernetes.io

### ISSUE THREAD

**Issue by sebastien-rosset** [kubernetes-sigs/aws-ebs-csi-driver#1002]
**Is your feature request related to a problem?/Why is this needed**

The documentation for the EBS CSI provider has discrepancies between the two locations below:
1. The K8s storage class doc: https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs 
1. This aws-ebs-csi-driver github repo: https://github.com/kubernetes-sigs/aws-ebs-csi-driver#createvolume-parameters

Documentation Issues at https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs:
1. The "gp3" type is not documented
2. The default type is "gp2", versus "gp3" in the https://github.com/kubernetes-sigs/aws-ebs-csi-driver#createvolume-parameters. Presumably this depends on the version of the CSI driver, but the version dependency is not documented.
3. There is no documented default value for the "encrypted" parameter.
4. The "throughput" parameter is not documented.
5. The "iops" parameter is not documented.
6. The "allowAutoIOPSPerGBIncrease" parameter is not documented.

Documentation Issues at https://github.com/kubernetes-sigs/aws-ebs-csi-driver#createvolume-parameters:
1. There is no documented default value for the "encrypted" parameter.
2. Unlike https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs, it's not clear whether the expected value is a string or boolean. is expected here, i.e. "true", not true.

**Describe the solution you'd like in detail**
Ensure the docs at https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs  and https://github.com/kubernetes-sigs/aws-ebs-csi-driver#createvolume-parameters are consistent.

Since it may be difficult to keep these two sites in sync, it might be helpful to add a cross-link from https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs to https://github.com/kubernetes-sigs/aws-ebs-csi-driver#createvolume-parameters.

For the "encrypted" parameter, AFAIK, the default value depends on the EBS encryption settings in EC2: *Set the default encryption status of all new EBS volumes and copies of snapshots created in your account.*

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by wongma7** [comment]
https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs is not documenting the CSI driver, it's documenting the "in-tree" driver whose code is embedded in kubernetes at https://github.com/kubernetes/kubernetes/tree/master/pkg/volume/awsebs. 

The storageclass parameters are not 100% compatible and there are no plans to add parameters that exist in the CSI one back in to the in-tree one, on the contrary the plan is to migrate everyone using the in-tree one (kubernetes.io/aws-ebs) to use the CSI one (ebs.csi.aws.com) https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/examples/kubernetes/dynamic-provisioning/specs/storageclass.yaml#L5.

Check out this blog post https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-csi-migration-beta/ for more details.

I do think the official docs could be clearer about this, in fact they seem to avoid mentioning the relationship between the in-tree and CSI drivers, and CSI Migration. With exception of vsphere section that says "In-tree provisioners are deprecated. For more information on the CSI provisioner, see Kubernetes vSphere CSI Driver and vSphereVolume CSI migration." which doesn't explain what "in-tree provisioner" is.

So IMO you are correct that at least we should link to this repo from the official docs and explain the relationship.
