### ISSUE TITLE
china arm 

### ISSUE THREAD

**Issue by DevOpserzhao** [kubernetes-sigs/aws-ebs-csi-driver#1009]
/kind bug

**What happened?**
 Failed to pull image "961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/aws-ebs-csi-driver:v1.2.0": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

 cat kustomization.yaml 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base
images:
  - name: k8s.gcr.io/provider-aws/aws-ebs-csi-driver
    newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/aws-ebs-csi-driver
    newTag: v1.2.0
  - name: k8s.gcr.io/sig-storage/csi-provisioner
    newName: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    newTag: v2.1.1-eks-1-18-3
  - name: k8s.gcr.io/sig-storage/csi-attacher
    newName: public.ecr.aws/eks-distro/kubernetes-csi/external-attacher
    newTag: v3.1.0-eks-1-18-3
  - name: k8s.gcr.io/sig-storage/livenessprobe
    newName: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
    newTag: v2.2.0-eks-1-18-3
  - name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    newName: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
    newTag: v2.1.0-eks-1-18-3

**Comment by DevOpserzhao** [comment]
please help me


 Failed to pull image "961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/aws-ebs-csi-driver:v1.2.0": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by AndyXiangLi** [comment]
Hi @DevOpserzhao 
For v1.20 we don't have arm ecr image. Totally understand the inconvenience and we will build arm ecr image start from v1.2.1 
Meantime, you can use the image `k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.2.0` which support arm.
