### ISSUE TITLE
Raw Block Volume Support

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#101]
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#raw-block-volume-support

**Comment by bertinatto** [comment]
Not supported by external provisioner yet: https://github.com/kubernetes-csi/external-provisioner/pull/135

**Comment by bertinatto** [comment]
PR above has been merged recently, so we can start working on this.
