### ISSUE TITLE
: could not create volume in EC2: WebIdentityErr: failed to retrieve credentials caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity           

### ISSUE THREAD

**Issue by DevOpserzhao** [kubernetes-sigs/aws-ebs-csi-driver#1010]
/kind bug

**What happened?**
: could not create volume in EC2: WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
          status code: 403, request id: 2550e4a3-f66a-4a6c-8080-47a7787e8bd3

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:
Cannot create pvc error

**Environment**
china cn-northwest-1

- Kubernetes version (use `kubectl version`):
 kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:35:50Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-8be107", GitCommit:"8be107e517a77bde856aced857f3428e4f344969", GitTreeState:"clean", BuildDate:"2021-06-12T03:14:13Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

- Driver version:

k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.2.0

**Comment by krmichel** [comment]
/remove-kind bug
/kind support

Are you using IAM roles for service accounts?  If so, is your assume role policy configured correctly?

**Comment by AndyXiangLi** [comment]
For reference: https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html

**Comment by leongross** [comment]
Facing the same issue, the pod i created keeps in a pending state. I followed [this](https://aws.amazon.com/de/premiumsupport/knowledge-center/eks-persistent-storage/#) tutorial:
```
$ kubectl get pods
NAME   READY   STATUS    RESTARTS   AGE
app    0/1     Pending   0          10m
```

```
$ kubectl get pvc
NAME        STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
ebs-claim   Pending                                      ebs-sc         11m
```

```
$ kubectl describe pvc ebs-claim
Name:          ebs-claim
Namespace:     default
StorageClass:  ebs-sc
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/selected-node: ip-192-168-88-33.us-east-2.compute.internal
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       app
Events:
  Type     Reason              Age    From                                                                                      Message
  ----     ------              ----   ----                                                                                      -------
  Warning  ProvisioningFailed  10m    persistentvolume-controller                                                               storageclass.storage.k8s.io "ebs-sc" not found
  Warning  ProvisioningFailed  9m24s  ebs.csi.aws.com_ebs-csi-controller-7c486f7676-db7zv_98aee66d-41fa-47bd-86a1-e9b193c65d8e  failed to provision volume with StorageClass "ebs-sc": rpc error: code = Internal desc = Could not create volume "pvc-bc0f4fa3-20ad-4f29-8dfa-d3265394b735": could not create volume in EC2: WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://oidc.eks.us-east-2.amazonaws.com/id/<ID>
           status code: 400, request id: 41da2fc7-6f38-4017-ba60-41750f47660c
  Normal   Provisioning          10s (x11 over 10m)  ebs.csi.aws.com_ebs-csi-controller-7c486f7676-db7zv_98aee66d-41fa-47bd-86a1-e9b193c65d8e  External provisioner is provisioning volume for claim "default/ebs-claim"
  Normal   ExternalProvisioning  8s (x43 over 10m)   persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
  Warning  ProvisioningFailed    0s (x10 over 10m)   ebs.csi.aws.com_ebs-csi-controller-7c486f7676-db7zv_98aee66d-41fa-47bd-86a1-e9b193c65d8e  failed to provision volume with StorageClass "ebs-sc": rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

AmazonEKS_EBS_CSI_Driver_Policy:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:AttachVolume",
                "ec2:CreateSnapshot",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:DeleteSnapshot",
                "ec2:DeleteTags",
                "ec2:DeleteVolume",
                "ec2:DescribeAvailabilityZones",
                "ec2:DescribeInstances",
                "ec2:DescribeSnapshots",
                "ec2:DescribeTags",
                "ec2:DescribeVolumes",
                "ec2:DescribeVolumesModifications",
                "ec2:DetachVolume",
                "ec2:ModifyVolume"
            ],
            "Resource": "*"
        }
    ]
}
```
AmazonEKS_EBS_CSI_DriverRole Trust Relationship:
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::<ID>:oidc-provider/oidc.eks.us-east-2.amazonaws.com/id/<XXXXXX>"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.us-east-2.amazonaws.com/id/<XXXXX>:sub": "system:serviceaccount:kube-system:ebs-csi-controller-sa"
        }
      }
    }
  ]
}
```

`$aws iam list-attached-role-policies --role-name AmazonEKS_EBS_CSI_DriverRole`:
```json
{
    "AttachedPolicies": [
        {
            "PolicyName": "AmazonEKS_EBS_CSI_Driver_Policy",
            "PolicyArn": "arn:aws:iam::<ID>:policy/AmazonEKS_EBS_CSI_Driver_Policy"
        }
    ]
}
```

The problem that seem to be obvious is this warning::
`No OpenIDConnect provider found in your account for https://oidc.eks.us-east-2.amazonaws.com/id/<ID>`
You can see that the role is attached properly, so where could be the error in the authentication?
Thanks in advance.

**Comment by leongross** [comment]
Okay, I think i fixed at least my error:
I researched a bit and found [this](https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html) article.
I wanted to verify if I had a oidc provider running and found out, that there was none by default.

Creating an oidc provider using
```bash
eksctl utils associate-iam-oidc-provider --cluster <cluster_name> --approve
```

and restarting the pods as well as the pvc and sc solved my issue.

**Comment by ndlanier** [comment]
The issue my coworker found was within Amazon's own documentation for the driver. The role binding annotation that was created by the command did not bind to the correct role. The end of the role arn from the documentation was `ebs-csi-role`, and the actual end of the arn for the role was `AmazonEKS_EBS_CSI_DriverRole`

**Comment by ashish-billore** [comment]
> Okay, I think i fixed at least my error: I researched a bit and found [this](https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html) article. I wanted to verify if I had a oidc provider running and found out, that there was none by default.
> 
> Creating an oidc provider using
> 
> ```shell
> eksctl utils associate-iam-oidc-provider --cluster <cluster_name> --approve
> ```
> 
> and restarting the pods as well as the pvc and sc solved my issue.

I had the same issue and these steps fixed it, thanks for sharing :)

**Comment by ikejones** [comment]
> AmazonEKS_EBS_CSI_DriverRole

How did you fix it?

**Comment by ashish-billore** [comment]
> > AmazonEKS_EBS_CSI_DriverRole
> 
> How did you fix it?

I followed these:
https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html

Then everything looked good, as mentioned here:

https://repost.aws/knowledge-center/eks-troubleshoot-ebs-volume-mounts

except, the volume is pending:

```
$ kubectl get pods --watch
NAME   READY   STATUS    RESTARTS   AGE
app    0/1     Pending   0          31s

```

Then after following this:

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1010#issuecomment-966149137

And mentioned article:
https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html

It started working :)

Also, I changes my SC from gp2 to gp3. Here is a nice article for that:

https://aws.amazon.com/blogs/containers/migrating-amazon-eks-clusters-from-gp2-to-gp3-ebs-volumes/

That's it :)

**Comment by vishnu-nagaraj** [comment]
If your running the Prometheus and  Grafana on AWS EKS cluster getting unauthorised error for creating the  PVC,
must have the permission in the role of the eks.
Attach the below policy for EKS role and node group role. after that restart the deployments. it will work 

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:AttachVolume",
                "ec2:CreateSnapshot",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:DeleteSnapshot",
                "ec2:DeleteTags",
                "ec2:DeleteVolume",
                "ec2:DescribeAvailabilityZones",
                "ec2:DescribeInstances",
                "ec2:DescribeSnapshots",
                "ec2:DescribeTags",
                "ec2:DescribeVolumes",
                "ec2:DescribeVolumesModifications",
                "ec2:DetachVolume",
                "ec2:ModifyVolume"
            ],
            "Resource": "*"
        }
    ]
}

**Comment by amirmisgav** [comment]
Hi, Please note if you upgrade eks to 1.27, [Amazon EBS CSI Driver](https://us-east-1.console.aws.amazon.com/eks/home?region=us-east-1#/clusters/devopslab/add-ons/aws-ebs-csi-driver) addon is changed a little bit. 2 services account (controller and node ) are installed automatically. You must use the controller sa in trusted relationship instead the legacy sa we used to create. Use: ebs-csi-controller-sa.
example:
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::XXXXXXXXXXXX:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "[oidc.eks.us-east-1.amazonaws.com/id/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:sub](http://oidc.eks.us-east-1.amazonaws.com/id/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:sub)": "system:serviceaccount:kube-system:ebs-csi-controller-sa"
        },
        "StringLike": {
          "[oidc.eks.us-east-1.amazonaws.com/id/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:aud](http://oidc.eks.us-east-1.amazonaws.com/id/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:aud)": "[sts.amazonaws.com](http://sts.amazonaws.com/)"
        }
      }
    }
  ]
} (edited)

**Comment by farazsiddiqui2010** [comment]
@amirmisgav Do we need to conifgure OIDC on our kubernetes cluster end. 

We have cluster setup via Kops and after upgrading to 1.22.17. It is not able to attach and detach the volumes with PVC. As per logs, i found same error messages as mentioned below. So do you have configure OIDC on your cluster also?

GRPC error: rpc error: code = Internal desc = Could not detach volume from node "i-xxxxxxxxxxxxxxx": error listing AWS instances: "WebIdentityErr: failed to retrieve credentials\ncaused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://abc.com\n\tstatus code: 400, request id: 5abc3029-0f49-4343-b6ae-8ebcc386330b"

Thanks in advance.
