### ISSUE TITLE
Volume snapshot is always not ready to use on k8s 1.19

### ISSUE THREAD

**Issue by AlexZhenWang** [kubernetes-sigs/aws-ebs-csi-driver#1012]
/kind bug

**What happened?**

I installed EBS CSI driver followed https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html.
Also, I installed v2.1.5 Snapshot Beta CRDs and Common Snapshot Controller following https://github.com/kubernetes-csi/external-snapshotter/tree/v2.1.5
Then I run this example https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/snapshot, 
but I stuck at step 6 because my volumesnapshot is always showing `READYTOUSE: false`

**What you expected to happen?**
volumesnapshot show `READYTOUSE:ture`

**How to reproduce it (as minimally and precisely as possible)?**
Create a new 1.19 eks cluster
Install EBS CSI driver follwed https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html.
Install v2.1.5 Snapshot Beta CRDs and Common Snapshot Controller following https://github.com/kubernetes-csi/external-snapshotter/tree/v2.1.5
Run example https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/snapshot

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): v1.19
- Driver version: 
CSI driver: v1.2.0
external snapshotter: v2.1.5

**Comment by AndyXiangLi** [comment]
Hi @AlexZhenWang, Can you see any log related to snapshot in the driver log by running
```
kubectl log -n kube-system -c ebs-plugin {csi-driver-podId}
```
If you don't see that, try to find the log from csi-snapshotter see if snapshotter get the request from `ebs-snapshot-controller`.

**Comment by nirmalaagash** [comment]
Uninstall the existing csi driver from the cluster. 
Clone the CSI Driver([link](https://github.com/kubernetes-sigs/aws-ebs-csi-driver)) to your local machine and delete the line [186](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/controller.yaml#L186) and [208](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/e7267f434a0129e2b4f15e29817910c3219530a1/charts/aws-ebs-csi-driver/templates/controller.yaml#L208) from the /charts/aws-ebs-csi-driver/templates/controller.yaml in your local repo and save it.
Install ONLY Snapshot CRD, Common Snapshot Controller from [here](https://github.com/kubernetes-csi/external-snapshotter#usage). [Do NOT install csi-snapshotter under 'Install CSI Driver' block in the same link]
Try installing the csi driver once again using the below command

`helm upgrade --install aws-ebs-csi-driver ./charts/aws-ebs-csi-driver --namespace kube-system`

Follow the steps in the snapshot [example](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/snapshot) and give it a few min for `READYTOUSE` to turn true in step 6.

**Comment by AlexZhenWang** [comment]
Thank you @nirmalaagash, let me try it

**Comment by knkarthik** [comment]
@AlexZhenWang Just wondering if you were able to get this working. I've a similar issue https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1065.
