### ISSUE TITLE
Mount Option Support

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#102]
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options

**Comment by leakingtapan** [comment]
@bertinatto do you know if this is supported by CSI already?

**Comment by bertinatto** [comment]
@leakingtapan: yes, it has been added a month ago: https://github.com/kubernetes/kubernetes/pull/67898
