### ISSUE TITLE
Setup docs don't work

### ISSUE THREAD

**Issue by yang** [kubernetes-sigs/aws-ebs-csi-driver#1034]
/kind bug

**What happened?**

I followed the installation docs here, with Helm, running on EKS:

https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html

From Helm I got:

```
ServiceAccount "ebs-csi-controller-sa" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: key "app.kubernetes.io/managed-by" must equal "Helm": current value is "eksctl"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "aws-ebs-csi-driver"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
```

**What you expected to happen?**

Success.

**How to reproduce it (as minimally and precisely as possible)?**

Follow the docs.

**Comment by nirmalaagash** [comment]
@yang I think the service account 'ebs-csi-controller-sa' is already up in the cluster and you are trying to run create the service account once again using the helm install.

Try running the helm install command without 
> --set serviceAccount.controller.create=true \
> --set serviceAccount.controller.name=ebs-csi-controller-sa

**Comment by yang** [comment]
Yeah, that's the issue I'm pointing out - it was already created by eksctl.

See https://github.com/weaveworks/eksctl/issues/3912 for another report of this bug.

**Comment by krmichel** [comment]
This is the way helm works.  It either manages a resource or it doesn't.  If eksctl created the resource then helm isn't managing it.  Since you already have a service account that you want to use and its name matches the default name in the chart, just set the creation for the service account to false when running the helm command.

`--set controller.serviceAccount.create=false`

**Comment by yang** [comment]
Setting `serviceAccount.controller.create=false` was the first thing I tried, but from your snippet I see the docs have a different setting than what's in values.yaml.

**Comment by krmichel** [comment]
The chart has been updated and those referenced docs were not.  I am not sure where those docs live or who maintains them.  Starting with chart version 2.0.0 `controller.serviceAccount.create` is the value you will want to set.

**Comment by yang** [comment]
OK, sorry for the noise then - I thought perhaps this would be the place to report the docs issue!

**Comment by nirmalaagash** [comment]
@yang Thanks for pointing this out. The team will soon update the AWS [docs](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html).
