### ISSUE TITLE
[Helm Chart][Feature] Allow Setting Custom imagePullPolicy for csi-resizer

### ISSUE THREAD

**Issue by jyaworski** [kubernetes-sigs/aws-ebs-csi-driver#1040]
**Is your feature request related to a problem?/Why is this needed**
We cache images on our worker nodes and would like to use that cache when possible. `imagePullPolicy: Always` doesn't allow us to do that.

/feature

**Describe the solution you'd like in detail**
I would like to have the ability to set the CSI Resizer imagePullPolicy.

**Describe alternatives you've considered**
None

**Additional context**
I can file a PR for this myself, if it's approved.

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/controller.yaml#L215

**Comment by wongma7** [comment]
yes feel free to file a PR to remove this line, I am not sure why it is there when all the other sidecars don't specify an imagePullPolicy, the PR will be approved.

(in addition, I suppose each sidecar should have a sidecars.*.pullPolicy field. But removing this line does not preclude adding a a sidecars.*.pullPolicy field later.)
