### ISSUE TITLE
"Warning" LogLevel for LivenessProbe 

### ISSUE THREAD

**Issue by iusergii** [kubernetes-sigs/aws-ebs-csi-driver#1044]
**Is your feature request related to a problem?/Why is this needed**
I'd like to have an option to turn LivenessProbe to "Warning" mode. Currently, it generates a message every 10 seconds.  This creates a lot of entries in my logging system.

/feature

**Describe the solution you'd like in detail**
I'd like to have only warning, error messages in the log output.

**Describe alternatives you've considered**
I've tried set `logLevel: 1` but this doesn't change the number of messages.

**Comment by nirmalaagash** [comment]
@iusergii It looks like the message is from connection.go [file](https://github.com/kubernetes-csi/csi-lib-utils/blob/master/connection/connection.go#L154) which is being used by [liveness-probe](https://github.com/kubernetes-csi/livenessprobe/blob/master/cmd/livenessprobe/main.go#L98). I think you should try requesting this feature in [here](https://github.com/kubernetes-csi/livenessprobe).

**Comment by ialidzhikov** [comment]
@iusergii , can the issue you facing with the livenessprobe sidecar be the same as https://github.com/kubernetes-csi/livenessprobe/issues/110? livenessprobe sidecar unnecessary verbose logging is fixed in `livenessprobe@v2.3.0`, see https://github.com/kubernetes-csi/livenessprobe/issues/110.

**Comment by iusergii** [comment]
@ialidzhikov , @nirmalaagash  thank you, guys. Yes my concern was about socket info
```
I0910 05:56:18.037171       1 connection.go:153] Connecting to unix:///csi/csi.sock
```
Verified on `livenessprobe@v2.3.0` and it doesn't have it. Shell we update default in helm chart?

**Comment by ialidzhikov** [comment]
> Verified on `livenessprobe@v2.3.0` and it doesn't have it. Shell we update default in helm chart?

In general, we can update the default livenessprobe version to v2.3.0. You should be able to pass the liveness probe image as chart value, so the update of the livenessprobe container should not be a blocker for you.

/remove triage/needs-information
/kind feature

**Comment by iusergii** [comment]
@ialidzhikov  sure will do. It fixes my issue,
Just want to remove the image tag hardcode in the future to not miss new releases.

**Comment by alex88** [comment]
Should upgrading to v2.4.0 fix the `Connecting to unix:///csi/csi.sock` continuous logginig? In my case I keep getting the message
