### ISSUE TITLE
Move helm chart to aws/eks-charts

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-ebs-csi-driver#1057]
same people will maintain the chart, just considering moving it to a different repo depending on what users expect/find most convenient.

pros:
- fewer helm repos for users to deal with
- decoupled release process (currently both helm chart and driver image releases show up in github releases page)
- simplified release process for maintainers (update image , then go to repo 2 and update helm chart, versus the current process which involves 2-3 PRs per release)

cons:
- how to generate kustomize templates if not from helm? the kustomize templates will diverge. (e2e tests may need to use kustomize instead of helm)
- helm chart releases might be slower?
- eks-charts might not be as discoverable, have to link to it from here? not everyone using the driver is using eks.

Any thoughts/objections? THX!

**Comment by ConnorJC3** [comment]
/close

Based on prior internal discussion, we intend to keep the chart in the `kubernetes-sigs/aws-ebs-csi-driver` repo for the time being.
