### ISSUE TITLE
issue in controller.yml

### ISSUE THREAD

**Issue by thetrendspider** [kubernetes-sigs/aws-ebs-csi-driver#1061]
after 3rd August update , i am facing while installing aws-ebs-csi-driver

I am getting this error :-

helm install -f ebs-csi-values.yml aws-ebs-csi-driver --namespace kube-system aws-ebs-csi-driver/aws-ebs-csi-driver --debug
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: C:\Users\502626~1\AppData\Local\Temp\helm\repository\aws-ebs-csi-driver-2.1.1.tgz

coalesce.go:202: warning: destination for env is a table. Ignoring non-table value []
coalesce.go:202: warning: destination for env is a table. Ignoring non-table value []
Error: INSTALLATION FAILED: YAML parse error on aws-ebs-csi-driver/templates/controller.yaml: error converting YAML to JSON: yaml: line 67: did not find expected '-' indicator
helm.go:88: [debug] error converting YAML to JSON: yaml: line 67: did not find expected '-' indicator
YAML parse error on aws-ebs-csi-driver/templates/controller.yaml

your response is highly appreciated.

Thank You

**Comment by vdhanan** [comment]
could you please tell me what version of the csi driver you are trying to install? also, could you please provide the contents of the ebs-csi-values.yaml file that you're using for the install?

**Comment by thetrendspider** [comment]
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
aws-ebs-csi-driver/aws-ebs-csi-driver   2.1.1           1.2.1           A Helm chart for AWS EBS CSI Driver

and 

ebs-csi-values.yml contenet -

# Default values for aws-ebs-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: k8s.gcr.io/provider-aws/aws-ebs-csi-driver
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

sidecars:
  provisionerImage:
    repository: k8s.gcr.io/sig-storage/csi-provisioner
    tag: "v2.1.1"
  attacherImage:
    repository: k8s.gcr.io/sig-storage/csi-attacher
    tag: "v3.1.0"
  snapshotterImage:
    repository: k8s.gcr.io/sig-storage/csi-snapshotter
    tag: "v3.0.3"
  livenessProbeImage:
    repository: k8s.gcr.io/sig-storage/livenessprobe
    tag: "v2.2.0"
  resizerImage:
    repository: k8s.gcr.io/sig-storage/csi-resizer
    tag: "v1.0.0"
  nodeDriverRegistrarImage:
    repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    tag: "v2.1.0"

snapshotController:
  repository: k8s.gcr.io/sig-storage/snapshot-controller
  tag: "v3.0.3"
  podAnnotations: {}
  podLabels: {}

proxy:
  http_proxy:
  no_proxy:

imagePullSecrets: []
nameOverride:
fullnameOverride:

# True if enable volume snapshot
enableVolumeSnapshot: false

# Moving to values under controller
affinity: {}
extraCreateMetadata: true
extraVolumeTags: {}
k8sTagClusterId:
nodeSelector: {}
podAnnotations: {}
priorityClassName: "system-cluster-critical"
region:
replicaCount: 2
resources: {}
tolerations: []
topologySpreadConstraints: []

controller:
  affinity: {}
  # True if enable volume scheduling for dynamic volume provisioning
  env:
    ebsPlugin: []
    provisioner: []
    attacher: []
    snapshotter: []
    resizer: []
  # If set, add pv/pvc metadata to plugin create requests as parameters.
  extraCreateMetadata: true
  # Will be removed in later version in favor of env.ebsPlugin
  extraVars: {}
  # Extra volume tags to attach to each dynamically provisioned volume.
  # ---
  # extraVolumeTags:
  #   key1: value1
  #   key2: value2
  extraVolumeTags: 
    uai: <UAI>
    appName: <AppName>
  httpEndpoint:
  # ID of the Kubernetes cluster used for tagging provisioned EBS volumes (optional).
  k8sTagClusterId:
  logLevel: 2
  nodeSelector: 
    role: <UAI>-slave
  podAnnotations: {}
  podLabels: {}
  priorityClassName:
  # AWS region to use. If not specified then the region will be looked up via the AWS EC2 metadata
  # service.
  # ---
  # region: us-east-1
  region:
  replicaCount:
  resources: {}
  containerResources:
    ebsPlugin: {}
    provisioner: {}
    attacher: {}
    snapshotter: {}
    resizer: {}
    liveness: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # Note that you will need to set resource requests if you want the cluster autoscaler to
  # scale your nodes when you increase/decrease the number of ebs-csi-controller replicas.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  tolerations: []
  # TSCs without the label selector stanza
  #
  # Example:
  #
  # topologySpreadConstraints:
  #  - maxSkew: 1
  #    topologyKey: topology.kubernetes.io/zone
  #    whenUnsatisfiable: ScheduleAnyway
  #  - maxSkew: 1
  #    topologyKey: kubernetes.io/hostname
  #    whenUnsatisfiable: ScheduleAnyway
  topologySpreadConstraints: []

# Moving to values under node
# The "maximum number of attachable volumes" per node
volumeAttachLimit:

node:
  env:
    ebsPlugin: []
    nodeDriverRegistrar: []
  kubeletPath: /var/lib/kubelet
  logLevel: 2
  priorityClassName:
  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  tolerateAllTaints: false
  tolerations: []
  resources: {}
  containerResources:
    ebsPlugin: {}
    nodeDriverRegistrar: {}
    liveness: {}
  volumeAttachLimit:

serviceAccount:
  controller:
    create: true 
    name: ebs-csi-controller-sa
    annotations: 
      eks.amazonaws.com/role-arn: arn:aws:iam::813871618402:role/eks-iamserviceaccount-uai3027675-eks-test-dev-ebs-csi-role
  snapshot:
    create: true
    name: ebs-snapshot-controller
    annotations: {}
  node:
    create: true
    name: ebs-csi-node-sa
    annotations: {}

# storageClasses:
# # Add StorageClass resources like:
# - name: ebs-csi-sc
  # # annotation metadata
  # annotations:
    # storageclass.kubernetes.io/is-default-class: "true"
  # # label metadata
  # labels:
    # encrypted-storage-class: true
  # # defaults to WaitForFirstConsumer
  # volumeBindingMode: WaitForFirstConsumer
  # # defaults to Delete
  # reclaimPolicy: Retain
  # parameters:
    # encrypted: "true"
    # type: "gp3"
    # kmsKeyId: "arn:aws:kms:eu-west-1:813871618402:key/0f69fb2b-617a-42d8-b4b2-322697c9b6ff"

**Comment by krmichel** [comment]
Will you please put your yaml into a code block? Without any of the whitespace, it makes it difficult to know what the yaml is actually saying.

**Comment by thetrendspider** [comment]
``# Default values for aws-ebs-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.2.1
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

sidecars:
  provisionerImage:
    repository: k8s.gcr.io/sig-storage/csi-provisioner
    tag: "v2.1.1"
  attacherImage:
    repository: k8s.gcr.io/sig-storage/csi-attacher
    tag: "v3.1.0"
  snapshotterImage:
    repository: k8s.gcr.io/sig-storage/csi-snapshotter
    tag: "v3.0.3"
  livenessProbeImage:
    repository: k8s.gcr.io/sig-storage/livenessprobe
    tag: "v2.2.0"
  resizerImage:
    repository: k8s.gcr.io/sig-storage/csi-resizer
    tag: "v1.0.0"
  nodeDriverRegistrarImage:
    repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    tag: "v2.1.0"

snapshotController:
  repository: k8s.gcr.io/sig-storage/snapshot-controller
  tag: "v3.0.3"
  podAnnotations: {}
  podLabels: {}

proxy:
  http_proxy:
  no_proxy:

imagePullSecrets: []
nameOverride:
fullnameOverride:

# True if enable volume snapshot
enableVolumeSnapshot: false

# Moving to values under controller
affinity: {}
extraCreateMetadata: true
extraVolumeTags: {}
k8sTagClusterId:
nodeSelector: {}
podAnnotations: {}
priorityClassName: "system-cluster-critical"
region:
replicaCount: 2
resources: {}
tolerations: []
topologySpreadConstraints: []

controller:
  affinity: {}
  # True if enable volume scheduling for dynamic volume provisioning
  env:
    ebsPlugin: []
    provisioner: []
    attacher: []
    snapshotter: []
    resizer: []
  # If set, add pv/pvc metadata to plugin create requests as parameters.
  extraCreateMetadata: true
  # Will be removed in later version in favor of env.ebsPlugin
  extraVars: {}
  # Extra volume tags to attach to each dynamically provisioned volume.
  # ---
  # extraVolumeTags:
  #   key1: value1
  #   key2: value2
  extraVolumeTags: 
    uai: uai3038316
    appName: gs-apm-menat
  httpEndpoint:
  # ID of the Kubernetes cluster used for tagging provisioned EBS volumes (optional).
  k8sTagClusterId:
  logLevel: 2
  nodeSelector: 
    role: uai3038316-slave
  podAnnotations: {}
  podLabels: {}
  priorityClassName:
  # AWS region to use. If not specified then the region will be looked up via the AWS EC2 metadata
  # service.
  # ---
  # region: us-east-1
  region:
  replicaCount:
  resources: {}
  containerResources:
    ebsPlugin: {}
    provisioner: {}
    attacher: {}
    snapshotter: {}
    resizer: {}
    liveness: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # Note that you will need to set resource requests if you want the cluster autoscaler to
  # scale your nodes when you increase/decrease the number of ebs-csi-controller replicas.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  tolerations: []
  # TSCs without the label selector stanza
  #
  # Example:
  #
  # topologySpreadConstraints:
  #  - maxSkew: 1
  #    topologyKey: topology.kubernetes.io/zone
  #    whenUnsatisfiable: ScheduleAnyway
  #  - maxSkew: 1
  #    topologyKey: kubernetes.io/hostname
  #    whenUnsatisfiable: ScheduleAnyway
  topologySpreadConstraints: []

# Moving to values under node
# The "maximum number of attachable volumes" per node
volumeAttachLimit:

node:
  env:
    ebsPlugin: []
    nodeDriverRegistrar: []
  kubeletPath: /var/lib/kubelet
  logLevel: 2
  priorityClassName:
  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  tolerateAllTaints: false
  tolerations: []
  resources: {}
  containerResources:
    ebsPlugin: {}
    nodeDriverRegistrar: {}
    liveness: {}
  volumeAttachLimit:

serviceAccount:
  controller:
    create: true 
    name: ebs-csi-controller-sa
    annotations: 
      eks.amazonaws.com/role-arn: arn:aws:iam::132880692619:role/eks-iam-sa-uai3038316-gs-apm-menat-prod-me-south-1-ebs-csi-role
  snapshot:
    create: true
    name: ebs-snapshot-controller
    annotations: {}
  node:
    create: true
    name: ebs-csi-node-sa
    annotations: {}

# storageClasses:
# # Add StorageClass resources like:
# - name: ebs-csi-sc
  # # annotation metadata
  # annotations:
    # storageclass.kubernetes.io/is-default-class: "true"
  # # label metadata
  # labels:
    # encrypted-storage-class: true
  # # defaults to WaitForFirstConsumer
  # volumeBindingMode: WaitForFirstConsumer
  # # defaults to Delete
  # reclaimPolicy: Retain
  # parameters:
    # encrypted: "true"
    # type: "gp3"
    # kmsKeyId: "arn:aws:kms:eu-west-1:813871618402:key/0f69fb2b-617a-42d8-b4b2-322697c9b6ff"

**Comment by thetrendspider** [comment]
> Will you please put your yaml into a code block? Without any of the whitespace, it makes it difficult to know what the yaml is actually saying.

i had put yaml code in code block ... please check
