### ISSUE TITLE
4 days released v1.3.0, still no Changelog

### ISSUE THREAD

**Issue by rubroboletus** [kubernetes-sigs/aws-ebs-csi-driver#1066]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when new release appears without Changelog, but changelog id mentioned on release page.

**Describe the solution you'd like in detail**
I wanna to see a changelog, what new features / bugfixes come with new release.

**Describe alternatives you've considered**
Alternatively I can switch from AWS to Azure or Google.

**Comment by vdhanan** [comment]
sorry for the delay. i'm going to merge the changes on the release 1.3 branch back to master today. in the meantime, you can see the Changelog here: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/release-1.3/CHANGELOG-0.x.md
