### ISSUE TITLE
Windows "volume id empty"

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-ebs-csi-driver#1090]
/kind bug
continuing discussion here

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1001#issuecomment-940215607

**What happened?** after rescheduling pod from windows node 1 to 2, the driver reports

`E1011 17:52:52.223938    6584 driver.go:119] GRPC error: rpc error: code = Internal desc = could not format "5" and mount it at "\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-1c0ecde3-cb0d-49a6-8e68-156f1738ceac\\globalmount": rpc error: code = Unknown desc = volume id empty`

**What you expected to happen?** no error

**How to reproduce it (as minimally and precisely as possible)?**
"After launching Windows Application pod with Dynamic Volume provisioning, terminate the EC2 instance where pod is scheduled, after some time pod will be scheduled on another node in same AZ due to nodes AZ affinity, but this pod gets stuck in ContainerCreating stage with above error."

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version: 4d5d7e7fea2b4b1d178f43c79957c2bebc2b0721

**Comment by vmasule** [comment]
@wongma7 I am already using `aws-node-termination-handler` with Queue mode and also have `cluster-autoscaler` installed in my cluster, so that is what getting me more worried as there will be lot of manual headache to manage Windows workloads if dynamic provisioning doesn't work as it works for Linux nodes(I don't see any issues there).

For your information I am using `Windows_Server-2019-English-Full-EKS_Optimized-1.21-2021.08.12`

Please try to reproduce and update your findings here that would be highly appreciated.

**Comment by vmasule** [comment]
There is something wrong, I just drained the node running Windows pod, after that pod got evicted and scheduled on another node in same AZ, but its giving same `volume id empty` error, so it is bit weird, what may be I am doing wrong and you are doing right? Could you please refer the guidelines setup you followed for using EBS CSI for windows support.

This is what I did.

**Drain the node:**
```
kubectl drain ip-172-12-34-94.us-west-2.compute.internal --ignore-daemonsets

evicting pod demo-tenant8/demo-tenant8-statefulset-0
pod/demo-tenant8-statefulset-0 evicted
node/ip-172-12-34-94.us-west-2.compute.internal evicted
```

**Pod Events from another node:**

```
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Normal   Scheduled               4m28s                default-scheduler        Successfully assigned demo-tenant8/demo-tenant8-statefulset-0 to ip-172-12-36-131.us-west-2.compute.internal
  Warning  FailedAttachVolume      4m28s                attachdetach-controller  Multi-Attach error for volume "pvc-8dafe081-ff6e-4f69-be8b-11de5a94395a" Volume is already exclusively attached to one node and can't be attached to another
  Normal   SuccessfulAttachVolume  4m9s                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-8dafe081-ff6e-4f69-be8b-11de5a94395a"
  Warning  FailedMount             34s (x9 over 3m47s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-8dafe081-ff6e-4f69-be8b-11de5a94395a" : rpc error: code = Internal desc = could not format "5" and mount it at "\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-8dafe081-ff6e-4f69-be8b-11de5a94395a\\globalmount": rpc error: code = Unknown desc = volume id empty
  Warning  FailedMount             11s (x2 over 2m25s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[xpandion-vol-mount], unattached volumes=[xpandion-vol-mount]: timed out waiting for the condition

```


I have setup this EBS CSI using helm chart with default setup and only `node.enableWindows` for windows support. All the required IAM Polices are attached to each Windows Node(i.e not passed through service accounts -- Is this might be an issue??). Do you see any issue in this setup?

Helm Chart Details:
Repo: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
version: "2.4.0"
image.repository: "amazon/aws-ebs-csi-driver"
"image.tag": "v1.4.0"
"node.enableWindows": true
"node.logLevel": 5
"controller.logLevel": 5

**Comment by vmasule** [comment]
@wongma7 Is anybody working on this? If not could you please guide us what could be potential fix I would check if someone from my team can look into this on urgent basis as this is impacting our Pod SLA.
