### ISSUE TITLE
error observed during making aws-ebs-csi-driver for version 0.4.0

### ISSUE THREAD

**Issue by zhoudayongdennis** [kubernetes-sigs/aws-ebs-csi-driver#1099]
/triage support

here was the makefile design in project to build aws-ebs-csi-driver from source code.

define build_aws_csi_image
        mkdir -p $(GOPATH)/src/github.com/kubernetes-sigs/
        cd $(GOPATH)/src/github.com/kubernetes-sigs/;export https_proxy="http://*.*.*.*4:8000/";curl -O -L https://github.com/kubernetes-sigs/aws-ebs-csi-driver/archive/$(2).zip;unzip -q $(2).zip&& rm -rf $(2).zip;mv * aws-ebs-csi-driver;

        cd $(GOPATH)/src/github.com/kubernetes-sigs/aws-ebs-csi-driver;export https_proxy="http://*.*.*.*:8000/";export GOPATH=$(HOME)/go;export GOROOT=/usr/local/go;export PATH=$(PATH):$(GOROOT)/bin:$(GOPATH)/bin;go mod download;make ;

but observed below error during executing "go mod download" step.

_cd /root/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver;export https_proxy="http://135.245.48.34:8000/";export GOPATH=/root/go;export GOROOT=/usr/local/go;export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/root/go/bin;go mod download;make ;
go: bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
make[2]: Entering directory `/root/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver'
mkdir -p bin
CGO_ENABLED=0 GOOS=linux go build -ldflags "-X github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.driverVersion=0.4.0 -X github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.gitCommit=86acd23b50775562ade108c2ef0d2b43374c55c5 -X github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.buildDate=2021-10-21T08:34:23Z -s -w" -o bin/aws-ebs-csi-driver ./cmd/
go: bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
make[2]: *** [aws-ebs-csi-driver] Error 1
make[2]: Leaving directory `/root/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver'
make[1]: *** [build] Error 2
make[1]: Leaving directory `/home/jenkins/workspace/CTO/CSF/LifeCycleAndConfiguration/CSF-CMT-IMAGE/csi_aws'
make: *** [build_app] Error 2_

**Comment by gtxu** [comment]
Hi @zhoudayongdennis, we recommend you use newer version of CSI Driver. Or would you please provide a specific reason using aws-ebs-csi-driver version 0.4.0?

**Comment by zhoudayongdennis** [comment]
Hi, @gtxu, the current customer was on this version without plan for upgrade recently, and I am working out the patch for it.

**Comment by gtxu** [comment]
Hi, @zhoudayongdennis any updates? Please note, version under v1.0.0 of aws-ebs-csi-driver is no longer supported and maintained, If you have any trouble migrate version to v1.0.0 or upper, please create a new issue with it. Thank you!
