### ISSUE TITLE
[Feature] Support initialization of EBS volumes created from Snapshots

### ISSUE THREAD

**Issue by aaroniscode** [kubernetes-sigs/aws-ebs-csi-driver#1100]
**Is your feature request related to a problem? Please describe.**
From EBS Documentation (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-initialize.html)
For volumes that were created from snapshots, the storage blocks must be pulled down from Amazon S3 and written to the volume before you can access them. This preliminary action takes time and can cause a significant increase in the latency of I/O operations the first time each block is accessed. Volume performance is achieved after all blocks have been downloaded and written to the volume.

The solutions in the documentation aren't compatible with storage assigned to pods. The instructions say "Use the dd or fio utilities to read all of the blocks on the device." However, the block device is not available to the Pod. 

**Describe the solution you'd like in detail**
Would like the CSI Driver mechanism to initialize the EBS volume to increase performance of data from snapshot volumes.

**Describe alternatives you've considered**
Not aware of any known alternatives besides migrating workload from EKS to EC2.

**Additional context**
None.

**Comment by abencomoc** [comment]
Similar request was open to add support for EBS Fast Snapshot Restore on the ebs csi driver, issue #869
Linking here for tracking.
