### ISSUE TITLE
Run containers with readOnlyRootFilesystem

### ISSUE THREAD

**Issue by gabegorelick** [kubernetes-sigs/aws-ebs-csi-driver#1101]
**Is your feature request related to a problem?/Why is this needed**
Running containers with a read-only root filesystem--when feasible--is considered a best practice. Not doing so causes EBS CSI driver containers to get flagged by security scanners/linters/questionnaires/overzealous admission controllers. 

/feature

**Describe the solution you'd like in detail**
Support running some or all containers with `readOnlyRootFilesystem: true`.

**Describe alternatives you've considered**
An explanation as to why a read-write container filesystem is required is also totally fine. But I would expect that at least some of the containers in EBS CSI driver don't need it.

**Comment by entscheidungsproblem** [comment]
/reopen

Can this be reopened to look into? I think this is an important issue.

**Comment by entscheidungsproblem** [comment]
@leakingtapan, @bertinatto, @d-nishi 
Could one of you help me and reopen this issue please?
