### ISSUE TITLE
still no ChangeLog for v1.5.0

### ISSUE THREAD

**Issue by rubroboletus** [kubernetes-sigs/aws-ebs-csi-driver#1128]
/kind bug

**What happened?**

was trying to understand, what is new in release 1.5.0, 16 days after it was released

**What you expected to happen?**

I expected ChangeLog describing changes in new release

**How to reproduce it (as minimally and precisely as possible)?**

open actual ChangeLog, ends with 1.4.0 changes

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): any
- Driver version: any

**Comment by wongma7** [comment]
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1114/files and https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1118/files need to be pushed to master branch (or the release should link to the changelog in the release branch) @gtxu

**Comment by gtxu** [comment]
Sorry for delay. I am working on merge release-1.5 branch to main. Please refer https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/release-1.5/CHANGELOG-0.x.md for ChangeLog while the merge work in progress. Sorry for your inconvenience!

**Comment by wongma7** [comment]
thx, I'll see how we can make changelog point to the branch of the release https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/.github/workflows/release.yaml#L24

And maybe github could mark the release pre-release and then as practice we could mark it as released only after we are done the final merge.

**Comment by gtxu** [comment]
Current version change log updated by PR #1132
