### ISSUE TITLE
Published docker images are vunerable to ALAS-2021-1552

### ISSUE THREAD

**Issue by dylanlingelbach** [kubernetes-sigs/aws-ebs-csi-driver#1129]
/kind bug

**What happened?**
Published docker images are vulnerable to [ALAS-2021-1552](https://alas.aws.amazon.com/ALAS-2021-1552.html)

**What you expected to happen?**
New docker images published with an updated base image

**How to reproduce it (as minimally and precisely as possible)?**
Check version of NSS in published docker image

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): N/A
- Driver version: 1.4.0/1.5.0

**Comment by gtxu** [comment]
Hi @dylanlingelbach,  the image of v1.5.0 has been re-build and now fixed this vulnerability.

**Comment by dylanlingelbach** [comment]
@gtxu confirmed this is fixed, thank you!

**Comment by dylanlingelbach** [comment]
@gtxu sorry, I had the vulnerabilities ignored when I checked. I am still seeing `k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.5.0` as containing unpatched vulnerabilities. Is there a different image I should be using?

**Comment by gtxu** [comment]
Hi @dylanlingelbach, the version 1.5.0 on ECR Public: https://gallery.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver is re-built and fix this vulnerabilities, for images on gcr, a new releasing v1.5.1 is up coming to fix this.

**Comment by dylanlingelbach** [comment]
@gtxu got it, confirmed the ECR public image is fixed, closing now.
