### ISSUE TITLE
CSI Driver PV creation failure 

### ISSUE THREAD

**Issue by brickpattern** [kubernetes-sigs/aws-ebs-csi-driver#1140]
Followed the examples given in this repo creating a POD "app" with Claim and StorageClass.

 Resulting in an error ...as seen in PVC describe as well the same in controller logs. Any suggestions on what am i missing?  

  Type     Reason                Age   From                                                                                      Message
  ----     ------                ----  ----                                                                                      -------
  Normal   WaitForFirstConsumer  11m   persistentvolume-controller                                                               waiting for first consumer to be created before binding
  Warning  ProvisioningFailed    11m   ebs.csi.aws.com_ebs-csi-controller-56c69bcf65-d5vjw_a9ed942d-7fa7-4133-aa06-2be287a4969e  failed to provision volume with StorageClass "ebscsi": rpc error: code = Internal desc = Could not create volume "pvc-fe352e9e-5d8b-4fd1-a5ab-6fc2493cce37": **failed to get an available volume in EC2: InvalidVolume**.NotFound: The volume 'vol-036f02de0e81cbb95' does not exist.
           status code: 400, request id: f4fc598c-5822-4c5b-9719-40e3741f6349
  Normal   Provisioning          3m16s (x11 over 11m)  ebs.csi.aws.com_ebs-csi-controller-56c69bcf65-d5vjw_a9ed942d-7fa7-4133-aa06-2be287a4969e  External provisioner is provisioning volume for claim "default/ebscsi"
  Warning  ProvisioningFailed    3m16s (x10 over 11m)  ebs.csi.aws.com_ebs-csi-controller-56c69bcf65-d5vjw_a9ed942d-7fa7-4133-aa06-2be287a4969e  failed to provision volume with StorageClass "ebscsi": **rpc error: code = AlreadyExists** desc = Could not create volume "pvc-fe352e9e-5d8b-4fd1-a5ab-6fc2493cce37": Parameters on this idempotent request are inconsistent with parameters used in previous request(s)
  Normal   ExternalProvisioning  101s (x42 over 11m)   persistentvolume-controller

**Comment by brickpattern** [comment]
this is using the latest v1.4.0-eksbuild.preview  of AWS EBS CSI Driver add-on

**Comment by brickpattern** [comment]
repurposed this ... the only update i made is the  zone /region im operating on. 
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/examples/kubernetes/storageclass/specs/example.yaml

Yes , my AWS CLI is good as im able to deploy other K8S intree storage pods/pvc.  Just that EBS CSI driver example is failing.

**Comment by brickpattern** [comment]
Error logs from csi-plugin container 

driver.go:119] GRPC error: rpc error: code = AlreadyExists desc = Could not create volume "pvc-0315dafb-245d-47e3-adef-74f782688d1c": Parameters on this idempotent request are inconsistent with parameters used in previous request(s)

since the PV never got created , how to track this volume id is truly existing on EBS end. Searching in EBS AWS console doesnt find any match?

**Comment by brickpattern** [comment]
Deleted/Uninstalled the CSI Driver add-on from AWS console... thought on the lines of caching issue at the controller / csi-provisioner end.  Reinstalled the add-on. Still the same error . This leaves me to the API endpoint (csi driver) is talking to.

**Comment by brickpattern** [comment]
i made the storageclass definition with parameter of  encryption: "false" 

Wouldnt that make the  KMS key and EBS encryption void ?

**Comment by brickpattern** [comment]
@juergenz  tks for the tip.

Resolved!!!

Added this policy snippet to the role/policy attached to the CSI Driver and   its able to create the volume. 

`        {
            "Sid": "MinimalEBSKMSCreateandAttach",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:GenerateDataKeyWithoutPlaintext",
                "kms:CreateGrant"
            ],
            "Resource": "*"
        }`

However its still curious to me ... the StorageClass definition of parameter. encrypted:"false" did not mandate a unencrypted volume. It appears parameter is only a qualifier. Anyways ... this is hardway.

**Comment by rayjanoka** [comment]
Thanks, I found that I was missing one of my `kms_key_arn` in the IAM policy for ebs-csi-plugin.

**Comment by sumanthkumarc** [comment]
This https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1140#issuecomment-993711047 worked for me. I had to add below to my driver policy. Just wondering why this isnt part of the official Driver policy.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:GenerateDataKeyWithoutPlaintext",
                "kms:CreateGrant"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by fheinecke** [comment]
For anybody else running into this issue, this can also happen if you use a KMS key alias on the storage class. Essentially what is happening is that the `ec2:CreateVolume` API call reports a success, but fails behind the scenes due to the role lacking KMS permissions to encrypt the new volume with the listed key. The CSI controller fails to attach the volume (which doesn't actually exist), then tries repeatedly to create the volume using the same client token for idempotency. The API calls then fail because the token has already been used to create the volume, despite internally failing the first time.

**Comment by headyj** [comment]
@fheinecke how did you manage to solve this issue? because on my side all permissions above are correct, the kms alias on the storageclass is also correct and correspond to the one specified in my role. annotation is also correctly set on ebs-csi-controller-sa service account

**Comment by thoefkens** [comment]
I am still facing this issue... I added the kms rights etc. as described in this thread, yet when debugging I still see:

`<CreateVolumeResponse xmlns="http://ec2.amazonaws.com/doc/2016-11-15/"><requestId>fe717057-b724-447e-9d3a-2c9c4a54cd2e</requestId><volumeId>vol-033acf4347abcacd1</volumeId><size>1</size><snapshotId></snapshotId><availabilityZone>eu-central-1a</availabilityZone><status>creating</status><createTime>2025-04-10T15:03:09.000Z</createTime><volumeType>gp2</volumeType><iops>100</iops><encrypted>true</encrypted><kmsKeyId>arn:aws:kms:eu-central-1:123:key/mrk-f3988e092fc34728bde3c8451fe31d1e</kmsKeyId><tagSet><item><key>ebs.csi.aws.com/cluster</key><value>true</value></item><item><key>CSIVolumeName</key><value>pvc-8b4a19da-0cbd-4570-bef0-a2689fe27cbf</value></item><item><key>kubernetes.io/created-for/pv/name</key><value>pvc-8b4a19da-0cbd-4570-bef0-a2689fe27cbf</value></item><item><key>KubernetesCluster</key><value>ak-eks</value></item><item><key>kubernetes.io/created-for/pvc/name</key><value>wine-logs-ak-engine-0</value></item><item><key>kubernetes.io/cluster/ak-eks</key><value>owned</value></item><item><key>kubernetes.io/created-for/pvc/namespace</key><value>ak</value></item><item><key>Name</key><value>ak-eks-dynamic-pvc-8b4a19da-0cbd-4570-bef0-a2689fe27cbf</value></item></tagSet><multiAttachEnabled>false</multiAttachEnabled></CreateVolumeResponse>
SDK 2025/04/10 15:03:11 DEBUG Request
POST / HTTP/1.1
Host: ec2.eu-central-1.amazonaws.com
User-Agent: aws-sdk-go-v2/1.26.1 os/linux lang/go#1.22.3 md/GOOS#linux md/GOARCH#amd64 exec-env/aws-ebs-csi-driver-v1.31.0-eks api/ec2#1.161.1
Content-Length: 107
Amz-Sdk-Invocation-Id: f1d78dd0-0cbc-4c49-a378-96a1a5b170b2
Amz-Sdk-Request: attempt=1; max=50
Signature=1442d4a7ce989e86bc4239e4f6f17eaafef9482e70d93fa79a29a52ae52def6d
Content-Type: application/x-www-form-urlencoded
X-Amz-Date: 20250410T150311Z

Action=DescribeVolumes&Version=2016-11-15&VolumeId.1=vol-09c025ab543ee4aa1&VolumeId.2=vol-033acf4347abcacd1
SDK 2025/04/10 15:03:11 DEBUG Response
HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store
Content-Type: text/xml;charset=UTF-8
Date: Thu, 10 Apr 2025 15:03:11 GMT
Server: AmazonEC2
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: accept-encoding
X-Amzn-Requestid: a62a42bb-44ca-4ff6-bcff-245677f68ec9 <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidVolume.NotFound</Code><Message>The volume 'vol-09c025ab543ee4aa1' does not exist.</Message></Error></Errors><RequestID>a62a42bb-44ca-4ff6-bcff-245677f68ec9</RequestID></Response>
0`

@brickpattern did you get this resolved?
