### ISSUE TITLE
panic: node providerID empty, cannot parse

### ISSUE THREAD

**Issue by leongross** [kubernetes-sigs/aws-ebs-csi-driver#1144]
/kind bug

**What happened?**
ebs-csi-controller's do crash due to missing `providerID`.

**What you expected to happen?**
A cluster with correctly working `ebs-csi-controller` which is connected to AWS and can create volumes

**How to reproduce it (as minimally and precisely as possible)?**
1. Created a cluster using `kubeadm`
2. Created secrets for AWS and Docker and applied them to cluster
3. applied the driver
4. `$ kubectl get pods -A` --> ebs-csi controller CreasLoopBackOff
```
NAMESPACE     NAME                                  READY   STATUS             RESTARTS      AGE
kube-system   coredns-78fcd69978-gwcp9              1/1     Running            0             145m
kube-system   coredns-78fcd69978-vj5c9              1/1     Running            0             145m
kube-system   ebs-csi-controller-76fbd7fd94-7sbr8   5/6     CrashLoopBackOff   3 (10s ago)   65s
kube-system   ebs-csi-controller-76fbd7fd94-kkrtl   5/6     CrashLoopBackOff   3 (8s ago)    65s
kube-system   ebs-csi-node-c4g6w                    2/3     CrashLoopBackOff   3 (10s ago)   65s
kube-system   ebs-csi-node-dk8vk                    2/3     CrashLoopBackOff   3 (7s ago)    65s
``` 
6. `$ kubectl logs ebs-csi-controller-76fbd7fd94-kkrtl -n kube-system ebs-plugin`
```bash
I1216 18:15:24.573938       1 metadata.go:67] retrieving instance data from ec2 metadata
W1216 18:15:24.824206       1 metadata.go:70] ec2 metadata is not available
I1216 18:15:24.824240       1 metadata.go:78] retrieving instance data from kubernetes api
I1216 18:15:24.824922       1 metadata.go:83] kubernetes api is available
panic: node providerID empty, cannot parse

goroutine 1 [running]:
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newControllerService(0xc00009a230)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/controller.go:83 +0x165
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver({0xc0004e9f38, 0x7, 0xc00006e6b0})
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:96 +0x23c
main.main()
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:46 +0x335
```

**Anything else we need to know?**:
The cluster is not an eks but a self created cluster in the AWS cloud using `kubeadm`

**Environment**
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}`
- Driver version: 705b545c8818a8f0699a3315838d8f39d5633e1a (5.2)

**Comment by leongross** [comment]
**EDIT**
I did some research and found out, that [pkg/cloud/metadata_k8s.go](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/aefaa900ae057acda57173977370a61e6b9b04bb/pkg/cloud/metadata_k8s.go) is detecting the error.
This may be the result of a missing connection to the AWS API which provides metadata, because the information provided in the NodeID would maybe be provided by this API.
The connectivity to the AWS API is also mentioned in the [Installtion](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/#installation) paragraph of this repo.

**Comment by cycwll** [comment]
My ebs-csi-controller was running well before.
![image](https://user-images.githubusercontent.com/6410130/167263334-4b8d5938-8faa-4cd2-ac1d-645144196173.png)
and the pod ebs-csi-node-xxx  was running well.
![image](https://user-images.githubusercontent.com/6410130/167263365-b2299a8e-99ee-4e1f-9cbc-477658ee8b94.png)

But, I don't know when they can't work anymore.
![image](https://user-images.githubusercontent.com/6410130/167263493-41ab2d8c-f988-430f-8238-953455a1eefc.png)
![image](https://user-images.githubusercontent.com/6410130/167263520-1c748c6b-abbe-48cd-89da-6206839b13b4.png)

**Comment by cycwll** [comment]
@leongross
Excuse me, have you solved this problem?

**Comment by cycwll** [comment]
The problem has been solved.
The root cause is I specifies that IMDSv2 must be used when accessing metadata, cause IMDSv1 to no longer function. This is a propulsion configuration in AWS security reinforcement. To verify if this is the reason, run the command on EC2 curl -v http://169.254.169.254/latest/meta-data/. If the response is 401, it proves that IMDSv1 is disabled.

After I enable IMDSv1 with the following command, the problem is solved.
`aws ec2 modify-instance-metadata-options     --instance-id i-0e4be1e0b1e30c8b4   --http-tokens optional     --http-endpoint enabled  `
