### ISSUE TITLE
Kubernetes Version Compabilities

### ISSUE THREAD

**Issue by leongross** [kubernetes-sigs/aws-ebs-csi-driver#1147]
**Is your feature request related to a problem?/Why is this needed**
The highest Kubernetes version the [compatibility matrix](https://github.com/kubernetes-sigs/aws-ebs-csi-driver#kubernetes-compatibility-matrix) seems to support is version 1.18. which AFAIK has reached it's end of life at the 28th April 2021.
Is the most up to date version of this driver compatible with the newer versions (1.21, 1.22) ?
If this is the case an update in the matrix would be great.
If not, when do you intend to update the driver to support the current releases?

/feature

**Describe the solution you'd like in detail**
A up-to-date driver version for the current releases

**Describe alternatives you've considered**
Mention of experimental support

**Comment by zhoudayongdennis** [comment]
@owners,

any further update/recommendation for this question? want to understand the correct AWS EBS CSI Driver version for Kubernetes 1.21 or 1.22.
