### ISSUE TITLE
missing capability to tag EBS volumes (--extra-tags) when using managed add-on for EBS CSI

### ISSUE THREAD

**Issue by nbbhall** [kubernetes-sigs/aws-ebs-csi-driver#1155]
**Is your feature request related to a problem?/Why is this needed**
/feature
After enabling EBS CSI add-on, EKS takes over management of field `spec.template.spec.containers.args` for deployment `ebs-csi-controller`. Controller periodically reconciles the state and overwrites any changes to managed fields, including deleting the container argument for `--extra-tags`. This prevents users from being able to add extra-tags as they were able to add when using self-managed add-on (unless I am missing an obvious workaround to achieve this).

```
# command shows that spec.template.spec.containers.args is managed by "manager": "eks"
$ kubectl get deployment ebs-csi-controller -n kube-system --show-managed-fields -o=jsonpath='{.metadata.managedFields}' | jq .
```

**Comment by philicious** [comment]
@nbbhall afaik the in-tree EBS CSI driver doesnt support extra-tags
