### ISSUE TITLE
PV volume destroyed from ext4 to "Microsoft basic data" partition

### ISSUE THREAD

**Issue by fierman333** [kubernetes-sigs/aws-ebs-csi-driver#1156]
/kind bug

We have persisten volume in AWS type gp2 ext4 fs which was part of statefulset running for more then 6 months.
So far so good. At some point one of our pods went to "Not Ready" state and when we checked pod logs we saw following error:

```
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/eu-central-1c/vol-06eab10b22ba426a5 --scope – mount -t ext4 -o defaults /dev/xvdcv /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/eu-central-1c/vol-06eab10b22ba426a5
Output: Running scope as unit run-25564.scope.

mount: /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/eu-central-1c/vol-06eab10b22ba426a5: wrong fs type, bad option, bad superblock on /dev/nvme1n1, missing codepage or helper program, or other error.

2m59s Warning FailedMount pod/vcd-f7de1b90-736a-434d-be50-92d5aa8a1941-2 MountVolume.MountDevice failed for volume "pvc-06e42c70-c657-41ce-851c-5d65148bb73f" : mount failed: exit status 32
```

When we manually attached that volume to another instance and checked volume partition and try to mount it we get following info for this volume:
```
fdisk -l /dev/nvme2n1
Disk /dev/nvme2n1: 500 GiB, 536870912000 bytes, 1048576000 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 6605D1BE-86AC-4563-857E-F25F7E8519C6Device         Start        End    Sectors  Size Type
/dev/nvme2n1p1  2048 1048573951 1048571904  500G Microsoft basic data
...
mount /dev/nvme2n1 /mnt/
mount: /mnt: wrong fs type, bad option, bad superblock on /dev/nvme2n1, missing codepage or helper program, or other error.
```

So the conclusion is that something happened with that volume and instead having ext4 volume it was corrupted and formatted somehow as `Microsoft basic data` partition.
Any idea how this may happen ? 
Is it possible that AWS EBS driver format volume with wrong fs type and partition was destroyed ?
We have contacted AWS support, but they didn't provide some value traces.
This happen for second time this week for different volumes volumes for the same cluster.

**What you expected to happen?**
AWS PV volume to be mounted properly in pod with correct ext4 fs.

**How to reproduce it (as minimally and precisely as possible)?**
It is difficult to be reproduces as this happen in very rear cases, but is something which happens from time to time and volume partitions and data is lost.

**Anything else we need to know?**:
N/A

**Environment**
- Kubernetes version (use `kubectl version`): v1.20.11
- Driver version: I suppose version is built-in Kuberneres v1.20.11 ?
- Kops version: 1.20.2

**Comment by wongma7** [comment]
> I suppose version is built-in Kuberneres v1.20.11 ?
have you installed the CSI driver and enabled CSI migration? If not, then the driver doing the mount and format is probably the "in-tree" driver https://github.com/kubernetes/kubernetes/tree/master/pkg/volume/awsebs. But this repo is for the CSI driver which is different. So we have to determine which one it is first to know where to look for logs

**Comment by fierman333** [comment]
@wongma7 I am not sure about that details. We are using Kubernetes 1.20.2 which is managed by kops 1.20.2 so I suppose driver us build-in Kubernetes ?
For sure I can see logs from `aws-ebs-csi-driver/vendor/k8s.io/mount-utils//mount_linux.go` in `etcd-manager` pods which I suppose is responsible for master nodes volumes management.

**Comment by fierman333** [comment]
Folks you can close this issue. We found the reason for this issue and it is related to our code bug which affected Kubernetes PVC volumes,
