### ISSUE TITLE
Incorrect partition is picked while mounting a volume created from an existing EBS volume snapshot

### ISSUE THREAD

**Issue by kanchwala-yusuf** [kubernetes-sigs/aws-ebs-csi-driver#1168]
/kind bug

**What happened?**
I am trying to import an existing ebs volume snapshot created from an ec2 instance and mount the reclaimed volume inside a pod using pvc. But, the pod is stuck in `ContainerCreating` state and I see the following error in `kubectl describe pod`
```
Events:
  Type     Reason                  Age               From                     Message
  ----     ------                  ----              ----                     -------
  Normal   Scheduled               26s               default-scheduler        Successfully assigned default/pod-restore to ip-192-168-55-69.ap-south-1.compute.internal
  Normal   SuccessfulAttachVolume  24s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-998b31cd-49c2-4f25-90d9-2ba6a65d2c93"
  Warning  FailedMount             3s (x5 over 10s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-998b31cd-49c2-4f25-90d9-2ba6a65d2c93" : rpc error: code = Internal desc = could not format "/dev/nvme2n1" and mount it at "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-998b31cd-49c2-4f25-90d9-2ba6a65d2c93/globalmount": mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/nvme2n1 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-998b31cd-49c2-4f25-90d9-2ba6a65d2c93/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-998b31cd-49c2-4f25-90d9-2ba6a65d2c93/globalmount: wrong fs type, bad option, bad superblock on /dev/nvme2n1, missing codepage or helper program, or other error.
```
**It seems that the wrong device is being mounted.** On ssh-ing into the k8s node and checking the `fdisk -l` output shows
```
Disk /dev/nvme2n1: 8 GiB, 8589934592 bytes, 16777216 sectors   <<<<<<<<<< kubelet tries to mount /dev/nvme2n1 and fails
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x24ca9e81

Device         Boot Start      End  Sectors Size Id Type
/dev/nvme2n1p1 *     2048 16777182 16775135   8G 83 Linux     <<<<<<<<<<<< kubelet should actually mount /dev/nvme2n1p1
```

**What you expected to happen?**
Correct partition should be mounted into the kubelet and the pod to should get into `Running` state

**How to reproduce it (as minimally and precisely as possible)?**
1. Create an EKS cluster
2. Install the VolumeSnapshot CRDs and Volume Snapshot Controller
3. Install the EBS CSI driver
4. Create a StorageClass for the ebs csi driver
5. Create a VolumeSnapshotClass
6. Create VolumeSnapshotContent (specifying the existing snapshot handle), VolumeSnapshot, PVC, POD followed https://kubernetes.io/blog/2020/12/10/kubernetes-1.20-volume-snapshot-moves-to-ga/#importing-an-existing-volume-snapshot-with-kubernetes

I followed the below reference:
- https://aws.amazon.com/blogs/containers/using-ebs-snapshots-for-persistent-storage-with-your-eks-cluster
- https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi-self-managed-add-on.html
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1065#issuecomment-951883326

**Anything else we need to know?**:
It seems that incorrect device (`/dev/nvme2n1`) is being mounted, the device with partition (`/dev/nvme2n1p1`) should be mounted by the kubelet.

**Environment**
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version:
```
helm -n kube-system list
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
aws-ebs-csi-driver      kube-system     1               2022-02-15 12:30:10.07408 +0530 IST     deployed        aws-ebs-csi-driver-2.6.2        1.5.0      
```

**Comment by neiljain** [comment]
we ran into the same issue on kops 
`Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}`

csi driver version used:
provider-aws/aws-ebs-csi-driver:v1.7.0
sig-storage/csi-provisioner:v3.1.0
sig-storage/csi-attacher:v3.4.0
sig-storage/csi-resizer:v1.4.0
sig-storage/livenessprobe:v2.5.0

Bound     pvc-9454c295-ca39-4240-815c-9711ec41be61   50Gi       RWO

```
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            ebs.csi.aws.com
    FSType:            ext4
    VolumeHandle:      vol-nnnnn
    ReadOnly:          false
    VolumeAttributes:      storage.kubernetes.io/csiProvisionerIdentity=nnnn-nnnn-ebs.csi.aws.com
```
    
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
mountOptions:
- tls
parameters:
  encrypted: "true"
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate    
```

```
  Warning  FailedMount             kubelet                  MountVolume.MountDevice failed for volume "pvc-9454c295-ca39-4240-815c-9711ec41be61" : rpc error: code = Internal desc = could not format "/dev/nvme2n1" and mount it at "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-9454c295-ca39-4240-815c-9711ec41be61/globalmount": mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o tls,defaults /dev/nvme2n1 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-9454c295-ca39-4240-815c-9711ec41be61/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-9454c295-ca39-4240-815c-9711ec41be61/globalmount: wrong fs type, bad option, bad superblock on /dev/nvme2n1, missing codepage or helper program, or other error.
```

**Comment by neiljain** [comment]
when we changed the storage class to set 
volumeBindingMode: WaitForFirstConsumer

and also removed mountOptions: tls 
as per https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/examples/kubernetes/dynamic-provisioning/manifests/storageclass.yaml#L6

it works
