### ISSUE TITLE
Add Storage Class to static_provisioning example

### ISSUE THREAD

**Issue by pptb-aws** [kubernetes-sigs/aws-ebs-csi-driver#1172]
**Is your feature request related to a problem?/Why is this needed**

The static_provisioning example does not have a storageclass in the example. This may result in confusion for people when looking at this example when all others have storageclasses.

/feature

**Describe the solution you'd like in detail**

Add a storageclass object to the example.

**Describe alternatives you've considered**

If there is a reason not to include a storageclass, please add it to the readme

**Additional context**

**Comment by wongma7** [comment]
why? i removed it for precisely the same reason, because it is confusing https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/794. storageclass dictates how volumes get dynamically provisioned. In the static provisioning case, it does not do anything

**Comment by pptb-aws** [comment]
Why I attempt to run the example without a storage class I get this error in the pvc,

```
Events:
  Type    Reason         Age                From                         Message
  ----    ------         ----               ----                         -------
  Normal  FailedBinding  13s (x5 over 59s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```

Running in EKS 1.21 with managed nodegroup.

Reproduction steps,

1. get the example.yaml file, update the volumeHandle in the pv to use a pre-created volume created using the CLI
2.  run using kubectl apply -f example.yaml

After some testing the fix is either to add a StorageClass or to add, volumeName: test-pv, to the pvc.  I am inclined to agree that not using the StorageClass does highlight a feature of static provisioning.  Please let me know if you agree @wongma7.

**Comment by torredil** [comment]
Hi @pptb-aws thanks for your feedback. Recent changes were made that address this issue. Can you please try out the static provisioning example with the updated instructions/manifest files and provide further feedback? Thanks.

**Comment by pptb-aws** [comment]
instructions work for me.  I am closing this, thank you for the explanations and assistance.
