### ISSUE TITLE
Image scan has detect several vulnerabilities

### ISSUE THREAD

**Issue by albertschwarzkopf** [kubernetes-sigs/aws-ebs-csi-driver#1173]
/kind bug

**What happened?**

Trivy image scanner has follwing findings:

```
trivy image -f table -o /tmp/aws_ebs_csi_driver k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.2.1          
2022-02-22T11:59:13.940+0100	INFO	Detected OS: debian
2022-02-22T11:59:13.941+0100	INFO	Detecting Debian vulnerabilities...
2022-02-22T11:59:13.963+0100	INFO	Number of language-specific files: 1
2022-02-22T11:59:13.963+0100	INFO	Detecting gobinary vulnerabilities...

k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.2.1 (debian 10.10)
================================================================
Total: 202 (UNKNOWN: 0, LOW: 110, MEDIUM: 44, HIGH: 35, CRITICAL: 13)


bin/aws-ebs-csi-driver (gobinary)
=================================
Total: 6 (UNKNOWN: 1, LOW: 1, MEDIUM: 3, HIGH: 1, CRITICAL: 0)
```

Also if I use the latest image:

```
trivy image -f table -o /tmp/aws_ebs_csi_driver_latest k8s.gcr.io/provider-aws/aws-ebs-csi-driver:latest
2022-02-22T12:00:28.413+0100	INFO	Detected OS: debian
2022-02-22T12:00:28.413+0100	INFO	Detecting Debian vulnerabilities...
2022-02-22T12:00:28.428+0100	INFO	Number of language-specific files: 1
2022-02-22T12:00:28.428+0100	INFO	Detecting gobinary vulnerabilities...

k8s.gcr.io/provider-aws/aws-ebs-csi-driver:latest (debian 10.5)
===============================================================
Total: 240 (UNKNOWN: 0, LOW: 110, MEDIUM: 58, HIGH: 50, CRITICAL: 22)


bin/aws-ebs-csi-driver (gobinary)
=================================
Total: 15 (UNKNOWN: 1, LOW: 1, MEDIUM: 11, HIGH: 2, CRITICAL: 0)

```
[aws_ebs_csi_v1.2.1.txt](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/files/8116033/aws_ebs_csi_v1.2.1.txt)
[aws_ebs_csi_latest.txt](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/files/8116037/aws_ebs_csi_latest.txt)

**What you expected to happen?**

Fix the "HIGH" and "CRITICAL" vulnerabilities please.

**Comment by gtxu** [comment]
Hi @albertschwarzkopf, for CVEs, we usually release a new patch version to fix them, and images on GCR will soon out of maintains and been redirected to ECR Public. I recommend you to use latest version on [ECR Public](https://gallery.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver). Thank you for raising up this security concern!

**Comment by albertschwarzkopf** [comment]
@gtxu thank you for the hint. But we use your helm chart. The registry is defined there.

**Comment by bkh4mmm** [comment]
The sidecar containers need to be updated as well--the defaults in the values file point to k8s.gcr.io for the sidecars and those are not hosted on ECR Public AFAICT.

**Comment by albertschwarzkopf** [comment]
Thank you! I will close this issue.
