### ISSUE TITLE
Have to recreate aws-ebs-csi-driver to create aws volume snapshot and bound it to pvc 

### ISSUE THREAD

**Issue by a-dimitrov** [kubernetes-sigs/aws-ebs-csi-driver#1180]
/kind bug
Hello team ,

**What happened?**
I have a Kubernetes cluster with ebs-csi-driver (latest version 2.6.3) and I am trying to build a new replication set and bound some Physical volume claims to the set build from AWS snapshot. For this purpose I am using external snapshotter deployed this way:
`kubectl create -f  https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
kubectl create -f  https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
kubectl create -f  https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
kubectl create -f  https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
kubectl create -f  https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml`

When I  create the volume snapshot class/snapshot(vs)/content(vsc) the vsc and snapshot are in "ready to use" false status and they stay like this, until I recreate the aws-ebs-csi-driver. Once recreated the vs gets in "ready to use" true state and I am able to bound the pvc to the replica set pods

**What you expected to happen?**
I am expecting the aws-ebs-csi-driver to get the vs ready to use without recreating.

**How to reproduce it (as minimally and precisely as possible)?**
Use Kubernetes cluster 1.21 with aws-ebs-csi-driver 2.6.3 (also reproducible  with 2.6.2), deploy external-snapshotter from the above code block. Create volume claims, vsclass, vs and vsc as:

PVC:
`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: name
  namespace: sisense
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-retain
  resources:
    requests:
      storage: 5Gi
  dataSource:
    name: name-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io`

vsclass:
`apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: name-class
driver: ebs.csi.aws.com 
deletionPolicy: Delete`

vs:
`apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: name-snapshot
  namespace: sisense 
spec:
  volumeSnapshotClassName: name-class
  source:
    volumeSnapshotContentName: name-content`

vsc:
`apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: name-content
  namespace: sisense
spec:
  volumeSnapshotRef:
    kind: VolumeSnapshot
    name: name-snapshot
    namespace: sisense
  source:
    snapshotHandle: snap-id
  driver: ebs.csi.aws.com
  deletionPolicy: Delete
  volumeSnapshotClassName: name-class`

**Anything else we need to know?**:
external-snapshoter 5.0

**Environment**
- Kubernetes version (use `kubectl version`): 1.21
- Driver version: 2.6.3

**Comment by a-dimitrov** [comment]
nope, still facing the issue and recreating when needed. It's not much effort, but still it is annoying.

**Comment by ahmadhajali80** [comment]
@a-dimitrov could you please share with the charts you have deployed and in which namespace you deployed it?
I deployed the following:

1. VolumeSnapshot CRDs
2. sanpshot-controller referencing csi-snapshotter:v3.0.3 docker image as a deployment in kube-system
3. ebs-csi-controller deployment that contains the following containers: aws-ebs-csi-driver:v1.4.0, csi-provisioner:v2.1.1, csi-attacher:v3.1.0 and livenessprobe:v2.2.0
4. Deploy AWS EBS CSI driver

Then I do the following:
1. Deploy VolumeSnapshot and VolumeSnapshotContent that referencing a snapshot ID from AWS snapshots.
2. Deploy MonogDB sts with a PVC that referencing the VolumeSnapshot from #1.

The MongoDB sts deployed successfully and the PVCs have been created but not on top of the snapshot ID. When I checked the PV I did not see any value of the snapshot ID in the PV properties.

Any idea what causing my issue?
