### ISSUE TITLE
Upgrade driver to be CSI 1.0 compliant

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#119]
**Is your feature request related to a problem?/Why is this needed**
CSI 1.0 is released: https://github.com/container-storage-interface/spec/blob/release-1.0/spec.md
The driver should be upgraded to be compatible with it.

TODOs:
 - [x] upgrade driver (#122)
 - [x] update documentation of compatibility matrix (#147)

/kind feature
/kind cleanup
/kind documentation

**Comment by bertinatto** [comment]
Code changes are addressed at #122.

**Comment by leakingtapan** [comment]
Documentation changes are addressed in #147
