### ISSUE TITLE
helm chart csi-snapshotter conditional not working as intended 

### ISSUE THREAD

**Issue by smark88** [kubernetes-sigs/aws-ebs-csi-driver#1192]
/kind bug

**What happened?**
This conditional is not working when rendering, I have the crds install and running and the chart will not render this 
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/controller.yaml#L196

**What you expected to happen?**
It should render the csi driver. I think adding a conditional for a bool is probably better as people will know if they want the snapshotter ahead of time.

**How to reproduce it (as minimally and precisely as possible)?**
install crds from https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd
try installing helm chart

**Anything else we need to know?**:

**Environment**
v1.20.11-eks-f17b81 Amazon Linux 2   5.4.176-91.338.amzn2.x86_64   docker://20.10.7
```
❯ k get crds | grep snap
volumesnapshotclasses.snapshot.storage.k8s.io    
volumesnapshotcontents.snapshot.storage.k8s.io    
volumesnapshots.snapshot.storage.k8s.io   
```

- Driver version:
1.5.0

**Comment by gtxu** [comment]
Hi @smark88, can you check if you have installed the common-snapshot-controller along with the CRDs? Thanks!

**Comment by smark88** [comment]
I have the following installed. I am using the external-snapshotter along with the CRDs

```
image:k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.5.1
image:k8s.gcr.io/sig-storage/csi-provisioner:v2.1.1
image:k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
image:k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
image:k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
image:k8s.gcr.io/sig-storage/livenessprobe:v2.4.0
image:gcr.io/k8s-staging-sig-storage/snapshot-controller:v5.0.1
image:k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.5.1
image:k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
image:k8s.gcr.io/sig-storage/livenessprobe:v2.4.0
```
