### ISSUE TITLE
StorageClass with paramter tagSpecification_1  leads to Invalid parameter key tagSpecification_1 for CreateVolume

### ISSUE THREAD

**Issue by youwalther65** [kubernetes-sigs/aws-ebs-csi-driver#1201]
/kind bug

**What happened?**
Not able to create EBS volume with tag using parameters tagSpecification_1 as described in documentation [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/TAGGING.md):

**What you expected to happen?**
Creation of a tagged dynamic PV

**How to reproduce it (as minimally and precisely as possible)?**
$ cat pvc1-gp3.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gp3-pvc1
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

$ cat pvc1-gp3-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pvc1-pod
spec:
  volumes:
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: gp3-pvc1
  containers:
    - name: pvc-container
      image: busybox
      args: ["sleep","3600"]
      volumeMounts:
        - mountPath: "/data"
          name: pvc-storage

$ k get sc gp3 -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2022-04-07T06:14:11Z"
  labels:
    kustomize.toolkit.fluxcd.io/name: dependend-csi-resources
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: gp3
  resourceVersion: "6361123"
  uid: d31f0ff7-e30c-4371-8445-73eff3d062a5
parameters:
  encrypted: "true"
  kmsKeyId: arn:aws:kms:eu-west-1:<redacted>:key/d6d6f23b-b77b-431f-a54e-4da1bbbf4b79
  tagSpecification_1: auto-delete=no
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

k describe pvc gp3-pvc1
  Normal   Provisioning          3m58s (x9 over 8m13s)   ebs.csi.aws.com_ebs-csi-controller-586f479d78-rvsck_71cd338f-ef35-483c-afaa-2ae3edbf00b5  External provisioner is provisioning volume for claim "default/gp3-pvc1"
  Warning  ProvisioningFailed    3m58s (x2 over 6m6s)    ebs.csi.aws.com_ebs-csi-controller-586f479d78-rvsck_71cd338f-ef35-483c-afaa-2ae3edbf00b5  failed to provision volume with StorageClass "gp3": rpc error: code = InvalidArgument desc = Invalid parameter key tagSpecification_1 for CreateVolume

**Anything else we need to know?**:

**Environment** AWS dev
- Kubernetes version (use `kubectl version`): EKS 1.21
- Driver version: 1.5.1 vial Helm chart 2.6.4

**Comment by youwalther65** [comment]
Thanks for the fast response. But then I would suggest updating the docs because it sounded like an available Feature

**Comment by rdpsin** [comment]
Yes, I've updated the docs to mention it'll be available in v1.6.0 and later. (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1202)

**Comment by gkaskonas** [comment]
When is v1.6.0 going to be available?

**Comment by rdpsin** [comment]
@gkaskonas It should be available in a couple of weeks.

**Comment by rdpsin** [comment]
v1.6.0 is now available.

**Comment by rishabhsinghvi** [comment]
Closing this since the new release is now available with tag support. 

/close
