### ISSUE TITLE
evalsymlink failure on

### ISSUE THREAD

**Issue by Preen** [kubernetes-sigs/aws-ebs-csi-driver#1223]
/kind bug

**What happened?**
```
 kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/alpha/?ref=master"
error: evalsymlink failure on '/private/var/folders/dc/dzh1vv214nj2hk8tt_3jtxrw0000gn/T/kustomize-2785750766/deploy/kubernetes/overlays/alpha' : lstat /private/var/folders/dc/dzh1vv214nj2hk8tt_3jtxrw0000gn/T/kustomize-2785750766/deploy/kubernetes/overlays/alpha: no such file or directory
```

**What you expected to happen?**
csidriver.storage.k8s.io/ebs.csi.aws.com created

**How to reproduce it (as minimally and precisely as possible)?**
create cluster in `eu-north-1` and run above command after creating iam etc.

**Anything else we need to know?**:
it worked if I used 1.5 version. `github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.5`. 

**Environment**
```Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-14c7a48", GitCommit:"35f06c94ad99b78216a3d8e55e04734a85da3f7b", GitTreeState:"clean", BuildDate:"2022-04-01T03:18:05Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"```

**Comment by rdpsin** [comment]
Seems like you're using `overlays/alpha` which doesn't exist. You used `overlays/stable` for 1.5. Can you try using `overlays/stable` to see if it works?
