### ISSUE TITLE
Support startup taint

### ISSUE THREAD

**Issue by sylr** [kubernetes-sigs/aws-ebs-csi-driver#1232]
**Is your feature request related to a problem?/Why is this needed**

I'd like the [aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) to implement a startup taint mechanism.

/feature

**Describe the solution you'd like in detail**

When you are dealing with clusters where nodes come and go often we want to ensure that those new nodes have all the required components before the actual workloads are started.

Cilium for example recommends that all nodes spawned in a cluster be added the taint `node.cilium.io/agent-not-ready=true:NoExecute`. The cilium agent, which is a required component in a cilium based cluster, tolerates that taint and, upon startup completion of the agent, removes the taint on the node so that the workload can be started with a network stack up and running.

When I start new nodes in a EKS / Karpenter / Cilium based cluster, it happens that workloads requiring mounting an EBS volume starts before the aws-ebs-csi-driver and the workloads enter a backoff loop which can be long.

I'd like to prevent that by adding a new startup taint to my new nodes, e.g.: **`ebs.csi.aws.com/agent-not-ready=true:NoExecute`** and I would like that this taint be removed upon aws-ebs-csi-driver startup completion.

**Comment by torredil** [comment]
Thanks for the request, this feature will be available in 1.19.
/close
