### ISSUE TITLE
panic: could not get number of attached ENIs - Error noticed on node daemonset

### ISSUE THREAD

**Issue by vaibhav-ak** [kubernetes-sigs/aws-ebs-csi-driver#1237]
k8 version is 1.21

I'm trying to install the helm chart onto an EKS cluster running 1.21. 

All pods are fine except the deamonset (ebs-plugin) container only which is in CrachLoopBackoff. It has access to EC2 metadata to get info. I think it failing  while getting eni data. Any pointers on this will be of great help. 

Here are the logs

==========================================

0517 11:49:46.267260       1 metadata.go:85] retrieving instance data from ec2 metadata
I0517 11:49:46.273836       1 metadata.go:92] ec2 metadata is available
panic: could not get number of attached ENIs

github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newNodeService(0xc0000c3180)
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/node.go:86 +0x269
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver({0xc00013ff30, 0x8, 0x55})
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:95 +0x38e
main.main()
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:46 +0x365

===========================================

**Comment by torredil** [comment]
Hi, can you please fill out the bug report template? https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Be sure to include K8s and driver versions. If possible, also provide your deployment or a sample, and instance type (Nitro?) Thanks.
