### ISSUE TITLE
Race condition with cluster-autoscaler

### ISSUE THREAD

**Issue by jimethn** [kubernetes-sigs/aws-ebs-csi-driver#1246]
/kind bug

**What happened?**

What I'm seeing is the cluster-autoscaler keeps trying to delete a node, one of the pods there gets stuck in Terminating state, and then cluster-autoscaler eventually gives up (with the message `Failed to delete ip-10-28-103-222.us-west-2.compute.internal: Failed to drain node /ip-10-28-103-222.us-west-2.compute.internal: pods remaining after timeout`) and un-taints the node.

When I `describe` the Terminating pod, it has no finalizers, and all the containers are in `State: Terminated`. So I checked the kubelet logs to see what's going on, and I see a bunch of errors like:

```
nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/ebs.csi.aws.com^vol-0eca1956c6260f0f3 podName:bbb12a45-a07c-4957-ad63-5f38c7db6775 nodeName:}" failed. No retries permitted until 2022-05-22 17:55:34.011742998 +0000 UTC m=+862790.775524064 (durationBeforeRetry 2m2s). Error: "UnmountVolume.TearDown failed for volume \"prometheus-prometheus-operator-prometheus-db\" (UniqueName: \"kubernetes.io/csi/ebs.csi.aws.com^vol-0eca1956c6260f0f3\") pod \"bbb12a45-a07c-4957-ad63-5f38c7db6775\" (UID: \"bbb12a45-a07c-4957-ad63-5f38c7db6775\") : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name ebs.csi.aws.com not found in the list of registered CSI drivers"
```

So I think what's happening is the ebs-csi-node pod is getting evicted before the other pod finishes terminating, and then it will never terminate because component that handles the volume cleanup is already gone.

**What you expected to happen?**

All the volumes should get unmounted and the node should be deleted.

**How to reproduce it (as minimally and precisely as possible)?**

It should be able to be reproduced without cluster-autoscaler, by just manually following the process:

1. Have a node with a pod that has a PVC
2. Taint the node
3. Delete all the pods on the node
4. If the ebs-csi-node pod gets deleted before the PVC pod finishes terminating, then the PVC pod should get stuck Terminating forever

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): v1.21.9-eks
- Driver version: v1.5.0

**Comment by torredil** [comment]
Hi @jimethn 👋 
When draining a node with `kubectl drain` DaemonSet pods do not get removed (see relevant documentation [here](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#drain)). If the cluster-autoscaler has a different behavior (and cannot be configured to behave similarly to `kubectl drain`) you would need to report that issue to the [cluster-autoscaler](https://github.com/kubernetes/autoscaler) project. The EBS CSI Driver will not stop itself from getting removed via the kubernetes API.

If [cluster-autoscaler](https://github.com/kubernetes/autoscaler) has an annotation or similar mechanism to indicate our pods should not be deleted when scaling down a node we can apply those to our official manifests and helm charts, let me know!
