### ISSUE TITLE
Unable to create CSI snapshot-EBS csi driver

### ISSUE THREAD

**Issue by keerthana1608** [kubernetes-sigs/aws-ebs-csi-driver#1249]
/kind bug

**What happened?**
Unable to create CSI snapshot 

**What you expected to happen?**
Should be able to create CSI driver snapshot without any failure.

**How to reproduce it (as minimally and precisely as possible)?**
Install the latest 1.5(1.5.3) or 1.6(1.6.2) ebs csi driver on EKS clsuter. Try creating the volumesnapshot.

**Anything else we need to know?**:
We are seeing following constant error in controller logs:
E0523 16:45:25.101262       1 reflector.go:127] k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1beta1.VolumeSnapshotContent: failed to list *v1beta1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
E0523 16:45:25.101335       1 reflector.go:127] k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1beta1.VolumeSnapshotClass: failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)

**Environment**
- Kubernetes version (use `kubectl version`):
 Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-eks-14c7a48", GitCommit:"717bfb2b8ceb809a42a6c0baabde59fae28637ef", GitTreeState:"clean", BuildDate:"2022-04-01T03:17:28Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

- Driver version: 1.5.3, 1.6.2
[csi-snapshotter_logs.txt](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/files/8757071/csi-snapshotter_logs.txt)

**Comment by torredil** [comment]
Hi @keerthana1608 👋

Have you installed the external-snapshotter sidecar? If you intend to use the csi-snapshotter functionality, you will need to first install the [CSI Snapshotter](https://github.com/kubernetes-csi/external-snapshotter).

**Comment by sgatdell** [comment]
> Hi @keerthana1608 👋
> 
> Have you installed the external-snapshotter sidecar? If you intend to use the csi-snapshotter functionality, you will need to first install the [CSI Snapshotter](https://github.com/kubernetes-csi/external-snapshotter).

@torredil  Yes, the external snapshotter was installed. The same tests were working fine with CSI driver 1.5.1 when this was tested previously a while back.

**Comment by rdpsin** [comment]
Looks like the snapshot CRDs are not installed. 

Can you try installing them with: 

```
kubectl kustomize client/config/crd | kubectl create -f -
```

**Comment by phuongatemc** [comment]
What we observed is the VolumeSnapshot was created and the associated VolumeSnapshotContent also created but the EBS CSI Driver does not show any action (in the log) that it starts working on the VolumeSnapshotContent so the VolumeSnapshot and VolumeSnapshotContent are just hanging there.
We ran "kubectl logs -n kube-system ebs-csi-controller-xxx csi-snapshotter" and see that it keep repeating that error mentioned in bug description.  
We checked the API version VolumeSnapshot and VolumeSnapshotContent.  Both are v1.
We also ran "kubectl get crd volumesnapshotcontent -o yaml" and check to see if there is any "v1beta1" at all but see nothing except v1.  Not sure why the csi-snapshotter log keeps refering to v1beta1 and not recognize the VolumeSnapshotContent being created.

**Comment by tgip-work** [comment]
Same behaviour for me as reported by @phuongatemc

**Comment by gtxu** [comment]
Hi @phuongatemc @sgatdell @tgip-work, [This PR](https://github.com/kubernetes-csi/external-snapshotter/pull/718) will fix the API version issue on sidecar. Updating the snapshot controller CRDs after this PR will fix it, for long term we will bump up our snapshotter sidecar version to make sure the API V1 works.

**Comment by keerthana1608** [comment]
@gtxu 
 I picked the latest snapshot CRDs from https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd. 
Still seeing the same issue

**Comment by tgip-work** [comment]
### SHORT UPDATE and good news!

A snapshot has been created:

```
Events:
  Type    Reason           Age    From                 Message
  ----    ------           ----   ----                 -------
  Normal  SnapshotCreated  2m10s  snapshot-controller  Snapshot default/ebs-volume-snapshot was successfully created by the CSI driver.
  Normal  SnapshotReady    105s   snapshot-controller  Snapshot default/ebs-volume-snapshot is ready to use.
```

**Summary: What I needed to change:**

1. Using latest helm chart 2.6.8 with csi-snapshotter image `v6.0.1` (instead of v3.0.3 which is the default). The managed EKS addon does not seem to work as I cannot customize the image thats being used for the CSI Snapshotter sidecar container.
2. Manually added verb "patch" to ClusterRole `ebs-external-snapshotter-role`

### Step by Step

**1. My helm values file `myvalues.yaml` :**

```
controller:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ARN OF THE IAM ROLE - See https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html

sidecars:
  snapshotter:
    image:
      tag: "v6.0.1"
```

**2. Helm Installation**

```
helm upgrade --install aws-ebs-csi-driver     --namespace kube-system     --version 2.6.8     -f myvalues.yaml     aws-ebs-csi-driver/aws-ebs-csi-driver
```

**3. ClusterRole ebs-external-snapshotter-role**

Due to error

```
  Type     Reason                  Age                From                             Message
  ----     ------                  ----               ----                             -------
  Warning  SnapshotCreationFailed  27m (x4 over 27m)  csi-snapshotter ebs.csi.aws.com  Failed to create snapshot: failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-cfca045d-559b-4075-9200-ba6270fe59e2: "snapshot controller failed to update snapcontent-cfca045d-559b-4075-9200-ba6270fe59e2 on API server: volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-cfca045d-559b-4075-9200-ba6270fe59e2\" is forbidden: User \"system:serviceaccount:kube-system:ebs-csi-controller-sa\" cannot patch resource \"volumesnapshotcontents\" in API group \"snapshot.storage.k8s.io\" at the cluster scope"

```

I added the verb `patch` to resource `volumesnapshotcontents`:

```
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
  - patch
```

**4. Then I had to restart the pods `ebs-csi-controller-*` in namespace `kube-system` in order to reflect the ClusterRole change as quick as possible.**

**Comment by gtxu** [comment]
Hi @tgip-work, thanks for the attempt and detailed description on the solution. The latest snapshot controller(deployed with CRDs) includes several changes that does not works well with the external-snapshotter sidecar lower than v6.0.0+. We will update the helm to use latest external-snapshotter after testing.

**Comment by gtxu** [comment]
Plus if you install & manage your EBS CSI Driver with Helm, I recommend pulling sidecar images from GCR currently.
```
k8s.gcr.io/sig-storage/livenessprobe
k8s.gcr.io/sig-storage/csi-node-driver-registrar
k8s.gcr.io/sig-storage/csi-resizer
k8s.gcr.io/sig-storage/csi-attacher
k8s.gcr.io/sig-storage/csi-provisioner
k8s.gcr.io/sig-storage/csi-snapshotter
```

**Comment by skrbug** [comment]
@tgip-work  I try this. Still seeing the same issue. ebs-csi-controller/csi-snapshotter can't found snapshot 
> ### SHORT UPDATE and good news!
> A snapshot has been created:
> 
> ```
> Events:
>   Type    Reason           Age    From                 Message
>   ----    ------           ----   ----                 -------
>   Normal  SnapshotCreated  2m10s  snapshot-controller  Snapshot default/ebs-volume-snapshot was successfully created by the CSI driver.
>   Normal  SnapshotReady    105s   snapshot-controller  Snapshot default/ebs-volume-snapshot is ready to use.
> ```
> 
> **Summary: What I needed to change:**
> 
> 1. Using latest helm chart 2.6.8 with csi-snapshotter image `v6.0.1` (instead of v3.0.3 which is the default). The managed EKS addon does not seem to work as I cannot customize the image thats being used for the CSI Snapshotter sidecar container.
> 2. Manually added verb "patch" to ClusterRole `ebs-external-snapshotter-role`
> 
> ### Step by Step
> **1. My helm values file `myvalues.yaml` :**
> 
> ```
> controller:
>   serviceAccount:
>     annotations:
>       eks.amazonaws.com/role-arn: ARN OF THE IAM ROLE - See https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html
> 
> sidecars:
>   snapshotter:
>     image:
>       tag: "v6.0.1"
> ```
> 
> **2. Helm Installation**
> 
> ```
> helm upgrade --install aws-ebs-csi-driver     --namespace kube-system     --version 2.6.8     -f myvalues.yaml     aws-ebs-csi-driver/aws-ebs-csi-driver
> ```
> 
> **3. ClusterRole ebs-external-snapshotter-role**
> 
> Due to error
> 
> ```
>   Type     Reason                  Age                From                             Message
>   ----     ------                  ----               ----                             -------
>   Warning  SnapshotCreationFailed  27m (x4 over 27m)  csi-snapshotter ebs.csi.aws.com  Failed to create snapshot: failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-cfca045d-559b-4075-9200-ba6270fe59e2: "snapshot controller failed to update snapcontent-cfca045d-559b-4075-9200-ba6270fe59e2 on API server: volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-cfca045d-559b-4075-9200-ba6270fe59e2\" is forbidden: User \"system:serviceaccount:kube-system:ebs-csi-controller-sa\" cannot patch resource \"volumesnapshotcontents\" in API group \"snapshot.storage.k8s.io\" at the cluster scope"
> ```
> 
> I added the verb `patch` to resource `volumesnapshotcontents` - also see #1243
> 
> ```
> - apiGroups:
>   - snapshot.storage.k8s.io
>   resources:
>   - volumesnapshotcontents
>   verbs:
>   - create
>   - get
>   - list
>   - watch
>   - update
>   - delete
>   - patch
> ```
> 
> **4. Then I had to restart the pods `ebs-csi-controller-*` in namespace `kube-system` in order to reflect the ClusterRole change as quick as possible.**
> 
> ### Appendix
> In case you want the helm release exactly look like the EKS managed addon (except 1. aws-ebs-csi-driver 1.6.2 instead of 1.6.1 and 2. csi-snapshotter 6.0.1 instead of 3.0.3) , you can use these helm values.
> 
> ```yaml
> image:
>   repository: 602401143452.dkr.ecr.<REGION>.amazonaws.com/eks/aws-ebs-csi-driver
> 
> controller:
>   k8sTagClusterId: <CLUSTER_ID>
>   region: <REGION>
>   serviceAccount:
>     annotations:
>       eks.amazonaws.com/role-arn: <ROLE_ARN>
>   affinity:
>     podAntiAffinity:
>       preferredDuringSchedulingIgnoredDuringExecution:
>       - podAffinityTerm:
>           labelSelector:
>             matchExpressions:
>             - key: app
>               operator: In
>               values:
>               - ebs-csi-controller
>           topologyKey: kubernetes.io/hostname
>         weight: 100
>   updateStrategy:
>     type: RollingUpdate
>     rollingUpdate:
>       maxSurge: 25%
>       maxUnavailable: 1
>   resources:
>     limits:
>       cpu: 100m
>       memory: 128Mi
>     requests:
>       cpu: 10m
>       memory: 40Mi
> 
> node:
>   resources:
>     limits:
>       cpu: 100m
>       memory: 128Mi
>     requests:
>       cpu: 10m
>       memory: 40Mi
> 
> 
> sidecars:
>   provisioner:
>     image:
>       repository: 602401143452.dkr.ecr.<REGION>.amazonaws.com/eks/csi-provisioner
>     resources:
>       limits:
>         cpu: 100m
>         memory: 128Mi
>       requests:
>         cpu: 10m
>         memory: 40Mi
>   attacher:
>     image:
>       repository: 602401143452.dkr.ecr.<REGION>.amazonaws.com/eks/csi-attacher
>     resources:
>       limits:
>         cpu: 100m
>         memory: 128Mi
>       requests:
>         cpu: 10m
>         memory: 40Mi
>   snapshotter:
>     image:
>       #repository: 602401143452.dkr.ecr.<REGION>.amazonaws.com/eks/csi-snapshotter
>       repository: k8s.gcr.io/sig-storage/csi-snapshotter
>       tag: "v6.0.1"
>     resources:
>       limits:
>         cpu: 100m
>         memory: 128Mi
>       requests:
>         cpu: 10m
>         memory: 40Mi
>   resizer:
>     image:
>       repository: 602401143452.dkr.ecr.<REGION>.amazonaws.com/eks/csi-resizer
>     resources:
>       limits:
>         cpu: 100m
>         memory: 128Mi
>       requests:
>         cpu: 10m
>         memory: 40Mi
>   livenessProbe:
>     image:
>       repository: 602401143452.dkr.ecr.<REGION>.amazonaws.com/eks/livenessprobe
>     resources:
>       limits:
>         cpu: 100m
>         memory: 128Mi
>       requests:
>         cpu: 10m
>         memory: 40Mi
>   nodeDriverRegistrar:
>     image:
>       repository: 602401143452.dkr.ecr.<REGION>.amazonaws.com/eks/csi-node-driver-registrar
> ```

**Comment by skrbug** [comment]
I try this, it works well. 

**apply CRD old version**.  [v6.0.0-rc4](https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v6.0.0-rc4) 

csi-snapshotter  image use v3.0.3.  
I installed driver by helm. chart version  2.6.8
![origin_img_v2_55418a8f-612b-43be-bc0a-629c7cacbf6h](https://user-images.githubusercontent.com/49090950/171161496-f2972922-43c3-45b9-974b-c69b46e6c5cc.png)

@keerthana1608  @gtxu

**Comment by keerthana1608** [comment]
Updated to latest snapshotter sidecars and added verb patch to resource volumesnaphsotcontents. 
It works fine.
