### ISSUE TITLE
Staging images are pushed to community infra but tagged releases are not promoted

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/aws-ebs-csi-driver#1251]
/kind bug

**What happened?**

It seems like images are intentionally (?) no longer published to the kubernetes project's package host k8s.gcr.io (soon registry.k8s.io https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)), but images are still being built on community staging resources as of the current latest commit and I found no announcement about this change 

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/d3d40c794e22debf505c80219ecd2eb62bfb8dff => https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/aws-ebs-csi-driver-push-images/1527779711642505216

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1213/commits/ed901f73851f17a995cfd88eeb9b1cf36913c212#diff-9c4ae3b5f6675180493e9a1a817baabf4c5314870a3fa67c9c6ab89186046a91L65

https://github.com/kubernetes-sigs/aws-ebs-csi-driver#container-images

**What you expected to happen?**

I expected these images to be available on k8s.gcr.io, which broke the testing for registry-sandbox.k8s.io (the registry.k8s.io staging instance). https://testgrid.k8s.io/sig-k8s-infra-oci-proxy#kops-grid-gcr-mirror-canary

If that's no longer the case, IMHO aws-ebs-cis-driver should stop pushing to the now-unused community staging registry, saving community resources.

Some sort of announcement would have also been helpful, but I can't seem to find one.

/sig k8s-infra
/sig cloud-provider

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

See also this thread where we discover this https://kubernetes.slack.com/archives/C8MKE2G5P/p1651005000692509

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by BenTheElder** [comment]
> Is it even allowed to be in the kubernetes-sigs org but not push to k8s.gcr.io?

As far as I know, there's no restrictions on this.

> [...] expect it to normally be something reserved for at least a minor, maybe even major version bump.

+1, this caught us unaware.

FWIW in the case that brought this to my attention, we're able to simply not install the driver and disable CSI testing, but I can imagine how this is problematic in other cases like @noah-bidziil's

**Comment by wongma7** [comment]
sorry for confusion, no decision has been made yet. That link you see above is my placeholder for stopping pushing to GCR, I don't intend for it to merge until we make a decision here with everyone's input

**Comment by wongma7** [comment]
1. We decided to backfill the missing images 1.5.3-1.6.2. I just lgtm'd https://github.com/kubernetes/k8s.io/pull/3791
2. What we do for future releases is TBD.
  a. https://github.com/kubernetes/test-infra/pull/26452 is a placeholder for if we decide to stop pushing to GCR
  b. we can add GCR back to the release process if we decide to resume/continue pushing to GCR

**Comment by torredil** [comment]
@eddie621 Thanks for noting that v1.5.2 is not included in the PR. That is intentional - the image is not included in the [staging repo](https://console.cloud.google.com/gcr/images/k8s-staging-provider-aws/global/aws-ebs-csi-driver?project=k8s-staging-provider-aws).

**Comment by torredil** [comment]
@MurphyPuppy @eddie621 Thanks! yeah, there is no image for v1.5.2 in the [staging repo](https://console.cloud.google.com/gcr/images/k8s-staging-provider-aws/global/aws-ebs-csi-driver?project=k8s-staging-provider-aws), hence why I've excluded 1.5.2 from the PR. The release for 1.5.2 was aborted part-way through and we recommend running 1.5.3 (or later), as it is functionally identical to 1.5.2 but includes additional fixes and security patches.

I will provide an update regarding future releases and answer your questions as soon as I am able to - we are discussing the issue with the security team to get a better understanding of the situation, hoping to clear up everything soon. There will be no further unannounced changes, sorry again folks.

**Comment by torredil** [comment]
The missed publication to GCR of 1.5.3-1.6.2 was caused by an AWS-internal error. We have corrected the problem. Going forward, EBS CSI driver releases will continue to be published to ECR, ECR Public, and GCR. We apologize again for the inconvenience.

**Comment by torredil** [comment]
@eddie621 @MurphyPuppy Thanks for letting us know how this issue impacted your teams. We appreciate your feedback and it really helped drive this issue to a resolution.

**Comment by torredil** [comment]
Thank you @olemarkus for helping with promoting the images to GCR. I'll cc you in the PRs.
