### ISSUE TITLE
EKS Addon Contains CVEs

### ISSUE THREAD

**Issue by Skiertsamba** [kubernetes-sigs/aws-ebs-csi-driver#1266]
/kind bug

Hi, version 1.6.2 was released 17 days ago: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/releases/tag/v1.6.2

It contains a fix for ALAS-2022-1792, and we'd like to get that fix ASAP. However, it seems like releasing 1.6.2 via the EKS Addon mechanism was forgotten? The latest version I see on our account is 1.6.1.

Please if possible expedite the release, it's already been over two weeks since this CVE was announced publicly. If not possible, please release a hotfix to address this CVE asap (I don't need the new features in 1.6.2, just the security fix).

I figured I'd ask here first as this seems to be the quickest way to contact the aws-ebs-csi-driver team, but I can raise this issue with our AWS TAM if that would be preferable.

**Comment by Skiertsamba** [comment]
@torredil @gtxu @wmesard hi, sorry for the ping but I saw that you're all active AWS employees on this repository. Can somebody please look into this (or if there is some way to access 1.6.2 via the EKS addon that I missed let me know what to do)? I can't be the only customer that has the requirement that images cannot contain known vulnerabilities/CVEs.

**Comment by torredil** [comment]
Hi all, sorry for the delayed response. 

Unfortunately, the add-on release for `v1.6.2` has been significantly delayed due to an AWS internal process. Completely agree that it is not acceptable to wait any longer and as such we are currently working on releasing a new version of the add-on which addresses the CVE.

I highly encourage you reach out to your TAM and create a TT so that we can track this internally as well to help bring visibility/escalate this issue.

**Comment by Skiertsamba** [comment]
@torredil thanks for the update! No worries on whatever internal process is keeping you up, I understand these things take time. Although publishing 1.6.2 is one way this could obviously be solved, if that is impossible please instead use a different method:

Just rebuild 1.6.1 with the fix, or create something like a 1.6.1-2. I really hope what @murphypuppy said about it taking another week is untrue. I can't wait another week for a fix for a *high vulnerability*, it's already unacceptable that it's been known in the image with no fix for almost a month.

Again, to reiterate: The specific urgency is the CVE, and I can't imagine it's AWS policy to leave customers sitting vulnerable for weeks with no fix, there has to be some process to prioritize a fix for that? As I said I understand the normal release may take some time, but please prioritize this specific issue - preferably within a day or two.

**Comment by torredil** [comment]
Thank you for being so understanding - I sincerely appreciate that. 

This issue is being prioritized and we are working with the EKS team to release a new version of the add-on which patches the CVE.

**Comment by Skiertsamba** [comment]
@torredil it's been a week since this was "being prioritized", how is it not out yet? As @MurphyPuppy says, should us addon customers expect this type of delay in future releases, and how can we avoid it if so?

**Comment by torredil** [comment]
Hi @MurphyPuppy @Skiertsamba,  based on my current understanding, add-on `v1.6.2` should be released by latest EOD tomorrow. Sorry for the delays, we are doing all we can to release it as soon as possible.

**Comment by Skiertsamba** [comment]
Given that AWS seems to be unable to commit to releasing the EKS Addon on a timely schedule for security issues, we've migrated off of it. Considering moving k8s workloads as a whole away from AWS as it seems other clouds have basic competencies like volume storage covered better.
