### ISSUE TITLE
VolumeSnapshot not perfomed

### ISSUE THREAD

**Issue by rrey-aviatrix** [kubernetes-sigs/aws-ebs-csi-driver#1268]
I have an EKS cluster (1.21) with `aws-ebs-csi-driver`  addon version 1.6.1 installed.
I have deployed `external-snapshotter` and created a `VolumeSnapshotClass` and a `VolumeSnapshot`.

I can see the `VolumeSnapshotContent` object  created and the `VolumeSnapshot` report that it is waiting for the snapshot:
```
Events:
  Type    Reason            Age   From                 Message
  ----    ------            ----  ----                 -------
  Normal  CreatingSnapshot  87s   snapshot-controller  Waiting for a snapshot telemetry/test-snapshot-2 to be created by the CSI driver.
```

The external-snapshotter's snapshot-controller is logging about the action:

```
I0608 15:11:12.510251       1 snapshot_controller.go:638] createSnapshotContent: Creating content for snapshot telemetry/test-snapshot-2 through the plugin ...
I0608 15:11:12.533927       1 snapshot_controller.go:918] Added protection finalizer to persistent volume claim telemetry/telemetry-daily-outputs-c82c3cfe
I0608 15:11:12.551094       1 event.go:285] Event(v1.ObjectReference{Kind:"VolumeSnapshot", Namespace:"telemetry", Name:"test-snapshot-2", UID:"a9b6411f-3627-4759-bf67-4a82a3f1c259", APIVersion:"snapshot.storage.k8s.io/v1", ResourceVersion:"21208616", FieldPath:""}): type: 'Normal' reason: 'CreatingSnapshot' Waiting for a snapshot telemetry/test-snapshot-2 to be created by the CSI driver.
```

From this moment my understanding is that this is the csi work to watch the `VolumeSnapshotContent` obects and perform the snapshot.

Unfortunately, the only thing I see in the `ebs-csi-controller` pod logs for the `csi-snapshotter` container is the following logs repeated:
```
E0608 15:16:31.084304       1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotContent: failed to list *v1beta1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
E0608 15:16:40.473429       1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotClass: failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
```

Could you assist me on determining why I have these messages in the `ebs-csi-controller` logs ? and how to fix the issue that prevents my snapshots to be performed  ?

/triage support

**Comment by rrey-aviatrix** [comment]
thx @gtxu, 

I guess that would fix the error messages about the v1beta1 resources, but is it also why the snapshot is not triggered for my v1 resource ?
I'm not using v1beta1 at all in my resources:

The VolumeSnapshotClass:
```
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: test-snapclass
driver: ebs.csi.aws.com
deletionPolicy: Retain
```

The VolumeSnapshot:
```

---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: test-snapshot-2
  namespace: telemetry
spec:
  volumeSnapshotClassName: test-snapclass
  source:
    persistentVolumeClaimName: telemetry-daily-outputs-c82c3cfe
```

**Comment by gtxu** [comment]
Hi @rrey-aviatrix, No it should work if you define VolumeSnapshot with v1. The [templates](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/snapshot) in our examples also uses v1 for snapshot.

**Comment by rrey-aviatrix** [comment]
Any pointer for investigation for me ?

**Comment by gtxu** [comment]
Hi @rrey-aviatrix  Add-on release v1.6.2-eksbuild.0 is now released to fix the support of snapshot with latest snapshot-controller. Please keep using `snapshot.storage.k8s.io/v1` in class defination.

**Comment by andrewhharmon** [comment]
not sure if i have the same issue, but seeing a similar message after installing aws-ebs-csi-driver v1.20.0-eksbuild.1 in eks 1.27. 

```
W0719 18:26:51.503266       1 reflector.go:424] k8s.io/client-go@v0.26.0/tools/cache/reflector.go:169: failed to list *v1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io) 
                                                                                                               
E0719 18:26:51.503307       1 reflector.go:140] k8s.io/client-go@v0.26.0/tools/cache/reflector.go:169: Failed to watch *v1.VolumeSnapshotClass: failed to list *v1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
```

**Comment by torredil** [comment]
Hi @andrewhharmon, it looks like the Volume Snapshot [CRDs](https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd) are not installed. 

1. Install the CRDs:
```
kubectl kustomize client/config/crd | kubectl create -f -
```
2. Verify CRDs are installed:
```
kubectl get volumesnapshotclasses.snapshot.storage.k8s.io
```

**Comment by andrewhharmon** [comment]
oh you are correct. i didn't even what to use Snapshots so took me some time to figure out how to disable it. In case someone else sees this, I was using the add-on in EKS and had to configure it with the following json
```
{
  sidecars = {
          snapshotter = {
            forceEnable = false
          }
      }
}
```
