### ISSUE TITLE
Minimal base image for Linux builds

### ISSUE THREAD

**Issue by torredil** [kubernetes-sigs/aws-ebs-csi-driver#1273]
**Announcement**
--
- Requesting community feedback on #1233  which would significantly enhance container security by reducing the number of vulnerabilities coming from the base image layer. Currently, most incoming CVEs are actually not related to the CSI driver binary, but the base AL2 image layer which includes a ton of extra dependencies not used by the driver. By using a more minimal base image, attack surface area and image size are significantly reduced.
- The new minimal base image only contains necessary driver dependencies which means it will not include a shell.

#272

**Comment by Skiertsamba** [comment]
If this change enhances security, why is it not the default? Are there some features missing or another reason the minimal image wouldn't be desirable?

**Comment by blair-small** [comment]
+1, why would the team intentionally choose a default that is known to have a bigger attack surface??? I've been a driver user/customer a long time and I remember a similar issue happening in the past when the driver shipped a Debian image that was known to be less secure and used as the default.

Also, will this new image be available to EKS Addon customers - and if yes what do we need to do to opt into using it?

**Comment by torredil** [comment]
- Hi folks, based on my current understanding of the situation, add-on `v1.6.2` should be released by latest EOD tomorrow. Sorry for the delays, we are doing all we can to release it as soon as possible. 
- Thanks for the feedback, it's really helpful and I will raise it up with the team. To answer your questions: based on the testing discussed in the PR, there are no missing features or any obvious reasons the minimal image wouldn't be desirable. I'd personally recommend using it asap, as a best practice, and all the benefits listed here. The reason we are thinking about using two tags is to avoid potentially breaking existing workflows and give everyone some time to switch over, but the plan is to definitely use the minimal build as default in the future.
- Presumably, introducing a minimal version of the add-on would be similar to [kube-proxy](https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html).

**Comment by Skiertsamba** [comment]
@torredil if that's the case, then will the minimal image receive the same support as the "fat" image? For example, it seems the CI doesn't test the minimal image and #1233 doesn't change that (also, off topic, but looking into that it seems like Windows builds receive no testing at all.....despite upstream tests being available).

It seems like certain workflows are already treated as second-class citizens (see: EKS Addon) - I'm worried that this is going to become another one. Are Amazon engineers even testing with the minimal image considering they aren't even bothering to run CI on it?

**Comment by torredil** [comment]
Hey @Skiertsamba, wanted to thank you for the feedback and let you know that this change has now been introduced as default and is tested by CI.
