### ISSUE TITLE
StorageClass not being created in helm

### ISSUE THREAD

**Issue by gabrielpasv** [kubernetes-sigs/aws-ebs-csi-driver#1275]
/triage support

I am trying to install aws-ebs-csi-driver chart from https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/charts/aws-ebs-csi-driver

I was able to install the csi driver, however the storageClass didn't install. When I ran the helm template I can't even see the respective yaml file.

Even after I remove the comments 
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L164

**Comment by rdpsin** [comment]
/king bug

Hi @gabrielpasv, could you provide us the `values.yaml` you're using?

Running `helm template` with `storageClasses` section uncommented renders the correct StorageClass manifest. 


```
$ cat values.yaml

...

storageClasses:
 - name: ebs-sc
#   # annotation metadata
   annotations:
     storageclass.kubernetes.io/is-default-class: "true"
#   # label metadata
   labels:
     my-label-is: supercool
#   # defaults to WaitForFirstConsumer
   volumeBindingMode: WaitForFirstConsumer
#   # defaults to Delete
   reclaimPolicy: Retain
   parameters:
     encrypted: "true"
```

```
$ helm template . | yq -y 'select(.kind=="StorageClass")'  
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
  labels:
    my-label-is: supercool
provisioner: ebs.csi.aws.com
parameters:
  encrypted: 'true'
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

```

(Did you remove the `[]` after `storageClasses`?)

**Comment by gabrielpasv** [comment]
I tested it again and It works fine with helm template. The problem is with helmfile. 
https://lyz-code.github.io/blue-book/devops/helmfile/

with helmfile it does not create the storageclass.yaml

**Comment by gabrielpasv** [comment]
nevermind, I found the problem
yaml.gotmpl file was wrong
