### ISSUE TITLE
PVC attached time

### ISSUE THREAD

**Issue by bengoldenberg** [kubernetes-sigs/aws-ebs-csi-driver#1279]
we have an Issue with the timeout of attach a pvc, and we wonder if there is any option to change the default timeout, or to improve the waiting time for the pvc to be attached.

**Comment by gtxu** [comment]
Hi @bengoldenberg, Would you please provide more information related the issue? Like K8s version, CSI Driver version, using EKS Add-on or deployed by Helm/Kustomize?

If you continuous encounter the timeout and never managed to crate PV/Attach PVC. Please try to confirm if the Driver IAM policy is attached to your cluster, or check if the node-roles are bind to your nodes.

For further information, please provide controller event by running this command when it is convenient to you:
`kubectl describe pod {POD_NAME} -n kube-system` (replace {POD_NAME} with the csi-controller that has this issue)

`kubectl logs -n kube-system {POD_NAME} -c csi-attacher`

**Comment by bengoldenberg** [comment]
hey,
we are able to create and attach PVC, our problem is that the attachment takes a lot of time and gets timeout, until the next retry the pod is not starting and the pod enters a crash loopbackoff.
We wonder why it might take a long time for the ebs controller to detach and attach the ebs volume to the new node once a pod has rescheduled to another node.

k8s version:  v1.20.11
csi driver version: 1.14
