### ISSUE TITLE
Add envFrom property to container specs

### ISSUE THREAD

**Issue by jebbens** [kubernetes-sigs/aws-ebs-csi-driver#1288]
**Is your feature request related to a problem?/Why is this needed**
I would like to add the envFrom property to all of the container specs in the controller.yaml and node.yaml templates. My use case is that I have a single configmap that contains values for http_proxy and no_proxy settings, which can be used for both kubectl or helm applications. Rather than define each of these values individually in each container spec using the env property, it would be simpler to point to the configmap. Also, though there are properties for proxy.http_proxy and proxy.no_proxy in the values.yaml file, it is sometimes required to define https_proxy plus capitalized versions of all these settings. In addition, there are many other uses for a configmap references to be used across multiple applications, so it makes sense to add this to the templates.

**Describe the solution you'd like in detail**
Add the envFrom property to all of the container specs in the controller.yaml and node.yaml templates. Add envFrom: [] to the values.yaml file for the image and sidecars.

**Describe alternatives you've considered**
Applying the settings as a patch.

**Additional context**

**Comment by torredil** [comment]
Addressed in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1312.
