### ISSUE TITLE
Remove annotation comment from serviceaccount-csi-controller.yaml template

### ISSUE THREAD

**Issue by jebbens** [kubernetes-sigs/aws-ebs-csi-driver#1289]
**Is your feature request related to a problem?/Why is this needed**
This isn't really an "enhancement", but the following comment should be removed from the serviceaccount-csi-controller.yaml template because 1) it contains an AWS account number, 2) the role name does not need to be "ebs-csi-role", and 3) the example should be in the values.yaml file since the annotation should be applied via the values file rather than uncommenting in the main template.

  #Enable if EKS IAM for SA is used
  #annotations:
  #  eks.amazonaws.com/role-arn: arn:aws:iam::586565787010:role/ebs-csi-role

/feature

**Describe the solution you'd like in detail**
Delete the comment from the template. Copy the comment, but modify the annotation to: eks.amazonaws.com/role-arn: arn:aws:iam::<accountId>:role/<roleName> or similar

**Describe alternatives you've considered**
None

**Additional context**

**Comment by torredil** [comment]
Addressed in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1312.
