### ISSUE TITLE
panic: could not get number of attached ENIs

### ISSUE THREAD

**Issue by idanl21** [kubernetes-sigs/aws-ebs-csi-driver#1291]
/kind bug

**What happened?**

 Hey all!
 im trying to install your Aws-ebs-csi-driver by that guide
 https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html
 created all the roles and policies.

on a quick look at the ebs-csi-node  pod at my k8s env i can see that i get that error from ebs-plugin container :
`I0628 10:44:05.130666       1 metadata.go:85] retrieving instance data from ec2 metadata
I0628 10:44:05.135264       1 metadata.go:92] ec2 metadata is available
panic: could not get number of attached ENIs

goroutine 1 [running]:
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newNodeService(0xc0000c6f00)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/node.go:86 +0x269
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver({0xc000609f30, 0x8, 0x55})
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:95 +0x38e
main.main()
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:46 +0x365` 

im using v1.7.0-eksbuild.0 deriver version and 1.20 k8s version.
do you now how can i solve it ? 
Thanks !

**Comment by torredil** [comment]
#1237

Hi @idanl21, are you deploying the driver on Nitro instances?

**Comment by idanl21** [comment]
@torredil 
dont think so, im deploying it on i3.xlarge or i3en.xlarge instances

**Comment by krisatverbidio** [comment]
This happened to me when I was using a patched version of kube2iam to disable sensitive metadata. It was preventing the `/{version}/meta-data/network/interfaces/macs/` endpoint from being passed through. Resolving that issue made this error go away.
