### ISSUE TITLE
ebs-csi-node fails to start on windows machine

### ISSUE THREAD

**Issue by pagarwal-tibco** [kubernetes-sigs/aws-ebs-csi-driver#1322]
/kind bug

**What happened?**
ebs-csi-node fails to start on windows machine. Following are the logs of ebs-plugin container,
```
$kubectl logs ebs-csi-node-windows-276q2 ebs-plugin
I0726 12:30:37.773873    9360 metadata.go:85] retrieving instance data from ec2 metadata
I0726 12:30:42.514227    9360 metadata.go:92] ec2 metadata is available
panic: open \\.\\pipe\\csi-proxy-filesystem-v1: The system cannot find the file specified.

goroutine 1 [running]:
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newNodeService(0xc000078140)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/node.go:91 +0x258
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver({0xc000655f30, 0x8, 0x55})
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:95 +0x38e
main.main()
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:46 +0x365
```

**Environment**
- Kubernetes version (use `kubectl version`): 1.21
- Driver version: 1.6.2

**Comment by torredil** [comment]
Have you installed the [CSIProxy](https://github.com/kubernetes-csi/csi-proxy) on your node? Installing this binary is a [prerequisite](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/windows) for using the CSI driver on Windows to perform storage related operations.

**Comment by pagarwal-tibco** [comment]
@torredil 
Thanks for your response. No, I haven't deployed csi-proxy. I could not find a helm chart for csi-proxy. Do you have any links for the same?

**Comment by ConnorJC3** [comment]
@pagarwal-tibco you cannot deploy the CSI-proxy via a helm chart or kubernetes in general because it needs privileged access to the host, and there is currently not privileged containers on Windows.

There are installation instructions on the [csi-proxy github repo](https://github.com/kubernetes-csi/csi-proxy/#installation), or I believe there is an AMI you can use that has the csi-proxy preinstalled.

**Comment by torredil** [comment]
In April we started shipping the [Amazon EKS Optimized Windows AMI](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-windows-ami.html) together with the [CSI Proxy](https://github.com/kubernetes-csi/csi-proxy), which enables customers to use CSI drivers on Windows nodes.

**Comment by pagarwal-tibco** [comment]
@ConnorJC3 and @torredil 
Thanks for help. It worked after using latest Amazon EKS Optimized Windows AMI.
