### ISSUE TITLE
Did not find AWS region in node providerID string

### ISSUE THREAD

**Issue by rmccarth** [kubernetes-sigs/aws-ebs-csi-driver#1327]
/kind bug

**What happened?**

I have tested this on both Azure AKS as well as a K3d on Ubuntu and I get the same error. 

running: `helm install ebs-csi --set region=us-east-2 .` deploys controllers but ebs-csi-nodes go into crashloopbackoff with the following message:

```
I0728 14:18:48.677477       1 metadata.go:85] retrieving instance data from ec2 metadata
W0728 14:18:48.687660       1 metadata.go:88] ec2 metadata is not available
I0728 14:18:48.687683       1 metadata.go:96] retrieving instance data from kubernetes api
I0728 14:18:48.689798       1 metadata.go:101] kubernetes api is available
panic: did not find aws region in node providerID string
```

**What you expected to happen?**

CSI driver successfully deploys the ebs-csi-node pods.

**How to reproduce it (as minimally and precisely as possible)?**

Shown above.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 
```
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.23.8+k3s1
```
- Driver version: latest helm chart

**Comment by ConnorJC3** [comment]
The `region` helm chart parameter (which sets the `AWS_REGION` environment variable) is only effective on the controller. It is provided for hybrid cloud style scenarios where the controller runs in a separate region or outside of AWS.

Nodes must run inside AWS and thus are expected to be able to access AWS's metadata service. You should configure your driver installation not to run node pods on non-AWS hosts (such as those from AKS), for example by using a node selector.

**Comment by rmccarth** [comment]
Great, thank you for clarifying!
