### ISSUE TITLE
failed to mount pv: ..../mount: no such file or directory

### ISSUE THREAD

**Issue by landinged** [kubernetes-sigs/aws-ebs-csi-driver#1345]
/kind bug

**What happened?**

Can't mount pv to pod, because mounting destination (a subpath called 'mount') doesn't exist. 
Error details as follow:

Aug 13 23:59:21 ip-10-97-2-xxx kubelet[10201]: I0813 23:59:21.751464   10201 operation_generator.go:626] "MountVolume.WaitForAttach succeeded for volume \"pvc-0832fe64-5a14-425a-87c8-06e3452adcf9\" (UniqueName: \"kubernetes.io/csi/ebs.csi.aws.com^vol-070db096ec1820ccf\") pod \"esmaster-0\" (UID: \"ff2dd7cd-ed0d-47f5-be2f-bcd52f7e009d\") DevicePath \"csi-d7173f83134fe433a605848e0af854e987b1493b4e03f16dd8d236d4c65c0a6a\"" pod="default/esmaster-0"

Aug 13 23:59:21 ip-10-97-2-xxx kubelet[10201]: E0813 23:59:21.758916   10201 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/csi/ebs.csi.aws.com^vol-070db096ec1820ccf podName: nodeName:}" failed. No retries permitted until 2022-08-13 23:59:37.75889226 +0000 UTC m=+46.711335080 (durationBeforeRetry 16s). Error: MountVolume.SetUp failed for volume "pvc-0832fe64-5a14-425a-87c8-06e3452adcf9" (UniqueName: "kubernetes.io/csi/ebs.csi.aws.com^vol-070db096ec1820ccf") pod "esmaster-0" (UID: "ff2dd7cd-ed0d-47f5-be2f-bcd52f7e009d") : applyFSGroup failed for vol vol-070db096ec1820ccf: lstat /k8s/kubelet/pods/ff2dd7cd-ed0d-47f5-be2f-bcd52f7e009d/volumes/kubernetes.io~csi/pvc-0832fe64-5a14-425a-87c8-06e3452adcf9/mount: no such file or directory

**What you expected to happen?**

Formerly, PV is mounted successfully, as expected. 
If extra mounting point (destination) is needed, create it automatically. Here is a subpath called "mount". 

**How to reproduce it (as minimally and precisely as possible)?**

Formerly environment:
- k8s 1.22.9
- docker 20.10.7

Then:
- remove docker and install containerD 1.6.6
- upgrade k8s from 1.22.9 to 1.23.9
- upgrade k8s from 1.23.9 to 1.24.3

Error as above comes out.

**Anything else we need to know?**:

Error shows the mounting destination doesn't exist. 
If creating that sub directory "..../..../..../pvc-xxxx-xxxx-xxxx/`mount`", pv can be mounted successfully again. 

Formerly, the successful mounting point doesn't contain a subpath 'mount" :
    /k8s/kubelet/pods/57480c7a-2599-4b63-9b0f-7d14ec20b47c/volumes/kubernetes.io~aws-ebs/pvc-e25d24bb-6599-4ffa-83da-231b32ec9594/nodes/0/

Currently, the required mount point contains a subpath 'mount', not same pod and pv: 
    /k8s/kubelet/pods/90314bba-557a-4532-8b9b-1306e392e1ac/volumes/kubernetes.io~csi/pvc-b004e978-01ad-40ab-9acd-c107efe7a967/`mount`/nodes/0/

**Environment**
- Kubernetes version (use `kubectl version`):
   Client Version: v1.24.3
   Kustomize Version: v4.5.4
   Server Version: v1.24.3
- Driver version:
   aws-ebs-csi-driver:v1.10.0
- OS version: Ubuntu 18.04.5 LTS
- Kernel version: 5.4.0-1055-aws

**Comment by ConnorJC3** [comment]
Have you set the [`kubeletPath`](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L171) to `/k8s/kubelet/`, as you seem to have a non-standard path?

**Comment by landinged** [comment]
> Have you set the [`kubeletPath`](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L171) to `/k8s/kubelet/`, as you seem to have a non-standard path?

Yes, this option has been set for kubelet: --root-dir=/k8s/kubelet/ .

**Comment by ConnorJC3** [comment]
@landinged have you set it in the helm values for the driver deployment, or have you changed references to `/var/lib/kubelet` in the manifests if not using helm?

**Comment by landinged** [comment]
> @landinged have you set it in the helm values for the driver deployment, or have you changed references to `/var/lib/kubelet` in the manifests if not using helm?

after updating 'kubeletDir' to '/k8s/kubelet' in DaemonSet 'ebs-csi-node', the issue has been resolved. 
thank you very much for your advice.
