### ISSUE TITLE
CHANGELOG, CHANGELOG, CHANGELOG!!!

### ISSUE THREAD

**Issue by rubroboletus** [kubernetes-sigs/aws-ebs-csi-driver#1352]
/kind bug

**What happened?**

missing changes description anywhere

**What you expected to happen?**

see changes at least in CHANGELOG!!!

**How to reproduce it (as minimally and precisely as possible)?**

open CHANGELOG and try to find latest changes

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

please, reporting this abot 8ths time. Is it really so big problem to list real changes with each one release when releasing it? We are your custommers and we are paying a lot for your support!

**Comment by torredil** [comment]
Hey, thanks for reporting this. Even though GitHub shows a new tag, the release process is not yet complete, hence why we haven't announced any changes in our CHANGELOG. As soon as container images are available in public ECR / GCR we will create a post-release commit and announce the changes in the CHANGELOG.

**Comment by olemarkus** [comment]
I still think the process is wrong. It should set the release as _draft_ and not _prerelease_. Pre-release means alpha, beta, RCs, while draft means the release is work in progress and won't trigger any notification to watchers etc. So I think the github action should be updated accordingly.

**Comment by torredil** [comment]
@olemarkus Agree, this has been addressed in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1351.

**Comment by olemarkus** [comment]
Lovely :heart_eyes:
