### ISSUE TITLE
Using fsGroup causes mount to fail

### ISSUE THREAD

**Issue by jhughes2112** [kubernetes-sigs/aws-ebs-csi-driver#1362]
/kind bug

**What happened?**
I am using Loki for logging.  It likes to use fsGroup 10001 so it doesn't run as root.  Works fine on an older cluster with the in-tree EBS driver, but that's obsolete now, so I upgraded a couple of months ago to aws-ebs-csi-driver, which worked for general purposes.  Once I tried to install Loki, I got a different error and tracked it down to a bug that was fixed on Jun 22.  So I upgraded to latest.  Now, it looks like it mounts more correctly, but it seems like the driver has read-only access on the HOST.  Not sure where to go from here, except that I can't install things using fsGroup until this is fixed.

**What you expected to happen?**
Volume should mount properly.

**How to reproduce it (as minimally and precisely as possible)?**
```
helm repo add grafana https://grafana.github.io/helm-charts
helm repo update
helm template loki grafana/loki-stack --create-namespace --namespace monitoring --version=2.6.5 -f values.yaml >loki-stack.yaml
kubectl apply -f loki-stack.yaml
```

Create a file called `values.yaml` with the following contents:
```
loki:
  enabled: true
  persistence:
    enabled: true
    size: 2Gi
promtail:
  enabled: true
grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: fals
pipelineStages:
- docker:
- match:
    selector: '{app="eventrouter"}'
    stages:
    - json:
        expressions:
          namespace: event.metadata.namespace
    - labels:
        namespace: ""
```

**Anything else we need to know?**:
```
36s         Normal    SuccessfulCreate         statefulset/loki                          create Claim storage-loki-0 Pod loki-0 in StatefulSet loki success
36s         Normal    WaitForFirstConsumer     persistentvolumeclaim/storage-loki-0      waiting for first consumer to be created before binding
36s         Normal    SuccessfulCreate         statefulset/loki                          create Pod loki-0 in StatefulSet loki successful
36s         Normal    Provisioning             persistentvolumeclaim/storage-loki-0      External provisioner is provisioning volume for claim "monitoring/storage-loki-0"
34s         Normal    ExternalProvisioning     persistentvolumeclaim/storage-loki-0      waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
29s         Normal    ProvisioningSucceeded    persistentvolumeclaim/storage-loki-0      Successfully provisioned volume pvc-566bb2f1-5fb0-48cf-ae57-91d3b8591b95
28s         Normal    Scheduled                pod/loki-0                                Successfully assigned monitoring/loki-0 to ip-172-31-71-150.ec2.internal
26s         Normal    SuccessfulAttachVolume   pod/loki-0                                AttachVolume.Attach succeeded for volume "pvc-566bb2f1-5fb0-48cf-ae57-91d3b8591b95"
9s          Warning   FailedMount              pod/loki-0                                MountVolume.MountDevice failed for volume "pvc-566bb2f1-5fb0-48cf-ae57-91d3b8591b95" : rpc error: code = Internal desc = could not create target dir "/var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/ebs.csi.aws.com/da95381da09c0d8863e3112bf689c1901ecb4ca7974c6d7660d79cf5d946ccbd/globalmount": mkdir /var/snap: read-only file system
```

**Environment**
- Kubernetes version (use `kubectl version`): 1.24.3-2  installed via microk8s
- Driver version: Installed from Helm chart 2.10.1 which has driver 1.11.2 in it.

Additionally, I did some hacking on the driver manifest and changed all the `privileged` to true and `readOnlyRootFilesystem` to false, which gave me a different error:
```
0s          Warning   FailedMount              pod/loki-0                                MountVolume.SetUp failed for volume "pvc-89915213-8660-4c19-8acb-336974fd0c2b" : applyFSGroup failed for vol vol-0af60ae6c514f47a2: lstat /var/snap/microk8s/common/var/lib/kubelet/pods/0cc3350e-d2a8-4484-ac98-ad9f9a94a455/volumes/kubernetes.io~csi/pvc-89915213-8660-4c19-8acb-336974fd0c2b/mount: no such file or directory
```
I then verified that the volume folder does exist on the host, which it does, but there is no /mount folder or file in there.  Only `vol_data.json` and nothing else.

**Comment by ConnorJC3** [comment]
Can you confirm you have set the helm parameter `node.kubeletPath` (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L171) to `/var/snap/microk8s/common/var/lib/kubelet/`.

And if you haven't, can you re-deploy the driver with that change and see if the issue still occurs? The docs really should mention this, but if you have a non-standard kubelet path you have to explicitly tell the helm chart about that so it gets mounted into the pod correctly.

**Comment by jhughes2112** [comment]
With microk8s, /var/lib/kubelet is symlinked to the proper place already.

**Comment by ConnorJC3** [comment]
A symlink won't work here, the driver needs to have the real path mounted (because the kubelet is going to give the driver paths that start with `/var/snap/microk8s/common/var/lib/kubelet/`, and thus the driver needs to have access to that path specifically).

**Comment by jhughes2112** [comment]
I'll be darned, it works.  Thanks for the tip about the helm parameter.  I didn't see that anywhere.

**Comment by jhughes2112** [comment]
It would be good to call that out specifically, since many non-vanilla k8s packages have their own install folders.
