### ISSUE TITLE
Use kubetest for running the e2e tests

### ISSUE THREAD

**Issue by olemarkus** [kubernetes-sigs/aws-ebs-csi-driver#1363]
Right now, the e2e tests runs a version of the CSI e2e suite copyed into this source tree.

I would think a better way would be to run something like this:
```
go install sigs.k8s.io/kubetest
go install k8s.io/kops/tests/e2e/kubetest2-tester-kops
go install k8s.io/kops/tests/e2e/kubetest2-kops

kubetest2 kops \                                            
  -v 2 \                         
  --down
 --cluster-name=<cluster name>
  --kops-version-marker=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt \
  --kubernetes-version=https://storage.googleapis.com/kubernetes-release/release/stable-<version>.txt \
  --cloud-provider=aws \
  --test=kops \
  -- \
  --test-package-version=<kubernetes version> \
  --focus-regex="External.Storage" \
  --parallel=25
```

One needs to provide some additional test binary flags pointing to the CSI driver spec. kubetest2 will assume a path by default, but can help out ensuring this is configurable.

kOps already run this for some time now: https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-aws-k8s-1-23

A fairly considerable benefit of doing this is getting rid of `k8s.io/kubernetes` dep in `go.mod`

**Comment by wongma7** [comment]
SGTM, we are doing https://kubernetes-csi.github.io/docs/functional-testing.html      'import the in-tree storage tests and run them using go test.'

a low-effort alternative would be to give test/e2e its own go.mod decoupled from driver go.mod, originally I had this don't recall why I ditched this idea (could have been the amount of effort to maintain 2 go.mods but that is totally irrelevant now with our resources)

**Comment by olemarkus** [comment]
Right. So we went for number 1 there "use [Kubernetes E2E Tests](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external), by providing a DriverDefinition YAML file via a parameter." Since we test a broad range of configurations and kubernetes versions, using a fixed k8s version isn't ideal.

The full ginkgo command is 
```
ginkgo --debug --nodes=25 /home/prow/go/src/k8s.io/kops/_rundir/96d9e28a-2433-11ed-b9f9-fa048dcbefc5/e2e.test -- --kubeconfig=/root/.kube/config --kubectl-path=/home/prow/go/src/k8s.io/kops/_rundir/96d9e28a-2433-11ed-b9f9-fa048dcbefc5/kubectl --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|nfs|NFS|Gluster|RuntimeClass.should.run|Metadata.Concealment|Topology.Hints|should.verify.that.all.nodes.have.volume.limits|In-tree.Volumes.\[Driver:.aws\] --ginkgo.focus= --report-dir=/logs/artifacts --ginkgo.flakeAttempts=1 -test.timeout=60m -num-nodes=0 --host=https://api.e2e-e2e-kops-aws-k8s-1-23.test-cncf-aws.k8s.io --provider=aws --gce-zone=ap-southeast-2a --cluster-tag=e2e-e2e-kops-aws-k8s-1-23.test-cncf-aws.k8s.io --gce-region=ap-southeast-2 --gce-multizone=false --non-blocking-taints=node-role.kubernetes.io/master,node-role.kubernetes.io/api-server,node-role.kubernetes.io/control-plane --storage.testdriver=/home/prow/go/src/k8s.io/kops/tests/e2e/csi-manifests/aws-ebs/driver.yaml --storage.migratedPlugins=kubernetes.io/aws-ebs --disable-log-dump
```
Where `--storage.testdriver=/home/prow/go/src/k8s.io/kops/tests/e2e/csi-manifests/aws-ebs/driver.yaml` is the important bit. This is a copy/paste of the one from this repo except that snapshot tests are disabled since we don't deploy snapshot controller by default right now.

We set the testdriver path by default when EBS CSI driver is enabled in the cluster, so this needs to take https://github.com/kubernetes/kops/pull/14164 into account. But I _think_ overriding the test driver path with a custom one should work.

I'll try to investigate a bit here and see what works.

**Comment by olemarkus** [comment]
I had a look at the various e2e suites we have in this repos and:
* e2e-kubernetes: this one is trivial to migrate to kubernetes2-tester-ginko and can then use the upstream test binaries
* e2e-upgrade: I am not sure how long you will need to run this one. kOps forces migration as of Kubernetes 1.24 so at some point it will not be possible to run these anyway. Kubernetes 1.25 has the in-tree driver removed as well if I am not mistaken. If we want to keep this one, we could use `--with-built-binaries` though and build a dedicated `e2e.test` binary that is placed in `run-dir`.
* e2e: these are project-specific. So again we can consider compiling and using `--with-built-binaries`.

I think I would prefer merging e2e-upgrade and e2e into a single module and use `--with-built-binaries` on the ginkgo tester (or the kops one, which extends ginkgo with some kOps specific defaults). The e2e-kubernetes one should use upstream test binaries.

**Comment by torredil** [comment]
@olemarkus that sounds good to me, agree with merging `e2e-upgrade` and `e2e` into a single module for now since the test is still relevant. This work is a big step in the right direction and helps alleviate the pain associated with upgrades, also unblocks #1341 and lets us run CI in 1.25 since we can self-manage the driver in kOps [v1.25.0-beta.1](https://github.com/kubernetes/kops/releases/tag/v1.25.0-beta.1).

**Comment by olemarkus** [comment]
Just to update on this one. I am piloting a similar change in the FSx driver repo. The stuff there is mostly copied from this repo, yet slightly simpler. Once that works, I'll try to do the same here.
