### ISSUE TITLE
Support additional leader election flags for csi-provisioner and csi-attacher

### ISSUE THREAD

**Issue by moogzy** [kubernetes-sigs/aws-ebs-csi-driver#1368]
**Is your feature request related to a problem?/Why is this needed**

We presently observe an intermittent problem with etcd writes in our EKS clusters which cause the csi-provisioner and csi-attacher to lose their lease and subsequently crash. The lease duration and renewal period is too tight and is exceeded upon a single etcd write deadline being exceeded (7s)

These two containers have the following flags which can be tuned:

- `leader-election-lease-duration`
- `leader-election-renew-deadline`
- `leader-election-retry-period`

Ref: https://github.com/kubernetes-csi/external-provisioner/blob/master/cmd/csi-provisioner/csi-provisioner.go#L93

None of these are presently supported by the `aws-ebs-csi-driver` helm chart but they should be. These would facilitate granular debugging as part of a process of elimination for issues such as the one we observe.

/feature

**Describe the solution you'd like in detail**

I'd like to add support into the helm chart for the three flags that are supported by the csi-provisioner and csi-attacher containers.

- `leader-election-lease-duration`
- `leader-election-renew-deadline`
- `leader-election-retry-period`

The plan would be to only add the flags with tuned values if they are specified... otherwise leave them as the defaults. As helm doesn't support safe navigation it might be simpler to default to the values used in the provisioner and attacher code with the `default` helm keyword.

**Describe alternatives you've considered**
Forking the chart, creating our own chart. Neither of these are ideal as the flags exist for tuning where needed. The helm chart should support these for leader election.

**Additional context**
We have a case open with our cloud provider to investigate the latency excursions for the control plane. However in the interim we want to stabilise the ebs-csi-controller containers to avoid them crashing intermittently.

**Comment by moogzy** [comment]
Closing this for the moment as the flags appear to be `time.Duration` objects in Go. I'll figure out what the path forward is there first.

**Comment by moogzy** [comment]
Ok scrap that - it accepts a format that `time.Duration` parses. Thus passing in the appropriate Nanoseconds format as an Int works.

Example:

```
flag.Duration("leader-election-retry-period", 20000000000, "Test flag for leader-retry-period")

Output: 

20s,
```

Why Nanoseconds? The base format for `time.Duration` is in ns so if you just pass in the raw seconds it treats it as 15ns.

```
flag.Duration("leader-election-retry-period", 15, "Test flag for leader-retry-period")
15ns
```

The plan would be to take in a human readable format in "SECONDS" and convert that to Nanoseconds for appropriate parsing by `time.Duration` via `flag.Duration` with `mul`.

```
echo "{{ mul 15 1000 1000 1000 }}" | sprig-cli                                                                                                                                                                                                                                             
15000000000
```

Any concerns about doing this?

**Comment by yizha** [comment]
golang time.Duration supports various time format, like '20s', '1m30s' etc, when there is no unit after the number it is parsed as nanosecond. Details here https://pkg.go.dev/time@go1.19#ParseDuration.

Basically in code you can define the flag like this which is more human friendly
```
flag.Duration("leader-election-retry-period", 20*time.Second, "Test flag for leader-retry-period")
```

And pass a human friendly time.Duration format (with unit) when setting the flag on cli,
```
./main -leader-election-retry-period=10s
```

In helm chart you don't need to covert it in to nanoseconds, just use string like '30s', '1m30', '1h' etc, from values file, and pass it directly as value to the cli flag, which is friendly to both chart user and chart developer.

**Comment by moogzy** [comment]
@yizha you're correct, I saw that in the flag.Duration docs and tested it in Go Playground but was getting a failure. Thus the proposal above.

This simplifies my request - I'll send a PR to update the chart to add the flags and take in a string format that is supported by time.Duration.

Thanks.

**Comment by moogzy** [comment]
PR out for review --> https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1371

As I'm a first time contributor to this repo there are a few extra hurdles to get over... but shouldn't take long :)

**Comment by torredil** [comment]
@moogzy I thank you for your contribution. If you have any questions I would be more than happy to help, but it seems like you have it all figured out :)

**Comment by moogzy** [comment]
Thank you @torredil @ConnorJC3 @rdpsin 

I couldn't find a common cadence to releases. What kind of eta should I be expecting for a chart release containg this changes?

**Comment by torredil** [comment]
@moogzy Previously, we relied on the judgement of maintainers to release new versions. Moving forward, we would like to stick to quarterly releases but would love to hear your thoughts / feedback on the subject.

**Comment by olemarkus** [comment]
@torredil Are you planning anything soon? Given the amount of PRs merged lately, I was waiting for a new release before doing the next kOps, but if nothing is planned in the near future, we'll just carry on.

**Comment by torredil** [comment]
@olemarkus I think we should plan to release new images once we work through some of the open PRs. It would be nice to see https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1335 in the next release. As far releasing a new Helm chart version, I would say within the next few days.

**Comment by olemarkus** [comment]
Sounds good

**Comment by moogzy** [comment]
@torredil for my knowledge kOps relates to the helm chart release?

> Moving forward, we would like to adopt a release schedule and would appreciate your thoughts / feedback on the subject.

This is dependent on the north star you want to aim for and where your risk tolerance sits for bundling `n`changes into a release IMHO. If there hasn't been a regular release cadence then starting somewhere/anywhere (>= 1 month) is a rough starting point. Once you start hitting that consistently then considering whether it needs to be tightened up would be a start.

I haven't looked at how many PRs you would regularly get within a month.... so with my SRE hat on I'd say that should be also taken into account.

Would you be interested in decoupling helm chart release from image release? I think that would avoid scenarios like mine where you could push out chart-only changes with a faster turnaround.
