### ISSUE TITLE
Support an ability to have initContainer for checking required permissions

### ISSUE THREAD

**Issue by InsomniaCoder** [kubernetes-sigs/aws-ebs-csi-driver#1378]
**Is your feature request related to a problem? Please describe.**

For `ebs-csi controller` to be able to provision volumes, it needs to be able to interact with AWS API.

In our current set up, we are using [kiam](https://github.com/uswitch/kiam) to Integrate our Kubernetes clusters with AWS IAM.

**Problem**

We are creating multiple Kubernetes clusters from scratch in a daily basis. There are some system applications that need to provision volumes. We install `ebs-csi-controller` and [kiam](https://github.com/uswitch/kiam) with ArgoCD, but it is difficult to make sure that kiam is ready before `ebs-csi-controller`'s pod start, otherwise, ebs csi will not be able to assume role successfully, and we need to manually intervene to restart the ebs csi pod which is not practical in our case since we are provisioning clusters with automation tools.

**Describe the solution you'd like in detail**

We forked the aws-ebs-csi-driver helm chart to modify the Deployment manifest to accept an `InitContainer`.

This allows us to add a check script that make sure the pod has a required permission before the operator container starts.

For example:

```
initContainers:
        - name: check-kiam
          image: containers.mpi-internal.com/cpr/coreos/awscli:master
          command: ["/bin/sh", "-c"]
          args:
            - result=$({ aws ec2 create-volume --size 20 --region eu-west-1 --availability-zone eu-west-1a --dry-run >&2; } 2>&1 >/dev/null);
              echo $result | grep "Request would have succeed";
```

so, it would be great if the chart accepts the initContainer, and we can converge to use the upstream.

I can make a [PR](https://github.com/InsomniaCoder/aws-ebs-csi-driver/commit/9fb4adaf39d057e2009cb674b4a75d96c32024e7) for this if it makes sense.

**Comment by torredil** [comment]
Sounds good to me, feel free to open the PR 👍
