### ISSUE TITLE
Clarify Release Cadence and Support

### ISSUE THREAD

**Issue by MurphyPuppy** [kubernetes-sigs/aws-ebs-csi-driver#1382]
I've seen some discussion on this in #1368, but I'd like to ask for a formal policy on this that us users can count on.

Firstly, is there an official release cadence? How often can we expect releases? I see @torredil mentioned quarterly releases, but that seems very very slow to me - do we really have to wait months to get the latest bugfixes?

Secondly, and more importantly: what is the official policy on supported versions? It seems like currently the unofficial policy is "latest version only" - previous versions never receive backports or even an image rebuild to deal with CVEs. If that is the case, it should be mentioned upfront In the README: "Versions older than the most recent receive NO support and NO SECURITY FIXES."

Also, I should point out that if that is the policy every user is immediately in "unsupported" territory as soon as a new version releases. Maybe consider adopting a policy to support the previous release for a month or so after a new release comes out to give users time to migrate? As of right now users are SOL if they have an issue 1 hour after the newest release and haven't had a chance to plan an upgrade yet.

**Comment by torredil** [comment]
Hi @MurphyPuppy 👋 

How does monthly release and bi-weekly Helm chart release sound? Starting with `v1.12.0` we plan to support the latest and n-1 version to give users some time to plan for upgrades, appreciate the feedback.

**Comment by torredil** [comment]
@MurphyPuppy We need to patch all of the sidecar containers before releasing a new add-on version, then we can work on 1.12.
