### ISSUE TITLE
EBS PVCs will not mount on nodes with iSCSI multipath installed

### ISSUE THREAD

**Issue by paalkr** [kubernetes-sigs/aws-ebs-csi-driver#1417]
Bug

**What happened?**
EBS PVCs fails to mount on hosts where open-iscsi and multipath-tools is installed.

**How to reproduce it (as minimally and precisely as possible)?**
On an Ubuntu host execute the following

1. write
```
      defaults {
        user_friendly_names yes
        find_multipaths no
      }
```
to 
`/etc/multipath.conf`

2. install and configure iscsi
apt --yes install open-iscsi lsscsi sg3-utils multipath-tools scsitools
sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
systemctl restart multipath-tools
systemctl restart iscsid

An EBS disk will then be attached under
```
lsblk
...
nvme1n1      259:4    0   10G  0 disk
└─mpathb     253:0    0   10G  0 mpath
```

And the PVC will not mount due to the multipath mount point.
```
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  12m (x1635 over 2d7h)  kubelet  MountVolume.MountDevice failed for volume "pvc-1f3f3a2c-4c78-4da6-ae56-e110f813fd0e" : rpc error: code = Internal desc = could not format "/dev/nvme1n1" and mount it at "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1f3f3a2c-4c78-4da6-ae56-e110f813fd0e/globalmount": format of disk "/dev/nvme1n1" failed: type:("ext4") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1f3f3a2c-4c78-4da6-ae56-e110f813fd0e/globalmount") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.42.9 (28-Dec-2013)
/dev/nvme1n1 is apparently in use by the system; will not make a filesystem here!
```

**Environment**
- Kubernetes version (use `kubectl version`): Kubernetes 1.21.14, deployed using kOps on AWS (similar behavior is issue observed with more recent version of k8s as well).
- Driver version: AWS EBS CSI driver v1.8.0
- Host: Ubuntu 20.04.4 LTS   5.15.0-1017-aws (kernel)

**Comment by paalkr** [comment]
The reason behand enabling iSCSI is to use AWS FSx for NetApp with the Trident CSI driver as a storage provider in our Kubernetes clusters.
https://docs.netapp.com/us-en/trident/trident-use/worker-node-prep.html#iscsi-volumes

**Comment by ConnorJC3** [comment]
Hi, I was able to replicate this issue with Ubuntu, thanks for the concise steps! Unfortunately, when `multipathd` "takes over" a device to add it's `mpathb` subvolume, there is nothing we can do. The linux kernel requires that nothing else is using the device for us to be able to mount it, so `multipathd` needs to be configured not to automatically take over every storage device that is attached.

With some digging, I was able to find that `find_multipaths no` actually causes `multipathd` to behave greedily. When I instead switched to `find_multipaths strict`, `multipathd` did not take over every storage device and instead only added the `mpathb` object to devices that are part of a multipath map. That allowed the EBS CSI Driver to format/mount and use these volumes as normal. I would recommend using that configuration if it is compatible with FSx for NetApp.

**Comment by paalkr** [comment]
Thanks for pointing me in the right direction. Using strict mode kind of works, but it's not ideal and do have some unfortunate side effects. On the other hand, I managed to create a multipath.conf that excluded EBS disks, but still includes NetApp iSCSI volumes.

```
      defaults {
        user_friendly_names yes
        find_multipaths no
      }
      blacklist {
        device {
          vendor "NVME"
          product "Amazon Elastic Block Store"
        }
      }
```

```
ubuntu@ip-10-26-156-208:~$ lsscsi
[0:0:0:0]    disk    NETAPP   LUN C-Mode       9110  /dev/sda
[1:0:0:0]    disk    NETAPP   LUN C-Mode       9110  /dev/sdb
[N:0:0:1]    disk    Amazon Elastic Block Store__1              /dev/nvme0n1
[N:1:0:1]    disk    Amazon Elastic Block Store__1              /dev/nvme1n1 ## EBS CSI PVC volume
```

When listing multipaths you will now see that EBS PVC volumes are not included due to blacklisting
```
ubuntu@ip-10-26-156-208:~$ sudo multipath -v3 -d
Oct 11 20:24:31 | set open fds limit to 1048576/1048576
Oct 11 20:24:31 | loading //lib/multipath/libchecktur.so checker
Oct 11 20:24:31 | checker tur: message table size = 3
Oct 11 20:24:31 | loading //lib/multipath/libprioconst.so prioritizer
Oct 11 20:24:31 | foreign library "nvme" loaded successfully
Oct 11 20:24:31 | nvme0n1: size = 157286400
Oct 11 20:24:31 | nvme0n1: vendor = NVME
Oct 11 20:24:31 | nvme0n1: product = Amazon Elastic Block Store
Oct 11 20:24:31 | nvme0n1: serial = vol0ce5933de455e128d
Oct 11 20:24:31 | nvme0n1: rev = 1.0
Oct 11 20:24:31 | nvme0n1: (NVME:Amazon Elastic Block Store              ) vendor/product blacklisted
Oct 11 20:24:31 | nvme1n1: size = 52428800
Oct 11 20:24:31 | nvme1n1: vendor = NVME
Oct 11 20:24:31 | nvme1n1: product = Amazon Elastic Block Store
Oct 11 20:24:31 | nvme1n1: serial = vol0d4c889d8413a4b6e
Oct 11 20:24:31 | nvme1n1: rev = 1.0
Oct 11 20:24:31 | nvme1n1: (NVME:Amazon Elastic Block Store              ) vendor/product blacklisted
Oct 11 20:24:31 | sda: size = 52428800
Oct 11 20:24:31 | sda: vendor = NETAPP
Oct 11 20:24:31 | sda: product = LUN C-Mode
Oct 11 20:24:31 | sda: rev = 9110
Oct 11 20:24:31 | sda: h:b:t:l = 0:0:0:0
Oct 11 20:24:31 | sda: tgt_node_name = iqn.1992-08.com.netapp:sn.e8391cf2339a11edafc7070f07981745:vs.3
Oct 11 20:24:31 | sda: 25600 cyl, 64 heads, 32 sectors/track, start at 0
Oct 11 20:24:31 | sda: serial = lWB18?TXJ5WX
Oct 11 20:24:31 | sda: detect_checker = yes (setting: multipath internal)
Oct 11 20:24:31 | sda: path_checker = tur (setting: storage device autodetected)
Oct 11 20:24:31 | sda: checker timeout = 30 s (setting: kernel sysfs)
Oct 11 20:24:31 | sda: tur state = up
Oct 11 20:24:31 | sda: uid_attribute = ID_SERIAL (setting: multipath internal)
Oct 11 20:24:31 | sda: uid = 3600a09806c574231383f54584a355758 (udev)
Oct 11 20:24:31 | sda: detect_prio = yes (setting: multipath internal)
Oct 11 20:24:31 | loading //lib/multipath/libpriosysfs.so prioritizer
Oct 11 20:24:31 | sda: prio = sysfs (setting: storage device autodetected)
Oct 11 20:24:31 | sda: prio args = "" (setting: storage device autodetected)
Oct 11 20:24:31 | sda: sysfs prio = 50
Oct 11 20:24:31 | sdb: size = 52428800
Oct 11 20:24:31 | sdb: vendor = NETAPP
Oct 11 20:24:31 | sdb: product = LUN C-Mode
Oct 11 20:24:31 | sdb: rev = 9110
Oct 11 20:24:31 | sdb: h:b:t:l = 1:0:0:0
Oct 11 20:24:31 | sdb: tgt_node_name = iqn.1992-08.com.netapp:sn.e8391cf2339a11edafc7070f07981745:vs.3
Oct 11 20:24:31 | sdb: 25600 cyl, 64 heads, 32 sectors/track, start at 0
Oct 11 20:24:31 | sdb: serial = lWB18?TXJ5WX
Oct 11 20:24:31 | sdb: detect_checker = yes (setting: multipath internal)
Oct 11 20:24:31 | sdb: path_checker = tur (setting: storage device autodetected)
Oct 11 20:24:31 | sdb: checker timeout = 30 s (setting: kernel sysfs)
Oct 11 20:24:31 | sdb: tur state = up
Oct 11 20:24:31 | sdb: uid_attribute = ID_SERIAL (setting: multipath internal)
Oct 11 20:24:31 | sdb: uid = 3600a09806c574231383f54584a355758 (udev)
Oct 11 20:24:31 | sdb: detect_prio = yes (setting: multipath internal)
Oct 11 20:24:31 | sdb: prio = sysfs (setting: storage device autodetected)
Oct 11 20:24:31 | sdb: prio args = "" (setting: storage device autodetected)
Oct 11 20:24:31 | sdb: sysfs prio = 10
Oct 11 20:24:31 | loop0: device node name blacklisted
Oct 11 20:24:31 | loop1: device node name blacklisted
Oct 11 20:24:31 | loop2: device node name blacklisted
Oct 11 20:24:31 | loop3: device node name blacklisted
Oct 11 20:24:31 | loop4: device node name blacklisted
Oct 11 20:24:31 | loop5: device node name blacklisted
Oct 11 20:24:31 | loop6: device node name blacklisted
Oct 11 20:24:31 | loop7: device node name blacklisted
Oct 11 20:24:31 | dm-0: device node name blacklisted
===== paths list =====
uuid                              hcil    dev dev_t pri dm_st chk_st vend/prod
3600a09806c574231383f54584a355758 0:0:0:0 sda 8:0   50  undef undef  NETAPP,LU
3600a09806c574231383f54584a355758 1:0:0:0 sdb 8:16  10  undef undef  NETAPP,LU
Oct 11 20:24:31 | libdevmapper version 1.02.167 (2019-11-30)
Oct 11 20:24:31 | DM multipath kernel driver v1.14.0
Oct 11 20:24:31 | params = 3 queue_if_no_path pg_init_retries 50 1 alua 2 2 service-time 0 1 2 8:16 1 1 service-time 0 1 2 8:0 1 1
Oct 11 20:24:31 | status = 2 0 1 0 2 2 E 0 1 2 8:16 A 0 0 1 A 0 1 2 8:0 A 0 0 1
Oct 11 20:24:31 | sda: udev property ID_WWN whitelisted
Oct 11 20:24:31 | sdb: udev property ID_WWN whitelisted
Oct 11 20:24:31 | unloading sysfs prioritizer
Oct 11 20:24:31 | unloading const prioritizer
Oct 11 20:24:31 | unloading tur checker
```
And that in fact the NetApp iSCSI columes are mounted by Trident CSI using real multipaths with connection to both the FSx for NetApp iSCSI controllers.

```
ubuntu@ip-10-26-156-208:~$ lsblk
NAME                   MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
loop0                    7:0    0 25.1M  1 loop  /snap/amazon-ssm-agent/5656
loop1                    7:1    0 67.8M  1 loop  /snap/lxd/22753
loop2                    7:2    0 55.6M  1 loop  /snap/core18/2538
loop3                    7:3    0   62M  1 loop  /snap/core20/1587
loop4                    7:4    0   47M  1 loop  /snap/snapd/16292
loop5                    7:5    0 10.9M  1 loop  /snap/kubectl/2624
sda                      8:0    0   25G  0 disk
└─3600a09806c574231383f54584a355758
                       253:0    0   25G  0 mpath /var/lib/kubelet/pods/4e4d035a-72ec-4c9e-9cc7-5d6ab147ff14/volumes/kubernetes.io~csi/pvc-d6a72f3f-4a66-4a26-b90c-b79854a58331/mount
sdb                      8:16   0   25G  0 disk
└─3600a09806c574231383f54584a355758
                       253:0    0   25G  0 mpath /var/lib/kubelet/pods/4e4d035a-72ec-4c9e-9cc7-5d6ab147ff14/volumes/kubernetes.io~csi/pvc-d6a72f3f-4a66-4a26-b90c-b79854a58331/mount
nvme0n1                259:0    0   75G  0 disk
├─nvme0n1p1            259:1    0 74.9G  0 part  /
├─nvme0n1p14           259:2    0    4M  0 part
└─nvme0n1p15           259:3    0  106M  0 part  /boot/efi
nvme1n1                259:4    0   25G  0 disk ## EBS CSI PVC volume
```

I would recommend that the AWS FSx for NetApp documentation is updated with a config that let people combine the NetApp Trident CSI driver and the EBS CSI driver in the same cluster.

https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/mount-iscsi-luns-linux.html
https://docs.netapp.com/us-en/trident/trident-use/worker-node-prep.html#iscsi-volumes

**Comment by Linuxine** [comment]
Thanks you very, very much @paalkr for your comment about  adding a blacklist in multipath.conf , it saved me ! 

I had the same issue with Kubernetes version 1.27 and the driver ebs.csi.aws.com version v1.19.0, because I am using a storage managed by NetApp Trident CSI driver, and so the multipath is activated on the nodes.  And I was not able to mount any PV with an EBS storage class in my pods.

It seems the documentation has not been updated, I did not manage to find the information anywhere except here. Thanks a lot ! :hugs:

**Comment by paalkr** [comment]
@Linuxine , the Trident CSI driver was exactly the reason I startet to look into this issue. Happy the solution worked for you as well. I have been in touch with NetApp representatives and suggested they update their examples and documentation.

**Comment by paalkr** [comment]
@Linuxine , the Trident CSI driver was exactly the reason I startet to look into this issue. glad it worked for you as well. I have been in touch with NetApp representatives and suggested that they should update their documentation ad examples.

**Comment by sdodson** [comment]
I'm going to look into whether the `find_multipaths no` option is recommended by any other storage providers. It seems like if we're going to have to co-exist with that configuration it'd be nice if multipath out of the box blacklisted EBS volumes or the plugin were smart enough to still mount them.

**Comment by wonderland** [comment]
Submitted an issue to get this covered in the Trident docs. Just as a side note, the user_friendly_names parameter is no longer required for Trident. So this `multipath.conf` should be all that is needed for proper co-existence of Trident and EBS CSI driver:

```
defaults {
    find_multipaths no
}
blacklist {
    device {
        vendor "NVME"
        product "Amazon Elastic Block Store"
    }
}
```
