### ISSUE TITLE
Add unit test for node service

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#142]
**Is your feature request related to a problem?/Why is this needed**
Add unit test for node service

 - [ ] NodeStageVolume
 - [ ] NodeUnStageVolume
 - [ ] NodePublishVolume
 - [ ] NodeUnpublishVolume
 - [ ] MountOpetion support
 - [ ] NodeStageVolume Idempotency

**Comment by bertinatto** [comment]
/assign

I've been thinking about this, so I'll take a stab at it.

**Comment by leakingtapan** [comment]
To share some ideas in my mind, we can define the driver's `mounter` definition [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/driver/driver.go#L43) using the `mounter.Interface` [interface](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount.go#L41) instead of `mount.SafeFormatAndMount` struct. Since it actual implements the interface [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount.go#L171). With that, we can easily create mocks using gomock and mock it out inside of out unit tests. 

Hope this aligns with what you are thinking

**Comment by bertinatto** [comment]
`FormatAndMount` is only implemented in `mount.SafeFormatAndMount`, so unless we drop it we need this type.

My idea was to use a file as a block device; and use it as a target device in the Node* calls. It might require root privileges, but it's more realistic.

**Comment by leakingtapan** [comment]
`FormatAndMount` is a simple wrapper around `mounter.Interface.Mount(source, target, fstype, options)`

**Comment by bertinatto** [comment]
From what I see, `SafeFormatAndMount.FormatAndMount()` [is a wrapper around  `SafeFormattAndMount.formatAndMount`](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount.go#L181-L183), that in turn [has a lot of logic in it](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_linux.go#L428-L510).

**Comment by leakingtapan** [comment]
You are right, didn't look at the right file...

**Comment by leakingtapan** [comment]
Given that, make `FormatAndMount` being an interface that `SafeFormatAndMount` implements make more make to be, the change will be in upstream which requires extra works, but this could benefit unit testing of other drivers which makes me think worth it.

I feel we can do something like:

```go
type SafeFormatAndMount struct {
    Interface
    Exec
    Formatter
}

type Formatter interface {
    FormatAndMount(source string, target string, fstype string, options []string) error
}

```

How do you think? Also running unit test with sudo is a bit over killing
