### ISSUE TITLE
Enhance Unit test using subtest

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#143]
**Is your feature request related to a problem?/Why is this needed**
golang [subtest](https://golang.org/pkg/testing/#hdr-Subtests_and_Sub_benchmarks) should be used in unit test.

This helps identifying different tests and its result in test results

**Comment by bertinatto** [comment]
/assign 

I've been thinking about this, so I'll take a stab at it.

**Comment by bertinatto** [comment]
/unassign

Sorry, wrong issue.
