### ISSUE TITLE
topology.ebs.csi.aws.com/zone label is unstable

### ISSUE THREAD

**Issue by toan-hf** [kubernetes-sigs/aws-ebs-csi-driver#1431]
/kind bug

**What happened?**

1 of our Prometheus rule detected a metric that always appeared without the label `topology.ebs.csi.aws.com/zone` then it appeared again like the screenshot below. 
![image](https://user-images.githubusercontent.com/57263227/196931737-7acfd587-3ecc-430b-b8f7-650b6b7e9de3.png)

We encountered an issue every time when a new node provisioned, the metric `kubelet_node_name` always reported with the 2 series. 1 **without** the label `topology.ebs.csi.aws.com/zone` then stop sending and another one reported **with** the label `topology.ebs.csi.aws.com/zone`

It seems quite similar to the discussion [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/729#issuecomment-786951950) but we are using the later version and i think it should not happen

**What you expected to happen?**

only 1 series is reported with the proper label `topology.ebs.csi.aws.com/zone` from initial time

**How to reproduce it (as minimally and precisely as possible)?**
I am using KOPS version 1.21.5 to generate the K8s cluster and running on AWS environment 
**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.22.15
- Driver version: 1.2.1

**Comment by toan-hf** [comment]
not sure is it because we failed to publish CSI Node as the Kubelet claims here 
![image](https://user-images.githubusercontent.com/57263227/196934647-e2eff204-aae1-40e4-9b47-51de20dbcbe6.png)

**Comment by torredil** [comment]
Kubelet is responsible for issuing [NodeGetInfo](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/b56e394f4c718d4515958fc03bfd1da5308fea16/pkg/driver/node.go#L556) calls to populate the topology label `topology.ebs.csi.aws.com/zone`. From my understanding, `Failed to publish CSINode` is not related, and the behavior you are experiencing is due to a race condition that is happening outside of the driver's control. In this scenario, I suggest discarding the first few data points or configuring Prometheus in such a way where the race condition doesn't occur by waiting for labels to be added to the node before collecting metrics.

**Comment by toan-hf** [comment]
@torredil thanks for your explanation, 
Indeed, i went through all of our K8s clusters and realized the problem is also happening not only with KOPS but also with EKS 1.23 and AWS EBS CSI Driver 1.5. 

```I suggest discarding the first few data points or configuring Prometheus in such a way where the race condition doesn't occur by waiting for labels to be added to the node before collecting metrics```

Just wondering what would be the actual action to achieve there if you don't mind sharing. I think about changing the scrape interval (extending it a bit longer).

**Comment by torredil** [comment]
@toan-hf Thank you for confirming! Would modifying the query to filter out the time series without the `topology.ebs.csi.aws.com/zone` label work for you? 

```
$ kubelet_node_name{instance="ip-172-31-74-184.eu-west-1.compute.internal",topology.ebs.csi.aws.com/zone=~".+"}
```

**Comment by torredil** [comment]
I have created a timeline to help describe my current understanding of the events that result in this behavior:

<--A------B----C----D-->

- A: New node is provisioned.
- B: Prometheus scrapes `kubelet_node_name` metric (time series **_without_** `topology.ebs.csi.aws.com/zone` is generated).
- C: Driver is deployed and registered with Kubelet using the `node-driver-registrar` sidecar by fetching driver information from the `NodeGetInfo` CSI endpoint. At this point, the `accessible_topology` instance field in `NodeGetInfoResponse` is used to add the `topology.ebs.csi.aws.com/zone` label to the node.
- D: Prometheus scrapes `kubelet_node_name` metric (time series **_with_** `topology.ebs.csi.aws.com/zone` is generated).

Metric labels that have high cardinality may result in excess observability data. Your particular scrape configuration for this metric currently maps **_node labels_** to **_metric labels_**, and a new time series is created every time a metric label value changes. 

Depending on your requirements, you could use relabeling to manipulate the labels being set and limit what gets monitored by the scrape job or opt not to include node labels altogether. For example, using the default labels for this metric:
```
kubelet_node_name{endpoint="https-metrics", instance="172.20.56.144:10250", job="kubelet", metrics_path="/metrics", namespace="kube-system", node="i-0cf45d0b8b81b32b6", service="prometheus-kube-prometheus-kubelet"}
```
results in only one time series when a new node is provisioned :)
