### ISSUE TITLE
CSI EBS driver keeps schedule volumes on NotReady node

### ISSUE THREAD

**Issue by lisikus** [kubernetes-sigs/aws-ebs-csi-driver#1434]
/kind bug

**What happened?**

The node went to the `NotReady` state, but label `topology.ebs.csi.aws.com/zone=us-east-2b` was still attached to it, and the driver assigned volume to this node.
```kubectl get nodes --show-labels
NAME                                                                    STATUS       ROLES      AGE     VERSION                         LABELS
ip-10-30-2-248.us-east-2.compute.internal    NotReady    <none>    4h3m    v1.23.9-eks-ba74326   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m5n.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-2,failure-domain.beta.kubernetes.io/zone=us-east-2b,k8s.io/cloud-provider-aws=0000,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-10-30-2-248.us-east-2.compute.internal,kubernetes.io/os=linux,node.kubernetes.io/instance-type=m5n.xlarge,topology.ebs.csi.aws.com/zone=us-east-2b,topology.kubernetes.io/region=us-east-2,topology.kubernetes.io/zone=us-east-2b
```
Events:
```
    Warning  FailedScheduling    default-scheduler  running PreBind plugin "VolumeBinding": binding volumes: timed out waiting for the condition
Warning  ProvisioningFailed    ebs.csi.aws.com_ebs-csi-controller-bla  failed to get target node: node "ip-10-30-2-248.us-east-2.compute.internal" not found
  Normal   ExternalProvisioning    persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
Normal   Provisioning     ebs.csi.aws.com_ebs-csi-controller-bla  External provisioner is provisioning volume for claim "bla/bla-bla"
```

**What you expected to happen?**
Volumes attachments can't be assigned to nodes with any status, except `Ready/Running`

**How to reproduce it (as minimally and precisely as possible)?**
No info

**Environment**
- Kubernetes version (use `kubectl version`): 
Client Version: v1.25.0
Kustomize Version: v4.5.7
- Driver version:
aws-ebs-csi-driver:v1.11.3

**Comment by ConnorJC3** [comment]
The EBS CSI Driver does not perform scheduling of volumes or pods. That task is performed by [`kube-scheduler`](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/), and any bugs in the process should be reported to the Kubernetes project.

It is likely that you had a pod scheduled to the node in the past when it was ready, or a pod scheduled to the node that tolerates the relevant taint; and that pod has a volume attached.

**Comment by lisikus** [comment]
> The EBS CSI Driver does not perform scheduling of volumes or pods. That task is performed by [`kube-scheduler`](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/), and any bugs in the process should be reported to the Kubernetes project.
> 
> It is likely that you had a pod scheduled to the node in the past when it was ready, or a pod scheduled to the node that tolerates the relevant taint; and that pod has a volume attached.

Thank you for your comment!
No, it was freshly created deployment with pvc, and the pod hasn't been even marked for scheduling, because it was waiting for pvc to be completed creating. 
I also will create requests to ArgoCD project and k8s scheduler teams, but what was surprisingly for me, is that the driver marked this node as available for volumes attachments. As I got from the documentation, it wasn't supposed to be happened, that the label was still assigned to the node, even if it was `NotReady`

**Comment by ConnorJC3** [comment]
The driver doesn't communicate an "available for volumes"/"unavailable for volumes" state, that is entirely determined by Kubernetes. The existence of the `topology.ebs.csi.aws.com` does not indicate anything related to scheduling.

If Kubernetes attempted to create a volume immediately upon creation of a PVC (rather than after the pod was scheduled), it is likely because you are using the `Immediate` [volume binding mode](https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode) rather than `WaitForFirstConsumer`.

**Comment by lisikus** [comment]
> The driver doesn't communicate an "available for volumes"/"unavailable for volumes" state, that is entirely determined by Kubernetes. The existence of the `topology.ebs.csi.aws.com` does not indicate anything related to scheduling.
> 
> If Kubernetes attempted to create a volume immediately upon creation of a PVC (rather than after the pod was scheduled), it is likely because you are using the `Immediate` [volume binding mode](https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode) rather than `WaitForFirstConsumer`.

No, we do have `WaitForFirstConsumer` as binding mode. Usually in that kind of situation, when scheduler tried to assign pod to the node, that went to `NotReady` state, we see that sort of messaged in the events:
```
failed to provision volume with StorageClass "ebs-sc": error generating accessibility requirements: no topology key found on CSINode ip-10-30-3-28.us-east-2.compute.internal
```
So, it triggers redeploy for this pvc and yhe pod. But this time it stuck in state `waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator`
This time, the label was still there, that the only reason I could assume for that weird behaviour happening.

**Comment by ConnorJC3** [comment]
We don't get to decide when a volume is scheduled, we just receive volume create requests and handle them. As for getting stuck on "waiting for a volume to be created", that likely means the driver is failing to create it for some reason. Take a look at the output of `kubectl describe`ing the PVC and the driver controller's logs, and feel free to post here if you can't figure it out.
