### ISSUE TITLE
Reduce time between GitHub and EKS add-on releases

### ISSUE THREAD

**Issue by MurphyPuppy** [kubernetes-sigs/aws-ebs-csi-driver#1445]
/kind bug

**What happened?**

The latest version of the EKS Addon version of this driver is `v1.11.4`. `v1.12.0` has been out since October 4th (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/releases/tag/v1.12.0) - OVER A MONTH ago. There are allegedly CRITICAL security fixes since then. `v1.13.0` is currently being released: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1444

**What you expected to happen?**

EBS CSI Driver is available as an EKS addon with the release that fixes CRITICAL security issues.

**How to reproduce it (as minimally and precisely as possible)?**

Try to install the driver as an addon: https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html

**Anything else we need to know?**:

N/A

**Comment by torredil** [comment]
Hey @murphypuppy, thanks for reaching out. 

Our team strives to deliver the latest CSI driver improvements and security fixes to the community as soon as possible. That’s why we have two release pipelines for the CSI driver: self-managed for [security conscious](https://aws.amazon.com/compliance/shared-responsibility-model/) customers, and the EKS managed add-on for those who place a premium on ease-of-use. Unfortunately, the EKS managed add-on requires additional validation, which sometimes delays its availability.

That said, we continue to look for ways to make the gap between these two releases both shorter and more predictable. As always, thanks for the feedback. We really do appreciate you pushing us to keep raising the bar. Sorry for the inconvenience (again).

**Comment by mikestef9** [comment]
Clarifying the position here. This 100% unrelated to security. In fact, security is one of the core value propositions of EKS add-ons, where all software installed through EKS add-ons is known to be tested and validated by AWS. This ultimately comes down to internal issues that slow down the release process from GitHub to EKS add-ons. It is a top priority to reduce this gap (shorter term to 3 business days, longer term to zero gap). 

We'll leave this open to track progress on these improvements.
