### ISSUE TITLE
Support defining VolumeSnapshotClass(es) via Helm Chart

### ISSUE THREAD

**Issue by sherifabdlnaby** [kubernetes-sigs/aws-ebs-csi-driver#1459]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like in detail**
Define VolumeSnapshotClass(es) via Helm Chart like StorageClass(es) are defined.

**Comment by Sajiyah-Salat** [comment]
Hello @sherifabdlnaby can you please describe your issue in detail?

**Comment by hanyuel** [comment]
PR is merged. Resolving this issue.
