### ISSUE TITLE
aws-ebs-csi-driver/aws-ebs-csi-driver @ 2.14.1 not in index

### ISSUE THREAD

**Issue by mprimeaux** [kubernetes-sigs/aws-ebs-csi-driver#1464]
/kind bug

**What happened?**

Version [2.14.1 is the current version of the Helm chart](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/c59eb1dfd07eefe47fc7cac22412969898cae3e3/charts/aws-ebs-csi-driver/Chart.yaml#L5).  However, after a `helm repo update`, the latest version I see is `2.13.0`.

The [CHANGELOG](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/CHANGELOG.md) indicates `2.14.1` is the latest version.

```shell
helm search repo aws-ebs-csi-driver/aws-ebs-csi-driver

NAME                                 	CHART VERSION	APP VERSION	DESCRIPTION
aws-ebs-csi-driver/aws-ebs-csi-driver	2.13.0       	1.13.0     	A Helm chart for AWS EBS CSI Driver
```

**What you expected to happen?**

I expected to see `2.14.1` as the chart version.

**How to reproduce it (as minimally and precisely as possible)?**

```shell
helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
helm repo update
helm search repo aws-ebs-csi-driver/aws-ebs-csi-driver
```

**Anything else we need to know?**:

Not at this time.

**Environment**
- Kubernetes version (use `kubectl version`): 
- Driver version:

```shell
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.24.7-eks-fb459a0
```

**Comment by ConnorJC3** [comment]
Sorry, seems to be a bug in our Github action for releasing. I've forced it to run again and it should have pushed out `v2.14.1`, please reopen if you have any other problems.

**Comment by mprimeaux** [comment]
@ConnorJC3 Thanks much. I do see `2.14.1` in the index. Thanks much!
