### ISSUE TITLE
Adding PodMonitor support in the chart

### ISSUE THREAD

**Issue by Razgoldenberg1** [kubernetes-sigs/aws-ebs-csi-driver#1466]
**Is your feature request related to a problem? Please describe.**
Hey, I would like to use `podMonitor` instead of `serviceMonitor` with the ebs-csi-driver, today we have a problem with the serviceMonitor of the ebs-csi-driver. the reason is that in some of our environments we have more than 1000 nodes and which creates more than 1000 endpoints for the ebs-csi-driver and there is a limit of 1000 endpoints per service. that limit causes us to lose data from the ebs-csi-driver when we send the data to Prometheus.

The chart has built-in support for serviceMonitor in the values and I would like the podMonitor to have the same.

Until this one going to be merged - https://github.com/prometheus-operator/prometheus-operator/issues/3862

**Comment by ConnorJC3** [comment]
Can you clarify the request? Our [sample Prometheus configuration](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/3eb7ca55a4335440b0a8978db2e14c7f03d14855/charts/aws-ebs-csi-driver/templates/metrics.yaml) only uses the controller, which should not be tied to the number of nodes. The node pod does not expose metrics itself at all (node-related metrics can be obtained via the kubelet).
