### ISSUE TITLE
Helm chart v2.15.0 is creating testing resources during `helm install`

### ISSUE THREAD

**Issue by robinkb** [kubernetes-sigs/aws-ebs-csi-driver#1476]
/kind bug

**What happened?**

Running a diff to upgrade our `aws-ebs-csi-driver` Helm chart to v2.15.0 shows that it is creating resources that are used for testing. These resources were introduced in #1454. The resources are located in [charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml).

**What you expected to happen?**

The chart does not deploy resources related to testing unless I run `helm test`.

**How to reproduce it (as minimally and precisely as possible)?**

Run `helm template` against chart version 2.15.0. Resources like a ServiceAccount named `helm-sa` will be rendered.

**Anything else we need to know?**:

I'm not very familiar with how Helm's test mechanisms, but I think that they are missing the `helm.sh/hook: test` annotation. The Pod is marked with this annotation, and is not being created.

**Environment**

Not relevant.

**Comment by ConnorJC3** [comment]
Hey, sorry about that! We're pushing out a new release that adds the hook - should be available as soon as CI finishes on #1477 as `v2.15.1`

**Comment by robinkb** [comment]
Thanks for the very quick response! ❤️
