### ISSUE TITLE
unable to attach  nvme EBS volume for a self-hosted kind cluster on EC2 instance

### ISSUE THREAD

**Issue by balusarakesh** [kubernetes-sigs/aws-ebs-csi-driver#1478]
**What happened?**
 - I've deployed a kubernetes cluster (1.21.14) on an EC2 instance and deployed a pod with persistent volume
 - I can see the volume attached to the EC2 instance on the console, I can see the volume in `lsblk` and I can also see the volume on the kubernetes node 
 - for some reason the csi-driver is not able to attach the volume to the pod

**What you expected to happen?**
 - EBS volume should be attached to the pod

**How to reproduce it (as minimally and precisely as possible)?**
 - deploy a kubernetes cluster and create persistent volume and attach it to a pod

**ebs-csi-node logs**:
```
I0113 06:34:55.015055       1 node.go:510] NodeGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0113 06:34:55.016811       1 node.go:112] NodeStageVolume: called with args {VolumeId:vol-00e2c7143ba97550d PublishContext:map[devicePath:/dev/xvdbb] StagingTargetPath:/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-a58048ed-eaf2-4dde-b060-3afc4974b96a/globalmount VolumeCapability:mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER >  Secrets:map[] VolumeContext:map[storage.kubernetes.io/csiProvisionerIdentity:1673589680047-8081-ebs.csi.aws.com] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0113 06:34:55.016890       1 node_linux.go:82] [Debug] Falling back to nvme volume ID lookup for: "/dev/xvdbb"
I0113 06:34:55.016901       1 node_linux.go:126] [Debug] nvme path "/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol00e2c7143ba97550d" not found
I0113 06:34:55.016909       1 node_linux.go:99] [Debug] error searching for nvme path "nvme-Amazon_Elastic_Block_Store_vol00e2c7143ba97550d": nvme path "/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol00e2c7143ba97550d" not found
I0113 06:34:55.016916       1 node.go:164] NodeStageVolume: volume="vol-00e2c7143ba97550d" operation finished
I0113 06:34:55.016922       1 inflight.go:74] Node Service: volume="vol-00e2c7143ba97550d" operation finished
E0113 06:34:55.016926       1 driver.go:120] GRPC error: rpc error: code = Internal desc = Failed to find device path /dev/xvdbb. no device path for device "/dev/xvdbb" volume "vol-00e2c7143ba97550d" found
```

**Environment**
- Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version:
helm chart version: `2.15.1`

pvc config:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 4Gi
```

pod config:
```
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: ubuntu:22.04
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
```

**screenshots**:
As you can see from the screenshots the volume is clearly attached to the instance but the logs say it is not found

<img width="1259" alt="Screenshot 2023-01-12 at 10 38 50 PM" src="https://user-images.githubusercontent.com/17168699/212254280-4ee8a591-eb43-481f-a1c0-c009394fe2c2.png">

<img width="702" alt="Screenshot 2023-01-12 at 10 39 01 PM" src="https://user-images.githubusercontent.com/17168699/212254274-30300a1b-c450-43aa-8baa-744b1e8989b2.png">

**Comment by ConnorJC3** [comment]
Can you please deploy a privileged pod in your cluster, and confirm you can see the EBS volumes from inside that pod? I strongly suspect that the method you are using to deploy via kind does not give the cluster access to the block devices on the host.

**Comment by balusarakesh** [comment]
@ConnorJC3  you are right, I ran a privileged container and I don't see any block devices attached to the host.
But I do see the attached volume when I run `lsblk` command.

<img width="616" alt="Screenshot 2023-01-13 at 9 20 10 AM" src="https://user-images.githubusercontent.com/17168699/212380289-7ae88e51-ad99-41f2-bba5-7b6913db5820.png">

**Comment by ConnorJC3** [comment]
The EBS CSI Driver needs access to the volume to mount it. We cannot support usecases where the driver does not have access to the volume to mount it. Please feel free to re-open if you have issues on a cluster where `NVMe` volumes are available at `/dev/disk/by-id/.....`

**Comment by balusarakesh** [comment]
figured it out, I had to mount the `/dev` directory onto control plane and worker nodes like this
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-cluster
nodes: 
- role: control-plane
  extraPortMappings:
  - containerPort: 8081
    hostPort: 8081
  extraMounts:
  - containerPath: /dev
    hostPath: /dev
- role: worker
  extraMounts:
  - containerPath: /dev
    hostPath: /dev
```
