### ISSUE TITLE
EBS CSI Controller pod starts but the logs only show an error: flag provided but not defined: -logging-format

### ISSUE THREAD

**Issue by ashishchandr70** [kubernetes-sigs/aws-ebs-csi-driver#1498]
/kind bug

**What happened?**
I am trying to use persistent volumes in EKS and have followed the instructions given at [EKS persistent storage](https://aws.amazon.com/premiumsupport/knowledge-center/eks-persistent-storage/). 

The CSI controller pods do come up and show running but the logs only show an error: `flag provided but not defined: -logging-format`. I also cannot `kubectl exec` into the pod.

Here is the entire log:

```  
flag provided but not defined: -logging-format
Usage of aws-ebs-csi-driver:
  -add_dir_header
    	If true, adds the file directory to the header of the log messages
  -alsologtostderr
    	log to standard error as well as files (no effect when -logtostderr=true)
  -aws-sdk-debug-log
    	To enable the aws sdk debug log level (default to false).
  -endpoint string
    	Endpoint for the CSI driver server (default "unix://tmp/csi.sock")
  -extra-tags value
    	Extra tags to attach to each dynamically provisioned resource. It is a comma separated list of key value pairs like '<key1>=<value1>,<key2>=<value2>'
  -extra-volume-tags value
    	DEPRECATED: Please use --extra-tags instead. Extra volume tags to attach to each dynamically provisioned volume. It is a comma separated list of key value pairs like '<key1>=<value1>,<key2>=<value2>'
  -http-endpoint :8080
    	The TCP network address where the HTTP server for metrics will listen (example: :8080). The default is empty string, which means the server is disabled.
  -k8s-tag-cluster-id string
    	ID of the Kubernetes cluster used for tagging provisioned EBS volumes (optional).
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory (no effect when -logtostderr=true)
  -log_file string
    	If non-empty, use this log file (no effect when -logtostderr=true)
  -log_file_max_size uint
    	Defines the maximum size a log file can grow to (no effect when -logtostderr=true). Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
  -logtostderr
    	log to standard error instead of files (default true)
  -one_output
    	If true, only write logs to their native severity level (vs also writing to each lower severity level; no effect when -logtostderr=true)
  -skip_headers
    	If true, avoid header prefixes in the log messages
  -skip_log_headers
    	If true, avoid headers when opening log files (no effect when -logtostderr=true)
  -stderrthreshold value
    	logs at or above this threshold go to stderr when writing to files and stderr (no effect when -logtostderr=true or -alsologtostderr=false) (default 2)
  -v value
    	number for the log level verbosity
  -version
    	Print the version and exit.
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
  -volume-attach-limit int
    	Value for the maximum number of volumes attachable per node. If specified, the limit applies to all nodes. If not specified, the value is approximated from the instance type. (default -1)
  -warn-on-invalid-tag
    	To warn on invalid tags, instead of returning an error
```

**What you expected to happen?**
I expected the CSI controllers to start. I also expected to be able to provision persistent volumes.

**How to reproduce it (as minimally and precisely as possible)?**
Follow the instructions at [EKS persistent storage](https://aws.amazon.com/premiumsupport/knowledge-center/eks-persistent-storage/) and try out the test (Test the Amazon EBS CSI driver) given at the end of the instructions

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):

```

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.14-eks-ffeb93d", GitCommit:"96e7d52c98a32f2b296ca7f19dc9346cf79915ba", GitTreeState:"clean", BuildDate:"2022-11-29T18:43:31Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```
- 
- Driver version:
```
{
  "kind": "CSIDriver",
  "apiVersion": "storage.k8s.io/v1",
  "metadata": {
    "name": "ebs.csi.aws.com",
    "uid": "45807c43-4638-4be5-b877-0ae3680882c8",
    "resourceVersion": "52494",
    "creationTimestamp": "2023-01-27T04:30:54Z",
    "labels": {
      "app.kubernetes.io/name": "aws-ebs-csi-driver"
    },
    "annotations": {
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"storage.k8s.io/v1\",\"kind\":\"CSIDriver\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/name\":\"aws-ebs-csi-driver\"},\"name\":\"ebs.csi.aws.com\"},\"spec\":{\"attachRequired\":true,\"fsGroupPolicy\":\"File\",\"podInfoOnMount\":false}}\n"
    },
    "managedFields": [
      {
        "manager": "kubectl-client-side-apply",
        "operation": "Update",
        "apiVersion": "storage.k8s.io/v1",
        "time": "2023-01-27T04:30:54Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:metadata": {
            "f:annotations": {
              ".": {},
              "f:kubectl.kubernetes.io/last-applied-configuration": {}
            },
            "f:labels": {
              ".": {},
              "f:app.kubernetes.io/name": {}
            }
          },
          "f:spec": {
            "f:attachRequired": {},
            "f:fsGroupPolicy": {},
            "f:podInfoOnMount": {},
            "f:requiresRepublish": {},
            "f:storageCapacity": {},
            "f:volumeLifecycleModes": {
              ".": {},
              "v:\"Persistent\"": {}
            }
          }
        }
      }
    ]
  },
  "spec": {
    "attachRequired": true,
    "podInfoOnMount": false,
    "volumeLifecycleModes": [
      "Persistent"
    ],
    "storageCapacity": false,
    "fsGroupPolicy": "File",
    "requiresRepublish": false
  }
}
``` 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by torredil** [comment]
My recommendation here is using our latest official Helm release: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/releases/tag/helm-chart-aws-ebs-csi-driver-2.16.0. We have not yet made a release that supports the `-logging-format` CLI flag which allows you to enable JSON logging.

You are likely running into this because you are using https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml which includes this new parameter but pulls `public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.15.0`. 

This feature will be available in our upcoming `v1.16.0` release.

**Comment by torredil** [comment]
Installation instructions: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md

```
$ helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver

$ helm repo update

$ helm upgrade --install aws-ebs-csi-driver \
    --namespace kube-system \
    aws-ebs-csi-driver/aws-ebs-csi-driver  
```

```
$ helm search repo aws-ebs-csi-driver
NAME                                 	CHART VERSION	APP VERSION	DESCRIPTION
aws-ebs-csi-driver/aws-ebs-csi-driver	2.16.0       	1.15.0     	A Helm chart for AWS EBS CSI Driver  
```

**Comment by ashishchandr70** [comment]
Thanks @torredil - I will try out your recommendations.

**Comment by ashishchandr70** [comment]
Thanks @torredil - the solution suggested by you worked. 

As per the documentation at [User persistent storage in Amazon EKS](https://aws.amazon.com/premiumsupport/knowledge-center/eks-persistent-storage/), Step 7 points to 
```
kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"

```
which I think is the root cause of the error I saw. As per the instructions at [Install EBS CSI driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md), the correct version is 
```
kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.14"
```

This is what resolved my issue.

**Comment by cloneluke** [comment]
the above instructions are more of a workaround "pinning" version of this repo, but shouldn't this issue remain open until the issue is fixed in master also?

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blame/b926e1ee4551e60b44c9b5a887409a8feaf91d86/deploy/kubernetes/base/controller.yaml#L69

**Comment by torredil** [comment]
@cloneluke Using the master branch to deploy the driver is not supported / recommended because the master branch may contain upcoming features incompatible with the currently released stable version of the driver.

If deploying via Kustomize, you should use our release branch (as per our installation guide):
```
kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.15"
```

The premium support article: https://aws.amazon.com/premiumsupport/knowledge-center/eks-persistent-storage/ provides inaccurate information and we are in the process of updating it.

**Comment by tico24** [comment]
The tagged branch also fails though, because the manifests for the tag v1.16.0 reference image tags v1.15.0:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/v1.16.0/deploy/kubernetes/base/controller.yaml#L64
