### ISSUE TITLE
The ebs-plugin container fails to start while deploying the Amazon EBS CSI driver

### ISSUE THREAD

**Issue by matt-finflx** [kubernetes-sigs/aws-ebs-csi-driver#1499]
/kind bug

**What happened?**
While deploying the latest version of the EBS CSI driver, the ebs-csi-controller and ebs-csi-node pods failed to start with CrashLoopBackOff status.
Deploy command:
`kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"`

Pods status:
```
kube-system   ebs-csi-controller-59dd7bf9b4-fb5t4   5/6     CrashLoopBackOff   1          24s
kube-system   ebs-csi-controller-59dd7bf9b4-wvmbq   5/6     CrashLoopBackOff   1          24s
kube-system   ebs-csi-node-5m5dt                    2/3     CrashLoopBackOff   1          24s
kube-system   ebs-csi-node-5nx4t                    2/3     CrashLoopBackOff   1          24s
kube-system   ebs-csi-node-rtmb4                    2/3     CrashLoopBackOff   1          24s
```

The ebs-plugin container failed to start with the following error:
```
kubectl logs -n kube-system ebs-csi-controller-59dd7bf9b4-fb5t4 -c ebs-plugin
flag provided but not defined: -logging-format
Usage of aws-ebs-csi-driver:
  -add_dir_header
    	If true, adds the file directory to the header of the log messages
  -alsologtostderr
    	log to standard error as well as files (no effect when -logtostderr=true)
  -aws-sdk-debug-log
    	To enable the aws sdk debug log level (default to false).
  -endpoint string
    	Endpoint for the CSI driver server (default "unix://tmp/csi.sock")
  -extra-tags value
    	Extra tags to attach to each dynamically provisioned resource. It is a comma separated list of key value pairs like '<key1>=<value1>,<key2>=<value2>'
  -extra-volume-tags value
    	DEPRECATED: Please use --extra-tags instead. Extra volume tags to attach to each dynamically provisioned volume. It is a comma separated list of key value pairs like '<key1>=<value1>,<key2>=<value2>'
  -http-endpoint :8080
    	The TCP network address where the HTTP server for metrics will listen (example: :8080). The default is empty string, which means the server is disabled.
  -k8s-tag-cluster-id string
    	ID of the Kubernetes cluster used for tagging provisioned EBS volumes (optional).
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory (no effect when -logtostderr=true)
  -log_file string
    	If non-empty, use this log file (no effect when -logtostderr=true)
  -log_file_max_size uint
    	Defines the maximum size a log file can grow to (no effect when -logtostderr=true). Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
  -logtostderr
    	log to standard error instead of files (default true)
  -one_output
    	If true, only write logs to their native severity level (vs also writing to each lower severity level; no effect when -logtostderr=true)
  -skip_headers
    	If true, avoid header prefixes in the log messages
  -skip_log_headers
    	If true, avoid headers when opening log files (no effect when -logtostderr=true)
  -stderrthreshold value
    	logs at or above this threshold go to stderr when writing to files and stderr (no effect when -logtostderr=true or -alsologtostderr=false) (default 2)
  -v value
    	number for the log level verbosity
  -version
    	Print the version and exit.
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
  -volume-attach-limit int
    	Value for the maximum number of volumes attachable per node. If specified, the limit applies to all nodes. If not specified, the value is approximated from the instance type. (default -1)
  -warn-on-invalid-tag
    	To warn on invalid tags, instead of returning an error

```

**What you expected to happen?**
Pods should start without errors

**How to reproduce it (as minimally and precisely as possible)?**
`kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
`
**Anything else we need to know?**:
It looks like the newly added parameter: --logging-format is not managed by the aws-ebs-csi-driver.

**Environment**
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-ffeb93d", GitCommit:"f76e2b475d1433cdb6bd546e9e8f129fde938fb7", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:00Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

- Driver version:
Not sure where to get it from. I deployed the latest version as of 29/01/2023

**Comment by ConnorJC3** [comment]
/close

Hi, using the master branch to deploy the EBS CSI driver is not supported, and the master branch may contain upcoming features incompatible with the currently released stable version of the driver.

When deploying via Kustomize, please use one of our release branches such as `release-1.15` (see the installation guide for an example). Alternatively, you can install the driver via Helm.

**Comment by matt-finflx** [comment]
Noted. 
You may need to update the documentation: https://aws.amazon.com/premiumsupport/knowledge-center/eks-persistent-storage/

**Comment by ConnorJC3** [comment]
Thanks, I wasn't aware of those docs. I'll reach out internally at AWS to see if I can get them updated.
