### ISSUE TITLE
Does it work with docker 23.x with CSI support? 

### ISSUE THREAD

**Issue by ieugen** [kubernetes-sigs/aws-ebs-csi-driver#1513]
Hi,

So docker 23.x was released with initial CSI support. 
Is this the right place to "ask" about adding docker support for this plugin ? 

Going through the issue It seems that CSI drivers should work out of the box if they are packaged for docker use.
See https://github.com/moby/moby/pull/41982#issuecomment-943636921 
> Basically, I've had to extract binaries from the images used by Kube or build those binaries from scratch and then build a Swarm CSI compatible Docker Plugin configuration. It's completely possible and doesn't require any changes in the CSI drivers, but I do have to start over from just the binaries.

There is some work relevant to this here https://github.com/olljanat/csi-plugins-for-docker-swarm 

Release notes mention the github issues and what was released.
https://docs.docker.com/engine/release-notes/23.0/

> Add experimental support for SwarmKit cluster volumes (CSI). [moby/moby#41982](https://github.com/moby/moby/pull/41982)
    CLI: Add cluster volume (CSI) options to docker volume. [docker/cli#3606](https://github.com/docker/cli/pull/3606)
    CLI: Add cluster volume (CSI) support to docker stack. [docker/cli#3662](https://github.com/docker/cli/pull/3662)

I am just a Docker user that would like to use EBS volumes with Docker. 
I am opening this issue in the hope that it makes a difference. 
I do imagine docker team can't handle everything on their own and it's something I would like to use.

Thanks,
Eugen

/triage support

**Comment by ConnorJC3** [comment]
Hi @ieugen. Our driver is known to work on alternative container orchestrators such as Nomad and Cloud Foundry. As long as Docker Swarm implements the CSI specification correctly I see no reason the driver couldn't use it.

There is one downside: the driver needs to know what region it is running in. Today, we get that information from either IMDS or Kubernetes (we try both in parallel on startup). Obviously, when not running as Kubernetes that is not an option, so IMDS _must_ be available to the driver to get the region from.

We likely won't provide any official documentation for Docker Swarm at the moment, but our official container image(s) are available [in our README](https://github.com/kubernetes-sigs/aws-ebs-csi-driver#container-images), and we have [documentation about most of the driver's CLI paramaters](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/options.md). In theory, it should be as simple as setting up the driver using Docker's system.

**Comment by ieugen** [comment]
Tracking here https://github.com/olljanat/csi-plugins-for-docker-swarm/pull/12

**Comment by YuryHrytsuk** [comment]
@ieugen is there a conclusion?
