### ISSUE TITLE
Snapshot Retention schedule/period

### ISSUE THREAD

**Issue by ravinayag** [kubernetes-sigs/aws-ebs-csi-driver#1516]
**Is your feature request related to a problem?/Why is this needed**
Looking similar to Lifecycle management for snapshot scheduler as we do in aws console. This enhancement is need as part of K8s ops.
/feature

**Comment by drew-eero** [comment]
Also wondering if there's an existing feature planned for this - scheduling and retention are very helpful to have for creating snapshots

**Comment by ConnorJC3** [comment]
/close

Hi, the EBS CSI Driver cannot schedule snapshots of volumes as it is a low-level CSI driver. Higher level functions such as snapshot scheduled are better performed by other components.

Searching the internet I can see there are already some k8s-native solutions in this space: https://backube.github.io/snapscheduler/

Alternatively, you can use our [volume tagging feature](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/tagging.md) to tag your volumes for [EBS DLM policies](https://docs.aws.amazon.com/ebs/latest/userguide/snapshot-lifecycle.html) you have already created.
