### ISSUE TITLE
Could not create target dir "xxx" mkdir /var/snap: read-only file system

### ISSUE THREAD

**Issue by stany-bns** [kubernetes-sigs/aws-ebs-csi-driver#1517]
/Warning  Failed Mount from kubelet   Message:  MountVolume.MountDevice failed for volume "xxx" rpc error: code = Internal desc = could not create target dir "xxx"  mkdir /var/snap: read-only file system

**What happened?**
Error on a pod when trying to **Dynamic Provisioning** by deploying a **StatefulSet** with a volumeClaimTemplate.
on process the pvc is created, an ebs is also created and attached but finally failed to be mounted on  pod.

**What you expected to happen?**
expected the *PVC* to be mounted on *StatefulSet* successfully and the pod state to be Running

**How to reproduce it (as minimally and precisely as possible)?**
- ubuntu 20.04 LTS
- install microk8s and configure it  [https://microk8s.io/docs/getting-started]()
- install aws-ebs-csi-driver and configure it [https://github.com/kubernetes-sigs/aws-ebs-csi-driver]()
- create a StorageClass
- create a StatefulSet with a volumeClaimTemplate

**Anything else we need to know?**:
![Capture](https://user-images.githubusercontent.com/58684241/221305829-8722602a-0a67-4b76-b888-e3f83303ca00.PNG)

**Environment**
- Kubernetes version (use `1.26`):

**Comment by m-sternberg** [comment]
I'm running into the exact same issue. How did you resolve this one? Thanks! M.
