### ISSUE TITLE
AccessDenied when create ebs-csi-driver

### ISSUE THREAD

**Issue by CuongGiap** [kubernetes-sigs/aws-ebs-csi-driver#1552]
Hi
I'm having a problem when I install ebs-csi-driver for AWS EKS
I used the account with administratoraccess to install via was console but had an error "namespaces "kube-system" is forbidden: User "eks:addon-manager" cannot patch resource "namespaces" in API group "" in the namespace "kube-system""
I don't know why the administrator permission can not install add-on.
I also tried to create IAM role but follow [Link](https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html) but receive error : Error from server (NotFound): serviceaccounts "ebs-csi-controller-sa" not found

I just started with EKS so don't know how t resolve, 
Anyone can help ?

Thank you

**Comment by ConnorJC3** [comment]
Hi, as this is a problem with the EKS Addons system in general (and not the driver addon specifically), please reach out to AWS support for assistance.

They will have the access to your cluster and the EKS Addons system to be able to assist you in debugging and fixing your issue.

**Comment by ConnorJC3** [comment]
/close

Closing this, as it is not a problem with the upstream EBS CSI Driver. As mentioned above, anybody encountering this issue should reach out to AWS support for assistance, as it is an issue with the EKS Addons system in general and not the EBS CSI Driver.
