### ISSUE TITLE
Observability and Proactive issue Identification and resolution

### ISSUE THREAD

**Issue by rajashekhargundeti** [kubernetes-sigs/aws-ebs-csi-driver#1557]
Hi,

CSI Driver has two main components, controller and driver. controller runs in control plane and driver runs in data/customer plane usually. As a could/service provider, you host and run control plane components. As driver gets installed on worker nodes, how do you get notified of any issues/errors and in general how do you improve observability for the components that get installed on worker nodes.

I'm curious to know the possible ways.

**Comment by ConnorJC3** [comment]
/close

Hi, logging and observability on Kubernetes is a complex topic not appropriate for discussion in the EBS CSI Driver docs.

The EBS CSI Driver does not behave in any significantly different way than other Kubernetes applications, and thus can be monitored similarly.

For prescriptive guidance on how EKS recommends logging is performed, check out the [EKS Documentation](https://docs.aws.amazon.com/prescriptive-guidance/latest/implementing-logging-monitoring-cloudwatch/kubernetes-eks-logging.html#eks-node-application-logging).
