### ISSUE TITLE
kubelet --root-dir is not respected → driver fails to start

### ISSUE THREAD

**Issue by artem-zinnatullin** [kubernetes-sigs/aws-ebs-csi-driver#1565]
/kind bug

**What happened?**

Trying to deploy `aws-ebs-csi-driver` add-on on EKS 1.25 cluster with different `kubelet` root dir (default is `/var/lib/kubelet`):

```js
/etc/eks/bootstrap.sh --kubelet-extra-args "--root-dir=/nvme1/var/lib/kubelet"
```

`aws-ebs-csi-driver` add-on fails to be start due to

```js
  Warning  FailedMount  17s (x13 over 10m)     kubelet            MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry/ is not a directory
```

```js
kubectl describe pod -n kube-system ebs-csi-node-dp8nz
Events:
  Type     Reason       Age                    From               Message
  ----     ------       ----                   ----               -------
  Normal   Scheduled    10m                    default-scheduler  Successfully assigned kube-system/ebs-csi-node-dp8nz to ip-172-31-4-61.ec2.internal
  Warning  FailedMount  3m59s (x2 over 8m30s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[registration-dir], unattached volumes=[kubelet-dir plugin-dir device-dir kube-api-access-xldkb registration-dir]: timed out waiting for the condition
  Warning  FailedMount  101s (x2 over 6m16s)   kubelet            Unable to attach or mount volumes: unmounted volumes=[registration-dir], unattached volumes=[plugin-dir device-dir kube-api-access-xldkb registration-dir kubelet-dir]: timed out waiting for the condition
  Warning  FailedMount  17s (x13 over 10m)     kubelet            MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry/ is not a directory
```

**What you expected to happen?**

`aws-ebs-csi-driver` add-on should deploy normally and respect `kubelet --root-dir` as it is the standard way for kubelet root dir to be overridden to a different location.

Or the driver should allow customizing `/var/lib/kubelet/plugins_registry/` via add-on `configuration_values` defined in Terraform.

**How to reproduce it (as minimally and precisely as possible)?**

Setup EKS cluster with node group that has custom startup script that points `kubelet --root-dir` to a different location, in our case we run `r5d.4xlarge` worker nodes and to utilize their NVMe for container images and workdir state we point `kubelet` `--root-dir` to `/nvme1/var/lib/kubelet` as this is how it should be done with `kubelet` via [/etc/eks/bootstrap.sh](https://github.com/awslabs/amazon-eks-ami/blob/1efc3d6630bac4f82c05f15faf698a481ff7129d/files/bootstrap.sh#L31) `--kubelet-extra-args`

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.25 EKS
- Driver version: `v1.17.0-eksbuild.1`

**Comment by ConnorJC3** [comment]
Hi, customization of the Kubelet dir via `configuration_values` will be available in the next EKS Addon release of the EBS CSI Driver (no firm release date I can promise, but currently planned for mid to late April).

In the meantime, as a workaround, you can either deploy the driver self-managed (via our helm chart) or deploy the driver an an EKS Addon and modify the node DaemonSet to replace `/var/lib/kubelet` with the modifies location in all occurrences.

**Comment by artem-zinnatullin** [comment]
For now as a workaround I had to make symlink back in `/var/lib/kubelet` for compatibility

```js
ln -s /nvme1/var/lib/kubelet /var/lib/kubelet
```

`ebs-csi-node-` pods were able to start on nodes with such symlink.

---

>Hi, customization of the Kubelet dir via configuration_values will be available in the next EKS Addon release of the EBS CSI Driver (no firm release date I can promise, but currently planned for mid to late April).

Great, thank you!

Please post update here when it will be available!

**Comment by ConnorJC3** [comment]
While pods may start with a symlink, I should warn that is not a supported configuration and EBS volumes will likely not mount correctly when you try to use them.

**Comment by artem-zinnatullin** [comment]
Ouch, thanks for the heads up. Will look into deploying custom Helm chart for `aws-ebs-csi-driver` then

**Comment by ConnorJC3** [comment]
Hi, sorry for the late comment, but the v1.18.0-eksbuild.1 of the EKS Addon version of the driver should now be available in all regions (or more specifically, it was available as of EoD last Friday April 28th).

This version should now support customizing the kubelet path via the [EKS Addons advanced config feature](https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/).

The config should be the same as the helm config, something like:
```json5
{
  "node": {
    "kubeletPath": "/my/custom/kubelet/path/"
  }
}
```

I'm going to proactively /close this issue as fixed, but please feel free to reopen and reach out if you need any further assistance!
