### ISSUE TITLE
v1.19.0 - Controller fails to start up, throwing error `unknown flag: --user-agent-extra`

### ISSUE THREAD

**Issue by tico24** [kubernetes-sigs/aws-ebs-csi-driver#1604]
/kind bug

**What happened?**
Installed v1.19.0 using kustomize:
`github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=v1.19.0`

Controller fails to start up, throwing error `unknown flag: --user-agent-extra`

I couldn't see anything in the release notes about this, and the `--user-agent-extra` flag is indeed passed to the controller as an arg in the v1.19 kustomization base.

**What you expected to happen?**
The official kustomize base to work for v1.19x.

**How to reproduce it (as minimally and precisely as possible)?**
Install v1.19.0 using kustomize.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.26.2
- Driver version: 1.19.0

**Comment by torredil** [comment]
Hey @tico24, thank you for reporting this. I was unable to reproduce it.

```
$ kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.19"
```

```
$ kubectl get pods -n kube-system

ebs-csi-controller-7fd9dbcfc6-vrs8m           6/6     Running   0             4s
ebs-csi-controller-7fd9dbcfc6-xjkn4           6/6     Running   0             4s
ebs-csi-node-8r6lc                            3/3     Running   0             4s
ebs-csi-node-jmhsh                            3/3     Running   0             4s
```

```
$ kubectl describe pod ebs-csi-controller-7fd9dbcfc6-vrs8m -n kube-system

Containers:
  ebs-plugin:
    Container ID:  containerd://0babf3a7a76869de60c183b34025bc849a45de0ca3f95e879c966205cb079337
    Image:         public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.19.0
    Image ID:      public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver@sha256:2fd443931212864f32df9aad64b6c5f33e0e62de62f907ca949f16465dcda17e
    Port:          9808/TCP
    Host Port:     0/TCP
    Args:
      --endpoint=$(CSI_ENDPOINT)
      --logging-format=text
      --user-agent-extra=kustomize
      --v=2
    State:          Running
```

**Comment by tico24** [comment]
It occurs on two eks clusters for me.

**Comment by tico24** [comment]
There seems to be a difference between

`github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.19`
and
` github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=v1.19.0`

**Comment by torredil** [comment]
`github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=v1.19.0` pulls the v1.18 image and will cause this issue. Use `release-1.19` instead as described in the [installation instructions](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md#kustomize).
