### ISSUE TITLE
PVC is pending then failing

### ISSUE THREAD

**Issue by idomic** [kubernetes-sigs/aws-ebs-csi-driver#1609]
/kind bug

**What happened?**
Been following this guide:
https://repost.aws/knowledge-center/eks-persistent-storage

Then when running cd aws-ebs-csi-driver/examples/kubernetes/dynamic-provisioning/
and `kubectl apply -f manifests/`
Seems like the pv doesn't start.

**What you expected to happen?**
I expected the storage to be bound.

**How to reproduce it (as minimally and precisely as possible)?**
Just run the commands in the manual.

**Anything else we need to know?**:
Here are the logs I'm seeing:
```
Type     Reason                Age                    From                                                                                      Message                    │
│   ----     ------                ----                   ----                                                                                      -------                    │
│   Normal   Provisioning          111s (x10 over 7m26s)  ebs.csi.aws.com_ebs-csi-controller-65987f7594-fjtb7_0ed2c32d-8ddc-4b04-9144-b4a8e61584d8  External provisioner is pr │
│ ovisioning volume for claim "default/slow"                                                                                                                                   │
│   Warning  ProvisioningFailed    101s (x10 over 7m16s)  ebs.csi.aws.com_ebs-csi-controller-65987f7594-fjtb7_0ed2c32d-8ddc-4b04-9144-b4a8e61584d8  failed to provision volume │
│  with StorageClass "generic": rpc error: code = DeadlineExceeded desc = context deadline exceeded                                                                            │
│   Normal   ExternalProvisioning  80s (x26 over 7m26s)   persistentvolume-controller                                                               waiting for a volume to be │
│  created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator      
```

**Environment**
- Kubernetes version (use `kubectl version`): 1.25
- Driver version: 1.18

**Comment by torredil** [comment]
Hey there @idomic, this sounds like a permissions issue; the EBS CSI driver requires IAM permissions to make calls to AWS APIs on your behalf. If you are deploying the driver as an EKS-managed add-on (recommended) [this user guide](https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html.) will walk you through creating the IAM role.

Please ensure that you have created an [IAM OIDC provider for your cluster](https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html), this is necessary to use IAM roles for service accounts.

Once that is complete, you can deploy the EBS CSI add-on by following the steps in [Adding the Amazon EBS CSI add-on](https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html#adding-ebs-csi-eks-add-on).

---
For your convenience:

1. Enable OIDC.
```
$ eksctl utils associate-iam-oidc-provider --approve --cluster <your_cluster> --region <your_region>
```

2. Create the service account.
```
$ eksctl create iamserviceaccount --cluster <your_cluster> --namespace kube-system --name ebs-csi-controller-sa --approve --role-only --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy --region <your_region> --role-name EBSCSIDriverRole
```

3. Get the role ARN.
```
$ ROLE_ARN=$(aws iam get-role --query 'Role.Arn' --output text --role-name EBSCSIDriverRole)
```

4. Install the add-on.
```
$ eksctl create addon --name aws-ebs-csi-driver --cluster <your_cluster> --service-account-role-arn $ROLE_ARN --region <your_region>
```

5. Deploy dynamic provisioning manifests.
```
$ cd aws-ebs-csi-driver/examples/kubernetes/dynamic-provisioning/
$ kubectl apply -f manifests/
```


If you run into any issues or any of that sounds confusing let me know and I'll be happy to help.

**Comment by ConnorJC3** [comment]
"context deadline exceeded" errors typically indicate a networking or DNS error - the EBS CSI Driver is timing out attempting to reach the AWS API.

Please make sure that pods in your cluster are able to reach both the AWS API and k8s API, which is necessary for the EBS CSI Driver to function.

If you are running a cluster using a private VPC subnet, you likely need to enable VPC endpoints or otherwise allow access to the AWS API: https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html
