### ISSUE TITLE
dynamically read AWS Creds from a file or k8s Secret

### ISSUE THREAD

**Issue by nkk1** [kubernetes-sigs/aws-ebs-csi-driver#1613]
**Is your feature request related to a problem?/Why is this needed**
We are unable to use IRSA (since we run a lot of EKS clusters and AWS has limits like 100 OIDC Providers etc) and we don't want to give so many permissions, required to EBS CSI Controller, to the Nodes as well as it would be a security issue.

So we are planning to use [Vault to generate dynamic creds and Inject via sidecar](https://www.hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar). From the [doc](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md#set-up-driver-permissions) we are left with the only option `kubectl create secret generic aws-secret`. We can use this but when Vault updates the creds we need EBS CSI Controller to re-read the creds.

/feature

**Describe the solution you'd like in detail**
We need EBS CSI Controller to re-read the creds coming from K8s Secret or from FS

**Describe alternatives you've considered**
may be some custom code running as side car that will restart the ebs-csi-controller when creds are updated

**Comment by opsroller** [comment]
Why aren't you using OIDC for the ServiceAccount?

**Comment by nkk1** [comment]
> Why aren't you using OIDC for the ServiceAccount?

we have more than 100 clusters, so we hit the OIDC Providers limit. Now that the [EKS Pod identities](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html) is out we will use that. So we can close this
