### ISSUE TITLE
csi-attacher restart causes EBS Detach Volume

### ISSUE THREAD

**Issue by kbsonlong** [kubernetes-sigs/aws-ebs-csi-driver#1623]
/kind bug

**What happened?**

csi-attacher get api-server timeout, csi-attacher restart causes EBS Detach Volume

**What you expected to happen?**

ebs-csi-controller restart should not cause EBS Disk Detach Volume

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

```text
I0607 08:33:50.607631       1 leaderelection.go:278] successfully renewed lease kube-system/external-attacher-leader-ebs-csi-aws-com
I0607 08:34:05.609223       1 round_trippers.go:553] GET https://10.254.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/external-attacher-leader-ebs-csi-aws-com  in 10000 milliseconds
E0607 08:34:05.609285       1 leaderelection.go:330] error retrieving resource lock kube-system/external-attacher-leader-ebs-csi-aws-com: Get "https://10.254.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/external-attacher-leader-ebs-csi-aws-com": context deadline exceeded
I0607 08:34:05.609327       1 leaderelection.go:283] failed to renew lease kube-system/external-attacher-leader-ebs-csi-aws-com: timed out waiting for the condition
F0607 08:34:05.609354       1 leader_election.go:182] stopped leading
```
<img width="1420" alt="image" src="https://github.com/kubernetes-sigs/aws-ebs-csi-driver/assets/23339284/1cc90658-998a-46eb-accd-19d989b10e76">

**Environment**
- Kubernetes version (use `kubectl version`):

```text
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:06:15Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:00:37Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version: 1.16.0

**Comment by hanyuel** [comment]
Hi @kbsonlong , thanks for opening this issue. Can you add repro steps? I'd like to try to reproduce it on my end so I can collect logs to investigate.

**Comment by AndrewSirenko** [comment]
Going to close this for now because it's been a few months, but feel free to re-open if the issue is still persisting and we were able to get some repro steps. /close
