### ISSUE TITLE
EKS 1.27 volume provisioning fails with User: assumed-role/role_name/instance_id is not authorized to perform: sts:AssumeRole on resource: role/role_name

### ISSUE THREAD

**Issue by EvgeniGordeev** [kubernetes-sigs/aws-ebs-csi-driver#1625]
/kind bug

NB: this configuration used to work in EKS 1.26. 

After the upgrade from 1.26 to 1.27 EBS volumes cannot be provisioned  due to 

```
E0614 01:12:39.578856       1 driver.go:122] "GRPC error" err=<
	rpc error: code = Internal desc = Could not create volume "pvc-hash": could not create volume in EC2: NoCredentialProviders: no valid providers in chain
	caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
	SharedCredsLoad: failed to load profile, .
	EC2RoleRequestError: failed to get role_name EC2 instance role credentials
	caused by: EC2MetadataError: failed to make EC2Metadata request
	AccessDenied: User: arn:aws:sts::account_id:assumed-role/role_name/instance_id is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::account_id:role/role_name
		status code: 403, request id: 2b38a173-6fae-42c3-ab6c-136448bf8792
	
		status code: 500, request id: 
```

Scenario:
1. EKS cluster 1.27 is created
2. Amazon EBS CSI Driver is installed via Cloud formation with Service Role created as per https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html
3. 
```bash
kubectl -n kube-system describe serviceaccount ebs-csi-controller-sa
Name:                ebs-csi-controller-sa
Namespace:           kube-system
Labels:              app.kubernetes.io/component=csi-driver
                     app.kubernetes.io/managed-by=EKS
                     app.kubernetes.io/name=aws-ebs-csi-driver
                     app.kubernetes.io/version=1.19.0
Annotations:         eks.amazonaws.com/role-arn: arn:aws:iam::account_id:role/AmazonEKS_EBS_CSI_DriverRole
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>
```
4. `kubectl logs -n kube-system -l app=ebs-csi-controller` gives the error when an EBS volume is attempted to be provisioned.
5. Node instance profile `arn:aws:iam::*:role/instance-profile-*` is allowed to assume the role in the log message: 
Trust relationship: 

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

Inline policy: 

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "sts:AssumeRole"
            ],
            "Resource": [
                "arn:aws:iam::*:role/instance-profile-*"
            ],
            "Effect": "Allow",
            "Sid": "AssumeRolesForKube2Iam"
        }
    ]
}
```

**Environment**
- Kubernetes version: 1.27
- Driver version: v1.19.0-eksbuild.2

**Comment by ConnorJC3** [comment]
Hi, this appears to be an issue with your IRSA configuration. The EBS CSI Driver is falling back to attempting to use the instance role (which would not happen if it was able to obtain IRSA creds).

For issues with IRSA, please contact AWS support, who have the knowledge and tools for debugging.

**Comment by EvgeniGordeev** [comment]
IRSA was configured right and the IAM role got changed from "Inherit from Node" to the IRSA role 'AmazonEKS_EBS_CSI_DriverRole'. Restarting ebs-csi-controller `kubectl rollout restart deployment ebs-csi-controller -n kube-system` or recreating the addon didn't help. 

Recreating serviceaccount helped and ebs volume attachment started working: 

```bash
kubectl -n kube-system get serviceaccount ebs-csi-controller-sa  -o yaml > sa.yaml
kubectl -n kube-system delete serviceaccount ebs-csi-controller-sa
kubectl apply -f sa.yaml
```
