### ISSUE TITLE
Add docs for migration ebs

### ISSUE THREAD

**Issue by nikolasj** [kubernetes-sigs/aws-ebs-csi-driver#1628]
Need documentation with examples on how to transfer data from ebs unencrypted to encrypted.

**Comment by hanyuel** [comment]
Hi @nikolasj , thanks for opening the issue. 
You cannot directly encrypt existing unencrypted volumes or snapshots. However, you can create encrypted volumes or snapshots from unencrypted volumes or snapshots. 
See the EBS documentation here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-parameters

**Comment by nikolasj** [comment]
Hi @hanyuel! 
Thank you. I understand how to encrypt a volume. But how to transfer data to this new encrypted EBS?
How do I specify that the new encrypted volume be used? 
Can this only be done using Static Provisioning? Or are there options with Dynamic Provisioning?

**Comment by ConnorJC3** [comment]
/close

Hi all, you can modify the type, iops, and/or throughput (and in a future release, tags) of a volume, see our documentation here: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/modify-volume.md

Modifying the encryption status of a volume is not supported by EBS at this time. We will look into adding support if/when EBS supports changing the encryption status of existing volumes.
