### ISSUE TITLE
Pod remains pending and PVC stays unbound

### ISSUE THREAD

**Issue by rabbagliettiandrea** [kubernetes-sigs/aws-ebs-csi-driver#1631]
/kind bug

**What happened?**
When launching a new release of the Bitnami/PostgreSQL Helm chart using EBS CSI with a storage class configured with `WaitForConsumer`, I sometimes encounter an issue where the Pod remains pending because it cannot find the PVC (PersistentVolumeClaim). The PVC also remains pending because it doesn't have any consumer associated with it, which is expected behavior. However, after several minutes (around 6 or 7), the issue seems to resolve itself, and the PVC binds successfully, allowing the Pod to be scheduled and start working.

**What you expected to happen?**
The Pod should be scheduled and start running immediately after the PVC binds successfully.

**How to reproduce it (as minimally and precisely as possible)?**
1. Deploy the Bitnami/PostgreSQL Helm chart using EBS CSI with a storage class configured with `WaitForConsumer`.
2. Observe the Pod and PVC creation process.

**Anything else we need to know?**:
Events from `kubectl describe pod`:

```
Events:
  Type     Reason                  Age   From                     Message
  ----     ------                  ----  ----                     -------
  Warning  FailedScheduling        36m   default-scheduler        running PreFilter plugin "VolumeBinding": error getting PVC "default/postgresql-0": could not find v1.PersistentVolumeClaim "default/data-postgresql-0"
  Normal   Scheduled               32m   default-scheduler        Successfully assigned default/postgresql-0 to worker1234
  Normal   SuccessfulAttachVolume  32m   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-348e7a01-c0af-4a0f-8fb9-9c9cf9a8bf45"
  Normal   Pulled                  32m   kubelet                  Container image "docker.io/bitnami/postgresql:15.3.0-debian-11-r7" already present on machine
  Normal   Created                 32m   kubelet                  Created container postgresql
  Normal   Started                 32m   kubelet                  Started container postgresql
```

**Environment**
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:36:43Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1+k3s1", GitCommit:"bc5b42c27908ab430101eff0db0a0b22f870bd7a", GitTreeState:"clean", BuildDate:"2023-04-27T21:02:08Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/arm64"}

- Driver version:
2.19.0

**Comment by hanyuel** [comment]
Hi @rabbagliettiandrea , do you have EBS CSI controller logs ``ebs-plugin`` and ``csi-provisioner`` logs for the pod and pvc creation process when the issue occurs?
