### ISSUE TITLE
CSI Driver reports error when retrieving EC2 metadata

### ISSUE THREAD

**Issue by gabrielkim-ibm** [kubernetes-sigs/aws-ebs-csi-driver#1632]
/kind bug

**What happened?**

OCP Version: 4.10.xx
EBS Driver Version: 1.19

The EBS CSI driver is configured to interact with the EC2 instance to retrieve the instance metadata, so it will know where to mount the dynamically provisioned volume. The AWS Instance MetaData Service (IMDS) is now in v2 and switched to "Required".
With this configuration, the driver reports the following error when retrieving ec2 instance metadata:

"Driver Information" Driver="ebs.csi.aws.com" Version="v1.19.0"
"regionFromSession Node Service" region="us-east-1"
"retrieving instance metadata from ec2 metadata"
"ec2 metadata is not available"
"retrieving instance data from kubernetes api"
"kubernetes api is available"
panic: node providerID empty,  cannot parse

Switching the IMDS enforcement to "Optional" reverts IMDS to v1 and makes the driver operate successfully. However, we need the IMDSv2 option to be turned to "Required" as an enterprise security mandate.

IMDSv2 requires a token in requests for metadata, and we believe that the error is due to non-availability of the token in the CSI drivers requests for metadata. Here are some questions that we need answers to:

- How and where can we secure the token for the CSI Driver?
- 
- What is the procedure to set the token, either on EC2 or on OpenShift, so that the driver operates with IMDSv2?

**Environment**
- OCP Version: 4.10.xx
- Driver version: 1.19

**Comment by Sina-IBM** [comment]
I can confirm that attaching the recommended policy to an instance profile is not supported if IMDSv2 is enabled. This should be made clear in the documentation.

**Comment by bryanasdev000** [comment]
For now, a workaround is possible by setting `hostNetwork: true` and `dnsPolicy: ClusterFirstWithHostNet` on `ebs-csi-controller`.

Although I am using Cillium as CNI, this should help in other cases too as we directly bind to the host network.

Maybe changing to IRSA or AWS Keys work too, but is not much practical in my case.

For me, this request timeouts inside a pod:

```
curl -vX PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"
*   Trying 169.254.169.254:80...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> PUT /latest/api/token HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/8.1.2
> Accept: */*
> X-aws-ec2-metadata-token-ttl-seconds: 21600
...
```

But not inside the host:

```
curl -vX PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"
*   Trying 169.254.169.254:80...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> PUT /latest/api/token HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.88.1
> Accept: */*
> X-aws-ec2-metadata-token-ttl-seconds: 21600
> 
< HTTP/1.1 200 OK
< X-Aws-Ec2-Metadata-Token-Ttl-Seconds: 21600
< Content-Length: 56
< Date: Thu, 22 Jun 2023 00:34:06 GMT
< Server: EC2ws
< Connection: close
< Content-Type: text/plain
< 
* Closing connection 0
```

Since we use node role, we get generic auth errors.

**Comment by Indresh2410** [comment]
@bryanasdev000 Just wondering by having PUT_RESPONSE_HOP_LIMIT > 1 for ec2 instance will fix the issue ? (Since the issue is seen only inside pod)

**Comment by s3than** [comment]
I can report that setting the response hop limit to `3` allows the metadata to be retrieved again..

**Comment by hanyuel** [comment]
From the [IMDSv2 documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html#imds-considerations): 
> In a container environment, if the hop limit is 1, the IMDSv2 response does not return because going to the container is considered an additional network hop. To avoid the process of falling back to IMDSv1 and the resultant delay, in a container environment we recommend that you set the hop limit to 2. 

EBS CSI Driver support IMDSv2 and it requires the hop limit to be 2 or greater. You can set the hop limit via ``aws ec2 modify-instance-metadata-options`` command like this
```
aws ec2 modify-instance-metadata-options \
    --instance-id <instance_id> \
    --http-put-response-hop-limit 2 \
    --http-tokens required \
    --http-endpoint enabled
```
 Details here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-IMDS-existing-instances.html#modify-PUT-response-hop-limit

**Comment by AndrewSirenko** [comment]
Going to close this for now due to the hop limit suggestion above, but feel free to reopen if you run into more issues!  /close
