### ISSUE TITLE
Advanced configuration for AWS EBS add-on does not work

### ISSUE THREAD

**Issue by EvgeniGordeev** [kubernetes-sigs/aws-ebs-csi-driver#1633]
/kind bug

Trying to update add-on's  advanced configuration in AWS console with 
```json
{"node": { "resources": { "requests": { "cpu": "10m", "memory": "40Mi"}}}}
```

leads to 

>   DaemonSet.apps "ebs-csi-node-windows" is invalid: [spec.template.spec.containers[0].resources.requests[memory:"40Mi"]: Invalid value: "memory:\"40Mi\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.template.spec.containers[0].resources.requests[memory:"40Mi"]: Invalid value: "memory:\"40Mi\"": must be a standard resource for containers, spec.template.spec.containers[0].resources.requests[cpu:"10m"]: Invalid value: "cpu:\"10m\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.template.spec.containers[0].resources.requests[cpu:"10m"]: Invalid value: "cpu:\"10m\"": must be a standard resource for containers, spec.template.spec.containers[1].resources.requests[memory:"40Mi"]: Invalid value: "memory:\"40Mi\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.template.spec.containers[1].resources.requests[memory:"40Mi"]: Invalid value: "memory:\"40Mi\"": must be a standard resource for containers, spec.template.spec.containers[1].resources.requests[cpu:"10m"]: Invalid value: "cpu:\"10m\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.template.spec.containers[1].resources.requests[cpu:"10m"]: Invalid value: "cpu:\"10m\"": must be a standard resource for containers, spec.template.spec.containers[2].resources.requests[memory:"40Mi"]: Invalid value: "memory:\"40Mi\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.template.spec.containers[2].resources.requests[memory:"40Mi"]: Invalid value: "memory:\"40Mi\"": must be a standard resource for containers, spec.template.spec.containers[2].resources.requests[cpu:"10m"]: Invalid value: "cpu:\"10m\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.template.spec.containers[2].resources.requests[cpu:"10m"]: Invalid value: "cpu:\"10m\"": must be a standard resource for containers]

**Environment**
- Kubernetes version: 1.27
- Driver version: v1.19.0-eksbuild.2

**Comment by hanyuel** [comment]
Hi @EvgeniGordeev , I'm wondering if you are able to set the same advanced configurations via ``aws eks update-addon`` command?

**Comment by torredil** [comment]
Tested on several versions of K8s and was unable to reproduce it. Will leave this open for now, let us know if you run into this again or find a way to reliably reproduce it, thanks.

**Comment by ConnorJC3** [comment]
/close

Hi @EvgeniGordeev - as mentioned above, we have attempted to replicate this issue and could not reproduce. Please reach out to AWS Support for debugging issues with the EKS Addon service, as they have the necessary knowledge, tools, and access to do so. Thanks!
