### ISSUE TITLE
Add documentation and helm chart --kube-api-burst --kube-api-qps

### ISSUE THREAD

**Issue by mirajranpura** [kubernetes-sigs/aws-ebs-csi-driver#1666]
**Is your feature request related to a problem?/Why is this needed**

Both parameters below are important for cluster with ebs backed pvcs at scale.  
--kube-api-burst 
--kube-api-qps

/feature

**Describe the solution you'd like in detail**
1. Add more information about such tuning parameters 
2. Include them in ebs csi helm chart 

**Describe alternatives you've considered**
Out of band changes for existing charts 

```[tasklist]
### Tasks
```

**Comment by torredil** [comment]
Closing now that https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1834 (more sensible defaults) and https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1697 (documentation) have been merged.

/close
