### ISSUE TITLE
CSI RPC call timeouts are non-optimal

### ISSUE THREAD

**Issue by gnufied** [kubernetes-sigs/aws-ebs-csi-driver#1671]
Currently we are using default timeout for most operations in helm charts and I do not think they are optimal. For example, default provisioner timeout is 10s and default attacher timeout is 15s. When last we measured these numbers, we found them to be too low for EBS driver.

**Comment by torredil** [comment]
@gnufied Yeah those default values are pretty aggressive. Will do some measuring and find more suitable defaults, thanks for flagging this.
