### ISSUE TITLE
Use AWS sdk v2 instead of v1

### ISSUE THREAD

**Issue by Fricounet** [kubernetes-sigs/aws-ebs-csi-driver#1684]
/kind feature

**Is your feature request related to a problem?/Why is this needed**
I would like to add more telemetry to the driver using opentelemetry traces. An easy way to get some interesting traces is by instrumenting the libraries like grpc and aws-sdk. But opentelemetry only supports the instrumentation of [aws-sdk-go-v2](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/github.com/aws/aws-sdk-go-v2/otelaws). So I would need to migrate the current driver to the sdk v2.

I do not know if this feature was not added yet for a specific reason. 

**Describe the solution you'd like in detail**
Follow the [AWS sdk migration doc](https://aws.github.io/aws-sdk-go-v2/docs/migrating/) and apply the migration steps described in it.

**Describe alternatives you've considered**

**Additional context**
I can try to implement the change if the community agrees to add it.

**Comment by ConnorJC3** [comment]
/priority important-soon

Needed by or before July: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/
