### ISSUE TITLE
Document parameters and mount options supported

### ISSUE THREAD

**Issue by cshiv** [kubernetes-sigs/aws-ebs-csi-driver#1690]
**Is your feature request related to a problem?/Why is this needed**
There is no single page documenting all the options supported with ebs-csi-driver. For example: To check if encryption at rest is supported by provisioning the volumes, I needed to finalize on the [github issue](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/16) . 
Other example, If I want to know if XFS file type can be opted for the volume, I needed to go to the [code](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/4bd6454fd606d9b422702ac4c614e4039fd14156/pkg/driver/node.go#L52)

/feature

**Describe the solution you'd like in detail**
Document all the fields like parameter, mount options which can be used in the storage class which is supported by EBS CSI driver.
Provide a brief explanation on the role of the field and the possible values.

**Describe alternatives you've considered**
No documentation is available now

**Additional context**
None

**Comment by cshiv** [comment]
@hanyuel My bad, I had missed this doc. This doc has all the relevant information which I was looking for. Thank you

**Comment by Nuru** [comment]
@cshiv I would like you to reopen this issue so I do not have to create a duplicate.

@hanyuel The document you linked to documents the parameters only. I still cannot find any documentation on the `MountOptions` that this driver supports.
