### ISSUE TITLE
Deploy aws-ebs-csi-driver using terraform

### ISSUE THREAD

**Issue by oburd** [kubernetes-sigs/aws-ebs-csi-driver#1700]
Hello!
There is a problem when i deploy to AWS EKS using terraform
Service accounts dont get annotation

repository = "https://kubernetes-sigs.github.io/aws-ebs-csi-driver"
  chart      = "aws-ebs-csi-driver"
  namespace  = "kube-system"
  version    = "v2.21.0"
  force_update = true

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = data.aws_iam_role.aws_ebs_csi_controller_role.arn
  }

after this service account is empty
i mean without annotation of role-arn

Do you have idea why it's happened ?

Thank you

**Environment**
- Kubernetes version 1.27 AWS EKS
- Driver version: v1.21.0

**Comment by torredil** [comment]
Hi @oburd, If you're facing issues with the annotation not being set, my recommendation to use the [iam-role-for-service-accounts-eks](https://github.com/terraform-aws-modules/terraform-aws-iam/tree/v5.14.0/modules/iam-role-for-service-accounts-eks) module provided by [terraform-aws-modules/terraform-aws-iam](terraform-aws-modules/terraform-aws-iam), example:

```
module "ebs_csi_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"

  role_name = "ebs-csi"
  attach_ebs_csi_policy = true

  oidc_providers = {
    main = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:ebs-csi-controller-sa"]
    }
  }
}
----

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "v19.15.3"

  cluster_name    = var.cluster_name

  ...

  cluster_addons = {
    aws-ebs-csi-driver = {
      service_account_role_arn = module.ebs_csi_irsa.iam_role_arn
      most_recent = true
    }
  }
}
```

Quick overview:
1. **IAM Role for Service Accounts (IRSA)**: 
    - Create an IAM role that can be assumed by the service account using the `iam-role-for-service-accounts-eks` module.

2. **OIDC Configuration**:
    - AWS EKS uses OIDC for Service Account to IAM Role mapping. 
    - Configure the relationship between the OIDC provider (which EKS uses) and the service account. In this case, the sevice account `ebs-csi-controller-sa` in the `kube-system` namespace is linked to the IAM role.

3. **EKS Cluster with Add-ons**:
    - Set the `service_account_role_arn` attribute to the ARN of the IAM role created earlier so that the driver can use the appropriate IAM role when interacting with AWS services.

Using this method, you are ensuring that the driver uses the IAM role created specifically for it, which follows best practices.

**Comment by oburd** [comment]
Hello!
It's not a problem with annotation or anything
because i didn't saw that you have 2 main path
controller and node
so
set must be looked like
controller.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
node.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
