### ISSUE TITLE
CSI Provisioner failed to provision PV "failed to get target node:"

### ISSUE THREAD

**Issue by mkmumbai** [kubernetes-sigs/aws-ebs-csi-driver#1713]
/kind bug

CSI -Provisoner log in splunk:
 ReportingInstance:\"\"}': 'events \"tmp-volume-job-7dd2c02c-2d69-4ff5-9b21-f037371bee2a-worker\" is forbidden: unable to create new content in namespace XXX because it is being terminated' (will not retry!)"

Reason:\"ProvisioningFailed\", Message:\"failed to get target node: node \\\"ip-10-116-5-81.eu-west-1.compute.internal\\\" not found\",

The above message I got from ebs-csi controller. Pod got stuck and PVC never bound to PV. We executed statefuleset where 24 pods were successful and 6 pods went into pending state. They never bound to PV and stuck forever. From logs it shows it was not able to connect node. Why did the CSI provisioned PV on another node and attached to POD?

From the above log we need to know why the PV was not created on another AWS node and bound to pod. What does csi-provisoner error above mean "will not retry" . 

Server Version: v1.24.15
Environment: prod
aws-ebs-csi-driver:v1.17.0

**Comment by ConnorJC3** [comment]
> unable to create new content in namespace XXX because it is being terminated

Use of PVCs other than the delete operation in namespaces that are being deleted is not supported. Please use a namespace that is not being terminated.

> Why did the CSI provisioned PV on another node and attached to POD?

I'm not sure what exactly you're trying to ask, but CSI drivers do not decide on (or influence) scheduling decisions - that is the job of Kubernetes.

**Comment by orz-nil** [comment]
I get this question too.
## context
we use  ephemeral volume with the volumeClaimTemplatePollcy.
we get `ProvisioningFailed` in this PVC because selected-node has been deleted by karpenter
```
Name:          xxx
Namespace:     xxx
StorageClass:  ebs-gp3
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/selected-node: ip-172-18-11-195
               volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                       From                                                                                      Message
  ----     ------                ----                      ----                                                                                      -------
  Warning  ProvisioningFailed    4m21s (x77 over 4h45m)    ebs.csi.aws.com_ebs-csi-controller-5d66d7bd77  failed to get target node: node "ip-172-18-11-195" not found
  Normal   ExternalProvisioning  2m46s (x1144 over 4h47m)  persistentvolume-controller
```
ebs failed to create PV
the pod failed to scheduler to target nodes because of `didn't find available persistent volumes to bind`
```apiVersion: v1
kind: Pod
metadata:
spec:
  containers:
...
  volumes:
  - ephemeral:
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: ebs-gp3
          volumeMode: Filesystem
    name: xxx
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-07-08T22:10:27Z"
    message: '0/355 nodes are available: 6 node(s) didn''t find available persistent volumes to bind, 8 node(s)
      had untolerated taint {k8s.tubi.io/ingress: true}. preemption: 0/355 nodes are
      available: 355 Preemption is not helpful for scheduling..'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
```

**Comment by ConnorJC3** [comment]
The EBS CSI driver does not control and cannot directly influence the Kubernetes scheduler.

Please direct any support requests and/or bug reports related to scheduling to the [upstream Kubernetes project](https://github.com/kubernetes/kubernetes) and/or your Kubernetes vendor (if applicable).

**Comment by orz-nil** [comment]
find the fixed udpate
https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/121#issuecomment-1497878232
