### ISSUE TITLE
[Announcement] Base image upgrade to AL2023

### ISSUE THREAD

**Issue by ConnorJC3** [kubernetes-sigs/aws-ebs-csi-driver#1719]
In a future release (EBS CSI Driver release 1.23 or later), the EBS CSI Driver's base image will be upgraded from Amazon Linux 2 (AL2) to Amazon Linux 2023 (AL2023). The previous major change to the base image was from [full AL2 to a minified AL2](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1233). This change will continue to improve the performance and security of the EBS CSI Driver via updates available only on AL2023.

As part of this change, `e2fsprogs` will be upgraded from `1.42.9` to `1.46.5` and `xfsprogs` will be upgraded from `5.0.0` to `5.18.0`. New volumes created on versions of the EBS CSI Driver with an AL2023 base image may fail to mount or resize on versions of the EBS CSI Driver with an AL2 base image. For this reason, downgrading the EBS CSI Driver across base images will not be supported and is strongly discouraged.

Please use this issue for any questions or feedback about the upcoming upgrade.

**Comment by lefterisALEX** [comment]
since the change is not applied yet, is there a reason that is it so emphasized in the [CHANGELOG](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG.md) of 1.22?

The sentence _"(No, really, you MUST read this before you upgrade)"_ is a bit confusing there imho.

**Comment by ConnorJC3** [comment]
Sorry about that, the "read this before you upgrade" wording is misleading. We wanted to pre-announce the change in the 1.22 CHANGELOG to gather any feedback, but it should have been under a section titled something more like "Announcements" or "Upcoming Changes". To be clear this change does not affect 1.22, but will affect 1.23.

**Comment by lefterisALEX** [comment]
great thanks for the clarification!

**Comment by ConnorJC3** [comment]
Released in EBS CSI Driver `v1.23.0`, closing. If anyone experiences an issue due to the new base image, feel free to reach out by creating a new GitHub Issue, thanks!

/close

**Comment by hajdukda** [comment]
This more or less means that we can only "roll-forward" and cannot revert in case of any issues yes ?
What it means for volumes created by EBS-CSI-Driver running on AL2 after we migrate to AL2023 ?
