### ISSUE TITLE
usage analytics by driver version

### ISSUE THREAD

**Issue by venkatamutyala** [kubernetes-sigs/aws-ebs-csi-driver#1725]
**Is your feature request related to a problem? Please describe.**
It's unclear when/if I should upgrade to the latest version of the CSI driver, as it could be have a bug.

**Describe the solution you'd like in detail**
It would be nice to have usage metrics on each driver version. This will let operators know what they are getting into before they roll it out into their production environments. This way I can knowingly roll out the latest version or can choose to wait until others have done so.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hanyuel** [comment]
We officially provide support for the latest version and one prior version, as stated in [README.md](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/README.md). I recommend upgrading to the latest driver version if possible.

**Comment by venkatamutyala** [comment]
That solves my problem. Thanks for pointing it out to me.
