### ISSUE TITLE
Feature request: Switch default StorageClass to GP3

### ISSUE THREAD

**Issue by Almenon** [kubernetes-sigs/aws-ebs-csi-driver#1726]
**Is your feature request related to a problem? Please describe.**
GP3 is generally speaking better than GP2. It's been around for a while now, so now it's a better default.

**Describe the solution you'd like in detail**
GP3 StorageClass as the default StorageClass

**Describe alternatives you've considered**
making GP3 StorageClass manually

**Additional context**
Not sure if I'm in the right place for this... I deployed the CSI driver via EKS blueprints but I don't see any mention of gp2/3 in https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/v4/modules/kubernetes-addons/aws-ebs-csi-driver/main.tf

**Comment by AndrewSirenko** [comment]
Hi @Almenon thank you for raising this question. Alas, the default storage class is decided by EKS, and not controlled by our driver. 

Looks like there has been an issue raised and merged in [awslabs/amazon-eks-ami](https://github.com/awslabs/amazon-eks-ami): [Use gp3 volume_type for 1.27+ #1197](https://github.com/awslabs/amazon-eks-ami/pull/1197). Hopefully we will all see this in EKS soon. 

This GP3 default makes sense and is already implemented in projects like [awslabs/eksdemo](https://github.com/awslabs/eksdemo) by setting a new default storage class.

**Comment by Almenon** [comment]
Thanks!
