### ISSUE TITLE
How can a single EBS gp2 volume can be attached to three pods ?

### ISSUE THREAD

**Issue by infinite8loop** [kubernetes-sigs/aws-ebs-csi-driver#1727]
![image](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/assets/103845823/f12da919-2e02-4bd6-a2d9-0b7af29d0052)

Please help me how is it working?

**Comment by torredil** [comment]
@infinite8loop The EBS CSI Driver supports `ReadWriteOnce` [access mode](https://kubernetes.io/docs/concepts/storage/persistent-volumes/).

```
ReadWriteOnce: the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can allow multiple pods to access the volume when the pods are running on the same node.
```

**Comment by infinite8loop** [comment]
@torredil  I found out that the same day but thanks a lot for responding.
Can you please help on this?
I have been managing configmaps and secrets manually across three environments that has become prone to human errors (duplicate envs, env mismatch etc) and causing feature break. Since envs have confidential data I couldn't let developers push to repository and no GitOps.
Kindly let me know the process(best practices) how env's are handled across multiple environments.
Please help me to handle the situation in an efficient way.
(I saw sealed secrets using Bitnami please let me know other than that.)
Thanks in advance.

**Comment by torredil** [comment]
@infinite8loop Thanks for your question and I commend your commitment to best practices. 

If we scope this to _defining a process for efficiently managing secrets across multiple environments in Kubernetes_, then I would recommend [**secrets-store-csi-driver-provider-aws**](https://github.com/aws/secrets-store-csi-driver-provider-aws), providing you:

1. **Automated secret management**. As you mentioned, manually managing secrets and config across different environments is error prone and has resulted in failures. An automated process that manages the lifecycle of your secrets is more resilient and will significantly reduce these errors.
2. **More granular access control**: In addition to managing access control via [**RBAC**](https://kubernetes.io/docs/reference/access-authn-authz/rbac/), you may use IAM resource policies on your secrets to restrict access to specific pods.

There's a great blog on this subject from AWS Security covering the process in more detail: [**How to use AWS Secrets & Configuration Provider with your Kubernetes Secrets Store CSI driver**](https://aws.amazon.com/blogs/security/how-to-use-aws-secrets-configuration-provider-with-kubernetes-secrets-store-csi-driver/).

This solution should also enable you to restore version control and GitOps workflows as you only manage references to these secrets or `SecretProviderClass` configs.

**Comment by infinite8loop** [comment]
Thanks a bunch @torredil 
This definitely helps me.
