### ISSUE TITLE
Add line in README.md for static provisioning ebs

### ISSUE THREAD

**Issue by oburd** [kubernetes-sigs/aws-ebs-csi-driver#1733]
Hello!
In your documentation https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/examples/kubernetes/static-provisioning/README.md need to add line with storageClassName for pv same as in pvc
because if you dont describe it you will have an error that claim can't attach to pv
And the error will be received: "Cannot bind to requested volume "name-pv": storageClassName does not match"
Thank you

**Comment by AndrewSirenko** [comment]
Thank you @oburd for bringing this to our attention, and do let us know if any other parts of the documentation led you astray.
