### ISSUE TITLE
Unable to attach or mount volumes: unmounted volumes=[xpandion-vol-mount], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition

### ISSUE THREAD

**Issue by hrushikeshpotbhare** [kubernetes-sigs/aws-ebs-csi-driver#1788]
Hi All,

As i am facing issue while doing static binding to the EBS volume using volume ID, it was working fine before from yesterday, i was facing this issue.

2023-10-17T17:41:09+05:30 E1017 12:11:09.416229    7784 driver.go:122] "GRPC error" err="rpc error: code = Internal desc = Failed to find device path /dev/xvdae. disk number for device path \"/dev/xvdae\" volume id \"vol-07928ba39424b09e8\" not found"

Everything is fine the EBS volume PV PVC and the csi ebs driver, but after updating the docker image version from the values.yaml file then that pod is geeting stuck state and showing above error,

Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  xpandion-vol-mount:
    Type:                     PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:                grc-dev
    ReadOnly:                 false
QoS Class:                    Burstable
Node-Selectors:               karpenter.sh/provisioner-name=windows-worker-general
                              kubernetes.io/arch=amd64
                              kubernetes.io/os=windows
Tolerations:                  node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
                              os=windows:NoSchedule
                              vpc.amazonaws.com/PrivateIPv4Address:NoSchedule op=Exists
Topology Spread Constraints:  topology.kubernetes.io/zone:ScheduleAnyway when max skew 1 is exceeded for selector project=Pathlock-GRC
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  6m43s (x89 over 177m)  kubelet  MountVolume.MountDevice failed for volume "grc-dev-shared-volume" : rpc error: code = Internal desc = Failed to find device path /dev/xvdae. disk number for device path "/dev/xvdae" volume id "vol-07928ba39424b09e8" not found
  Warning  FailedMount  66s (x86 over 175m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[xpandion-vol-mount], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition

/triage support

**Comment by nicwoerner** [comment]
We are seeing the exact same issue in version 1.21 after restarting nodes. As a manual temporary workaround it helped to remove the volumeattachment manually. Any idea what caused this issue exactly and how could we fix it?
