### ISSUE TITLE
Use CSI secret field for aws secret handling

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#179]
**Is your feature request related to a problem? Please describe.**
We are currently passing secret using environment variable. And CSI spec provide a native way of passing secret. Investigate how this could be beneficial.

**Additional context**
* https://github.com/container-storage-interface/spec/blob/37e74064635d27c8e33537c863b37ccb1182d4f8/lib/go/csi/csi.pb.go#L4520-L4527
* https://github.com/container-storage-interface/spec/blob/master/spec.md#createvolume

**Comment by dkoshkin** [comment]
>We are currently passing secret using environment variable.

The fact that the driver supports using the metadata api and the EC2 instance role to acquire the needed permissions helps with this problem. Using the instance roles is also how the cloud-provider functionality worked, my thoughts is that most users will be comfortable using this mechanism and it provides a smooth transition from using the cloud-provider feature to this CSI driver.

**Comment by leakingtapan** [comment]
@dkoshkin agree with instance profile is good choice now. We could revisit this issue later.
