### ISSUE TITLE
Publish the volume-modifier image to `registry.k8s.io` as well to support IPv6

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes-sigs/aws-ebs-csi-driver#1826]
**Is your feature request related to a problem?/Why is this needed**
At time time of writing this ECR (`public.ecr.aws`) does not support container image pulls over IPv6.

```
% host public.ecr.aws
public.ecr.aws is an alias for a961edf72200aa9b1.awsglobalaccelerator.com.
a961edf72200aa9b1.awsglobalaccelerator.com has address 75.2.101.78
a961edf72200aa9b1.awsglobalaccelerator.com has address 99.83.145.10
```

The volume-modifier image (`public.ecr.aws/ebs-csi-driver/volume-modifier-for-k8s`) is published to ECR only. It is currently a blocker for the IPv6 story on our side as ECR does not support image pulls over IPv6.

/feature

**Describe the solution you'd like in detail**
The volume-modifier image (`public.ecr.aws/ebs-csi-driver/volume-modifier-for-k8s`) can be published to `registry.k8s.io` as well similar to the awe-ebs-csi-driver image that is present in both ECR and `registry.k8s.io` - see https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/v1.24.1#container-images.

**Describe alternatives you've considered**
Alternative is everyone to maintain its image in a registry that supports IPv6. 😕 

**Additional context**
N/A

**Comment by torredil** [comment]
Hi there @ialidzhikov, thanks for this request. We've been discussing the idea of setting up a [DockerHub](https://www.docker.com/blog/docker-hub-registry-ipv6-support-now-generally-available/) repo, given that the `volume-modifier-for-k8` sidecar is not officially part of `kubernetes-sigs` - Would that satisfy your requirements?

**Comment by ialidzhikov** [comment]
Not really. DockerHub does not support IPv6 natively. See https://www.docker.com/blog/beta-ipv6-support-on-docker-hub-registry/.
AFAIS, you have to apply custom containerd (or other container runtime) registry config to make it work.
Why we don't push it to `registry.k8s.io`? The driver is already maintained in `registry.k8s.io`. So, I don't really see why we have to use another registry for the volume-modifier-for-k8s image.
I assume in AWS you will also face a similar issue when you try to run the volume-modifier-for-k8s image on IPv6 single stack cluster.

**Comment by ialidzhikov** [comment]
> That blog post is outdated (released in Oct 27, 2021). Today, DockerHub does support IPv6 natively, see [Docker Hub Registry IPv6 Support Now Generally Available](https://www.docker.com/blog/docker-hub-registry-ipv6-support-now-generally-available/).

Thanks! I didn't know that. However I am afraid that we won't be able to consume the dockerhub image due to its rate limiting - 100 pulls per 6 hours per IP address.

**Comment by torredil** [comment]
Thanks for that context @ialidzhikov, it's very helpful. 

In that case, we'll scrap the DockerHub idea and share some great feedback here with our ECR friends.

The good news - looking shortly ahead, Kubernetes provides the ability to modify volumes via `VolumeAttributesClass` parameters: https://github.com/kubernetes/enhancements/issues/3751, which resolves this issue.

**Comment by torredil** [comment]
As discussed, `volume-modifier-for-k8` will not be published to `registry.k8s.io` because the sidecar is not officially part of `kubernetes-sigs`.

/close
