### ISSUE TITLE
Would like to have possibility manage allowvolumeexpansion

### ISSUE THREAD

**Issue by romankydybets** [kubernetes-sigs/aws-ebs-csi-driver#1848]
right now we don't have this possibility with helm chart
it would be great to have this parameter if possible

this is what we expected
kubectl get sc gp3 -o yaml
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
...
  name: gp3
```

**Comment by ConnorJC3** [comment]
Hi @romankydybets, by default our Helm chart doesn't deploy any `StorageClass`es so there is nothing to configure. If you are using our optional `storageClasses` parameter to deploy an SC, you should be able to specify it there.

For example, the following parameters to helm via a `values.yaml`
```
storageClasses:
 - name: ebs-gp3
   volumeBindingMode: WaitForFirstConsumer
   parameters:
     type: gp3
   allowVolumeExpansion: true
```

will create a `StorageClass` with `allowVolumeExpansion` enabled:
$ helm template aws-ebs-csi-driver . -s templates/storageclass.yaml
---
# Source: aws-ebs-csi-driver/templates/storageclass.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-gp3
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
parameters:
  type: gp3
volumeBindingMode: WaitForFirstConsumer
```

If you are using another tool (not our Helm chart) to deploy your `StorageClass`, you will have to specify the `allowVolumeExpansion` as our chart won't have control over that tool.

**Comment by ConnorJC3** [comment]
/close

I'm going to go ahead and close this issue out as there hasn't been a response in 2 weeks. If you need further assistance, please feel free to reopen this issue or open a new one.
