### ISSUE TITLE
Bump aws go sdk to > v1.47.11

### ISSUE THREAD

**Issue by yenoromm** [kubernetes-sigs/aws-ebs-csi-driver#1849]
**Is your feature request related to a problem?/Why is this needed**
Currently v1.47.8 of aws go sdk does not support new pod identities agent, bump to version >v1.47.11 

/feature

**Describe the solution you'd like in detail**
Bump version to at least v1.47.11
https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html

**Describe alternatives you've considered**
Currently a more recent version is the only option

**Comment by torredil** [comment]
Hi @yenoromm thank you for this request and the kind reminder. Dependencies in this repository are upgraded ahead of the monthly release. We strive to do that right before the actual release to be efficient in our process and grab the latest updates available at that time. I'll keep an eye out and make sure the sdk is bumped up as per your request.

Thanks,
Eddie
