### ISSUE TITLE
please enumerate mount options for the aws-ebs-csi-driver

### ISSUE THREAD

**Issue by vstthomas** [kubernetes-sigs/aws-ebs-csi-driver#1853]
/kind bug

This is a documentation bug. The [release notes] list `Mount Options`, that refer to the official Kubernetes docs. Their docs (indirectly) indicates that the `aws-ebs-csi-driver` [does not support mount options].

Please post the mount options that are supported by the `aws-ebs-csi-driver`; below, for now. But somewhere longer-term, for future reference. I can't seem to find them anywhere.

Bonus: it would be super helpful if you posted some examples of very popular types as well. For example, in my case I'm creating a new storage class for on-cluster db operations with KubeDB.

[release notes]:https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/cb2054692b1a55da436f77fd413b1a1633e36d5d/README.md?plain=1#L12

[does not support mount options]:https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options

**Comment by AndrewSirenko** [comment]
Hi @vstthomas, thank you for the feedback on needing clearer documentation for mount options. We will work on this.

In the meantime, you can find a list inside the StorageClass Parameters documentation page: [aws-ebs-csi-driver/docs/parameters.md at master · kubernetes-sigs/aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/parameters.md)

Here is a quick table of the supported options to unblock you at the moment: 

| Formatting Parameters | Description                                                                                                  | xfs      | ext3    | ext4    |
|-----------------------|--------------------------------------------------------------------------------------------------------------|-----------|---------|---------|    
| "blockSize"           | The block size to use when formatting the underlying filesystem.                                             | &check; | &check; | &check; |
| "inodeSize"           | The inode size to use when formatting the underlying filesystem.                                             | &check; | &check; | &check; |
| "bytesPerInode"       | The `bytes-per-inode` to use when formatting the underlying filesystem.                                      |          | &check; | &check; |
| "numberOfInodes"      | The `number-of-inodes` to use when formatting the underlying filesystem.                                     |          | &check; | &check; |
| "ext4ClusterSize"     | The cluster size to use when formatting an `ext4` filesystem using clustered allocation. See warnings below. |         |         |         | &check; |

**Comment by vstthomas** [comment]
excellent, thank you!

**Comment by vstthomas** [comment]
Regarding the bonus question: would AWS have configuration suggestions for FS options for databases on EKS?

**Comment by AndrewSirenko** [comment]
The EBS CSI Driver team does not have configuration suggestions for FS options for databases on EKS. 

For more information on the use case for the `ext4ClusterSize` format option, see [Torn write prevention - Amazon Elastic Compute Cloud](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/storage-twp.html).
