### ISSUE TITLE
Connecting EBS with a local host cluster

### ISSUE THREAD

**Issue by handpro-git** [kubernetes-sigs/aws-ebs-csi-driver#1863]
Hello, 

I installed microk8s on my laptop. Would it be possible to attach an EBS volume to the local cluster?

I created the IAM user with the policy, PV, and PVC. No issues. Everything went smoothly. When I update my pods to use the PVC, pods don't start due to **0/1 nodes are available: 1 node(s) had volume node affinity conflict.**

**Comment by ConnorJC3** [comment]
/close

Hi @handpro-git - unfortunately the EBS CSI Driver only works in environments where EBS is available - primarily on AWS EC2 instances (as well as some other places like AWS Snowball devices). Thus, it will not work on your local laptop as EBS volumes cannot be attached to it.
