### ISSUE TITLE
[Deprecation Announcement] `v2.28.0` of the EBS CSI Driver Helm Chart is the last minor version to support  `--reuse-values`

### ISSUE THREAD

**Issue by ConnorJC3** [kubernetes-sigs/aws-ebs-csi-driver#1864]
## Summary

Today, the EBS CSI Driver supports upgrading with `--reuse-values` in some scenarios (opt-in features do not support it). In a future release, that support will no longer be tested for or guaranteed.

If you use `--reuse-values` today, we strongly suggest you consider switching to [`--reset-then-reuse-values`, a new Helm flag available in Helm 3.14.0 and later](https://github.com/helm/helm/issues/8085).

## FAQ

_I don't upgrade with `--reuse-values`, does this affect me?_

If you (or a tool on your behalf) does not explicitly pass `--reuse-values` to Helm, this change does not affect you. `helm upgrade`, `helm upgrade --reset-values`, and `helm upgrade --reset-then-reuse-values` will still be supported.

_Why is this happening?_

`--reuse-values` behaves in an unintuitive way that greatly increases the burden on maintainers and contributors to the EBS CSI Driver Helm chart ([this blog post](https://shipmight.com/blog/understanding-helm-upgrade-reset-reuse-values#--reuse-values-and-schema-change) provides a useful summary of the issue with `--reuse-values`). The team evaluated this burden and decided to deprecate `--reuse-values` upgrade support, which is consistent with other popular Helm charts. 

_When will this happen?_

The specific release this deprecation will take place in is undecided at the moment. When more information is available, it will be announced on this issue and in the [EBS CSI Helm chart CHANGELOG](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/CHANGELOG.md).

**Update: As announced in the [CHANGELOG](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/5a56f6672dc474604bb90d65a3fc067560cf6c1b/charts/aws-ebs-csi-driver/CHANGELOG.md#v2280), `v2.28.0` will be the last minor version of the EBS CSI Driver Helm Chart to support `--reuse values`.**

_I have more questions or feedback_

Please comment on this issue to ask additional questions about or provide feedback on this change.

**Comment by sossickd** [comment]
Whatever

**Comment by ConnorJC3** [comment]
/close

This deprecation has occurred as of `v2.29.0` - the EBS CSI Driver chart no longer supports upgrading with `--reuse-values`, closing this announcement out.

We will continue to monitor this issue if anyone has any questions about the change.
