### ISSUE TITLE
Not able to provision PVC volumes due to conflict with AWS Organization Service Control Policies

### ISSUE THREAD

**Issue by abasu0713** [kubernetes-sigs/aws-ebs-csi-driver#1881]
/kind bug

**What happened?**
I am trying to deploy a Stateful application (Rabbitmq) using Bitnami Charts/Helm in my EKS cluster with managed node-groups. The pods never pass `Pending` state. Upon investigating I see the reason. The AWS Account has Organization Service Control Policies in place (that I can't view with my federated access). But I do see the error at the EBS-CSI-Controller. 
 
<img width="1661" alt="Screenshot 2023-12-21 at 8 34 31 PM" src="https://github.com/kubernetes-sigs/aws-ebs-csi-driver/assets/11951136/e1a4353d-d78d-45ed-b770-74035d463993">

I am using [Terraform IAM Module](https://registry.terraform.io/modules/terraform-aws-modules/iam/aws/latest/submodules/iam-role-for-service-accounts-eks) to create the service account for EBS-CSI-Driver. 

**What you expected to happen?**
I would assume we should be able to pass service control policies. If not at least be able to customize the IAM role? Any suggestions will be much appreciated.

**How to reproduce it (as minimally and precisely as possible)?**

- Create a Service Control Policy that includes something like this:
```bash
"Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Statement1",
            "Effect": "Deny",
            "Action": [
                "ec2:Create*"
            ],
            "Resource": "*"
        }
    ]
```
- Provision an EKS cluster with a managed node-group. Using any method. I am using: [Terraform AWS EKS Module](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/eks-managed-node-group). Turn on EBS CSI Add-on with custom [IRSA](https://registry.terraform.io/modules/terraform-aws-modules/iam/aws/latest/submodules/iam-role-for-service-accounts-eks) with `attach_ebs_csi_policy` set to `true`. 
- Add Helm locally and try deploying [Bitnami RabbitMQ chart](https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq). 

You will notice that the Stateful Set for rabbit MQ stays stuck in pending because Service control policies doesn't allow provisioning of PVC Volumes

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
```bash
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4-eks-8cb36c9
```
- Driver version: `v1.26.0-eksbuild.1`

**Comment by AndrewSirenko** [comment]
Hi @abasu0713, I'm sorry to hear you are running into an authorization issue. Our team is not familiar with deploying the driver via terraform, but three troubleshooting questions come to mind.  

1. Did you let the driver know what the service account role-arn is? Make sure that if you are deploying via helm that you have explicitly set [the role-arn in the chart's values.yaml](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/0c459169dd183c1b1fb27443d562cc0f6579a62b/charts/aws-ebs-csi-driver/values.yaml#L269)
2. Did you create and connect an IAM OIDC Provider? Follow the EKS Guide: [Creating the Amazon EBS CSI driver IAM role](https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html) to make sure you have created an IAM OIDC provider for your cluster (You can skip step 4 unless you are using a custom KMS key).
3. Finally, I have successfully deployed the driver via terraform by using [the stateful pattern from terraform-aws-eks-blueprints](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/stateful). I understand that this is deploying the driver via the add-on, but perhaps you would get a hint about how to grant permissions via terraform from it. 

I hope this helps, and please let me know if you are still stuck or if you need a more thorough explanation on any of the above steps.

**Comment by torredil** [comment]
Hi @abasu0713

The problem as described here isn't with the CSI driver itself - it's related to the permissions that have been restricted by the SCPs at the AWS account level. SCPs are what control the actions users can perform on AWS services. In this case, they are limiting the driver's ability to create volumes.

For more information and best practices related to SCPs see the official docs: https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html

To resolve this, you'll need to work with whoever manages your AWS account and its SCPs - they have the authority and capability to adjust these policies / grant you access to create volumes.

Aside: AWS maintains a managed policy for the EBS CSI Driver: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1033#issuecomment-1578825424

Feel free to re-open if you need further help here, thanks!

/close

**Comment by abasu0713** [comment]
@torredil thank you for the clarification. That was my assumption as well. I was able to use static provisioning with the driver and provision volumes and bind them just fine.. Thank you for confirming. Really appreciate it.

**Comment by torredil** [comment]
@abasu0713 Absolutely! Feel free to reach out any time should you run into any hiccups while using the driver and we'll be more than happy to help improve your experience. Can also be reached via `kubernetes.slack.com`.

See you around 👋
