### ISSUE TITLE
Improve securityContext implementation (Capabilities\Seccomp)

### ISSUE THREAD

**Issue by YogevMaty** [kubernetes-sigs/aws-ebs-csi-driver#1882]
What is this PR about? / Why do we need it?

Implements default securityContext Capabilities and Seccomp profiles for the node pod and all containers (including sidecar containers). Also add the option to manage securityContext Capabilities and Seccomp profiles in the helm chart

**Comment by AndrewSirenko** [comment]
Hi @YogevMaty, did you mean to submit this as an issue?

**Comment by YogevMaty** [comment]
yes, I would like that, as the securityContext of - aws-ebs-csi-driver:v1.22.0 , livenessprobe:v2.10.0-eks-1-27-9
 is only 
         privileged: true
        readOnlyRootFilesystem: true
I am not sure if you need all the k8s Capabilities or can limit only to the relevant that are in use 
same for  Seccomp profile - not sure why it is not used

**Comment by devopserio** [comment]
This is definitely needed still to manage PSA restrictions - when will this functionality be added?
