### ISSUE TITLE
Can possible to skip (detach -> attach) step when pod re-assign the node same as before

### ISSUE THREAD

**Issue by jungrae-prestolabs** [kubernetes-sigs/aws-ebs-csi-driver#1909]
Hi, I have a challenge that minimize the downtime when re-scheduling the pod which has gp3 volume.

I thought if re-schedule the pod on same node, then (detach -> attach) step gonna be skip because it same node.
But, in some case, I found few of them is not Even if they are re-scheduling the pod on same node, they try to `UnpublishVolume` and `PublishVolume`.

Do you know why? And Is there any way to skip it so that minimize the downtime of pod which has volume mount (gp3)?

fyi. Currently, we are using
- eks 1.23 
- Using sc as gp3
- v1.26.0-eksbuild.1
- statefulset + ReadWriteOnce

**Comment by ConnorJC3** [comment]
/close

Hi @jungrae-prestolabs , unfortunately the EBS CSI Driver (and CSI drivers in general) do not choose when to detach/attach volumes from nodes - that decision is made entirely by the container orchestrator.

As you are using Kubernetes as your container orchestrator, you would need to raise this feature request to Kubernetes itself, at https://github.com/kubernetes/kubernetes/

Please feel free to reach out on this issue or a new one if you need further assistance.
