### ISSUE TITLE
Allow modifyVolumeRequestHandlerTimeout to be configurable

### ISSUE THREAD

**Issue by andrewcharlton** [kubernetes-sigs/aws-ebs-csi-driver#1911]
**Feature Request**

**Issue**
When modifying our volumes, we change both the size and the iops/throughput annotations together so that we only perform a single volume modification call to AWS.  However, we have seen a race condition where the iops/throughput gets modified by itself first, and then the volume is unable to resize because the volume is now in a 6 hour window.

**Proposed Solution**
There is a currently a hard coded 2 second window (the driver's `modifyVolumeRequestHandlerTimeout`) during which both size and iops/throughput modification requests must be received for them to be processed together. It is more important for us that they be processed together (and so avoid the 6 hour windows) than the speed at which they are processed, so we would like to extend this window.

I propose that this becomes an option in the `ControllerOptions` instead, defaulting to 2 seconds, so that users can tune this setting.

If this is reasonable, please let me know and I'll put a PR together.  Thanks!

**Comment by ConnorJC3** [comment]
Hi @andrewcharlton , we talked about this and you're good to go to submit a PR to make this change (note that you, or your employer if you're contributing on their behalf, will need to sign the standard Kubernetes CLA).

We'll get the PR reviewed as soon as time allows, thanks for contributing to the EBS CSI Driver!

**Comment by AndrewSirenko** [comment]
/close 

Due to fix being merged. Thanks for putting the PR together Andrew!

**Comment by andrewcharlton** [comment]
> Due to fix being merged. Thanks for putting the PR together Andrew!

Thank you all for the speedy reply/review!
