### ISSUE TITLE
Allow resource annotations to be configurable

### ISSUE THREAD

**Issue by olibenni** [kubernetes-sigs/aws-ebs-csi-driver#1918]
**Is your feature request related to a problem?/Why is this needed**
Running static analysis tools like KubeLinter against the chart fails due to pods (specifically ebs-plugin node.containerSecurityContext) allowing a container to run in privilege mode.

These can be ignored via annotations to the resource (not the pod but the daemonset) but currently there are no means to provide them.

/feature

**Describe the solution you'd like in detail**
I would like the ability to add annotations through values.yaml overrides.

**Comment by AndrewSirenko** [comment]
Hi @olibenni, this chart request makes sense, thanks for the suggestion. I will try to get to this later this week, unless you wish to submit the PR yourself. Thank you.

**Comment by AndrewSirenko** [comment]
Hi @olibenni, please take a look at my example in [Allow driver node daemonSet annotations to be configurable #1923](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1923) to see if it is satisfactory for you.

**Comment by olibenni** [comment]
Thanks a lot!
