### ISSUE TITLE
Add value on helm chart to customize test pod image

### ISSUE THREAD

**Issue by LMantovan** [kubernetes-sigs/aws-ebs-csi-driver#1920]
**Is your feature request related to a problem? Please describe.**
I'm trying to substitute images registry with my personal registry, using a caching mechanism. I noticed that this Pod (line 199) https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml has an hardcoded image which is not modifiable by helm chart

**Describe the solution you'd like in detail**
I'd like to have a value in Chart helm chart values similar to the others to change the registry or customize the image name/tag

**Comment by AndrewSirenko** [comment]
Hi @LMantovan, we are open to this addition to our helm chart, thank you for the suggestion. I will try to get to this this week, unless you want to submit the PR yourself.
