### ISSUE TITLE
test job can't run on arm64

### ISSUE THREAD

**Issue by camaeel** [kubernetes-sigs/aws-ebs-csi-driver#1921]
/kind bug

**What happened?**

I installed aws-ebs-csi-driver on arm64 only cluster. Test job faield due to: 
```
kubetest2 exec /bin/sh: exec format error
```

**What you expected to happen?**
```
Test should succeed, especially aws-ebs-csi-driver supports both architectures. Image used for testing (`gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master`) doesn't support non-amd64 architectures. 
It would be best if the image was multiarch, and if not possible, test job could have at least a nodeSelector set for selecting nodes with proper architecture: `kubernetes.io/arch=amd64` so the test would run on amd64 nodes (in mixed architecture clusters). 

```

**How to reproduce it (as minimally and precisely as possible)?**
```
1. create a cluster running only on arm64 infrastructure
2. Install ebs-csi-driver from helm chart with tests
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
    ```
     Client Version: v1.28.0
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.27.9  
    ```
- Driver version:
    Helm chart version: aws-ebs-csi-driver-2.26.0

**Comment by AndrewSirenko** [comment]
Hi @camaeel, regarding

> Image used for testing doesn't support non-amd64 architectures

That kubekins-e2e image is maintained by SIG-Testing and is `amd` only. (Source: [their kubekins-e2e Dockerfile](https://github.com/kubernetes/test-infra/tree/master/images/kubekins-e2e)). There is no multi-arch version available for us to use in our tests at the moment. 

Looks like there's a [PR in kubernetes/test-infra to make a mutli-arch kubekins v2 image](https://github.com/kubernetes/test-infra/pull/31421). When that is merged and released we may consider upgrading to it, but that requires it to be released first.

---
Regarding 

> "test job could have at least a nodeSelector set for selecting nodes with proper architecture"

This request makes sense (we should also select for `kubernetes.io/os=linux` to be safe). I will try to get to this in the near future, unless you wish to submit the PR yourself.

Thank you for the suggestions and have a great day!

**Comment by camaeel** [comment]
@AndrewSirenko that was fast. Thank you.
