### ISSUE TITLE
Optimize LCH Behavior During Termination Events

### ISSUE THREAD

**Issue by torredil** [kubernetes-sigs/aws-ebs-csi-driver#1926]
**Issue Description**

Currently, the CSI node pod utilizes OS graceful shutdown time during termination events by waiting for volumes on a node to be detached because Kubelet's node shutdown manager does not consider volume cleanup as a signal and tends to prematurely terminate the driver pod, which can result in delayed attachments.

Ideally, `DetachVolume` calls should complete before `TerminateInstances` is invoked - however, in scenarios where `TerminateInstances` is called by autoscalers such as Karpenter, it is undesirable for the lifecycle hook to wait for detachments to succeed in the backend because `DetachVolume` requests made after `TerminateInstances` will wait for the `TerminateInstances` workflow to complete.

**Additional Context**

According to the external attacher [docs](https://github.com/kubernetes-csi/external-attacher/blob/master/doc/development.md), checking for the presence of `DeletionTimestamp` in VA objects can be used to ensure that volumes have been successfully unmounted from k8s perspective (which is more reliable than scanning for mounts on the host).

Also, kubelet sets a `NotReady` condition on the node with the reason set to "node is shutting down", which can be used to determine node status to stop waiting on detaches in specifically the scenario described above.

**Comment by levanlongktmt** [comment]
@torredil I guess this is reason for my problem at https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1665#issuecomment-1974447831

**Comment by primeroz** [comment]
Is this also the reason for https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1955 ?

**Comment by AndrewSirenko** [comment]
/close 

Team consensus: not planned.
