### ISSUE TITLE
Transfer ownership to kubernetes-sigs as sig-aws subproject

### ISSUE THREAD

**Issue by bertinatto** [kubernetes-sigs/aws-ebs-csi-driver#2]
Re-opening #1 as an issue.

The intent of this pull request is to complete the steps necessary to migrate coreos/alb-ingress-controller repository to k8s-sig-aws as a subproject.

The steps below use rules for [new](https://github.com/kubernetes/community/blob/master/kubernetes-repositories.md#rules-for-new-repositories) and [donated](https://github.com/kubernetes/community/blob/master/kubernetes-repositories.md#rules-for-donated-repositories) repositories:

TODO - Complete check-list:
- [x] All contributors must have signed the CNCF Individual CLA (https://github.com/cncf/cla/blob/master/individual-cla.pdf) or CNCF Corporate CLA (https://github.com/cncf/cla/blob/master/corporate-cla.pdf)
- [ ] If (a) contributor(s) have not signed the CLA and could not be reached, a NOTICE file should be added referencing section 7 of the CLA with a list of the developers who could not be reached.
- [x] Licenses of dependencies are acceptable; project owners or @d-nishi to ping @caniszczyk (https://github.com/caniszczyk) for review of third party deps.
- [x] @bertinatto to give permissions to @d-nishi to initiate transfer of the repository [bertinatto/ebs-csi-driver/](https://github.com/bertinatto/ebs-csi-driver/) to [kubernetes-sigs repository](http://github.com/kubernetes-sigs/)
- [ ] [kubernetes-sigs-owners] and/or Kubernetes steering committee to authorize temporary repository creation permission to representative initiating the transfer.
- [x] Transfer repo to http://github.com/kubernetes-sigs/<project-name>
- [x] Add the topic for the sponsoring SIG - e.g. k8s-sig-aws. 
- [x] Adopt the CNCF CLA bot, merge bot and Kubernetes PR commands/bots.
- [ ] Update the sigs.yaml (https://github.com/kubernetes/community/blob/master/sigs.yaml) section with the subprojects and code, with valid OWNERS files

COMPLETED - as part of this PR:
- [x] Add the Kubernetes Code of Conduct to the repo.
- [x] Ensure that all code projects use the Apache License version 2.0. 
- [x] Ensure that All OWNERS of the project must also be active SIG members.
- [x] Ensure SIG membership votes using lazy consensus to create a new repository.

**Comment by bertinatto** [comment]
@d-nishi @leakingtapan: seems like we can close this, right?

Feel free to re-open it if necessary.

**Comment by leakingtapan** [comment]
Ref kubernetes/community#2780
