### ISSUE TITLE
RE: Addon Version Not available in all regions

### ISSUE THREAD

**Issue by venkatamutyala** [kubernetes-sigs/aws-ebs-csi-driver#2044]
On numerous occassions I have found that a new CSI driver will be published but it won't be available in all regions after publish. So far, it's been 4 days and v0.31.0 remains unavailable in us-west-2. 

What's the maximum amount of time between a release to being fully deployed across all regions?

**Comment by torredil** [comment]
Hi @venkatamutyala, thanks for reaching out and sharing this feedback. The team has been working diligently to ensure that EKS users have access to the latest version of the driver following an upstream release - that gap has been significantly reduced in recent times but we fully recognize that there is always room for improvement, so we'll keep this top of mind.

> What's the maximum amount of time between a release to being fully deployed across all regions?

We strive to make EKS add-on versions of the driver available within one week after an upstream release. Recent releases have typically been available within 3-4 business days. 

This extra time is necessary for thorough testing and validation to maintain the highest standards of reliability and compatibility across all supported EKS versions. In some cases, such as when EKS is preparing to release a new version, additional validation may be required, resulting in a slightly longer delay. As for `v1.31.0`, we expect the add-on to be available by tomorrow - I'll keep you posted on any updates.

**Comment by torredil** [comment]
Hey @venkatamutyala, `v1.31.0-eksbuild.1` is now available in all commercial regions (including us-west-2).

/close
