### ISSUE TITLE
Change the number of replicas for the EBS CSI addon using aws eks API

### ISSUE THREAD

**Issue by praseedasathaye** [kubernetes-sigs/aws-ebs-csi-driver#2068]
**Is your feature request related to a problem? Please describe.**
Seems like EKS AddOn coreDNS does support setting the replicaCount but EBS CSI addon does not. There be consistency across all EKS addons in setting the common advance configuration via AWS api as well as helm chart. the This is need for having a same schema structure across all addons, so its better to give that provision to customers.

**Describe the solution you'd like in detail**
Solution just like we have for coreDNS via aws eks update-addon 

**Describe alternatives you've considered**
Currently this can be only done via helm chart https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L260

**Additional context**
Even if this cannot be supported, we need documentation which ones are supported and which ones are not and if possible the reason.

**Comment by ConnorJC3** [comment]
Hi @praseedasathaye - I'll leave this open as a feature request for the ability to change the number of replicas on the EKS Addons version of the driver.

As for documentation of supported parameters, you can use the AWS `DescribeAddonConfiguration` API (https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeAddonConfiguration.html) to return the JSON schema containing all the parameters available for any specific release of the EKS addon version of the EBS CSI Driver.

**Comment by torredil** [comment]
This request has been addressed in driver release `v1.32.0-eksbuild.1`
/close
