### ISSUE TITLE
csi-node-driver-registrar logs in json format

### ISSUE THREAD

**Issue by gmarcot** [kubernetes-sigs/aws-ebs-csi-driver#2070]
Hey folks,

i ask to you if possible add the option to choose the logs format ( text , json ) for the csi-node-driver-registrar

Thanks

**Comment by torredil** [comment]
Hey there @gmarcot , this feature will be supported in our upcoming monthly driver release `v1.32.0` which includes the latest `node-driver-registrar` version (`v2.11.0`). Once the release is published, you may configure the log format by specifying `logging-format` via the `sidecars.nodeDriverRegistrar.additionalArgs` Helm parameter:

```yaml
nodeDriverRegistrar:
  additionalArgs:
    - "--logging-format=json"

```

example JSON log output:

```
{"ts":1719254704626.5413,"caller":"csi-node-driver-registrar/main.go:150","msg":"Version","v":0,"version":"v2.11.0"}
{"ts":1719254704626.5776,"caller":"csi-node-driver-registrar/main.go:151","msg":"Running node-driver-registrar","v":0,"mode":""}
...

```

For more information see node driver registrar release notes: https://github.com/kubernetes-csi/node-driver-registrar/blob/release-2.11/CHANGELOG/CHANGELOG-2.11.md#release-notes-for-v2110 and relevant PR https://github.com/kubernetes-csi/node-driver-registrar/pull/349

**Comment by gmarcot** [comment]
Good morning @torredil 

many thanks for your replay, very good notice for me, great works

many thanks
