### ISSUE TITLE
sidecars.snapshotter.logLevel not being respect

### ISSUE THREAD

**Issue by zyue110026** [kubernetes-sigs/aws-ebs-csi-driver#2101]
/kind bug

We have noticed an instance of incorrect helming in one of your Kubernetes configuration files. Hardcoded or default configuration values in the template are considered anti-pattern and configurable values in the values.yaml file are not being respect, resulting in user-provided configurations never being applied. Additionally, we provide anecdotal evidence from [trivy-operator#729](https://github.com/aquasecurity/trivy-operator/issues/729) regarding the incorrect helming defect.

**What happened?**

[sidecars.snapshotter.logLevel](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/93dd985300a0fc61fe5e4957d43c52bc590abd28/charts/aws-ebs-csi-driver/values.yaml#L77) does not take affect when change the value. This issue arises due to a missing implementation for this value in controller.yaml file:

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/93dd985300a0fc61fe5e4957d43c52bc590abd28/charts/aws-ebs-csi-driver/templates/controller.yaml#L320

**What you expected to happen?**

The log level can be changed for sidecars snapshotter

**How to reproduce it (as minimally and precisely as possible)?**

1. changing the sidecars.snapshotter.logLevel to any value in values.yaml
2. using helm chart to deploy it

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version: main version

**Comment by AndrewSirenko** [comment]
Hi @zyue110026 thank you so much for filing the issue and creating the fix PR. Our team will review this and release the fix in our next monthly EBS CSI Driver helm chart release.
