### ISSUE TITLE
Does ebs-csi-driver have impact on the AZ chosen when EKS replace a worker node?

### ISSUE THREAD

**Issue by ensean** [kubernetes-sigs/aws-ebs-csi-driver#2133]
Hello, we are planning to deploy a stateful application(Clickhouse) to EKS with the support of ebs-csi-driver. 

But we are concerning that during the process of worker node replacement(may be due to hardware failure etc.), is there a chance that an instance in a different AZ is launched, causing EBS volume mount failure?

/triage support

**Comment by ConnorJC3** [comment]
Hi @ensean - EBS volumes are a zonal resource, so any instances using a volume must be in the same zone as the volume (for more info see the [AWS docs for EBS volumes](https://docs.aws.amazon.com/ebs/latest/userguide/ebs-volumes.html)). The EBS CSI Driver will automatically populate a [CSI Topology label](https://kubernetes-csi.github.io/docs/topology.html) with the key `topology.kubernetes.io/zone` containing the AZ of the associated volume/node.

Most node scalers such as `cluster-autoscaler` or Karpenter either automatically are aware of CSI topology labels or can be configured to do so. For example, here is the [Karpenter documentation about PV-aware scheduling](https://karpenter.sh/v1.0/concepts/scheduling/#persistent-volume-topology).

**Comment by ensean** [comment]
Hi @ConnorJC3 , thanks a lot for your explanation. 

Suppose the AZ where the PV belongs fails, will ebs-csi-driver try to copy the PV to another AZ through snapshot?

**Comment by AndrewSirenko** [comment]
> Suppose the AZ where the PV belongs fails, will ebs-csi-driver try to copy the PV to another AZ through snapshot?

No, the ebs-csi-driver will not try to copy a failed PV to another AZ through snapshot.

You may be able to write your own Kubernetes Operator which would do this.

**Comment by AndrewSirenko** [comment]
It seems that all active support questions have been answered. If you have any new questions or feature requests please file a separate issue. Thank you!

/close
