### ISSUE TITLE
Allow for user PDB configuration so new fields can be added

### ISSUE THREAD

**Issue by peterabarr** [kubernetes-sigs/aws-ebs-csi-driver#2146]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like in detail**
Currently it is not possible to add new fields to the PDB such as [unhealthyPodEvictionPolicy](https://kubernetes.io/blog/2023/01/06/unhealthy-pod-eviction-policy-for-pdbs/). If the PDB template file is altered it should be able to accept new fields.

**Additional context**
For example the AWS Load Balancer Controller Helm Chart currently supports this through the template file [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/helm/aws-load-balancer-controller/templates/pdb.yaml#L13).

**Comment by ConnorJC3** [comment]
/kind feature

Hi, thanks for the feature request - I've added it to our backlog for the team to evaluate. I can't promise any sort of ETA at this moment, but any updates or other information will be posted to this issue.

**Comment by ConnorJC3** [comment]
/close

Added in #2159 and will be released with the next monthly release of the EBS CSI Driver (later in October).
