### ISSUE TITLE
Refactor controller unit test with proper mock

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#220]
Proper mocking should be used for controller unit testing instead of using the current [fake cloud provider](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/cloud/fakes.go) that has fake logic that are implemented for sanity testing purpose.

**Goal**
* move fake cloud provider inside `tests/sanity` package and make sure it is only used there
* auto generate cloud provider using gomock. See [./hack/update-gomock](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/hack/update-gomock) as an example
* update controller_test.go and node_test.go to use the generated cloud provider mock.

**Reference PR**

Could you create a `mock_cloud` using gomock? With that, we could truly unit test controller service without depending on the fake cloud implementation. 

Here is something similar I did for another driver: https://github.com/aws/aws-fsx-csi-driver/blob/master/pkg/driver/controller_test.go#L224

_Originally posted by @leakingtapan in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/219_

**Comment by bertinatto** [comment]
+1

The fake cloud provider object was introduced way before I started using gomock, so we should definitely get rid of it in unit tests.

**Comment by zacharya** [comment]
If no one has taken this up, I'd like to contribute

**Comment by leakingtapan** [comment]
@zacharya I updated the issue description. let me know if you have any questions, will be happy to clarify more.

**Comment by zacharya** [comment]
I submitted #269 for this.  Let me know if you have any issues with the implementation or test refactors.
