### ISSUE TITLE
Report Metrics for the driver

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#223]
**Is your feature request related to a problem? Please describe.**
Report Metrics for the driver

**Describe the solution you'd like in detail**
TBD

**Ref**
* https://github.com/container-storage-interface/spec/issues/236

**Comment by rgarcia89** [comment]
Awesome to see that this will be part of milestone 0.6
very looking forward to it

**Comment by AceHack** [comment]
What's going on here, how do we get metrics, this seems very incomplete without it.

**Comment by konduktor4ik** [comment]
Any update?

**Comment by AceHack** [comment]
Any update, I really hope this is done before 1.19 when CSIMigrationAWS is likely to be enabled.  This will break tons of our alarms and auto-resizing code if we can't get metrics.

**Comment by Ramneekkhurana** [comment]
can we have any updates on this ?

**Comment by ayberk** [comment]
We're currently not actively working on this but we understand how important it is. I'll see if we can get some resources soon. 

@AceHack I believe currently it's planned to be on by default with 1.21 release.

**Comment by AceHack** [comment]
Any update?

**Comment by AceHack** [comment]
Great updates, thanks so much for the work on this.

**Comment by kovalyukm** [comment]
Please, tell in which version of the driver and when volume stats metrics are going to be available? (For now #677 is in master only).

**Comment by ayberk** [comment]
We'll have it in the next release, so `0.9.0`.

**Comment by Pluies** [comment]
For those wondering (as I did!) what metrics are now available, as I couldn't find any info about them in this project's docs, they are the standard:

```
kubelet_volume_stats_inodes_used
kubelet_volume_stats_used_bytes
kubelet_volume_stats_available_bytes
kubelet_volume_stats_capacity_bytes
kubelet_volume_stats_inodes
kubelet_volume_stats_inodes_free
```

And they're exposed on the kubelet metrics endpoint without any extra config. So if you have e.g. Prometheus scraping the kubelet, the metrics should be available already! 👍

Thank you for adding this @AndyXiangLi , it's super helpful 🙏

**Comment by augustovictor** [comment]
Even though these metrics are now available, are they collected by cloudwatch as well or it'd be necessary to configure prometheus to scrape them, for example?

**Comment by miltodorov** [comment]
I'm in a similar situation like @augustovictor - my EBS driver is deployed as an addon via Terraform. 
I also have enabled CloudWatch integration (addon) with Container Insights. 
Running commands such as kubectl get --raw /api/v1/nodes/<HOST>/proxy/metrics | grep 'kubelet_volume_stats_available_bytes' does indeed show metrics but how do I get these metrics into CloudWatch so I can create alarms?
