### ISSUE TITLE
Can new extraVolumeTags be added to existing volumes ?

### ISSUE THREAD

**Issue by adrianmiron** [kubernetes-sigs/aws-ebs-csi-driver#2233]
Hi,

I want to add new tags to new and existing volumes using `extraVolumeTags`  but it only works for new volumes as far as i can tell.

Is that the intended behaviour or can i trigger some update on the tags from the controller ?

Thanks

**Comment by ConnorJC3** [comment]
`extraVolumeTags` only applies to new volumes, that is correct.

If you want to add/modify/delete tags of an existing volume, you can do so via a `VolumeAttributesClass` as documented here: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/tagging.md#adding-modifying-and-deleting-tags-of-existing-volumes

**Comment by adrianmiron** [comment]
Thanks for the links, good to have info , i will test it out once we move to EKS 1.31

**Comment by ihor-kokhan-onereach** [comment]
I try add tags to volumes. But its not work for me.
I create VAC

`apiVersion: storage.k8s.io/v1beta1
kind: VolumeAttributesClass
metadata:
  name: gp3
  namespace: kube-system
driverName: ebs.csi.aws.com
parameters:
  tagSpecification_1: "test=test"`

and add to PVC spec this config

`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-loki-read-0
  namespace: monitoring
  labels:
    app.kubernetes.io/component: read
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
    k8slens-edit-resource-version: v1
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  finalizers:
    - kubernetes.io/pvc-protection
  selfLink: /api/v1/namespaces/monitoring/persistentvolumeclaims/data-loki-read-0
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pvc-ed1af8d7-e4ca-45f0-a002-5ad553738395
  storageClassName: gp3
  volumeMode: Filesystem
  volumeAttributesClassName: gp3
`

But still don't see tags in AWS EC2 volumes. EKS 1.31 version. Amazon EBS CSI Driver  v1.38.1-eksbuild.1
