### ISSUE TITLE
EBS CSI Driver Provisioning Failure: Unsupported MULTI_NODE_MULTI_WRITER for io2 StorageClass

### ISSUE THREAD

**Issue by hemanth-avs** [kubernetes-sigs/aws-ebs-csi-driver#2237]
/kind bug

**What happened?**

Provisioning failure occurred when attempting to create an EBS volume using the AWS EBS CSI driver. The specific error indicates that the requested volume capabilities are not supported.

InvalidArgument desc = Volume capabilities MULTI_NODE_MULTI_WRITER not supported. Only AccessModes[ReadWriteOnce] supported.

**What you expected to happen?**

The expectation was likely to successfully provision an EBS volume with multi-node, multi-writer capabilities using the io2 storage class. 

**How to reproduce it (as minimally and precisely as possible)?**

followed instructions from official docs
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/multi-attach.md

enured 
1. accessModes is ReadWriteMany
2. volumeMode: Block
3. storage class type is io2

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.2-eks-7f9249a
- Driver version:

aws-ebs-csi-driver-2.19.0

**Comment by voliveira-tmx** [comment]
Is this not supported?
