### ISSUE TITLE
Attached volumes are not getting detached from old instance and trying to attach to newinstance

### ISSUE THREAD

**Issue by PRYeswanthReddy** [kubernetes-sigs/aws-ebs-csi-driver#2251]
With v1.29.1-eksbuild.1 version the volumes which are assigned a instance is getting detached and it is triggering an attaching call to attach the volume to new instance.

when we upgrade to the v1.30.0eksbuild.1 we could see when a volume is attached to an instance and it is not trying to detach the volume first instead it is sending an volume attachment call, as a result we are getting errors in volume attachments to node.

I       1 controller.go:439] "ControllerPublishVolume: attaching" volumeID="vol-********" nodeID="i-************"
I     1 controller.go:439] "ControllerPublishVolume: attaching" volumeID="vol-*********" nodeID="i-*************"
E 1 driver.go:156] "GRPC error" err="rpc error: code = Internal desc = Could not attach volume \"vol-*************\" to node \"i-**********\": attachment of disk \"vol-**********\" failed, expected device to be attached but was attaching"

reproducing steps:

1. A node should have full capacity of volume attachment (for examples if you are using r5.4Xlarge we can attach 27 volumes and try to deploy the pod which is using volume and then you can see the issue.

Can you please look into this issue and let us the update?

**Comment by ConnorJC3** [comment]
Hi - `v1.29.0` and `v1.30.0` are not supported versions of the EBS CSI Driver ([See the support policy here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver?tab=readme-ov-file#support)). Please upgrade to a supported version (Currently, that would be `v1.37.0` or `v1.36.0`). Several attachment related bugfixes have been released that may solve your issue.

If you are able to reproduce this issue on a supported version, please either provide steps to reproduce (strongly preferred and the best way to get your issue fixed) and/or logs from the EBS CSI controller pod.

**Comment by PRYeswanthReddy** [comment]
Hi @ConnorJC3 , we will test it with latest ebs-csi-driver till then please keep this issue open we will update details once tested.

**Comment by PRYeswanthReddy** [comment]
This issue is fixed in 1.36.0 , Thanks for your update, you can close this issue.
