### ISSUE TITLE
aws ebs csi driver on Kube 1.14 doesnt register driver under `csidrivers.storage.k8.io` as expected

### ISSUE THREAD

**Issue by anusha-ragunathan** [kubernetes-sigs/aws-ebs-csi-driver#259]
/kind bug

**What happened?**
- Install Kube 1.14 GA (via Docker EE)

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.0-docker-2", GitCommit:"71e7c2cb4250a28d6a5bfdbc6a7a111e3f25e215", GitTreeState:"clean", BuildDate:"2019-03-26T19:55:37Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

#Confirm that CSIDrivers and CSINodes are part of core api-resources. 
```
$ kubectl api-resources | grep csi
csidrivers                                     storage.k8s.io                 false        CSIDriver
csinodes                                       storage.k8s.io                 false        CSINode
```
- Install aws ebs csi driver
```
$ kubectl apply -f /home/aragunathan/code/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/secret.yaml
secret/aws-secret created

$ kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-ebs-csi-driver/master/deploy/kubernetes/manifest.yaml
serviceaccount/csi-controller-sa created
clusterrole.rbac.authorization.k8s.io/external-provisioner-role created
clusterrolebinding.rbac.authorization.k8s.io/csi-provisioner-binding created
clusterrole.rbac.authorization.k8s.io/external-attacher-role created
clusterrolebinding.rbac.authorization.k8s.io/csi-attacher-binding created
clusterrole.rbac.authorization.k8s.io/cluster-driver-registrar-role created
clusterrolebinding.rbac.authorization.k8s.io/csi-driver-registrar-binding created
clusterrole.rbac.authorization.k8s.io/external-snapshotter-role created
clusterrolebinding.rbac.authorization.k8s.io/csi-snapshotter-binding created
statefulset.apps/ebs-csi-controller created
daemonset.apps/ebs-csi-node created
```
- Now query the list of installed csi drivers.

```
$ kubectl get csidrivers.storage.k8s.io
No resources found.
```

This should list the aws ebs driver. Note that the driver can be listed using the old method as follows:
```
$ kubectl get csidrivers.csi.storage.k8s.io
NAME              AGE
ebs.csi.aws.com   2m56s
```

**What you expected to happen?**
Driver should be listed using `kubectl get csidrivers.storage.k8s.io`

**How to reproduce it (as minimally and precisely as possible)?**
Please refer to above steps.

**Anything else we need to know?**:
driver works fine otherwise. I can create sc, pvc/pv and pods successfully.

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by anusha-ragunathan** [comment]
cc @leakingtapan

**Comment by leakingtapan** [comment]
Seems 1.14 is still using `csidrivers.csi.storage.k8s.io` as the resource name: https://github.com/kubernetes/kubernetes/blob/v1.14.0/staging/src/k8s.io/csi-api/pkg/crd/manifests/csidriver.yaml#L8

Where is the `csidrivers.storage.k8s.io` coming from?

**Comment by leakingtapan** [comment]
cluster-driver-registrar is still missing 1.14 release: https://quay.io/repository/k8scsi/csi-cluster-driver-registrar?tag=latest&tab=tags

**Comment by anusha-ragunathan** [comment]
> Seems 1.14 is still using `csidrivers.csi.storage.k8s.io` as the resource name: https://github.com/kubernetes/kubernetes/blob/v1.14.0/staging/src/k8s.io/csi-api/pkg/crd/manifests/csidriver.yaml#L8
> 
> Where is the `csidrivers.storage.k8s.io` coming from?

Does CSI CRD matter anymore, now that 1.14 has the `csidrivers` resource built-into core?

**Comment by anusha-ragunathan** [comment]
I updated the manifest.yaml to use the `canary` for most images.

```diff --git a/deploy/kubernetes/manifest.yaml b/deploy/kubernetes/manifest.yaml
index a64b42c..b9362fe 100644
--- a/deploy/kubernetes/manifest.yaml
+++ b/deploy/kubernetes/manifest.yaml
@@ -85,7 +85,7 @@ rules:
   - apiGroups: ["apiextensions.k8s.io"]
     resources: ["customresourcedefinitions"]
     verbs: ["create", "list", "watch", "delete"]
-  - apiGroups: ["csi.storage.k8s.io"]
+  - apiGroups: ["storage.k8s.io"]
     resources: ["csidrivers"]
     verbs: ["create", "delete"]
 
@@ -212,10 +212,9 @@ spec:
             periodSeconds: 10
             failureThreshold: 5
         - name: cluster-driver-registrar
-          image: quay.io/k8scsi/csi-cluster-driver-registrar:v1.0.1
+          image: quay.io/k8scsi/csi-cluster-driver-registrar:canary
           args:
             - --csi-address=$(ADDRESS)
-            - --driver-requires-attachment=true
             - --v=5
           env:
             - name: ADDRESS
@@ -224,7 +223,7 @@ spec:
             - name: socket-dir
               mountPath: /csi
         - name: csi-provisioner
-          image: quay.io/k8scsi/csi-provisioner:v1.0.1
+          image: quay.io/k8scsi/csi-provisioner:canary
           args:
             - --provisioner=ebs.csi.aws.com
             - --csi-address=$(ADDRESS)
@@ -237,7 +236,7 @@ spec:
             - name: socket-dir
               mountPath: /var/lib/csi/sockets/pluginproxy/
         - name: csi-attacher
-          image: quay.io/k8scsi/csi-attacher:v1.0.1
+          image: quay.io/k8scsi/csi-attacher:canary
           args:
             - --csi-address=$(ADDRESS)
             - --v=5
@@ -248,7 +247,7 @@ spec:
             - name: socket-dir
               mountPath: /var/lib/csi/sockets/pluginproxy/
         - name: csi-snapshotter
-          image: quay.io/k8scsi/csi-snapshotter:v1.0.1
+          image: quay.io/k8scsi/csi-snapshotter:canary
           args:
             - --csi-address=$(ADDRESS)
             - --connection-timeout=15s
@@ -259,7 +258,7 @@ spec:
             - name: socket-dir
               mountPath: /var/lib/csi/sockets/pluginproxy/
         - name: liveness-probe
-          image: quay.io/k8scsi/livenessprobe:v1.0.1
+          image: quay.io/k8scsi/livenessprobe:canary
           args:
             - --csi-address=/csi/csi.sock
             - --connection-timeout=3s
@@ -344,7 +343,7 @@ spec:
             - name: registration-dir
               mountPath: /registration
         - name: liveness-probe
-          image: quay.io/k8scsi/livenessprobe:v1.0.1
+          image: quay.io/k8scsi/livenessprobe:canary
           args:
             - --csi-address=/csi/csi.sock
             - --connection-timeout=3s
```

**Comment by anusha-ragunathan** [comment]
With this, I'm able to query the installed driver correctly. 

```
$ kubectl get csidrivers.storage.k8s.io
NAME              CREATED AT
ebs.csi.aws.com   2019-03-28T18:57:19Z
```

However, Node Attach fails due to error:
 ```failed to attach: node "ip-172-31-30-54.us-west-2.compute.internal" has no NodeID annotation```

`kubectl logs pod/ebs-csi-controller-0 -c csi-attacher -n kube-system` output here:
[logs.txt](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/files/3019803/logs.txt)

Error essentially due to:
```
I0328 18:58:10.241275       1 csi_handler.go:523] Can't get CSINodeInfo ip-172-31-30-54.us-west-2.compute.internal: csinodeinfos.csi.storage.k8s.io "ip-172-31-30-54.us-west-2.compute.internal" not found
I0328 18:58:10.241300       1 csi_handler.go:387] Saving attach error to "csi-21da6639f45892e2b5b505ea21386f855f4cc1f2e022c4d5782b66a8b6951ef6"
I0328 18:58:10.244366       1 csi_handler.go:397] Saved attach error to "csi-21da6639f45892e2b5b505ea21386f855f4cc1f2e022c4d5782b66a8b6951ef6"
I0328 18:58:10.244389       1 csi_handler.go:102] Error processing "csi-21da6639f45892e2b5b505ea21386f855f4cc1f2e022c4d5782b66a8b6951ef6": failed to attach: node "ip-172-31-30-54.us-west-2.compute.internal" has no NodeID annotation
```

**Comment by leakingtapan** [comment]
Looks like the external-attacher needs to be updated still.

**Comment by leakingtapan** [comment]
I suspect upgrading the sidecars too early will be a breaking change. Since in 1.13, the CSINodeInfo is not built-in CRD yet, and the upgraded sidecars will try to talk to the built-in CRD with name `csinode.storage.k8s.io` instead of `csinodeinfos.csi.storage.k8s.io`

**Comment by leakingtapan** [comment]
@anusha-ragunathan have you tried your amended manifest (with canary image tags) in 1.13 cluster?

**Comment by anusha-ragunathan** [comment]
@leakingtapan : I have a 1.14 cluster. In 1.14, CSINodeInfo and CSIDriverInfo are both part of the core API resources. So the sidecars should be updated to reflect that. However, the sidecars havent been updated to reflect that, which leads to this problem.

According to @ddebroy, updating sidecars will happen in a week or so.

**Comment by leakingtapan** [comment]
What I mean is we probably cannot upgrade the sidecars, since it could break when running the upgraded driver in 1.13 cluster.

**Comment by anusha-ragunathan** [comment]
This is indeed a breaking change. I would expect a driver set for cluster version 1.13 and below and another driver set for cluster version 1.14 and above. 

However, since both features (CSIDriver and CSINodeInfo) are in beta, breaking changes are expected. So it should be okay. Thoughts?

**Comment by ddebroy** [comment]
The features `CSIDriverRegistry` and `CSINodeInfo` were in alpha before. They are [promoted](https://github.com/kubernetes/kubernetes/commit/6265f4f78c7bf27697b8781e391605b4d4e683fc#diff-84e72664a7cc9add01954d3a7b8cbb45) to Beta starting v1.14. Therefore, I think no backward compatibility should be expected wrt those features in clusters prior to v1.14 according to k8s deprecation policies.

Regarding the update in attacher to use the beta in-tree `CSINodeInfo`: the PR [merged](https://github.com/kubernetes-csi/external-attacher/commit/3156c24cc625b6af2d0940f70e1213a1235b7e04) 10 days ago. Looks like @anusha-ragunathan was trying the attacher from before then [12 days ago]. So @anusha-ragunathan, can you please update the side-car images once more and check please? The [canary](https://quay.io/repository/k8scsi/csi-attacher?tag=latest&tab=tags) images also got updated 3/4 days back.

**Comment by anusha-ragunathan** [comment]
@ddebroy : Using the new set of sidecar canaries worked!

**Comment by anusha-ragunathan** [comment]
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.0-docker-2", GitCommit:"71e7c2cb4250a28d6a5bfdbc6a7a111e3f25e215", GitTreeState:"clean", BuildDate:"2019-03-26T19:55:37Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

# Note that the new convention works.
$ kubectl get csinode.storage.k8s.io
NAME                                         CREATED AT
ip-172-31-16-44.us-west-2.compute.internal   2019-04-09T17:13:15Z
ip-172-31-5-2.us-west-2.compute.internal     2019-04-09T17:13:20Z
ip-172-31-7-152.us-west-2.compute.internal   2019-04-09T17:13:15Z

# Note that the new convention works.
$ kubectl get csidriver.storage.k8s.io
NAME              CREATED AT
ebs.csi.aws.com   2019-04-09T17:13:17Z

$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM               STORAGECLASS   REASON   AGE
pvc-2053931d-5aeb-11e9-88ff-0242ac11000e   4Gi        RWO            Delete           Bound    default/ebs-claim   ebs-sc                  2m29s

$ kubectl get pvc
NAME        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
ebs-claim   Bound    pvc-2053931d-5aeb-11e9-88ff-0242ac11000e   4Gi        RWO            ebs-sc         2m44s

$ kubectl get pod
NAME   READY   STATUS    RESTARTS   AGE
app    1/1     Running   0          2m47s
```

**Comment by anusha-ragunathan** [comment]
Updates to manifest.yaml 
[diff.txt](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/files/3060212/diff.txt)

**Comment by anusha-ragunathan** [comment]
Applying the diff doesnt work anymore.

**Comment by leakingtapan** [comment]
Upgrading cluster-driver-registrar will be blocked on https://github.com/kubernetes-csi/cluster-driver-registrar/issues/44

**Comment by leakingtapan** [comment]
Updated other sidecars [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/291), since it is required to unblock 1.14 e2e testing.
