### ISSUE TITLE
Use aws native wait function for volume

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#280]
**Is your feature request related to a problem?/Why is this needed**
The driver need to wait for volume creation after it is created; wait for volume attachment after it is attached to some instance. We currently implement the functionality ourselves, but instead the aws natvie wait functions could be used:

* ec2.[WaitUntilVolumeAvailableWithContext](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.WaitUntilVolumeAvailableWithContext) -> [waitForVolume](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/cloud/cloud.go#L653)
* ~ec2.[WaitUntilVolumeInUseWithContext](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.WaitUntilVolumeInUseWithContext) -> [WaitForAttachmentStatus](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/cloud/cloud.go#L387)~

/feature

**Comment by bertinatto** [comment]
+1

**Comment by zacharya** [comment]
I'd like to take this on if there are no objections
