### ISSUE TITLE
Return error if snapshot doesn't exist

### ISSUE THREAD

**Issue by bertinatto** [kubernetes-sigs/aws-ebs-csi-driver#287]
/kind bug

**What happened?**

It seems like we're not returning a `status.NotFound` error when `CreateVolume` is given a non-existent snapshot ID.

https://github.com/kubernetes-csi/csi-test/blob/e1f2421c7f0a0cc7f9942fea1192392f253891db/pkg/sanity/controller.go#L738

CC @tsmetana @leakingtapan

**Comment by bertinatto** [comment]
My guess is that AWS will return an `InvalidSnapshot.NotFound` error. In that case, we just have to  return an `cloud.ErrNotFound` in `CreateDisk`; and in `CreateVolume` return an `status.NotFound`.

**Comment by tsmetana** [comment]
The strange thing is that the tesuite complains about controller returning `nil` not a wrong error. I'll take a look at this.

**Comment by bertinatto** [comment]
> The strange thing is that the test suite complains about controller returning nil not a wrong error. I'll take a look at this.

Yes, I fixed that in #288. However, in addition to fixing the fake cloud implementation (ie #288), we need to make sure this is fixed in `cloud.go` as well.

**Comment by tsmetana** [comment]
> Yes, I fixed that in #288. However, in addition to fixing the fake cloud implementation (ie #288), we need to make sure this is fixed in `cloud.go` as well.

OK. So we miss the error "translation". Thanks for explaining.
