### ISSUE TITLE
Dynamic volume limits

### ISSUE THREAD

**Issue by bertinatto** [kubernetes-sigs/aws-ebs-csi-driver#290]
**Is your feature request related to a problem?/Why is this needed**

[NodeGetInfo](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/v0.3.0/pkg/driver/node.go#L283-L295) should return an `NodeGetInfoResponse` with the maximum number of volumes that the node supports set in the field `MaxVolumesPerNode`.

This number may vary on a per-instance-type basis, so we should detect the instance type first.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_limits.html

**Comment by gnufied** [comment]
Just for reference the in-tree implementation is here - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/awsebs/aws_ebs.go#L106

**Comment by ayberk** [comment]
#289 fixed this.

/close

**Comment by ayberk** [comment]
Nvm I think this issue for per-instance limits. 
/reopen

**Comment by vdhanan** [comment]
it looks like we already get the volume limit based on instance type here: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/driver/node.go#L599

closing this issue

**Comment by vdhanan** [comment]
nvm, can't close :)

**Comment by AndyXiangLi** [comment]
We already have this resolved
/close

**Comment by bertinatto** [comment]
@AndyXiangLi the [current implementation](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/66efa6843ad08936ae50d7ef20f2237886de1d5e/pkg/driver/node.go#L626-L636) is very limited in the sense that it doesn't take into account every instance type available. For instance, the limit will always be 39 or 25, but [this page](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_limits.html) describes other values depending on the instance type.

Ideally the driver would get the volume limit from the instance metadata. Do you know if this information is available there? If not, is hardcoding in the driver all instance types and their volume limits the only remaining option?

I'll re-open this issue, but feel free to close it if that's already solved (and I missed it).
