### ISSUE TITLE
Run e2e test for CSI migration

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#294]
**Is your feature request related to a problem? Please describe.**
Run upstream ebs plugin e2e test case again EBS CSI driver.

**Ref**
* https://testgrid.k8s.io/sig-gcp-compute-persistent-disk-csi-driver#Migration%20Kubernetes%20Master%20Driver%20Stable
* https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/258/files

**Comment by bertinatto** [comment]
Running those tests will give us a lot more confidence :+1: 

I think @pohly made changes necessary to facilitate running k8s e2e tests against CSI drivers. He wrote a blog post about it:

https://kubernetes.io/blog/2019/03/22/kubernetes-end-to-end-testing-for-everyone/

And I think we can use the pmem CSI driver as an example: https://github.com/intel/pmem-CSI

**Comment by pohly** [comment]
Today I also submitted a PR which shows how to do that testing in Prow:
https://github.com/kubernetes-csi/csi-driver-nfs/pull/14

Not sure whether that is relevant for you, though.

**Comment by leakingtapan** [comment]
@pohly thx for the input. Will definitely take a look
/assign

**Comment by davidz627** [comment]
@leakingtapan I also wrote up how to do this here: https://docs.google.com/document/d/16h9vLLbqQCN83KnlPtn7qL_GB1TYwhWkoA5G4FS3KBI/edit#heading=h.bzyig0rahh0w

If you have any confusion/issues with the instructions please comment on the doc so we can improve it for others as well :)

**Comment by leakingtapan** [comment]
Al the tests are running with: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/362

**Comment by leakingtapan** [comment]
See here for dashboard:
* https://testgrid.k8s.io/sig-aws-ebs-csi-driver#pull-migration-test-latest
* https://testgrid.k8s.io/sig-aws-ebs-csi-driver#migration-test-latest

**Comment by leakingtapan** [comment]
this is done as part of CSI migration beta.

/close
