### ISSUE TITLE
Support for multiple pods on the same node to share the same EBS volume

### ISSUE THREAD

**Issue by riteshnaik** [kubernetes-sigs/aws-ebs-csi-driver#295]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to share the PV backed with EBS volume to share between the pods on the same node if pods are Deployment objects. I could get this behavior working by using the StatefulSets but not with Deployment.

I have a use case to use the dataset optimized for EBS to access on all the pods in readonly mode.  Currently, I am spinning up the nodes with EBS volume attached. When pods are scheduled on these nodes, same volume is mounted on each of these pods. So the single EBS volume is mounted on all the pods. 

I am trying to replicate the similar behavior where I am mounting the same EBS volume on all the pods in the same node using PV and PVC. 

I am trying to learn more on the scope of this feature for aws-ebs-csi driver. I briefly discussed this use case on the sig-aws slack channel on how this use case would interact with scheduling in core Kubernetes. I would like to understand more on what it looks like to support this feature.

**Comment by leakingtapan** [comment]
This should be working already see e2e test case: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/tests/e2e/dynamic_provisioning.go#L269

**Comment by frittentheke** [comment]
/remove-lifecycle stale

@riteshnaik did you get to check out if it works already?

**Comment by riteshnaik** [comment]
@leakingtapan @frittentheke It works. Multiple pods on the same node can share the same EBS volume. Thanks for looking into it. Please feel free to close the issue.

**Comment by randych-gilad** [comment]
No, it doesn't work, after first deployment every each other falls off with "node had no available disk".
