### ISSUE TITLE
Investigate how to keep helm chart in sync with deploy manifest

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#305]
**Is your feature request related to a problem? Please describe.**
We created Helm chart for the driver [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/303). Since we still have a deploy/kubernetes/manifest.yaml, this creates a problem about how to sync the two.

**Describe the solution you'd like in detail**
Potential solutions:
* deprecate the deploy/kubernetes/manifest.yaml (not ideal)
* Evaluate Kustomize 
* etc.

**Additional Context**
* We have aws-alb-ingress-controler that is doing the same thing, I will check on that side how is this problem solved there.

**Comment by krmichel** [comment]
@leakingtapan, I don't know if this has been dealt with, but I think that if `helm template` was used with a correct values file it could be used to create the base manifests.  Then the helm chart could be maintained and Kustomize manifests could just synced by generating them from the chart.  Thoughts?

**Comment by leakingtapan** [comment]
/reopen
It’s a good idea :)

**Comment by krmichel** [comment]
/remove-lifecycle rotten
Yeah, let me read up a little bit more on Kustomize and I will take a crack at it.
