### ISSUE TITLE
Node service vs idempotency

### ISSUE THREAD

**Issue by bertinatto** [kubernetes-sigs/aws-ebs-csi-driver#307]
/kind bug

I think our `inFlight` object isn't providing idempotency for the node service. For example:

1) CO calls `NodeStageVolume` for a 500 GB volume.
2) The driver starts formatting the volume.
3) CO calls calls `NodeStageVolume` **again** for the same volume.
4) The driver returns an error [0] because the first request `NodeStageVolume` call hasn't returned yet (the driver is still formatting the volume).

Since the call is supposed to be idempotent, we shouldn't return an error in step 4.

I believe the best option is to have a per-volume lock, so any operation (stage, publish, resize etc.) on a specific volume will be executed synchronously.

[0] https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/v0.3.0/pkg/driver/node.go#L84-L91

CC @leakingtapan @dkoshkin

**Comment by leakingtapan** [comment]
The `inFlight` object locks around the `NodeStageVolumeRequest` which contains the volume ID with other fields like `GetStagingTargetPath`, what if there is an node request for the same volume but different path?

**Comment by bertinatto** [comment]
>The inFlight object locks around the NodeStageVolumeRequest which contains the volume ID with other fields like GetStagingTargetPath

I think the `inFlight` object only locks when the key (which is a request's hash containing the volume ID and other fields, like you mentioned above) is being inserted and deleted:

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/2ea44a9e8cb60d1b98c1db7410a585a263d2c46e/pkg/driver/internal/inflight.go#L48-L61

It won't lock until a `NodeStageVolume` call completes to start processing the second one, it'll return an error for the latter. Note that the responses of these two calls (which are the equally addressed to the same volume, path etc.) will be different (no idempotency).

>what if there is an node request for the same volume but different path?

Currently the driver will process both requests at the same time, which is OK in this case. However, if the request is for the *same volume and same path*, it'll return an error, which is not correct.

Note that the problem is not about the **key** being used, but instead the error returned by the driver. According to the specs, the **key** should contain the volume ID, the path and the capabilities. We are mostly OK here, but we can't return an error if the same key is being processed:

```
This operation MUST be idempotent. If the volume corresponding to the volume_id is already staged to the staging_target_path, and is identical to the specified volume_capability the Plugin MUST reply 0 OK.
```
