### ISSUE TITLE
EBS CSI Driver doesn't respect fstype from existing storage

### ISSUE THREAD

**Issue by shanesiebken** [kubernetes-sigs/aws-ebs-csi-driver#324]
/kind bug

**What happened?**
The AWS EBS CSI Driver fails to mount pre-existing (in-tree) storage with CSIMigration / CSIMigrationAWS feature flags where the fstype on the storage is different than ext4 (the driver's default).

**What you expected to happen?**
The AWS CSI Driver should successfully read the in-tree storage fstype and mount the volume correctly.

**How to reproduce it (as minimally and precisely as possible)?**

1. Create a persistent volume with the in-tree aws cloud-provider with a volume fstype other than "ext4".
2. Install the EBS csi driver, and enable CSIMigration and CSIMigrationAWS feature gates.
3. Attempt to attach the existing storage to a pod.

**Anything else we need to know?**:
Looking at the requests coming from the storage shim (CSIMigration code), it looks like the fstype is referenced in a different part of the request than "attributes", which is where node.go looks for it at [line 175](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/driver/node.go#L175). Another case for shimmed storage could likely be added here.

**Environment**
- Kubernetes version (use `kubectl version`): 1.15.0
- Driver version: commit sha:2aed4b5de3976c8e551b492137c58be642e05897

**Comment by leakingtapan** [comment]
Another potential issue is [NodePublishVolume](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/driver/node.go#L443) is not taking the fstype as well

**Comment by shanesiebken** [comment]
@leakingtapan I think addressing [this issue](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/326) would solve this issue as well. I believe the fstype is passed in the volume capability from the Migration shim.
