### ISSUE TITLE
Driver does not format volumes as xfs

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/aws-ebs-csi-driver#326]
/kind bug

**What happened?**
This storage class should provision XFS volumes:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2019-08-06T14:27:30Z"
  name: e2e-volume-4295-ebs.csi.aws.com-sc
  resourceVersion: "20116"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/e2e-volume-4295-ebs.csi.aws.com-sc
  uid: 529e3b50-b856-11e9-9486-06385e99b400
parameters:
  csi.storage.k8s.io/fstype: xfs
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

It provisions this PV (truncated):
```
  spec:
    csi:
      driver: ebs.csi.aws.com
      fsType: xfs
      volumeAttributes:
        fstype: ""
        storage.kubernetes.io/csiProvisionerIdentity: 1565101200642-8081-ebs.csi.aws.com
      volumeHandle: vol-censored
```

Such PV is then formatted as ext4.

**What you expected to happen?**
The PV is formatted as xfs.

**Anything else we need to know?**:
There are actually two issues:

- CreateVolume call should check `csi.storage.k8s.io/fstype` parameter. I am not sure it's actually passed to the CSI driver, maybe it's passed via `VolumeOptions`.

- NodeStage should use the fsType passed in `NodeStageVolumeRequest.volume_capability.MountVolume.fs_type` instead of the one in volume context. The driver does not need to carry the filesystem type in the volume context at all. 

**Environment**
- Kubernetes version (use `kubectl version`): 1.14
- Driver version: `amazon/aws-ebs-csi-driver:latest` (as of today)

**Comment by leakingtapan** [comment]
/assign

Yep. Confirming that the driver doesn't respect `csi.storage.k8s.io/fstype` yet. This is something we need to fix

**Comment by leakingtapan** [comment]
/close

As the PR is merged
