### ISSUE TITLE
New e2e test layout on testgrid

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#338]
**Is your feature request related to a problem? Please describe.**
As we are adding more and more test into testgrid, we need re-organize the testgrid tabs as follows:
* verify
* unit-test - run both unit test and sanity test
* ~integration-test~ deprecated
* e2e-test-latest - run both single az and multi az tests on latest kubernetes version
* e2e-test-stable - run both single az and multi az tests on stable kubernetes version
* migration-test-latest - run migration e2e on latest kubernetes version (period job)
* ~e2e-test-eks-latest - run on EKS latest supported version~
* ~e2e-test-eks-stable - run on EKS stable supported version~

/cc @wongma7

**Comment by wongma7** [comment]
SGTM. Best we can do for testing on latest kubernetes version is the latest alpha release (kops won't accept master branch or git hash).
