### ISSUE TITLE
no matches for kind "CSIDriver" in version "storage.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by sridharvellingiri** [kubernetes-sigs/aws-ebs-csi-driver#342]
Hi,
I have deployed EKS cluster version 1.13 in AWS and followed the steps to configure ebs csi driver and I got the below error

After I have run the below command and I got the error for CSIDriver and all other services has been created from manifest.yaml

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-ebs-csi-driver/master/deploy/kubernetes/manifest.yaml
**error:** unable to recognize "https://raw.githubusercontent.com/kubernetes-sigs/aws-ebs-csi-driver/master/deploy/kubernetes/manifest.yaml": no matches for kind "CSIDriver" in version 
```

Am I doing something wrong.! Can you please help me to identify the solution to configure this ebs csi driver in my clsuter.

Since I am using dedicated EBS for our applications, I thought this driver will be very helpful to maintain EBS features including snapsshot and automate restore from the volume disaster?

Please let me know if you need any other information. Thanks

**Comment by wongma7** [comment]
Master branch isn't compatible with 1.13, please try an older manifest.yaml. The README needs a slight update.

Also, the snapshot feature `VolumeSnapshotDataSource` is still alpha in 1.13 so please keep that in mind if you plan to rely on it.

**Comment by wongma7** [comment]
@leakingtapan actually I'm not sure if master branch is incompatible with 1.13 if the only issue is the CSIDriver object?

**Comment by leakingtapan** [comment]
@wongma7 the latest driver container image is still compatible with 1.13, what's causing issue here is the CSIDriver object (which is still alpha at 1.13) and the [Topology support](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/manifest.yaml#L152) that is enabled (still alpha at 1.13, but going beta at 1.14).

@sridharvellingiri if you remove the line about [Topology](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/manifest.yaml#L152) and the section about CSIDriver object in manifest file. You should be able to use the driver at EKS 1.13

**Comment by sridharvellingiri** [comment]
@leakingtapan Thanks for coming back.

I have removed Topology line "--feature-gates=Topology=true" and "apiVersion: 
 storage.k8s.io/v1beta1" section completely. so i didn't get the error CSIDriver now. 
It's all deployed but all pods were not completely deployed. Please find the error below
Found from the k8s dashboard events (attached screenshot)

MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry/ is not a directory

<img width="1008" alt="Screenshot 2019-08-15 at 09 08 22" src="https://user-images.githubusercontent.com/36194798/63082176-721e2800-bf3d-11e9-9bbe-d22c5a96a66b.png">

**Comment by leakingtapan** [comment]
What's your worker node version?

**Comment by sridharvellingiri** [comment]
Im in one of the worker node and I have found the below directories (attached scrrenshot) available in "/var/lib/kubelet" folder
EKS kubernetes cluster version is 1.13 and sorry Im not sure how to check worker node version here
Whats is the expected directory location can be replaced in manifest file instead of "/var/lib/kubelet/plugins_registry/" ?

![Screenshot 2019-08-16 at 09 15 47](https://user-images.githubusercontent.com/36194798/63153615-a4e02300-c006-11e9-8a5a-87b87819b161.png)

**Comment by sridharvellingiri** [comment]
![Screenshot 2019-08-16 at 09 43 05](https://user-images.githubusercontent.com/36194798/63155344-4452e500-c00a-11e9-9951-5b1f8638192d.png)
Looks my worker nodes are in v1.11.5 version. I will upgrade and try the rest.
Thank you for your guidance.

**Comment by sridharvellingiri** [comment]
@leakingtapan , Is this driver will do auto restoration from the lastest snapshot without any manual steps.
For example: After deployed app with attached EBS mountpoint. Later if I delete the EBS volume or corrupted, is the driver will get restored with new EBS volume from the latest snapshot automatically??

**Comment by leakingtapan** [comment]
@sridharvellingiri the EBS CSI driver doesn't do auto restoration for cluster admin. But it provides building blocks for cluster admin to build on top it. One feature it provides is volume snapshot, cluster admin can create snapshot by creating snapshot object. And the driver takes care of creating the snapshot under the hood. For application developer, they can choose to restore volume from a snapshot using PVC or they can choose to create a new volume out of PVC. See [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/snapshot) for volume snapshot example. 

Let me know what your use case so I can better assist you

**Comment by leakingtapan** [comment]
/close this issue since the original one is resolved.
Please reopen if the same issue persists.

**Comment by jicowan** [comment]
> @wongma7 the latest driver container image is still compatible with 1.13, what's causing issue here is the CSIDriver object (which is still alpha at 1.13) and the [Topology support](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/manifest.yaml#L152) that is enabled (still alpha at 1.13, but going beta at 1.14).
> 
> @sridharvellingiri if you remove the line about [Topology](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/manifest.yaml#L152) and the section about CSIDriver object in manifest file. You should be able to use the driver at EKS 1.13

There is no [Topology support](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/manifest.yaml#L152).  You can please post the manifest so we can edit it?

**Comment by XiaoYangZhu** [comment]
I came across the same issue when doing on EKS 1.13 today with content below:
yaml:
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: fsx.csi.aws.com
spec:
  attachRequired: false

error:
no matches for kind "CSIDriver" in version "storage.k8s.io/v1beta1"

Any suggest how to fix this?

**Comment by leakingtapan** [comment]
@XiaoYangZhu @jicowan  You are seeing the error because, `CSIDriver` CRD was not built-in by 1.13. It was an alpha object at 1.13. Could you use 1.14 cluster for v0.2 EFS driver? Could you elaborate more on your use cases, so I can assist further?
