### ISSUE TITLE
Fix raw block volume resizing for EBS

### ISSUE THREAD

**Issue by gnufied** [kubernetes-sigs/aws-ebs-csi-driver#346]
We need to fix raw block volume resizing (`NodeExpandVolume`) to not resize the volume if given `volume_path` in resize request is a block device and not a mounted file system.

**Comment by gnufied** [comment]
@wongma7 will you have time to fix this?

**Comment by wongma7** [comment]
/assign
Yes, will have a look

**Comment by leakingtapan** [comment]
It's more explicit to return `NodeExpansionRequired=false` during `ControllerExpandVolume` call when the controller block volume expansion is requested. But I also realized that volume capability is not passed into `ControllerExpandVolume` which make controller harder to know if is this request for block or filesystem.

**Comment by wongma7** [comment]
Yeah, @leakingtapan let's help review https://github.com/container-storage-interface/spec/pull/381 & https://github.com/container-storage-interface/spec/issues/380 to get volume capability passed to ControllerExpandVolume

**Comment by leakingtapan** [comment]
> We need to fix raw block volume resizing (NodeExpandVolume) to not resize the volume if given volume_path in resize request is a block device and not a mounted file system. 

I can understand not do node resize for block volume. But what does `not a mounted file system` mean?

@gnufied

**Comment by gnufied** [comment]
the `volume_path` specified in `NodeExpandVolumeRequest` field could be a mount point (or a directory with file system) or it could be a block device (such as `/dev/xvdba`). We should be able to differentiate between two and only resize the volume if `volume_path` is a mounted file system and not a raw block device. I think skipping fs resize if `mount_path` is a raw block device should do the job.

**Comment by zhucan** [comment]
@gnufied what's version with the kubernetes support NodeExpandVolume for raw block volume? v1.14&v1.15 doesn't support it?

**Comment by leakingtapan** [comment]
@zhucan There is not feature flag for raw block volume expansion, it fall under `ExpandCSIVolumes` flag, which is beta since 1.16

**Comment by zhucan** [comment]
@leakingtapan Yes, In my kubernetes cluster(v1.15.0), The expansion(NodeExpandVolume) for raw block not be called.

**Comment by frittentheke** [comment]
@leakingtapan  I took the liberty to "unstale" this ... should bugs, especially those you already triaged and marked as such, ever go stale?

**Comment by leakingtapan** [comment]
Thx for doing this. It looks fejta-bot isn’t smart enough to figure out if the issue is triaged or not... and I don’t have more time to work on the fix

**Comment by AndyXiangLi** [comment]
/assign
looking into this
