### ISSUE TITLE
Allow overriding node attach limits as driver CLI parameter

### ISSUE THREAD

**Issue by gnufied** [kubernetes-sigs/aws-ebs-csi-driver#347]
Given all the complexities around how limits will be calculated on the node, it is a good idea to just allow an admin to override the limits when starting the csi-ebs driver.

**Comment by leakingtapan** [comment]
Not sure how is this going to work if the worker nodes are of different instance type where each has a different attach limit. I think this should be a per node attributes.

**Comment by gnufied** [comment]
The `CSINode` object where limits are actually saved are *per-node* basis, so we should be able to support this as per-node attribute. 

Are you referring to how will this be set during deploy time?

**Comment by gnufied** [comment]
The flow of this code is:

csi-ebs-driver-on-node --> store-limit-> CSINode --> scheduler uses CSINode object during counting volumes.

So it is perfectly possible to support this on per-node basis. It is another problem, how will tools like kops will surface this configuration parameter though..

**Comment by leakingtapan** [comment]
Probably I missed something. How could cluster operator set this new CLI parameter differently for drivers on different node? Since it is deployed as daemon set, I am assuming the pods in daemon set are identical

**Comment by otterley** [comment]
On EC2 Nitro instances, the number of attachable EBS volumes is not a fixed value that can be calculated and supplied when the CSI driver is launched, regardless of instance type, that is correct throughout the lifetime of the node.  Because the formula is _MaxEbsAttachableVolumes = MaxAttachments - AttachedENIs_, where _MaxAttachments_ depends on the EC2 instance type, the value must be recalculated each time a new ENI is attached or detached from the instance.

**Comment by leakingtapan** [comment]
Agree that this proposal is very suboptimal

**Comment by gnufied** [comment]
> Agree that this proposal is very suboptimal

Designing a generic mechanism to calculate number of attachments as shared resource is kind of a tricky problem. There are various ways overrides can be configured such as pre-allocating a number for ENIs or percentage of attachments(and subtracting it from max). It would be nice if AWS had a API for determining `MaxEbsAttachableVolumes` an instance supports, so as we can remove the hacks in this driver and in-tree.

**Comment by rfranzke** [comment]
Given the fact that prior CSI there was no solution that allowed overriding the volume limits per node (https://v1-18.docs.kubernetes.io/docs/concepts/storage/storage-limits/#custom-limits) but only globally in the whole cluster, and given the above discussed complexities: Would it make sense to proceed with the suggested CLI flag for now until a more sophisticated solution can be implemented? This way, at least the existing clusters that were levering the `KUBE_MAX_PD_VOLS` method can continue to work as before when they migrate to CSI. It wouldn't make things worse. WDYT?

**Comment by gnufied** [comment]
This is fixed https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/522
