### ISSUE TITLE
[Design][K8S] EBS Tagger Sidecar

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#351]
**Is your feature request related to a problem? Please describe.**
This is Kubernetes specific feature. Following are requirements:
* User needs to provide arbitrary tag for created EBS volume through PVC annotation. 
* Driver needs to tag created EBS volume with a list of built-in Kubernetes tags as follow:

Key | Value
-- | --
Name | kubernetes-dynamic-pvc-e814cb42-57c3-11e9-8335-0ef9bfaa78f6
kubernetes.io/cluster/1-12-driver | owned
kubernetes.io/created-for/pv/name | pvc-e814cb42-57c3-11e9-8335-0ef9bfaa78f6
kubernetes.io/created-for/pvc/name | ebs-claim
kubernetes.io/created-for/pvc/namespace | default

This design provides an alternative solution for #180. And it provides an alternative way to apply static tags.

**Describe the solution you'd like in detail**
We will create a side car container, ebs-tagger, running along side EBS CSI controller service. It will be a k8s operator that watches for PV creation. When is a new PV is created and iff it is a EBS CSI pv, the operator will:
* apply built-in k8s 
* read PVC annotation `ebs.csi.aws.com/extra-tags` and apply tags

**Describe alternatives you've considered**
Extending storage class as described in #180

**Additional context**
Related similar sub problem: #333

**Comment by frittentheke** [comment]
@leakingtapan thank you for looking into this issue!

This tagger sidecar approach unfortunately has a major drawback: There is not enforced tagging right when the volume is created.

If you look at my comment regarding best-practices on doing IAM policies https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/180#issuecomment-462024613 or also https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/180#issuecomment-465627467

It's just a strict requirement to have the volume tagged upon their initial creation and not "dynamically" later. In "my" case I want to restrict / filter the EBS driver to only be able to touch and handle its own volumes - the tag works like a tenant in this case.
The other comments in this thread a either about being restricted in the first place to have to use certain tags to even being allowed to create volumes or to create billing based on those tags. 

Having forced thags for EVERY volume the EBS driver creates / handles is just what I would want to configure to isolate EBS volumes in that AWS account that belong to others.

**Comment by sstarcher** [comment]
I just tossed this controller together.  It does not work specifically for the csi, but for the built-in kubernetes ebs provider.  It fetches the labels from the pv and pvc and applies them to the AWS EBS volume.

https://github.com/sstarcher/kube-ebs-tagger

**Comment by leakingtapan** [comment]
@frittentheke 

> This tagger sidecar approach unfortunately has a major drawback: There is no enforced tagging right when the volume is created.

Thx for your input. The major drawback of current CSI spec is that there is no way for the driver to know what's the tag value it's suppose to use during volume creation (except for storageclass parameter, which has other problems on ease of use). So we either stuck on this feature or build a sidecar as post volume creation tag.

**Comment by fentas** [comment]
Is there a way to tag ebs volumes?
