### ISSUE TITLE
AWS volume type 'standard' missing

### ISSUE THREAD

**Issue by MeikelLP** [kubernetes-sigs/aws-ebs-csi-driver#365]
**What happened?**

In our Rancher fork we wanted to add the volume type `standard` as it is a valid volume type [in AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html) (see "Previous Generation Volume Types").

In Rancher we get the message: 
```
Failed to provision volume with StorageClass "ebs-magnetic-purge": invalid AWS VolumeType "standard"
```

**What you expected to happen?**

Standard is accepted as volume type.

[The array/enum](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/cloud/cloud.go#L40) is missing the member `standard`

**Environment**
- Rancher: 2.2.8
- Kubernetes: 1.14.6

**Comment by leakingtapan** [comment]
Although being undocumented on K8S side: https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs, it is supported by EBS as the link you pasted. Will take a look into this.
