### ISSUE TITLE
Can't expand the pvc create by aws-ebs-csi-driver!

### ISSUE THREAD

**Issue by RottenLeaf24** [kubernetes-sigs/aws-ebs-csi-driver#366]
/kind bug

**What happened?**
I want to expand the pvc,so I edit the pvc to more large size like the example of volume resizing.But nothing happened.
then, I used the describe command check the pvc,find the warning message like this:

```
Events:
  Type     Reason                Age                From                                                                       Message
  ----     ------                ----               ----                                                                       -------
  Normal   Provisioning          41s                ebs.csi.aws.com_ebs-csi-controller-0_bec83ef1-d395-11e9-ae93-1a14128a7df1  External provisioner is provisioning volume for claim "default/test"
  Normal   ExternalProvisioning  37s (x2 over 41s)  persistentvolume-controller                                                waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
  Warning  ExternalExpanding     5s (x2 over 20s)   volume_expand                                                              Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
```
It looks like the ebs-csi-controller have no csi-resizer,then I read the file of controller.yaml for deploy aws-ebs-csi-driver,also can't find the csi-resizer container.
This is a bug,or the aws-ebs-csi-driver not support expand size yet?

**What you expected to happen?**
I want the pvc size change to correct size,what is by my specified.

**How to reproduce it (as minimally and precisely as possible)?**
You just need to create a pvc by aws-ebs-csi-driver and edit the size to a large one,then you can get the warning message.The pvc size also don't change.

**Anything else we need to know?**:
deploy the  aws-ebs-csi-driver by the command:
kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"

The file of create storageclass:
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  type: gp2
  fsType: ext4

**Environment**
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Driver version:
amazon/aws-ebs-csi-driver:latest

**Comment by leakingtapan** [comment]
The stable overlay doesn't come with external resizer. If you want to test out the resizing feature, try the overlay/alpha:

```
kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csidriver/deploy/kubernetes/overlays/alpha/?ref=master"
```

**Comment by leakingtapan** [comment]
Updating the doc to reduce confusion: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/367

**Comment by RottenLeaf24** [comment]
> Updating the doc to reduce confusion: #367

**Comment by RottenLeaf24** [comment]
@leakingtapan 
Thank you very much for your kind reply.I will try that new feature.
