### ISSUE TITLE
Snapshot file out.txt empty following Volume snapshot example

### ISSUE THREAD

**Issue by fiftoine** [kubernetes-sigs/aws-ebs-csi-driver#376]
/kind bug

**What happened?**
I followed the [snapshot example](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/snapshot) and checked that a snapshot is created from the AWS console. When I do the restore step, and check the content of the `out.txt` file, it starts empty and the app pod appends new dates.

**What you expected to happen?**
The `out.txt` file should contain the previous logged dates.

**How to reproduce it (as minimally and precisely as possible)?**
Running a K8S 1.14 cluster on AWS (deployed with kops) following all requirements (feature-gates and installation of the driver)
Deploy the app, wait for dates to be appended to `out.txt`, deploy the volumesnapshot.
To check the content of the snapshot, from AWS console, I created a volume from the snapshot and mounted it into a EC2 instance. The file `out.txt` is there but is empty.

**Anything else we need to know?**:
I tried to update the app pod to log only once the date (and with `restartPolicy: never`)
```
args: ["-c", "echo $(date -u) >> /data/out.txt"]
```
 and in that case, the file is kept with its data. I could check from mounting a volume from the snapshot and also through the snapshot-restore step.
So it seems the issue occurs when snapshotting the volume while some writings are still done.

**Environment**
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version:
alpha

**Comment by leakingtapan** [comment]
@fiftoine how long have you waited before taking snapshot? If the file was just written when the snapshot was taken, the data might be still cached in kernel and NOT flushed into disk yet. I am actually able to reproduce this if the snapshot is taken too soon. To solve your problem, you can either run `kubectl exec -ti app -- sync` before taking the snapshot. Or you can wait some longer time for the data to be flushed by the kernel.

**Comment by leakingtapan** [comment]
Feel free to reopen the issue if this still happen to you with the above solution.

/close
