### ISSUE TITLE
Support create pvc in other regions

### ISSUE THREAD

**Issue by RottenLeaf24** [kubernetes-sigs/aws-ebs-csi-driver#378]
/kind feature

**What happened?**
When I create pvc use aws-ebs-csi-driver,if the pvc in Tokyo region always get the error like:
```
could not create volume in EC2: InvalidZone.NotFound: The zone 'ap-northeast-1c' does not exist.
or
could not create volume in EC2: InvalidZone.NotFound: The zone 'ap-northeast-1a' does not exist.
```
The reason for this phenomenon is cause by multiple region.
After multiple tests, I can confirm the aws-ebs-csi-driver can only create pvc in the same region with controller.When the region of pvc and controller is different,the ebs-csi-node can report it's own zone to controller,but the controller can't recognize the zone in other region.Then we get the error:```The zone does not exist```.

**What you expected to happen?**
Can create cross-regional pvc in kubernetes cluster on aws machine by aws-ebs-csi-driver.
**How to reproduce it (as minimally and precisely as possible)?**
Create a cross-regional kubernetes cluster,and create a pvc in a different region with ebs-csi-controller pod.
**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Driver version:
latest alpha

**Comment by leakingtapan** [comment]
Yep. The current controller service assumes that PVC's are in the same region as the controller. This is definitely something I can improve. I would like to assign this as a feature. Please up vote if this feature is important to you.

/kind feature

**Comment by RottenLeaf24** [comment]
That's wonderful,this feature will bring us great convenience.And I think this feature will also bring a lot of benefits to other users who have cross-regional kubernetes cluster on aws.
