### ISSUE TITLE
Stable installation instructions point to the private repository

### ISSUE THREAD

**Issue by zerkms** [kubernetes-sigs/aws-ebs-csi-driver#384]
/kind bug

**What happened?**
The current stable deployment instructions refer to the kustomize config that tries to pull from the private AWS ECR repository
```
kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
```
eg `602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-ebs-csi-driver`

**What you expected to happen?**
It should not

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by leakingtapan** [comment]
That's the official public repo hosted by EKS where ppl can use to pull images. Do you have any issue on using the image url?

**Comment by zerkms** [comment]
```
➜ docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-ebs-csi-driver:v0.4.0
Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/eks/aws-ebs-csi-driver/manifests/v0.4.0: no basic auth credentials
```

**Comment by leakingtapan** [comment]
try 
```
eval $(aws ecr get-login --region us-west-2 --no-include-email --registry-ids 602401143452)
docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-ebs-csi-driver:v0.4.0
```

**Comment by Quarky9** [comment]
I added the basic ECR IAM permission the nodes and that seemed to have fixed it.
Using containerd not docker btw.

**Comment by zerkms** [comment]
@Quarky9 it did not change anything

```
➜ docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-ebs-csi-driver:v0.4.0
Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/eks/aws-ebs-csi-driver/manifests/v0.4.0: no basic auth credentials
```

You must have at least any authentication

@leakingtapan where would one run it given the readme tells (not to mean that aws might be not installed on the kubernetes cluster, or you may have no access to the cluster command line, or you may not have AWS account at all):

```
kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
```

**Comment by leakingtapan** [comment]
```
eval $(aws ecr get-login --region us-west-2 --no-include-email --registry-ids 602401143452)
docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-ebs-csi-driver:v0.4.0
``` 
The above is meant to prove that the images are public accessible as long as you have a IAM identity. 

Kubelet has built-in credential provider that does ecr login automatically for you as long as worker node has proper IAM permission to access ECR.

**Comment by zerkms** [comment]
Right, I see now, thanks.
