### ISSUE TITLE
CSI Resizer Crashes on v0.4.0

### ISSUE THREAD

**Issue by jammerful** [kubernetes-sigs/aws-ebs-csi-driver#387]
/kind bug

**What happened?**
The csi-resizer pod crashes:
```logs
I1007 21:05:24.186157       1 main.go:61] Version : v0.2.0-0-g07a4fd9
I1007 21:05:24.187262       1 connection.go:151] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
I1007 21:05:24.189513       1 common.go:111] Probing CSI driver for readiness
I1007 21:05:24.189633       1 connection.go:180] GRPC call: /csi.v1.Identity/Probe
I1007 21:05:24.189638       1 connection.go:181] GRPC request: {}
I1007 21:05:24.192865       1 connection.go:183] GRPC response: {}
I1007 21:05:24.194470       1 connection.go:184] GRPC error: <nil>
I1007 21:05:24.194521       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I1007 21:05:24.194527       1 connection.go:181] GRPC request: {}
I1007 21:05:24.195632       1 connection.go:183] GRPC response: {"name":"ebs.csi.aws.com","vendor_version":"0.3.0"}
I1007 21:05:24.196010       1 connection.go:184] GRPC error: <nil>
I1007 21:05:24.196055       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I1007 21:05:24.196064       1 connection.go:181] GRPC request: {}
I1007 21:05:24.196846       1 connection.go:183] GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}},{"Type":{"Service":{"type":2}}}]}
I1007 21:05:24.197922       1 connection.go:184] GRPC error: <nil>
I1007 21:05:24.197936       1 connection.go:180] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I1007 21:05:24.197941       1 connection.go:181] GRPC request: {}
I1007 21:05:24.198674       1 connection.go:183] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":5}}}]}
I1007 21:05:24.200700       1 connection.go:184] GRPC error: <nil>
I1007 21:05:24.200766       1 connection.go:180] GRPC call: /csi.v1.Node/NodeGetCapabilities
I1007 21:05:24.200776       1 connection.go:181] GRPC request: {}
I1007 21:05:24.202638       1 connection.go:183] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]}
I1007 21:05:24.203897       1 connection.go:184] GRPC error: <nil>
F1007 21:05:24.203913       1 main.go:72] CSI driver neither supports controller resize nor node resize
```

**What you expected to happen?**
The csi-resizer to work.

**How to reproduce it (as minimally and precisely as possible)?**
* Install via helm:
```
helm install --name aws-ebs-csi-driver \
    --set enableVolumeScheduling=true \
    --set enableVolumeResizing=true \
    --set enableVolumeSnapshot=true \
    https://github.com/kubernetes-sigs/aws-ebs-csi-driver/releases/download/v0.4.0/helm-chart.tgz
```
* See the `csi-resizer` container crash the `ebs-csi-controller-0` pod

**Environment**
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9", GitCommit:"3e4f6a92de5f259ef313ad876bb008897f6a98f0", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.11.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version: v0.4.0

Is this because the `ExpandCSIVolumes` feature gate is by default no enabled on 1.14 as it is still Alpha?

**Comment by jammerful** [comment]
@leakingtapan A tangential question, are you going to continue to support the helm install or just kustomize?

**Comment by jammerful** [comment]
Figured out this is because I didn't enable a feature gate on my EKS cluster, also from what I can tell I'm not able to set feature gates on the kube-apiserver for EKS. 
@leakingtapan does this sound right? Thanks.

**Comment by leakingtapan** [comment]
> Figured out this is because I didn't enable a feature gate on my EKS cluster, also from what I can tell I'm not able to set feature gates on the kube-apiserver for EKS.
> @leakingtapan does this sound right? Thanks.

Yep, EKS doesn't enable alpha feature gates. That's why resize and snapshot are only in alpha overlay.

**Comment by leakingtapan** [comment]
> @leakingtapan A tangential question, are you going to continue to support the helm install or just kustomize?

I will keep supporting both :)

**Comment by jammerful** [comment]
Thanks!

/close

**Comment by jammerful** [comment]
@leakingtapan I had a question and was hoping you could help me out. I need to use the snapshot feature right now in EKS, and found the [old external storage repository](https://github.com/kubernetes-incubator/external-storage/tree/master/snapshot). The external storage repo has the disclaimer that the code is pre-alpha.

Empirically, have you had to make substantial changes to the code to get it to the alpha state?

**Comment by leakingtapan** [comment]
> I need to use the snapshot feature right now in EKS, and found the old external storage repository

Don't think this is possible if you want to restore a volume from snapshot since `VolumeSnapshotDataSource` feature gate needs to be enabled on apiserver. However, if you just want to create snapshot (without restore from data source), this might work, but I haven't tested.

> Empirically, have you had to make substantial changes to the code to get it to the alpha state?

The EBS CSI snapshot feature was implemented independent of external-storage snapshot, the implementation is based off CSI spec per snapshot requirements, if that's what you are asking.

**Comment by jammerful** [comment]
> > I need to use the snapshot feature right now in EKS, and found the old external storage repository
> 
> Don't think this is possible if you want to restore a volume from snapshot since `VolumeSnapshotDataSource` feature gate needs to be enabled on apiserver. However, if you just want to create snapshot (without restore from data source), this might work, but I haven't tested.

It just uses a set of CRDs and a controller and is not based on the CSI at all. It seems to work fine from my testing.

> 
> > Empirically, have you had to make substantial changes to the code to get it to the alpha state?
> 
> The EBS CSI snapshot feature was implemented independent of external-storage snapshot, the implementation is based off CSI spec per snapshot requirements, if that's what you are asking.

Thanks, I had just assumed that it was based off the existing work, in that case I'll find out in a few weeks.
