### ISSUE TITLE
Handle DescribeInstances eventual consistency

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#389]
**Is your feature request related to a problem? Please describe.**
See https://github.com/kubernetes/kubernetes/issues/77389 for more details for the specific race condition.

**Describe the solution you'd like in detail**
There is a potential [fix](https://github.com/kubernetes/kubernetes/pull/83567) upstream for in-tree EBS CSI plugin. We should do the same for EBS CSI.

**Comment by msau42** [comment]
Is there a plan to port https://github.com/kubernetes/kubernetes/pull/83567 to the CSI driver, or to do it as part of https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/393?

**Comment by leakingtapan** [comment]
I would like to do it separately instead of part of #393

**Comment by Jiawei0227** [comment]
Hey, I am wondering is there any stress tests that been done on NodePublishVolume and NodeUnpublishVolume? Is this bug even reproducible on the csi driver?
