### ISSUE TITLE
Unify cloud provider between legacy and CSI driver

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/aws-ebs-csi-driver#393]
[Kubernetes cloud provider for AWS](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/legacy-cloud-providers/aws) is still being actively maintained and bugs are fixed there. It could be worth importing it instead of using a fork in this repo. The code there has been well tested in real world and it would ensure that migration to CSI is as smooth as possible.

On the other hand, the code is old and has very little unit tests so refactoring is hard.

**Comment by wongma7** [comment]
100% agree. For example, https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/389 refers to a fix in legacy cloudprovider. If we use legacy, we could get the fixes for free instead of having to backport every improvement to our "mini" cloudprovider fork in pkg/cloud

**Comment by leakingtapan** [comment]
I like the idea of unifying the two cloud provider between legacy cloud provider and the once being implemented in this CSI driver. I would like more discussion on which one to pick before we can go with importing legacy cloud provider. Several questions:
1. I'm assuming you are proposing to use [legacy provider for AWS](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/legacy-cloud-providers/aws) to replace the [cloud.go](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/cloud/cloud.go) in this package, right?

2. Both provider defines the interface in slight different way, do we know what are the deltas? Also the cloud.go in the package implements extra features such as snapshot. I don't think it will be a drop in replacement.

3. What's your long term view of the legacy provider? My understanding is that it will be moved to CCM for non EBS related code and EBS related code will be moved into this project. 

I would propose to change this issue topic to **Unify cloud provider between legacy and CSI driver**

**Comment by jsafrane** [comment]
> I'm assuming you are proposing to use legacy provider for AWS to replace the cloud.go in this package, right?

Yes

> Both provider defines the interface in slight different way, do we know what are the deltas? Also the cloud.go in the package implements extra features such as snapshot. I don't think it will be a drop in replacement.

I don't disagree...

> What's your long term view of the legacy provider? My understanding is that it will be moved to CCM for non EBS related code and EBS related code will be moved into this project.

Yes, probably.

> Given above, I would propose to change this issue topic to Unify cloud provider between legacy and CSI driver

Ack, all I want is to pull the fixes we do in the legacy cloud provider also into the CSI driver. The legacy provider has been tested really lot in production.

**Comment by wongma7** [comment]
/reopen

/lifecycle frozen

this is imporant otherwise the csi driver will just suffer all the same bugs the intree driver ran into over the years

**Comment by wongma7** [comment]
closing, we have mostly copy/pasted the important parts from cloudprovider-aws into pkg/cloud , so we kind of have achieved goal of unifying, just in the opposite direction. cloud-provider-aws is working on v2 api, someday we might depend on it but it's probably easier to treat this repo's pkg/cloud as source of truth.
