### ISSUE TITLE
Create container registry account 

### ISSUE THREAD

**Issue by bertinatto** [kubernetes-sigs/aws-ebs-csi-driver#41]
We need to host the driver in a container registry. Currently it's being stored in my personal account [1], but it'd be better to store it in its own account.

[1] https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/Makefile#L1

**Comment by d-nishi** [comment]
Lets place it in docker hub for now. I could create a common place for all sig-aws subproject containers

**Comment by leakingtapan** [comment]
im talking to our internal team to put it under: https://hub.docker.com/u/amazon/

**Comment by leakingtapan** [comment]
The account is created: https://hub.docker.com/r/amazon/aws-ebs-csi-driver/

/close
