### ISSUE TITLE
e2e/unit/integration flake: pull-aws-ebs-csi-driver-e2e-single-az 

### ISSUE THREAD

**Issue by jnaulty** [kubernetes-sigs/aws-ebs-csi-driver#415]
/kind bug

**What happened?**
e2e test failure from a non-related change (change was in a markdown file)
With error:
```
[ebs-csi-e2e] [single-az] Dynamic Provisioning
/home/prow/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/e2e/dynamic_provisioning.go:40
  should create a volume on demand with volume type "sc1" and fs type "ext2" [It]
  /home/prow/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/e2e/dynamic_provisioning.go:59
  Expected error:
      
      <*errors.errorString | 0xc0007fde80>: {
          s: "Gave up after waiting 15m0s for pod \"ebs-volume-tester-4zmgm\" to be \"success or failure\"",
      }
```

**What you expected to happen?**
When changing documentation, all tests should pass.

**How to reproduce it (as minimally and precisely as possible)?**
Run `/test pull-aws-ebs-csi-driver-e2e-single-az`

**Anything else we need to know?**:

Useful links:
- 1st failure for #414  [link](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-ebs-csi-driver/414/pull-aws-ebs-csi-driver-e2e-single-az/1197803352977575939)
- 2nd failure for #414  [link](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-ebs-csi-driver/414/pull-aws-ebs-csi-driver-e2e-single-az/1197803352977575939)
- all failures for test suite [link](https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-aws-ebs-csi-driver-e2e-single-az)

**Environment**
- Kubernetes version (use `kubectl version`):
`2019/11/22 09:07:10 Downloading KOPS from https://github.com/kubernetes/kops/releases/download/1.14.0-alpha.1/kops-linux-amd64 to /tmp/tester-e2e-test/kops`

- Driver version:
55f84a5f1683de145498703ce302da347b2d519f

**Comment by leakingtapan** [comment]
Thx for reporting! the test cases with `sc1` does have flaky issue. We need to look into this. I suspect one issue could be due to sc1's minimum size is 500GiB which cause it takes long time to format the filesystem and causes timeout.

**Comment by leakingtapan** [comment]
sample failure: https://prow.k8s.io/log?id=1234190954236219395&job=pull-aws-ebs-csi-driver-e2e-single-az

**Comment by leakingtapan** [comment]
As the minimum size for sc1 volume is 500GiB, is could be taking too much time on formatting the filesystem
