### ISSUE TITLE
Driver name can't be changed. 

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes-sigs/aws-ebs-csi-driver#428]
**Is your feature request related to a problem? Please describe.**
I need to run multiple CSI drivers on the same Kubernetes cluster because the worker nodes in my cluster are provisioned under user account (which is different from the account which provisions master node ). So I can't provision new volume using the same CSI driver due to access issues.  

**Describe the solution you'd like in detail**
If the driver name can be configured. Then I can run one CSI driver instance for each user.

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/94107a3c633141b7834d022c60c76af5e64eec77/pkg/driver/driver.go#L31

**Comment by leakingtapan** [comment]
@MartinForReal the CSI driver name needs to be unique and stable, it's not supposed to be configured dynamically. And CSI driver controller service deployment is supposed to be one per cluster.

For you use case, is it possible for you to assign the CSI driver a role that can assume role in other account?

**Comment by MartinForReal** [comment]
@leakingtapan This might be reasonable but I can hardly agree. 

> controller service deployment is supposed to be one per cluster.

This might not be true because if I use different storage implementation on the same cluster. There will be more than one CSI controller on the same cluster available. 

And the driver identification is stable after the controller daemon is started. Here we treat each controller as a unique storage provider even though these controllers are using the same implementation. And CSI has support for this scenario.

And we can set a default value to support migration.

**Comment by leakingtapan** [comment]
Different storage implementation comes with different csi drivers. You can see that all aws csi driver has different driver name, efs.csi.aws.com, ebs.csi.aws.com, which enables you to deploy them all in the same cluster. 

> And CSI has support for this scenario.

Where do u see this is documented?

**Comment by MartinForReal** [comment]
@leakingtapan As you said in the last comment. We can have multiple instances of the driver if we can change the name. such as ebs.csi.aws.com.us-east1, ebs.csi.aws.com.cn-west2, ebs.csi.aws.com.cn-west-user1
