### ISSUE TITLE
multi user support

### ISSUE THREAD

**Issue by phantooom** [kubernetes-sigs/aws-ebs-csi-driver#429]
out kubernetes node distributed in multi Amazon account.  the network communicate use vpc peering + aws cni plugin. 

these days,we need a Dynamic Provisioning  volume plugin . we found this plugin not support currently. is this feature in your road map? or any suggestion?

**Comment by leakingtapan** [comment]
@phantooom thx for reporting the issue. The driver only supports dynamic provisioning within the same account. To clarify, are you asking for dynamic provisioning EBS volume in different aws accounts?
