### ISSUE TITLE
move help chart to https://github.com/aws/eks-charts

### ISSUE THREAD

**Issue by fmedery** [kubernetes-sigs/aws-ebs-csi-driver#443]
**Is your feature request related to a problem?/Why is this needed**

/feature

**Describe the solution you'd like in detail**
More and more of our helm charts are hosted on https://github.com/aws/eks-charts

It will be easier for the customer to list all the AWS helm charts that way

**Describe alternatives you've considered**
none

**Additional context**

**Comment by leakingtapan** [comment]
I would prefer `cp` instead of `mv` as the chart is not eks only

**Comment by jshrack-ssi** [comment]
Could this please get done? Without sourcing this from an actual Helm repo it makes automation quite challenging.

**Comment by leakingtapan** [comment]
@jshrack-ssi please create an issue in the aws/eks-chart repo for hosting the eks specific chart in the repo. 

/close
