### ISSUE TITLE
Add ability to change kubelet default path

### ISSUE THREAD

**Issue by Amos-85** [kubernetes-sigs/aws-ebs-csi-driver#448]
There is no option in the helm chart values file to define the kubelet mountPath

it would be nice if we can define it if some cluster has some kubelet path other then the default one which is /var/lib/kubelet

**Comment by leakingtapan** [comment]
Hey @Amos-85 thx for reporting the issue. Could you add more details on why "some cluster has some kubelet path other then the default one"?

**Comment by Amos-85** [comment]
Hi @leakingtapan 
**Case 1**
- [RKE](https://rancher.com/docs/rke/latest/en/) use this path` /opt/rke/var/lib/kubelet` as default.

**Case 2**
- Sometimes you don't want to deploy k8s components under root paths cause of small root fs.

**Comment by leakingtapan** [comment]
It is possible now if you update the path yourself here: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/base/node.yaml#L38 if this is the path being concerned?

**Comment by Amos-85** [comment]
@leakingtapan, the file you mentioned refer to kustimize, not for the helm chart.

the `/var/lib/kubelet` is not template in the helm chart:
[as-daemonset-reference](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/aws-ebs-csi-driver/templates/daemonset.yaml#L47)

**Comment by leakingtapan** [comment]
Yep. the above is a workaround while the path is not configurable. You could either manually edit the helm or kustomize file.

But free feel to submit a PR to make helm configubale, I will review the change

**Comment by wongma7** [comment]
/reopen
/help-wanted
/lifecycle frozen

more configuration options  welcome.
