### ISSUE TITLE
Clarify why kubernetes tag prefix is disallowed

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/aws-ebs-csi-driver#450]
/kind bug

**What happened?**
I'm wondering why the kubernetes.io tag prefix is [restricted](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/2c0ad7b0e7840d3dbc8deb28161c665794892ae8/pkg/driver/validation.go#L53). Assuming that the aws in-tree cloud provider is removed from K8s entirely in the future, there should be nothing in K8s that is using this tag prefix on EBS volumes right?

**Comment by leakingtapan** [comment]
We are reserving this for the driver itself. Hence, it is disallowed to be used by end user. Hope this make sense to you. 

/cc @jieyu

**Comment by msau42** [comment]
It's likely that in the future the deployer of the CSI driver is a Kubernetes distribution itself (especially once intree is turned off). In that case I think it is reasonable for the K8s distribution to use the prefix.

There's also the theoretical principle that a CSI driver should be k8s agnostic.

**Comment by leakingtapan** [comment]
Makes sense. What's the upstreams recommendation for setting k8s related tags in CSI drivers? The EBS CSI driver just supports setting static tags now. And that is what's being validated to disallow kubernetes.io tag. I also see the currently populated [in-tree tags](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/351#issue-483658726) are all dynamical tag values. We probably could loose the constraint to allow kubernetes.io tag for static tags, but it doesn't help too much for current situation in order to be compatible with in-tree implementation on volume tag wise.

**Comment by msau42** [comment]
Sorry for the delay. https://github.com/kubernetes-csi/external-provisioner/pull/399 will make it possible to be compatible with the in-tree tagging with PVC name and namespace, but it does require the CSI driver to explicitly act on these fields, so does make it not CO-agnostic.

My use case for the static tag is to use "kubernetes.io/cluster" prefix, which despite the prefix, is not a first-class concept in K8s (it's only defined in the aws cloud provider).

**Comment by msau42** [comment]
@leakingtapan do you see another way the ebs-driver can get the k8s cluster name to set the "kubernetes.io/cluster" tag?

**Comment by leakingtapan** [comment]
Assuming the controller service is running inside ec2, I’m thinking of reading the cluster name from ec2 instance tag

**Comment by msau42** [comment]
That assumes the deployment mechanism will tag the ec2 instances where the driver is running on, and that the driver is running in the same cluster. It also makes this particular tag handling special cased in the driver, which I guess will already need to be done for the other kubernetes.io tags.

**Comment by msau42** [comment]
A more flexible option could be to: 1) continue to make this special cased, but make the behavior more explicit with an arg 2) don't special case it, and allow it to be passed in via the generic tags

**Comment by msau42** [comment]
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/529 should address my use case of setting kubernetes.io/cluster

/close
