### ISSUE TITLE
Cluster leak during e2e test

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#454]
/kind bug

**What happened?**
```
[32m• [SLOW TEST:153.241 seconds][0m
[ebs-csi-e2e] [single-az] Dynamic Provisioning
[90m/home/prow/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/e2e/dynamic_provisioning.go:40[0m
  should create a volume on demand with volume type "st1" and fs type "ext2"
  [90m/home/prow/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/e2e/dynamic_provisioning.go:59[0m
[90m------------------------------[0m
{"component":"entrypoint","file":"prow/entrypoint/run.go:168","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Entrypoint received interrupt: terminated","time":"2020-02-25T07:00:02Z"}
```
This happens when a new PR is submitted while the exiting e2e test is still on going

**Comment by wongma7** [comment]
/lifecycle frozen

- it would be nice if the tester could catch interrupt and clean up
- even with an interrupt catch, we still need a periodic cleaner in the test account. Interrupt catcher is not foolproof, it could get killed for any reason in the middle of clean up.

**Comment by ConnorJC3** [comment]
/close

This has not been observed in significant time, and nowadays the test-infra AWS account has a cleaner run on it occasionally.
