### ISSUE TITLE
Helm chart image registries different to kustomize manifests

### ISSUE THREAD

**Issue by groodt** [kubernetes-sigs/aws-ebs-csi-driver#469]
/kind bug

**What happened?**

The Helm chart is referencing images in Dockerhub and quay.io.

The kustomize manifests appear to be referencing images in:
602401143452.dkr.ecr.us-west-2.amazonaws.com/eks 

**What you expected to happen?**
They should be the same presumably?

**How to reproduce it (as minimally and precisely as possible)?**
Compare the image versions in the Helm chart with the output of
`kubectl kustomize "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"`

**Anything else we need to know?**:
I'm happy to submit a fix if necessary.

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by krmichel** [comment]
I already have a [PR](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/475) to keep the helm chart and the manifest in sync.  If @leakingtapan or someone else can tell me which set of images should be used I can update them, if needed, on that PR to fix this.

**Comment by leakingtapan** [comment]
Let's keep the combination of quay.io (for side car image) and dockerhub (for driver itself). Since ecr is lacking on latest images.
@krmichel
