### ISSUE TITLE
Add Kubernetes e2e tests of the driver

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/aws-ebs-csi-driver#470]
Kubernetes allows to run its e2e tests against a CSI driver: https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external

It will go through all Kubernetes features - dynamic provisioning, topology, subpath, volume expansion, snapshots, cloning... It allows a CSI driver to select features to tests (e.g. no cloning for AWS EBS).

What is necessary:

1. Kubernetes cluster.
2. Upstream tests, see the link above. Basically run `ginkgo -focus=...` in a specific kubernetes/kubernetes dir.
3. Test manifest describing what to tests (see readme linked above, simple yaml file).

From the other tests in this repo, 1. and 3. look easy, however, getting upstream tests at point 2. may be complicated. Is `tester/migration-test-config.yaml` something similar?

/feature

**Comment by leakingtapan** [comment]
Are you trying to test CSI migration with the k/k external test suites or test EBS CSI with the external test? Either way the tester config file [single-az-config.yaml](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/tester/single-az-config.yaml), tells the tester what cluster to spin up and what test to run.

If you want to download k/k source and compile it, you could put it inside the `test` block.
