### ISSUE TITLE
Imagepullbackoff because basic auth credentials

### ISSUE THREAD

**Issue by T00mm** [kubernetes-sigs/aws-ebs-csi-driver#477]
/kind bug

**What happened?**
Following the guide after this step

`kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"`

The images should be pulled in but it seems that the ECR can't be accessed. Other images do not have this problem.

`  Normal   Scheduled  23m                   default-scheduler                                     Successfully assigned kube-system/ebs-csi-node-spdzt to ip-172-31-70-169.eu-west-1.compute.internal
  Normal   BackOff    23m                   kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Back-off pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-liveness-probe:v1.1.0"
  Warning  Failed     23m                   kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Error: ImagePullBackOff
  Normal   BackOff    23m                   kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Back-off pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar:v1.1.0"
  Warning  Failed     23m                   kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Error: ImagePullBackOff
  Warning  Failed     23m                   kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Error: ImagePullBackOff
  Normal   Pulling    23m (x2 over 23m)     kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-ebs-csi-driver:v0.4.0"
  Warning  Failed     23m (x2 over 23m)     kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Error: ErrImagePull
  Normal   Pulling    23m (x2 over 23m)     kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-liveness-probe:v1.1.0"
  Normal   Pulling    23m (x2 over 23m)     kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar:v1.1.0"
  Warning  Failed     23m (x2 over 23m)     kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Error: ErrImagePull
  Warning  Failed     23m (x2 over 23m)     kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-ebs-csi-driver:v0.4.0": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/eks/aws-ebs-csi-driver/manifests/v0.4.0: no basic auth credentials
  Warning  Failed     23m (x2 over 23m)     kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar:v1.1.0": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/eks/csi-node-driver-registrar/manifests/v1.1.0: no basic auth credentials
  Warning  Failed     23m (x2 over 23m)     kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Error: ErrImagePull
  Warning  Failed     23m (x2 over 23m)     kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-liveness-probe:v1.1.0": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/eks/csi-liveness-probe/manifests/v1.1.0: no basic auth credentials
  Normal   BackOff    3m19s (x84 over 23m)  kubelet, ip-172-31-70-169.eu-west-1.compute.internal  Back-off pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-ebs-csi-driver:v0.4.0"`

**What you expected to happen?**

Images can be pulled without basic auth credentials

**How to reproduce it (as minimally and precisely as possible)?**

We are using EKS 1.14

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): Client Version: v1.17.3
- Driver version: master

**Comment by inetika** [comment]
Same issue but with vanilla kubernetes run on EC2 (1.14.8) with `AmazonEC2ContainerRegistryFullAccess` policy attached for each node.

**Comment by inetika** [comment]
Adding `--cloud-provider=aws` and `kubernetes.io/cluster/<cluster-name>` tags to each instance solved it.

**Comment by T00mm** [comment]
@inetika 
Where exactly did you add the --cloud-provider=aws? Or did you install through helm?

**Comment by T00mm** [comment]
Got it working with Helm V3 with the following command

`helm install aws-ebs-csi-driver \
    --set enableVolumeScheduling=true \
    --set enableVolumeResizing=true \
    --set enableVolumeSnapshot=true \
    --set cloud-provider=aws \
    https://github.com/kubernetes-sigs/aws-ebs-csi-driver/releases/download/v0.5.0/helm-chart.tgz`

**Comment by inetika** [comment]
@T00mm to kube api, controller and kubelets as described here: https://docs.google.com/document/d/17d4qinC_HnIwrK0GHnRlD1FKkTNdN__VO4TH9-EzbIY/edit

**Comment by dghubble** [comment]
I also have the expectation that the image be truly publicly available. [#384](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/384) describes the image as public, but hosting on ECR which requires Kubelets enable an optional in-tree cloud provider path and have IAM roles isn't the same as being public.

What about publishing or mirroring to a public image registry (quay, gcr.io)? Allow those images to be audited and inspected externally. Or pulled from clusters that intentionally do not enable cloud provider.

**Comment by dghubble** [comment]
For anyone else, ended up using https://hub.docker.com/r/amazon/aws-ebs-csi-driver instead of the ECR image.
