### ISSUE TITLE
Fargate node cannot run ebs-csi-controller

### ISSUE THREAD

**Issue by literalice** [kubernetes-sigs/aws-ebs-csi-driver#492]
/kind bug

**What happened?**

When the `ebs-csi-controller` pods are bound to fargate nodes, the pods stay in `CrashLoopBackOff` status.

**What you expected to happen?**

The `ebs-csi-controller` pods should successfully run.

**How to reproduce it (as minimally and precisely as possible)?**

1. Creates a fargate profile for `kube-system` namespace.
2. Deploys the csi driver like this:

```
kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
```

**Anything else we need to know?**:

I'm going to submit a pull request which fixes `compute-type` of the deployment like this:

```yaml
# deploy/kubernetes/base/controller.yaml
# ...
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ebs-csi-controller
  template:
    metadata:
      annotations:
        eks.amazonaws.com/compute-type: ec2  # I'll add this annotation.
      labels:
        app: ebs-csi-controller
```

Error log is:

```
$ kubectl logs -p ebs-csi-controller-6cd475bdbb-5wkvs -n kube-system -c ebs-plugin
I0503 10:08:32.978758       1 driver.go:43] Driver: ebs.csi.aws.com Version: 0.4.0
panic: could not get metadata from AWS: EC2 instance metadata is not available

goroutine 1 [running]:
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newControllerService(...)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/controller.go:63
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver(0x7ffc9c21faed, 0x30, 0x3, 0x3, 0x0)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:47 +0x237
main.main()
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:45 +0x15f
```

Fargate node cannot access the EC2 instance metadata endpoint and cannot run the pod normally.

**Environment**
- Kubernetes version (use `kubectl version`): v1.15.11-eks-af3caf
- Driver version: ebs.csi.aws.com Version: 0.4.0

**Comment by wongma7** [comment]
Yes, the driver depends on the metadata service (discussed here) https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/474.

I agree with adding the annotation. Even if the metadata issue were overcome, there's no point running the driver on a fargate node where ebs volumes can't be attached.

**Comment by literalice** [comment]
Thank you for your comment. I created a PR #496 .

**Comment by sarbajitdutta** [comment]
> I agree with adding the annotation. Even if the metadata issue were overcome, there's no point running the driver on a fargate node where ebs volumes can't be attached.

Is there any plans to attach ebs volumes to fargate nodes? We are running a heterogenous compute type in our eks cluster. Would really love this feature? @wongma7

**Comment by dodtsair** [comment]
Is this the issue being used to track EBS on fargate + EKS?
