### ISSUE TITLE
Doc request: adding custom tags 

### ISSUE THREAD

**Issue by iamjaekim** [kubernetes-sigs/aws-ebs-csi-driver#497]
On v0.5.0, the driver now supports custom tags to apply when creating new volumes. It appears, in the example folder, there isn't an example for adding custom tags to ebs volumes that the driver creates via `kubectl apply` 

Can I ask for a how-to and/or example for passing custom tags to the driver to create in a YAML file? so when i do `kubectl apply -f volumes.yaml` it creates a volume and tags I include in volume.yaml file?

**Comment by dayglojesus** [comment]
I was literally just looking for this as well 😂

**Comment by dayglojesus** [comment]
After some more reading, you need to add the following args ...
```
  -extra-volume-tags value
    	Extra volume tags to attach to each dynamically provisioned volume. It is a comma separated list of key value pairs like '<key1>=<value1>,<key2>=<value2>'
```
... to the `amazon/aws-ebs-csi-driver:v0.5.0` container in the `ebs-csi-controller` Deployment.

**Comment by iamjaekim** [comment]
@dayglojesus 
have you found a way? I am using fluxcd and my env currently tells 
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

However, with helm install command, I was able to install it, and couldn't see my optional tags i pushed through this. this is what i used. i might be wrong.
```
helm install aws-ebs-csi-driver \
 --namespace kube-system \ 
--set enableVolumeScheduling=true \
--set enableVolumeResizing=true \
--set enableVolumeSnapshot=false \
--set extra-volume-tags=backup=true \
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/releases/download/v0.5.0/helm-chart.tgz

**Comment by qw1mb0** [comment]
@iamjaekim You need to pass the parameter `extraVolumeTags`. As in the example: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/aws-ebs-csi-driver/values.yaml#L65-L70

**Comment by kostenkoi** [comment]
@qw1mb0, unfortunately, this doesn't work

helm upgrade --install aws-ebs-csi-driver \
    --namespace kube-system \
    --set enableVolumeScheduling=true \
    --set enableVolumeResizing=true \
    --set enableVolumeSnapshot=true \
    --set extraVolumeTags=isMonitored=false \
    aws-ebs-csi-driver/aws-ebs-csi-driver

sorry, but the link provided in the comment above also not found, so it's unclear how to properly use additional tags for future provisioned ebs volumes. Could you plz suggest?

**Comment by gsaraf** [comment]
> @qw1mb0, unfortunately, this doesn't work
> 
> `helm upgrade --install aws-ebs-csi-driver \ --namespace kube-system \ --set enableVolumeScheduling=true \ --set enableVolumeResizing=true \ --set enableVolumeSnapshot=true \ --set extraVolumeTags=isMonitored=false \ aws-ebs-csi-driver/aws-ebs-csi-driver`
> 
> sorry, but the link provided in the comment above also not found, so it's unclear how to properly use additional tags for future provisioned ebs volumes. Could you plz suggest?

I got stuck on this for a bit as well. The problem is that extraVolumeTags is a map, so the correct syntax is `--set 'extraVolumeTags.isMonitored=false'`.

**Comment by kostenkoi** [comment]
@gsaraf, thanks! Will check
