### ISSUE TITLE
Attach volume fails after resizing completed

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/aws-ebs-csi-driver#498]
/kind bug

**What happened?**
Running the "verify offline volume expansion" e2e test.

After controller resize finishes, a pod is created and we try to attach the volume, but attach fails because it still thinks the volume is being modified. This continues for at least 5 minutes after the resizing has finished, at which point the test times out.

```
May  7 21:19:58.215: INFO: At 2020-05-07 21:14:42 +0000 UTC - event for standard-rwoc4mps: {external-resizer ebs.csi.aws.com } FileSystemResizeRequired: Require file system resize of volume on node
May  7 21:19:58.215: INFO: At 2020-05-07 21:14:44 +0000 UTC - event for security-context-00009429-f857-4280-a75f-710af14c0a0b: {attachdetach-controller } FailedAttachVolume: AttachVolume.Attach failed for volume "pvc-683dd3d3-4858-4471-858e-b9cd72eb2b43" : rpc error: code = Internal desc = Could not attach volume "vol-085a666d487519e08" to node "i-0968acda4b0e832b6": could not attach volume "vol-085a666d487519e08" to node "i-0968acda4b0e832b6": OperationNotPermitted: Cannot attach volume vol-085a666d487519e08 when it is in modification state: MODIFYING
        status code: 400, request id: c73d69dd-73c9-45c5-9b53-5bd5346a3196
...
May  7 21:19:58.215: INFO: At 2020-05-07 21:18:54 +0000 UTC - event for security-context-00009429-f857-4280-a75f-710af14c0a0b: {attachdetach-controller } FailedAttachVolume: AttachVolume.Attach failed for volume "pvc-683dd3d3-4858-4471-858e-b9cd72eb2b43" : rpc error: code = Internal desc = Could not attach volume "vol-085a666d487519e08" to node "i-0968acda4b0e832b6": could not attach volume "vol-085a666d487519e08" to node "i-0968acda4b0e832b6": OperationNotPermitted: Cannot attach volume vol-085a666d487519e08 when it is in modification state: MODIFYING
```

csi resizer and csi attacher are running on the same node:

csi-resizer logs:
```
2020-05-07T21:14:42.029991782Z stderr F I0507 21:14:42.029885       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"volume-expand-4343", Name:"standard-rwoc4mps", UID:"683dd3d3-4858-4471-858e-b9cd72eb2b43", APIVersion:"v1", ResourceVersion:"1339926", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-683dd3d3-4858-4471-858e-b9cd72eb2b43
2020-05-07T21:14:42.10216938Z stderr F I0507 21:14:42.102085       1 controller.go:364] Resize volume succeeded for volume "pvc-683dd3d3-4858-4471-858e-b9cd72eb2b43", start to update PV's capacity
2020-05-07T21:14:42.11061756Z stderr F I0507 21:14:42.110511       1 controller.go:370] Update capacity of PV "pvc-683dd3d3-4858-4471-858e-b9cd72eb2b43" to 2Gi succeeded
2020-05-07T21:14:42.115934588Z stderr F I0507 21:14:42.115826       1 controller.go:420] Mark PVC "volume-expand-4343/standard-rwoc4mps" as file system resize required
2020-05-07T21:14:42.116025699Z stderr F I0507 21:14:42.115932       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"volume-expand-4343", Name:"standard-rwoc4mps", UID:"683dd3d3-4858-4471-858e-b9cd72eb2b43", APIVersion:"v1", ResourceVersion:"1339926", FieldPath:""}): type: 'Normal' reason: 'FileSystemResizeRequired' Require file system resize of volume on node
```

csi-attacher logs:
```
2020-05-07T21:14:44.678247064Z stderr F I0507 21:14:44.678194       1 csi_handler.go:222] Error processing "csi-ef5d4ec725f7bc17245640d27c3e79928881a0dccbb6644450639151cd3a2b08": failed to attach: rpc error: code = Internal desc = Could not attach volume "vol-085a666d487519e08" to node "i-0968acda4b0e832b6": could not attach volume "vol-085a666d487519e08" to node "i-0968acda4b0e832b6": OperationNotPermitted: Cannot attach volume vol-085a666d487519e08 when it is in modification state: MODIFYING
...
2020-05-07T21:19:27.650980466Z stderr F I0507 21:19:27.650835       1 csi_handler.go:222] Error processing "csi-ef5d4ec725f7bc17245640d27c3e79928881a0dccbb6644450639151cd3a2b08": failed to attach: rpc error: code = Internal desc = Could not attach volume "vol-085a666d487519e08" to node "i-0968acda4b0e832b6": could not attach volume "vol-085a666d487519e08" to node "i-0968acda4b0e832b6": OperationNotPermitted: Cannot attach volume vol-085a666d487519e08 when it is in modification state: MODIFYING
```

**What you expected to happen?**
Attach to succeed after resizing finished.

**How to reproduce it (as minimally and precisely as possible)?**
Run "verify offline volume expansion" e2e test.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.16
- Driver version: v0.5.0

**Comment by msau42** [comment]
https://github.com/kubernetes/kubernetes/issues/90866 may also be playing a factor

**Comment by msau42** [comment]
cc @gnufied

**Comment by msau42** [comment]
This also appears to be a timing issue, as the test is flaky

**Comment by gnufied** [comment]
@bertinatto has been also looking into similar problem with CSI EBS tests.

**Comment by bertinatto** [comment]
Occasionally, 5 minutes isn't enough for AWS to resize the volume. Increasing the timeout to 10 minutes in our CI helped, but it didn't fix the problem completely.

Note that the controller doesn't wait for the volume to be completely expanded, it only waits until it's in the `Optimizing` state. When the pod tries to attach the volume, AWS returns an error saying that the volume is being modified.

**Comment by bertinatto** [comment]
Increased the timeout to 15 min and ran the test hundreds of times. The maximum amount of time this test took was 11m29s.

`passed: (11m29s) 2020-06-19T17:16:39 "External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (block volmode)(allowExpansion)] volume-expand Verify if offline PVC expansion works"`

https://github.com/kubernetes/kubernetes/issues/88848 would be useful here.

**Comment by msau42** [comment]
> Note that the controller doesn't wait for the volume to be completely expanded, it only waits until it's in the `Optimizing` state. When the pod tries to attach the volume, AWS returns an error saying that the volume is being modified.

Would it be help if resize doesn't return until the operation is completely done? Then at least we avoid errors on attach?

**Comment by bertinatto** [comment]
> > Note that the controller doesn't wait for the volume to be completely expanded, it only waits until it's in the `Optimizing` state. When the pod tries to attach the volume, AWS returns an error saying that the volume is being modified.
> 
> Would it be help if resize doesn't return until the operation is completely done? Then at least we avoid errors on attach?

The current logic was taken from the in-tree plugin, and I believe it was a recommendation from AWS to avoid timeouts during resizes.

@gnufied do you have any inputs on this?

**Comment by gnufied** [comment]
At a glance this looks like an eventual consistency problem. It is possible that we don't see this problem with in-tree driver because resizer and attacher are same clients. If https://github.com/kubernetes/kubernetes/issues/90866 were a problem, I have opened https://github.com/kubernetes/kubernetes/pull/93654 to fix it. But since we don't see this in openshift(with in-tree driver where AWS tests are blocking), I am bit skeptical.

**Comment by gnufied** [comment]
Thinking through other differences between in-tree driver and CSI driver, I realized that in CSI driver we are using context everywhere including calls to AWS SDK. So if a context expires and we retry expansion - we could in-effect issue multiple expansion requests against same volume. When this happens - while one resize request will succeed the other one may be pending (and there is something weird in EBS backend and how it deals with volume expansion).

When this happens - attach will likely fail. In failure cases I did notice context deadline exceeded error:

```
1236   │ Aug  3 13:46:56.015: INFO: At 2020-08-03 13:41:30 +0000 UTC - event for ebs.csi.aws.comx8zd4: {external-resizer ebs.csi.aws.com } VolumeResizeFailed: resize volume pvc-1be483d0-1f33-4c97-8661-572d74c471b2 failed: rpc error: code = DeadlineExceeded desc = context deadline exc
```

To test my theory I increased context timeout in external-resizer sidecar to 2mins and I have not seen this flake/fail yet.

**Comment by bertinatto** [comment]
> To test my theory I increased context timeout in external-resizer sidecar to 2mins and I have not seen this flake/fail yet.

I had tried this as well in the past, but I was still able to reproduce the error after running the test sequentially for a few times.

I can be wrong, but I saw context deadline errors happen only in *attach* calls (due to the volume being in _modifying_ state), not on volume modification calls. I noticed that AWS processing time to volume modification calls are usually not the problem (as long as we wait for the state to be _optimizing_ rather than _completed_).

So far the only thing that has worked for me was increasing the attach timeout to 15 minutes (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/498#issuecomment-646788074).

**Comment by chrishenzie** [comment]
I'm not sure I understand. How does increasing a timeout on the external-resizer fix the issue? I understand the context supplied by the external-resizer is passed to the CSI driver and then to the AWS API. I don't see any deadline exceeded error (except for during attachment). Which API call in the CSI driver times out? And when it times out, what does the AWS API return?

**Comment by msau42** [comment]
I'm still suspicious about this Optimizing state. Can we try removing the check for that and see if that helps with the test flakiness? It would be good to also compare run times of the test case with the various suggestions in this thread.

**Comment by gnufied** [comment]
@msau42 @chrishenzie opened https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/552 to fix the idempotency issue. 

@chrishenzie I always see context deadline errors whenever this test flakes:

```
│ I0828 10:29:04.241579       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"e2e-volume-expand-8716", Name:"ebs.csi.aws.comllpsz", UID:"a3abefcb-314b-4285-8f9c-cd85ede3f38
       │ 6", APIVersion:"v1", ResourceVersion:"40754", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-a3abefcb-314b-4285-8f9c-cd85ede3f386
   9   │ I0828 10:29:10.960633       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"e2e-volume-expand-8716", Name:"ebs.csi.aws.comllpsz", UID:"a3abefcb-314b-4285-8f9c-cd85ede3f38
       │ 6", APIVersion:"v1", ResourceVersion:"40754", FieldPath:""}): type: 'Normal' reason: 'FileSystemResizeRequired' Require file system resize of volume on node

  10   │ I0828 10:29:20.573229       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"e2e-volume-expand-7736", Name:"ebs.csi.aws.comgc8p2", UID:"f23e1bd5-5941-4036-b61a-30d8dd3861c
       │ 0", APIVersion:"v1", ResourceVersion:"41113", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-f23e1bd5-5941-4036-b61a-30d8dd3861c0

  11   │ E0828 10:31:20.573335       1 controller.go:272] Error syncing PVC: resize volume "pvc-f23e1bd5-5941-4036-b61a-30d8dd3861c0" by resizer "ebs.csi.aws.com" failed: rpc error: code = DeadlineExceeded desc = 
│ context deadline exceeded

  12   │ I0828 10:31:20.573402       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"e2e-volume-expand-7736", Name:"ebs.csi.aws.comgc8p2", UID:"f23e1bd5-5941-4036-b61a-30d8dd3861c
       │ 0", APIVersion:"v1", ResourceVersion:"41113", FieldPath:""}): type: 'Warning' reason: 'VolumeResizeFailed' resize volume "pvc-f23e1bd5-5941-4036-b61a-30d8dd3861c0" by resizer "ebs.csi.aws.com" failed: rpc
       │  error: code = DeadlineExceeded desc = context deadline exceeded
  13   │ I0828 10:31:21.580123       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"e2e-volume-expand-7736", Name:"ebs.csi.aws.comgc8p2", UID:"f23e1bd5-5941-4036-b61a-30d8dd3861c
       │ 0", APIVersion:"v1", ResourceVersion:"45076", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-f23e1bd5-5941-4036-b61a-30d8dd3861c0

  14   │ I0828 10:31:21.669120       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"e2e-volume-expand-7736", Name:"ebs.csi.aws.comgc8p2", UID:"f23e1bd5-5941-4036-b61a-30d8dd3861c
       │ 0", APIVersion:"v1", ResourceVersion:"45076", FieldPath:""}): type: 'Normal' reason: 'FileSystemResizeRequired' Require file system resize of volume on node


  15   │ I0828 10:34:19.552953       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"e2e-volume-expand-169", Name:"ebs.csi.aws.comp7s4b", UID:"9018c4eb-f96e-4717-9c46-6d2157be38fe
       │ ", APIVersion:"v1", ResourceVersion:"51035", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-9018c4eb-f96e-4717-9c46-6d2157be38fe
  16   │ I0828 10:34:26.045450       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"e2e-volume-expand-169", Name:"ebs.csi.aws.comp7s4b", UID:"9018c4eb-f96e-4717-9c46-6d2157be38fe
       │ ", APIVersion:"v1", ResourceVersion:"51035", FieldPath:""}): type: 'Normal' reason: 'FileSystemResizeRequired' Require file system resize of volume on node
  17   │ I0828 10:34:47.909092       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"e2e-volume-expand-9357", Name:"ebs.csi.aws.coms8pqs", UID:"6a12eef5-00db-4a4d-9b21-6591b59e709
       │ 6", APIVersion:"v1", ResourceVersion:"52161", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-6a12eef5-00db-4a4d-9b21-6591b59e7096
  18   │ I0828 10:34:54.386519       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"e2e-volume-expand-9357", Name:"ebs.csi.aws.coms8pqs", UID:"6a12eef5-00db-4a4d-9b21-6591b59e709
       │ 6", APIVersion:"v1", ResourceVersion:"52161", FieldPath:""}): type: 'Normal' reason: 'FileSystemResizeRequired' Require file system resize of volume on node
```

In this case test flaked on pvc-f23e1bd5-5941-4036-b61a-30d8dd3861c0 and as you can see first 2 calls to resizing resulted in context deadline errors and then it finally succeeded (it took approx 2mins+ in total)

I am currently testing the PR I linked above and see if it fixes the problem. @msau42 yes I also distrust "optimizing" state but then attach volume says volume is in "modifying" state *after* volume entered "optimizing" state. This can IMO only happen if:

1. We issued another resize call somehow.
2. AWS's describeVolume somehow lied to us and returned "optimizing" when it was in "modifying" state.

**Comment by gnufied** [comment]
@wongma7 Is there a way to confirm with EBS folks that if we issue modifyVolume call to a volume which was previously expanded to same size (and might be in "optimizing" state) will enter "modifying" state because of same call being issued second time?

**Comment by gnufied** [comment]
I can confirm that - https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/552 fixes the resizing flake for offline resizing. The root cause is something a combination of short context timeout and the fact that describeVolume can return targetSize even when volume is still being resized.
