### ISSUE TITLE
Report volume usage

### ISSUE THREAD

**Issue by shukla2009** [kubernetes-sigs/aws-ebs-csi-driver#499]
How can I identify the volume usage ?

as of now aws-ebs-csi-driver emits 
`kube_persistentvolume_capacity_bytes`
but it doesn't have anything like 
`kube_persistentvolume_usage_bytes`

Ideally its should support standard metrics as below
```
kubelet_volume_stats_inodes_used
kubelet_volume_stats_used_bytes
kubelet_volume_stats_available_bytes
kubelet_volume_stats_capacity_bytes
kubelet_volume_stats_inodes
kubelet_volume_stats_inodes_free
```

**Comment by Henni** [comment]
This seems to be a duplicate of #223

**Comment by frittentheke** [comment]
> This seems to be a duplicate of #223

@Henni not really. The intention of https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/223 is to report metrics for the EBS driver, so some stats on the requests to the AWS APIs maybe - Number of them, success / failure rate / timeouts ....
So generally about the functionality of the CSI driver, not the resulting volumes or their stats.

See: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/216 (which somewhat resulted of my discussion with @leakingtapan in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/214).
