### ISSUE TITLE
no data recovered while restoring snapshot of a pvc

### ISSUE THREAD

**Issue by nitinkansal1984** [kubernetes-sigs/aws-ebs-csi-driver#503]
/kind bug

**What happened?**
kubectl apply -f snapshot.yaml
error: unable to recognize "snapshot.yaml": no matches for kind "VolumeSnapshot" in version "snapshot.storage.k8s.io/v1beta1"

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
dev
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
- Driver version:
I installed CSI controller as described in github.
ebs-csi-controller-6d9dfdc989-6hmrc        6/6     Running   0  
ebs-csi-controller-6d9dfdc989-6xfln        6/6     Running   0  
ebs-csi-node-85p45                         3/3     Running   0  
ebs-csi-node-vsjg7                         3/3     Running   0  
ebs-snapshot-controller-0                  1/1     Running   0

**Comment by leakingtapan** [comment]
Similar to #426

**Comment by leakingtapan** [comment]
/close

Feel free to reopen if it is a different issue

**Comment by nitinkansal1984** [comment]
Can I go back to AWS console and note the snapshot id and use that in pod definition meanwhile to restore the volume to the new pod? 

  volumes:
  - name: persistent-storage
    awsElasticBlockStore:
      volumeID: vol-XXX
      fsType: ext4

**Comment by leakingtapan** [comment]
You can only set volume ID in pod definition but snapshot ID using the inline volume style.
