### ISSUE TITLE
Wrong Error Returned When Volume is Attached

### ISSUE THREAD

**Issue by kainoaseto** [kubernetes-sigs/aws-ebs-csi-driver#515]
/kind bug

**What happened?**
When a EBS volume is attached to another EC2 instance the `ALREADY_EXISTS` error is returned when it seems like the `FAILED_PRECONDITION` error should be returned instead because the `node_id` and `volume_id` do not match what the request attachment of `volume_id` and `node_id`. 

CSI Spec: https://github.com/container-storage-interface/spec/blob/master/spec.md#controllerpublishvolume-errors

**What you expected to happen?**
I expected a `FAILED_PRECONDITION` error to be thrown or have this error thrown if the volume was already attached to my node/ec2-instance.

**How to reproduce it (as minimally and precisely as possible)?**
1. Attach a EBS volume to a ec2-instance using any method, easiest would likely be calling 'CreateVolume`, and go through the normal attachment process or by scheduling a job.

2. Call the RPC `ControllerPublishVolume` with the same `volume_id` but different `node_id` than the already attached volume. 

**Anything else we need to know?**:
I've located the line that produces this problem here:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/db95482f8963350d70e9932b0936e6794fe76bf2/pkg/cloud/cloud.go#L358

It would be ideal to have this `ALREADY_EXISTS` still work but just also check for the `node_id` that it is attached to before returning that and otherwise return `FAILED_PRECONDITION`.

**Environment**
- Kubernetes version (use `kubectl version`): N/A (Using Nomad v0.11.2)
- Driver version: v0.6.0-dirty

**Comment by AndyXiangLi** [comment]
/reopen
/assign
looking into this
