### ISSUE TITLE
Clarification on IAM requirements

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/aws-ebs-csi-driver#517]
Reviewing this for inclusion in https://github.com/kubernetes-sigs/cluster-api-provider-aws, I just want a clarification as I've been going through the code. Are IAM permissions required specifically on every node, or only nodes running the controller? The driver-only code path doesn't seem to call into `pkg/cloud/NewCloud()` as far as I can tell. Is that reading correct?

/triage support
/kind docs

**Comment by ConnorJC3** [comment]
/close

(closing out old issues)

Driver required permissions are documented in the installation docs (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md#set-up-driver-permissions) - no permissions are required on each node.
