### ISSUE TITLE
Provide a helm repo

### ISSUE THREAD

**Issue by galindro** [kubernetes-sigs/aws-ebs-csi-driver#520]
I just would like that the aws-ebs-csi-driver helm chart could be available via helm repo, like any other helm chart. I'm using helmsman to deploy it and I currently need to download the tgz, extract and them install.

**Comment by leakingtapan** [comment]
helm repo created here: https://kubernetes-sigs.github.io/aws-ebs-csi-driver/index.yaml

**Comment by galindro** [comment]
Thank you very very much!

**Comment by galindro** [comment]
@leakingtapan just asked the same in https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/200

**Comment by leakingtapan** [comment]
/close
As the repo is published

**Comment by alexandregomes-acceptto** [comment]
Version 0.6 is not available. How do we get it updated on that repo?

**Comment by krmichel** [comment]
> Version 0.6 is not available. How do we get it updated on that repo?

PRs #623 and #624 should deal with this issue
