### ISSUE TITLE
EBS CSI Driver is creating volume in incorrect availability zone

### ISSUE THREAD

**Issue by hussainsaify** [kubernetes-sigs/aws-ebs-csi-driver#525]
Environment-

AWS EKS(1.14) cluster in multiple availability zone
Helm chart version for ebs-csi-driver - aws-ebs-csi-driver-0.3.0

**What I am trying to do?**

I am installing postgresql on kubernetes with persistent volume claim with below storage class

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  encrypted: "true"
reclaimPolicy: Delete
```

**What did I expect to happen?**

Volume getting created in the same availability zone as the node on which pod gets launched

**What happened?**

Volume should get created in the same availability zone as the instance **ip-10-*****-246.ec2.internal** which is **us-east-1d**

Following is the output of describing pvc through kubectl
```
_Name:          data-postgresql-test-0
Namespace:     test-vmware
StorageClass:  ebs-sc
Status:        Bound
Volume:        pvc-d6c9315a-b148-11ea-94ac-121ea13dab89
Labels:        app=postgresql
               release=postgresql-test
               role=master
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/selected-node: **ip-10-*******-246.ec2.internal**
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      25Gi_
```
But volume got created in **us-east-1-a**, because of that pod did not got launched.

Here are the events from describing pod
```
_Events:
  Type     Reason              Age               From                     Message
  ----     ------              ----              ----                     -------
  Warning  FailedScheduling    4m (x2 over 14m)  default-scheduler        timed out waiting for the condition
  Normal   Scheduled           24s               default-scheduler        Successfully assigned test-vmware/postgresql-test-0 to **ip-10-*****-246.ec2.internal**
  Warning  FailedAttachVolume  23s               attachdetach-controller  AttachVolume.Attach failed for volume "pvc-***********************dab89" : rpc error: code = Internal desc = Could not attach volume "vol-*****************" to node "i-************": could not attach volume "vol-***********" to node "i-************": InvalidVolume.ZoneMismatch: The volume 'vol-*****************' is not in the same availability zone as instance 'i-************'_
```
Please let me know in case you need more information.

**Comment by leakingtapan** [comment]
Do you have the ebs-csi-driver log when this happened, you can get the log with something like:
```
kubectl logs ebs-csi-controller-xx -n kube-system -c ebs-plugin
```

**Comment by hussainsaify** [comment]
@leakingtapan I can see following in the logs

_I0626 10:48:00.829605       1 controller.go:93] CreateVolume: called with args {Name:pvc-8098bd31-b79a-11ea-94ac-121ea13dab89 CapacityRange:required_bytes:64424509440  VolumeCapabilities:[mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > ] Parameters:map[encrypted:true] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0626 10:48:00.906846       1 cloud.go:273] AZ is not provided. Using node AZ []_

This means it is not getting the node's availability zone and creating volume in some random region.

**Comment by hussainsaify** [comment]
This issue is fixed after enabling --feature-gates=Topology=true in external-provisioner. This can be done by setting enableVolumeScheduling: true while deploying the chart.
