### ISSUE TITLE
Attachment failures when multiple volumes are attached to a node

### ISSUE THREAD

**Issue by notnoop** [kubernetes-sigs/aws-ebs-csi-driver#528]
/kind bug

**What happened?**
The EBS CSI driver may fail to attach a volume to node, if it receives two concurrent `AttachVolume` RPCs for the same node.

The following is a sample log entry:

```
failed to setup alloc: pre-run hook "csi_hook" failed: claim volumes: rpc error: controller publish: attach volume: controller attach volume: rpc error: code = Internal desc = Could not attach volume "vol-0e5f3d9ecd9abf8ec" to node "i-089c85a9dd396c760": could not attach volume "vol-0e5f3d9ecd9abf8ec" to node "i-089c85a9dd396c760": InvalidParameterValue: Invalid value '/dev/xvdba' for unixDevice. Attachment point /dev/xvdba is already in use status code: 400, request id: be1b9057-cf3c-420d-85b2-8994b632cad9
```

**What you expected to happen?**

Both volumes mount to different attachment points

**How to reproduce it (as minimally and precisely as possible)?**
Sorry for the hand-waveness here.  The triggering conditions seem a bit straightforward, by reading the code:

1. Start a nomad cluster, configured with EBS CSI volume: https://learn.hashicorp.com/nomad/stateful-workloads/csi-volumes
2. Submit a job that requires two EBS volumes!

**Anything else we need to know?**:
Two contributing factors seem at play in 
* [`NewDevice`](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/563a72bc88850ace60a62a05860d3986b659801f/pkg/cloud/devicemanager/manager.go#L109).

First, it consults the ec2 instance info and makes an attachment point determination - so is susceptible to check-then-act condition.  Second, it relies on `d.inFlight` in-memory structure to contain on-going info, but the in-memory info may be stale when running multiple controllers.

The [CSI spec states](https://github.com/container-storage-interface/spec/blob/master/spec.md#concurrency):
> In general the Cluster Orchestrator (CO) is responsible for ensuring that there is no more than one call “in-flight” per volume at a given time

The spec seems silent with regards to concurrency per node.

**Environment**
- Nomad version: Nomad 0.11.3
- Driver version: v0.5.0

**Comment by Jiawei0227** [comment]
A quick read of the code logic. Nothing obviously wrong seems to me. The logic of NewDevice is synchronized. And also it adds the devices info into the in-memory attach-in-progress map. So in theory the next NewDevice call should not return the same name. Is there anything wrong that I did not spot here?

**Comment by Jiawei0227** [comment]
One possible issue is that the controller is not running in leader-election mode? So there might be cases two ControllerPublishVolume() call get processed by two different controller? Guess this might be problematic.

**Comment by wongma7** [comment]
Yeah, external attacher should be run with leader election so there should not be multiple controllers racing to attach volumes. It will be unfeasible to synchronize 2 controllers' in flight requests. I think the best we can do is make the controller tolerate the possibility that something else "steals" an chosen attach point and pick another one if so. But that could introduce more bugs so I think in the meantime, shouldn't running with leader election prevent this from happening?

> in-memory info may be stale when running multiple controllers.

From https://github.com/kubernetes-csi/external-attacher

> Note that the external-attacher does not scale with more replicas. Only one external-attacher is elected as leader and running. The others are waiting for the leader to die. They re-elect a new active leader in ~15 seconds after death of the old leader.

**Comment by wongma7** [comment]
I guess even if leader election is on it's possible for there to be an issue like if 1 controller is unable to renew its lease for some reason but 1 of its attaches is in flight e.g. volA to xvda and the new leader then tries to attach volB to xvda.

**Comment by Jiawei0227** [comment]
@wongma7 agree that this can happen when leader changes. But from the original issue report on nomad, it seems this issue happens almost every time. This is unnormal. And I cannot seem to reproduce the issue on kubernetes. @notnoop Can you verify if the controller is running in leader-election mode if you have more than one controller deployed in nomad?

**Comment by tgross** [comment]
Hi folks, following up on @notnoop's behalf from the Nomad team. We don't run `csi-provisioner`, `external-attacher`, etc., but have the CSI controller RPCs implemented in-tree. So there's nothing to run elections between controllers.
