### ISSUE TITLE
Migrated AWS EBS volumes don't have tags

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/aws-ebs-csi-driver#529]
/kind bug

**What happened?**
In-tree awes-ebs provisioner creates volumes with these tags:
```
kubernetes.io/cluster/jsafrane-10235-vgdv6: owned     
Name:                                       jsafrane-10235-vgdv6-dynamic-pvc-447cc711-bb65-4b4d-836d-a822e4e77e43     
kubernetes.io/created-for/pv/name:          pvc-447cc711-bb65-4b4d-836d-a822e4e77e43     
kubernetes.io/created-for/pvc/name:         myclaim     
kubernetes.io/created-for/pvc/namespace:    default     
```

When migration to CSI is enabled, provisioned volumes don't have such tags, only
```
CSIVolumeName: pvc-4e4cb311-3907-4192-bc58-cde8ea112392
```

**What you expected to happen?**
When requested on cmdline, the driver should add also the "legacy" tags to EBS volumes.

**Anything else we need to know?**:
- Driver version: today's master

**Comment by jsafrane** [comment]
* The cluster ID is hard to get, I can imagine a new driver option `--kubernetes-cluster-id=XXX` or let `--extra-volume-tags` accept `kubernes.io` prefix as suggested in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/450, so Kubernetes vendor can add it.

* PV / PVC namespace/name: `CreateVolume` request, if enabled via `external-provisioner --extra-create-metadata=true`, gets PVC name+namespace + PV name.
  * The driver can either *always* tag volumes with pv/pvc names when it gets them from the provisioner (i.e. someone has deployed the external-provisioner with `--extra-create-metadata=true`. This would be my preferred solution.
  * Or there is a new cmdline options in the driver, say `--legacy-tags=true`, that then explicitly enables volume tags.

**Comment by wongma7** [comment]
> let --extra-volume-tags accept kubernes.io prefix as suggested in #450, so Kubernetes vendor can add it.

I prefer this.

> always tag volumes with pv/pvc names when it gets them from the provisioner (i.e. someone has deployed the external-provisioner with --extra-create-metadata=true.

Also prefer this, I can't think of a reason someone would need a driver cmdline option to disable these tags.

**Comment by jsafrane** [comment]
Thinking more about it... tag `Name: jsafrane-10235-vgdv6-dynamic-pvc-447cc711-bb65-4b4d-836d-a822e4e77e43` [includes cluster-id](https://github.com/kubernetes/kubernetes/blob/442a69c3bdf6fe8e525b05887e57d89db1e2f3a5/pkg/volume/awsebs/aws_util.go#L88). So the CSI driver still needs to get it from somewhere. I'll add it as extra parameter.
