### ISSUE TITLE
Support for multiple aws account

### ISSUE THREAD

**Issue by gajanankulkarni09** [kubernetes-sigs/aws-ebs-csi-driver#533]
**Is your feature request related to a problem?/Why is this needed**
CreateVolume fails on Custom deployment of kubernetes on aws with multiple account.

I have kubernetes installed on aws ec2 instances spread across 2 aws accounts.  When I schedule pod object with dynamic Persistent Volume Claim, sometimes operation succeeds and sometime it fails. Below are 2 cases
Case 1.
When EBS Create Volume request is for pod allocated on one account ec2 instance and ebs volume got created on another aws account, mount operation fails. 
Case 2.
But if pod getting scheduled on same account ec2 instance as that of aws account where EBS volume was created, CreateVolume and mount operation succeeds.

/feature
support for multiple aws accounts 

*Describe the solution you'd like in detail**

Here is one solution I can think of. Storage class will have details of credentials of multiple aws accounts. So when CreateVolume request comes, it should create ebs volume in the same account where pod is being created.
If this is not possible I have alternate solution described below.

**Describe alternatives you've considered**

Another solution I have considered is manual where in user will create multiple storage classes ( one for each account, in my case 2 storage classes as I have 2 accounts), and provide account secret in storage class yaml.  And while creating pod, user will give affinity of only one account, so pod will be scheduled only in aws account where Persistent Volume was created ( by mentioning account secret in storage class yaml
Storage class yaml currently does not have provision for giving secret of Aws Account.

**Comment by wongma7** [comment]
I don't think putting creds in the StorageClass will ever be possible for security reasons. ATM there is some effort to put service account tokens in CSIDrivers but it is focused on NodePublish not ControllerPublish/CreateVolume https://github.com/kubernetes/enhancements/pull/1855/files

If the driver can't get creds from StorageClass, then you'll have to deploy two drivers, each with creds for 1 account, and somehow ensure that CreateVolume requests for pods scheduled to account A go to the driver in account A, B to B. 

For that to happen automatically, NodeGetInfo would have to report what account it is in via topology, then the driver would have to get creds for the right account. Like if it had some mapping of account to role and AssumeRole'd before every API call. Seems quite complicated security-wise, not sure it will be worth the risk/effort

/lifecycle frozen

**Comment by msau42** [comment]
storageclass supports secret parameters
https://kubernetes-csi.github.io/docs/secrets-and-credentials-storage-class.html

**Comment by wongma7** [comment]
TY, works for me, then we need to update driver to read it and use the creds there to AssumeROle

**Comment by wongma7** [comment]
Reopened old issue about it, I think this one can be closed since the proposed solution is totally possible if we just implement the old issue https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/179/
