### ISSUE TITLE
Cannot resize volume

### ISSUE THREAD

**Issue by foreversor** [kubernetes-sigs/aws-ebs-csi-driver#534]
/kind bug

**What happened?**
Got below error with Volume Resizing 
Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**
1. Create new cluster with Kubernetes 1.17
2. Deploy the stable driver
3. Deploy Volume Resizing example (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/resizing)
4. Edit the ebs-claim pvc

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.17
- Driver version:v0.5.0

**Comment by gkrizek** [comment]
> CSI volume resizing is still alpha as of Kubernetes 1.15

You need to use the `alpha` driver to enable volume resizing. Not `stable`.

**Comment by Amos-85** [comment]
Hi @foreversor ,

Ensure that you add all the `feature-gates` in kube-api & kubelet.
Check that you all those policies attached to an instance profile:

`https://raw.githubusercontent.com/kubernetes-sigs/aws-ebs-csi-driver/v0.5.0/docs/example-iam-policy.json`

Check the `csi-resizer` container logs.

**Comment by foreversor** [comment]
> > CSI volume resizing is still alpha as of Kubernetes 1.15
> 
> You need to use the `alpha` driver to enable volume resizing. Not `stable`.

**Comment by foreversor** [comment]
> > CSI volume resizing is still alpha as of Kubernetes 1.15
> 
> You need to use the `alpha` driver to enable volume resizing. Not `stable`.

tried with alpha driver, works okay
