### ISSUE TITLE
Snapshot CRDs are not installed

### ISSUE THREAD

**Issue by timmyers** [kubernetes-sigs/aws-ebs-csi-driver#536]
/kind bug

**What happened?**

Following directions for alpha features does not install the `VolumeSnapshot` related CRDs

**What you expected to happen?**

`VolumeSnapshot` related CRDs are installed.

**How to reproduce it (as minimally and precisely as possible)?**

Follow instructions in `README` for alpha features, i.e.:
`kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/alpha/?ref=master"`

**Anything else we need to know?**:

It seems these CRDs exist in `deploy/kubernetes/cluster`, but this is not included as part of the kustomization.

**Environment**
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.6-eks-4e7f64", GitCommit:"4e7f642f9f4cbb3c39a4fc6ee84fe341a8ade94c", GitTreeState:"clean", BuildDate:"2020-06-11T13:55:35Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version:
`master` branch

**Comment by Amos-85** [comment]
Hi @timmyers ,

I face the same issue today,
it's looks like it's a missing part when installing the snapshot-controller, it doesn't install those crd's VolumeSnapshot, VolumeSnapshotContent, and VolumeSnapshotClass

Those crd's is not part of the k8s core api according to there documentation:

https://kubernetes.io/docs/concepts/storage/volume-snapshots

The workaround is to install them manually:

https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml"

https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml

https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml

don't forget to ensure all those policies attached to an ec2 instance profile:

https://raw.githubusercontent.com/kubernetes-sigs/aws-ebs-csi-driver/v0.5.0/docs/example-iam-policy.json

**Comment by sgatdell** [comment]
Now that CSI Volumesnapshot support has moved out of alpha and is enabled by default, any idea when the VolumeSnapshot support in EBS driver will be moved to stable version of the driver  instead of being as part of the driver with alpha features?

**Comment by dschunack** [comment]
Whats the current state ? Is it possible to add the CRDs for snapshots in the helm chart?

**Comment by wongma7** [comment]
Yes it is a bug that we install snapshot controller https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/a3a0bc328e35d0a6e4776ac2f4febf2e2990cb64/charts/aws-ebs-csi-driver/templates/statefulset.yaml but not the assojciated CRD ?

Although iti s arguable whether we should install snapshot controller by default at all or leave it as prerequisite since it is not EBS-specific

**Comment by dschunack** [comment]
We rollout all our Deployments with terraform and the kubernetes/helm provider.
As workaround we implement a terraform resource to create the CRDs on EKS before we apply the helm chart.
It's working but not the best solution. I think it makes sense to add the CRDs in the Helm Chart.

**Comment by bobbywatson3** [comment]
Agreed. They should be a part of the helm chart. Anyone who doesn't want to install them as part of the helm chart can use `--skip-crds`

**Comment by mszumilak** [comment]
With 1.20 VolumeSnapshots are no longer in beta, CRDs are still not available though. Any update on this?

**Comment by krmichel** [comment]
This is related to issue #635
