### ISSUE TITLE
VolumeSnapshotClass not in  "snapshot.storage.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by PSjoe** [kubernetes-sigs/aws-ebs-csi-driver#537]
/kind bug

**What happened?**
Following the directions for CSI volume snapshots:  https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/snapshot 

Step 1 returns with:  
`error: unable to recognize "specs/classes/snapshotclass.yaml": no matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1beta1"`

**What you expected to happen?**
VolumeSnapshotClass should be created.

**How to reproduce it (as minimally and precisely as possible)?**
Run through example deployment in aws-ebs-csi-driver/examples/kubernetes/snapshot/ on a newly instantiated EKS cluster running 1.17.

**Environment**
- Kubernetes version (use `kubectl version`):
`    Server Version: GitVersion:"v1.17.6-eks-4e7f64", 
    Client Version:  GitVersion:"v1.17.7-eks-bffbac"`
- Driver version:
` kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"`
Also attempted with the 0.5.0 tag with the same results.

CSI driver appears to be running:  

    kubectl get pods --all-namespaces`
    NAMESPACE     NAME                                  READY   STATUS    RESTARTS   AGE
     kube-system   aws-node-tkfvb                        1/1     Running   0          42h
     kube-system   coredns-55c5fcd78f-kj828              1/1     Running   0          43h
     kube-system   coredns-55c5fcd78f-mlqms              1/1     Running   0          43h
     kube-system   ebs-csi-controller-78bc69cb98-7bfcm   4/4     Running   0          3s
     kube-system   ebs-csi-controller-78bc69cb98-w9fc9   4/4     Running   0          3s
     kube-system   ebs-csi-node-vg4j5                    3/3     Running   0          3s
     kube-system   kube-proxy-cx66g                      1/1     Running   0          42h`

And according to this:  https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/   the feature gate for VolumeSnapshotDataSource should be enabled by default in 1.17.

**Comment by kingli-crypto** [comment]
I am facing the same issue. I believe this is due to VolumeSnapshotDataSource is not enabled in EKS 1.17.
Maybe a maintainer can kindly comment on that.

**Comment by Amos-85** [comment]
Hi @PSjoe & @kingli-crypto  ,
I face the same issue today,
it's looks like it's a missing part when installing the snapshot-controller, it doesn't install those crd's `VolumeSnapshot`, `VolumeSnapshotContent`, and `VolumeSnapshotClass`

Those crd's  is not part of the k8s core api according to there documentation:

`https://kubernetes.io/docs/concepts/storage/volume-snapshots`

The workaround is to install those crd's:

`https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml"`
`https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml`
`https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml`

don't forget to ensure all those policies attached to an ec2 instance profile:

`https://raw.githubusercontent.com/kubernetes-sigs/aws-ebs-csi-driver/v0.5.0/docs/example-iam-policy.json`

**Comment by PSjoe** [comment]
Thanks for the tip!  That got me closer.  I no longer get any error messages when stepping through the example.  However, it seems my snapshot never gets created.  Are you able to get Step 5:
`kubectl apply -f specs/snapshot/`
to work?  It doesn't error. It just never gets to `Ready To Use: true`.

**Comment by PSjoe** [comment]
Never mind.  I've backed out everything and started over and it seems to be working now.

**Comment by Amos-85** [comment]
@PSjoe ,
Cheers!

**Comment by nothingofuse** [comment]
it seems these crds are no longer in that location, does anyone know of the current solution to this issue?

**Comment by Amos-85** [comment]
@nothingofuse ,
You can follow the [external-snapshotter](https://github.com/kubernetes-csi/external-snapshotter) project and install the crd's version you wish.

**Comment by PSjoe** [comment]
Found them here:

https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd

**Comment by ayberk** [comment]
Closing this as we've updated the README.

/close
