### ISSUE TITLE
Receiving a Multi-Attach error when the EBS volume is not attached to any instance

### ISSUE THREAD

**Issue by gkrizek** [kubernetes-sigs/aws-ebs-csi-driver#542]
/kind bug

**What happened?**

I have two EC2 instances attached to my EKS cluster in the same Availability zone. A single pod is running on Node1 that has a PVC attached to it. I terminate Node1 to simulate a node failure. EKS sees that Node2 is available and has the correct affinity for the pod, so it schedules the pod onto Node2. The pod is stuck in `ContainerCreating` for about 7 minutes with the following message:

```
  Warning  FailedAttachVolume  15s   attachdetach-controller  Multi-Attach error for volume "pvc-16293fb9-4a67-4508-b112-178e5c4455cd" Volume is already exclusively attached to one node and can't be attached to another
```

When I go to the EC2 console I see that the EBS volume it's referencing is not attached to any instance. After the ~7 minutes is up, it detects the EBS volume is free and attaches it to Node2 and my pod starts running.

**What you expected to happen?**

I expect the EBS CSI to detect when the EBS Volume is no attached to an instance and therefore allow it to be attached to a new instance.

**How to reproduce it (as minimally and precisely as possible)?**

- Create EKS Cluster with 2 nodes in the same AZ
- Schedule a pod that has a PVC
- Terminate the node the pod is running on

**Environment**
- Kubernetes version (use `kubectl version`): 1.17 in EKS
- Driver version: 0.5.0-alpha

**Comment by msau42** [comment]
This is probably related to https://github.com/kubernetes-csi/external-attacher/issues/215

**Comment by gkrizek** [comment]
Ah, yeah. Looks like it could be. Thanks for the reference
