### ISSUE TITLE
Fix e2e-test-single-az failures

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-ebs-csi-driver#545]
/kind bug

**What happened?** tests have been incredibly failureprone as of late https://testgrid.k8s.io/sig-aws-ebs-csi-driver#e2e-test-single-az&width=20

**What you expected to happen?** tests should pass consistently

**How to reproduce it (as minimally and precisely as possible)?** create a PR and let the CI run tests

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by wongma7** [comment]
Need to dump csi driver logs to aid in debugging.

**Comment by wongma7** [comment]
Most failures are sc1 and st1 which are slow hdd with minimum 500GiB size. Not sure how long formatting should take, of course formatting 500GiB does not mean all 500GiB needs to be written, but let's say it does then in a best case scenario of 250MiB/s writing all 500GiB would take 34 mins.

io1 tests also fail a bunch and it could be because we provision with bare minimum iops of 100.

Doesn't really explain why the tests have been so flaky only over last couple months

Anyway I do not see the value in testing every volume type fs type combination so I will remove all but gp2 and one of io2/io1 + xfs

**Comment by ayberk** [comment]
I'm closing this as I think it doesn't happen anymore. @wongma7 to confirm.

/close
