### ISSUE TITLE
Bring back the vendor directory

### ISSUE THREAD

**Issue by gnufied** [kubernetes-sigs/aws-ebs-csi-driver#553]
Compared to every other repository in k8s org, EBS CSI driver does not vendor the dependencies. This creates problems like - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-ebs-csi-driver/552/pull-aws-ebs-csi-driver-unit/1300182099357077505/build-log.txt

When we removed vendor via  - https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/202 the argument was, it will result in "consistent build image". Isn't this other way around? Whereas having vendored depenencies and using those depenencies during build time will result in consistent images?

/kind bug

cc @bertinatto @leakingtapan @wongma7

**Comment by leakingtapan** [comment]
IIRC the "consistent build image" was referring to the usage of go.mod/go.sum which lock down all the dependency version, compared to go vendor dir could potentially modified without being noticed. But anyway, what's the advantage of vendor dir? I think Golang is moving toward go mod and vendor dir will be deprecated.

**Comment by gnufied** [comment]
I have added verification check so as any direct modification to vendor files will be detected and will cause tests to fail. I think that should address concerns about vendored files being silently modified.  If anything - vendored dependencies make builds more reproducible.

**Comment by leakingtapan** [comment]
Fair enough. I feels this is more golang issue on whether vendor dir or go mod should be preferred. Let’s use vendor then if all k8s projects are doing the same thing
