### ISSUE TITLE
Enable user-provided tags on volume snapshots

### ISSUE THREAD

**Issue by chrishenzie** [kubernetes-sigs/aws-ebs-csi-driver#566]
**Is your feature request related to a problem? Please describe.**
Right now we have an `--extra-volume-tags` flag for enabling user-supplied tags on provisioned EBS volumes. I would like to extend this to also tag snapshots of these EBS volumes.

**Describe the solution you'd like in detail**
- Add an `--extra-snapshot-tags` flag for user-supplied tags on EBS snapshots
- Pass these tags in the `cloud.CreateSnapshot()` call

**Describe alternatives you've considered**
- Reuse the existing `--extra-volume-tags` flag and pass the same tags to both provisioned EBS volumes and snapshots.
  - Optionally, we could rename this flag to be more reflect that it affects more than just volumes
    - This would be a backwards incompatible change, any thoughts around this?
- Provision snapshots using the tags that are already set on the EBS volume
  - Potential problem, if tags are set on the volume outside of K8s, these would be propagated

@msau42

**Comment by msau42** [comment]
I prefer reusing --extra-volume-tags since I'm not sure when you wouldn't want to add the tag to both. But agree that it would be a breaking change to rename it. cc @leakingtapan @wongma7
