### ISSUE TITLE
Resizing disk partition in EBS from smaller snapshot size

### ISSUE THREAD

**Issue by symanovich-a** [kubernetes-sigs/aws-ebs-csi-driver#569]
/kind bug

**What happened?**
Disk partition isn't resized after creation

**What you expected to happen?**

Disk partition is resized after creation
**How to reproduce it (as minimally and precisely as possible)?**
- Create disk(ebs) snapshot 
- Restore disk from this snapshot but with bigger size.
I see normal disk size from lsblk command, but partition isn't resized. All work good, if i do disk resizing after pvc editing 

**Anything else we need to know?**:

**Environment**
- Kubernetes version 1.17(eks)
- Driver version: 0.6.0

**Comment by AndyXiangLi** [comment]
There is an upstream discussion about this issue https://github.com/container-storage-interface/spec/pull/452
Looks like driver need to resize the fs if detect volume size is larger than current fs when stage volume.
And as per @jsafrane , we can always call resize2fs / xfs_growfs after mount as alternate
@ayberk @leakingtapan what do you think?
