### ISSUE TITLE
Helm chart : snapshot-controller image location is hardcoded, we should be able to set overwrite the value

### ISSUE THREAD

**Issue by JonathanLachapelle** [kubernetes-sigs/aws-ebs-csi-driver#572]
**Is your feature request related to a problem?/Why is this needed**
It is not possible to use the helm chart with a private repository

/feature

**Describe the solution you'd like in detail**
Add the possibility in the snapshot controller stateful set to input the image location

**Describe alternatives you've considered**
Fork the repo

**Comment by JonathanLachapelle** [comment]
Also ImagePullSecret is not working

**Comment by JonathanLachapelle** [comment]
I created a pull request to fix this issue : https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/583

**Comment by wongma7** [comment]
Actually it is a mistake that the helm chart installs snapshot controller at all. I got confused myself, cuz there is the snapshot controller and then there is the snapshot sidecar...... REF, contiunue discussion there: 
Don't install snapshot controller https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/635
