### ISSUE TITLE
Push debain-base target to Dockerhub

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes-sigs/aws-ebs-csi-driver#580]
In #573 @wongma7 mentions that he needs to get approval to push debian based image to Dockerhub. That's why v0.7.0 is still with amazonlinux base image.
I am opening this issue to track the progress on this topic.

/assign @wongma7

**Comment by wongma7** [comment]
I mentioned already in #573 but what do we think about maintaining our own community Docker hub not tied to the amazon Docker hub? Or is it important to people that they are getting an image from an "official" source?

Plus, Docker hub is implementing rate limiting which I gather is not popular. Any other options?

**Comment by msau42** [comment]
Another option is to push community images to k8s-infra, since this project is part of kubernetes-sigs. There already is a staging repo for aws: https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io/manifests/k8s-staging-provider-aws

**Comment by wongma7** [comment]
OK, I pushed debian-base to gcr.
`docker pull k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.8.0`
LMK if that solves the issue or if we still need it in Docker Hub

**Comment by ialidzhikov** [comment]
Thank you @wongma7! gcr is even better. This issue was more about using the debian base image which is already done with the v0.8.0 release. Thank you again!

/close
