### ISSUE TITLE
Helm Chart for 0.7 deploys 0.6 image

### ISSUE THREAD

**Issue by dnoland1** [kubernetes-sigs/aws-ebs-csi-driver#584]
/kind bug

**What happened?**
When using 0.7 of the helm chart, it deploys 0.6 of the aws ebs csi driver.

**What you expected to happen?**
Would expect this helm chart would deploy 0.7.

**How to reproduce it (as minimally and precisely as possible)?**
```
$ wget https://github.com/kubernetes-sigs/aws-ebs-csi-driver/releases/download/v0.7.0/helm-chart.tgz
$ tar -xf helm-chart.tgz
$ grep -A2 -B2 tag aws-ebs-csi-driver/values.yaml
image:
  repository: amazon/aws-ebs-csi-driver
  tag: "v0.6.0"
  pullPolicy: IfNotPresent
...
```
After deploying helm chart, seeing:
```
> kubectl get pods -n kube-system -o custom-columns=name:.metadata.name,image:.spec.containers[].image | grep ebs
ebs-csi-node-gfnd4                      amazon/aws-ebs-csi-driver:v0.6.0
ebs-snapshot-controller-0               quay.io/k8scsi/snapshot-controller:v2.1.1
ebs-csi-controller-84dfb567df-vcmh4     amazon/aws-ebs-csi-driver:v0.6.0
ebs-csi-node-8qz5l                      amazon/aws-ebs-csi-driver:v0.6.0
ebs-csi-controller-84dfb567df-tkhrb     amazon/aws-ebs-csi-driver:v0.6.0
```
**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2+k3s1", GitCommit:"d38505b124c92bffd45f6e0654adb9371cae9610", GitTreeState:"clean", BuildDate:"2020-09-21T17:00:07Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version:
v0.7 (but getting v0.6!)

**Comment by tyrken** [comment]
I'm guessing this is as updating the version-tags on the helm chart (and kustomise manifest) is seen as a manual post-release task, e.g. https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/a2aecd2db7b8d27f97ab4e0c673bad36103cb8f4, whereas that helm-chart.tgz is uploaded via GitHub Actions immediately upon release, i.e. before that.

The (human?) documentation as to the release process needs to be fixed to swap the order, though I could imagine this mistake being made again - humans are fallible, especially with infrequent operations like releases.  Not sure if it's possible for the on-release GH Action to bump those versions & merge to master before cutting the helm-chart to upload...

**Comment by krmichel** [comment]
The app version and the chart version are not necessarily the same version number.  Especially in a chart like this that manages resources for multiple images.  The chart version can't match the version of the driver and the snapshotter and the attacher.  That being said when installing with helm you can use the set flag to change values.  Like `--set image.tag=v0.7.1` would set the version of the driver to install to 0.7.1 independent of the version of the chart.  The values for the various versions and their defaults for version 0.6.1 of the chart can be found here.
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/aws-ebs-csi-driver/values.yaml#L7:L30

**Comment by ayberk** [comment]
This should be all resolved now thanks to @krmichel.

/close
