### ISSUE TITLE
Helm repo index.yaml out of date

### ISSUE THREAD

**Issue by Chili-Man** [kubernetes-sigs/aws-ebs-csi-driver#587]
**Is your feature request related to a problem?/Why is this needed**
The current Helm repo index.yaml (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/gh-pages/index.yaml) is out of date and pointing to an older version.

/feature

**Describe the solution you'd like in detail**
Please update the Helm repo index.yaml and point it to the published release of the 0.7.0 Helm chart

**Describe alternatives you've considered**
Current work around is to source the helm chart directly from the release as in the provided directions

**Additional context**
This would make the Helm chart experience consistent and up to date

**Comment by galindro** [comment]
I'm facing the same issue also. I would like to install the newer version but I can't. I must say that the current published version has a bug that causes helm to always try to update it. The version on index.yaml is 0.4.0 but the published Chart's version is 0.3.0.

**Comment by galindro** [comment]
PR created with the required update: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/592

@leakingtapan could you please review it?

**Comment by galindro** [comment]
@leakingtapan any return? I really need this feature because the current chart version that is available through the helm repo lacks a nodeAffinity rule that makes it not run inside fargate nodes.

**Comment by Chili-Man** [comment]
Hey @galindro I ended up forking this repo under my company's organization (https://github.com/noteable-io/aws-ebs-csi-driver/tree/gh-pages) and manually publishing the latest version there it there; You should be able to do the same or you can use ours (`helm repo add noteable-aws-ebs-csi-driver https://noteable-io.github.io/aws-ebs-csi-driver`)

**Comment by galindro** [comment]
Yeah, I was considering it as well...

**Comment by Morl99** [comment]
This issue is the updated version of #557

**Comment by krmichel** [comment]
The chart repo has been updated for the current releases

**Comment by Chili-Man** [comment]
@krmichel thank you
