### ISSUE TITLE
Migration from in-tree to ebs csi driver

### ISSUE THREAD

**Issue by njuettner** [kubernetes-sigs/aws-ebs-csi-driver#597]
When migrating to csi-driver and enabling the CSIMigrationAWS feature gate, what happens with the current storage class? Do I need to change the provisioner, is this even possible?

I know that when you create a new pvc with the in-tree storage class Kubernetes will take care it uses the new csi driver.

Additionally do I need to modify existing pvcs to set the new provisioner since I guess it only takes care of new created pvcs after setting the feature gate?

What happens when setting the CSIMigrationComplete does that mean storage class with the in-tree plugin will not work anymore when specified in the pvc?

What would be the best way to transition from in-tree to ebs csi driver?

**Comment by njuettner** [comment]
Sorry for pinging directly here, but @leakingtapan any ideas?

**Comment by msau42** [comment]
With csimigration feature, you don't need to change anything, including the storageclass, and previous PVs.

It's still recommended that any new volumes directly use a csi storageclass, so that they can take advantage of new csi features like snapshots.

**Comment by leakingtapan** [comment]
yep, @msau42 is right.
