### ISSUE TITLE
Push container images to all AWS regions

### ISSUE THREAD

**Issue by ecrousseau** [kubernetes-sigs/aws-ebs-csi-driver#598]
It is great to have the container images available in ECR (see [overlay](https://raw.githubusercontent.com/kubernetes-sigs/aws-ebs-csi-driver/master/deploy/kubernetes/overlays/stable/ecr/kustomization.yaml)) but not all of the images are mirrored to the ap-southeast-2 region, so we can't access them using our private ECR endpoint. For example, 602401143452.dkr.ecr.ap-southeast-2.amazonaws.com/eks/csi-provisioner:v1.5.0 does not exist.

/feature

**Describe the solution you'd like in detail**
Mirror all the images to all AWS regions (or selfishly: at least to ap-southeast-2) so they can be accessed via PrivateLink.

**Describe alternatives you've considered**
We can work around the issue for now by pulling the image over the internet, and pushing into our own ECR.

**Comment by groodt** [comment]
I've run into this issue as well. Seems really problematic.

I can find the images here:
```
docker pull 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/aws-ebs-csi-driver:v0.7.1
docker pull 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/csi-attacher:v1.2.0
```

But this fails bizarrely:
```
docker pull 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/csi-provisioner:v1.5.0
```

Instead, I have to go to us-west-2 for this one image.
```
docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-provisioner:v1.5.0
```

In China, it's similary odd, but with incorrect documentation. https://docs.amazonaws.cn/en_us/eks/latest/userguide/ebs-csi.html

The commands in that documentation don't work.


The images however, do exist in China, but not all of them.

Works
```
docker pull 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/aws-ebs-csi-driver:v0.7.1
docker pull 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-attacher:v1.2.0
```

Missing
```
docker pull 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-provisioner:v1.5.0
```

It's also missing in `cn-north-1`.

**Comment by wongma7** [comment]
/remove-lifecycle rotten
/lifecycle frozen

this is still relevant.

the images are in eks-distro's public ECR repos e.g. public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/overlays/stable/ecr/kustomization.yaml#L10 but I know public ECR doesn't work for everyone (private vpc)

I'll update when this has been fixed

**Comment by ConnorJC3** [comment]
/close

All images should be mirrored to all commercial regions in the aforementioned private ECR repo. Please reopen if you experience any issues.
