### ISSUE TITLE
Add StorageClass support to Helm chart

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/aws-ebs-csi-driver#605]
**Is your feature request related to a problem? Please describe.**
It would be valuable to be able to create a StorageClass to consume this driver together with Helm chart, which is used for deployment.

**Describe the solution you'd like in detail**
Helm chart should have values for enabling storage class management and enabling it as a default storage class. I suppose customizations can be implemented on demand.

**Comment by invidian** [comment]
/remove-lifecycle stale

ehhh, there is even PR opened for this...

**Comment by krmichel** [comment]
@ayberk The tied PR was closed in favor of PR #697 which has been merged so I think this should be closed.
