### ISSUE TITLE
volumesnapshot not working on Amazon Outpost

### ISSUE THREAD

**Issue by rohit-dikkar** [kubernetes-sigs/aws-ebs-csi-driver#615]
/kind bug

**What happened?**   Volumesnapshot READYTOUSE showing **False**

**What you expected to happen?** : VolumeSnapshot should work

**How to reproduce it (as minimally and precisely as possible)?**   

1) Install aws-ebs-csi-driver using helm -- https://github.com/kubernetes-sigs/aws-ebs-csi-driver
2) Created storage class: https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html
3) Applied 3rd party Snapshotter -- https://kubernetes-csi.github.io/docs/snapshot-controller.html 
4) Created volumesnapshotclass -- https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):

[root@mmdedupecentos2 dynamic-provisioning]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.7-eks-bffbac", GitCommit:"bffbacfd13a805a12d10ccc0ca26205ae1ca76e9", GitTreeState:"clean", BuildDate:"2020-07-08T18:30:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Driver version:
CSI Driver Version : v0.7.0 and v0.6.0

**Comment by adam-imeson** [comment]
This is happening on an Outpost, for context.

**Comment by ayberk** [comment]
@rohit-dikkar Would you be able to provide ebs-csi-controller logs by any chance? That'd give us a good starting point for the investigation.

**Comment by manosoft** [comment]
@ayberk 
Attaching logs, me and @rohit-dikkar were checking this together.

[aws-op-csi.log](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/files/5567684/aws-op-csi.log)

Help is appreciated.

**Comment by rohit-dikkar** [comment]
Can someone please check we have to finish the AWS outpost support testing

**Comment by rohit-dikkar** [comment]
In this chart, we are downloading v0.6.0 image and the fix is available in v0.7.0, can someone please confirm?

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/releases/download/v0.7.0/helm-chart.tgz

**Comment by ayberk** [comment]
Yes, we started supporting outposts on version v0.7.0. I thought we fixed the chart, but regardless v0.6.0 wouldn't work on outposts. Please try with the new version.

**Comment by ayberk** [comment]
Closing as it was due to using an older version. Reopen if needed.

/close
