### ISSUE TITLE
New versions on helm chart repository

### ISSUE THREAD

**Issue by trunet** [kubernetes-sigs/aws-ebs-csi-driver#617]
/kind bug

**What happened?**
New versions are not being deployed on helm charts repository. This repository is recent looks like, it was done on https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/520

**What you expected to happen?**
New versions should be available on the helm charts repository.

**How to reproduce it (as minimally and precisely as possible)?**
`curl https://kubernetes-sigs.github.io/aws-ebs-csi-driver/index.yaml`

There's no 0.6, or 0.7 version there.

**Comment by krmichel** [comment]
The chart repo has been updated for the current releases
