### ISSUE TITLE
Support for gp3 volumes

### ISSUE THREAD

**Issue by Chili-Man** [kubernetes-sigs/aws-ebs-csi-driver#628]
**Describe the solution you'd like in detail**
AWS announced the new gp3 ebs class; this driver should support provisioning them. 
https://aws.amazon.com/blogs/aws/new-amazon-ebs-gp3-volume-lets-you-provision-performance-separate-from-capacity-and-offers-20-lower-price/

**Describe alternatives you've considered**
We can work with gp2 for now, but gp3 allows to scale the iops independent of the storage size

**Additional context**

**Comment by wongma7** [comment]
Support has been added to driver version v0.8.0, helm chart version v0.7.0, just released (albeit with some hicccups). 

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG-0.x.md
