### ISSUE TITLE
Don't install snapshot controller

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-ebs-csi-driver#635]
/kind bug

**What happened?** Snapshot controller is installed by helm.

**What you expected to happen?** Snapshot controller should not be installed, the driver should reuse an existing installation of snapshot controller, since the controller might be reused by other drivers. Or helm could somehow check if the controller already exists. Trying to install it again can cause conflict issues.

**How to reproduce it (as minimally and precisely as possible)?** do helm install

**Anything else we need to know?**: see also https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/601

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by wongma7** [comment]
I think the issue is we haven't ujpdated the yamls ever since snapshot controller gto split into a sidecar and separate controller. It's still a bug because we are out of date for not doing so!!

**Comment by ayberk** [comment]
This confused me when I was updating the sidecars for the arm overlay. Unless someone else picks it up by then, I'll do this as part of updating sidecar images.

**Comment by wongma7** [comment]
Our chart's handling of snapshotter controller and CRDs is causing a lot of headaches for both users and maintainers (i have spent way too much time thinking and writing comments about it -_-). I intend to remove the CRDs and controller and simply list it as a prerequisite to the chart. As of 1.20 kops will install the controller and CRDs by default. Other distros may do the same. Users whose distros don't will have to install themselves, we'll link them to https://github.com/kubernetes-csi/external-snapshotter
