### ISSUE TITLE
Release helm-chart aws-ebs-csi-driver-0.8.0

### ISSUE THREAD

**Issue by mhulscher** [kubernetes-sigs/aws-ebs-csi-driver#657]
**Is your feature request related to a problem? Please describe.**
Version 0.8.0 of the aws-ebs-csi-driver has been released. However, the helm-chart (the tarball artifact) with of new version has not yet been released.

**Describe the solution you'd like in detail**
I would like a release of the 0.8.0 helm-chart :) Or I would be happy to know when it is expected to be released.

**Comment by ayberk** [comment]
Our helm chart version is little bit tricky. 0.7.0 chart actually installs the 0.8.0 driver: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/gh-pages/index.yaml#L5

**Comment by mhulscher** [comment]
@ayberk Thank you. I overlooked this. I see that chart 0.7.1 was just released. I will be using that. Thanks again.
