### ISSUE TITLE
Snapshots should support metadata tags

### ISSUE THREAD

**Issue by scoof** [kubernetes-sigs/aws-ebs-csi-driver#660]
**Is your feature request related to a problem?/Why is this needed**
Volumes are already tagged with namespace and pvc metadata. Snapshots lack this data. The CSI snapshot controller adds this data. It just needs to be used in the driver.

**Describe the solution you'd like in detail**
I want these tags to be populated for snapshots:
kubernetes.io/created-for/pv/name
kubernetes.io/created-for/pvc/name
kubernetes.io/created-for/pvc/namespace

**Additional context**
I believe the functionality can be copied/extracted wholesale from CreateVolume: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/af7d1616e69c5be9007abd2ce61e4129260e600c/pkg/driver/controller.go#L172

**Comment by mtougeron** [comment]
I'm new to the CSI drivers but I tried looking into this today. It looks like that metadata isn't passed to the `CreateSnapshot()` as part of the request. It only receives the volume id and the snapshot name. i.e.,

```
I0219 23:21:52.109617       1 controller.go:448] CreateSnapshot: called with args source_volume_id:"vol-0d434e859801e9621" name:"snapshot-3b9e0bbe-a14a-4b75-93dd-57b7be1cd054" 
```

Correct me if I'm wrong, but it appears to run into the same boundary/permission issue as #180 which prevent the plugin from looking up additional information about the PVC the snapshot is for.

Am I looking at this correctly? If not, I'm happy to start digging through the code some more to see what's available. But I think that the metadata would first need to be passed in from the [external-snapshotter](https://github.com/kubernetes-csi/external-snapshotter)

**Comment by jeffhubLR** [comment]
/reopen
Snapshots created by in-tree CSI provider contain the following tags which are not included by snapshots created with aws-ebs-csi snapshotter:
```
kubernetes.io/created-for/pvc/namespace
kubernetes.io/created-for/pv/name
kubernetes.io/created-for/pvc/name
```
Lacking these tags, migrating from in-tree to the aws-ebs-csi provider results in a loss of functionality

**Comment by duckie** [comment]
/reopen

This should not be closed.
