### ISSUE TITLE
How to migrate from GP2 to GP3 ?

### ISSUE THREAD

**Issue by Chili-Man** [kubernetes-sigs/aws-ebs-csi-driver#664]
I've used an earlier version of this driver to create GP2 volumes, however, now that I've upgraded to 0.8.0 ; what is the path to migrate existing PVs and storage classes to the new GP3 volumes?

**Comment by wongma7** [comment]
if the StorageClass does not say "volumeType: gp2" then from now on any PVs created from it will automatically be GP3.

As for existing volumes, there is no Kubernetes API for modifying volume type so I'm afraid that will have to be done directly through the AWS API/console.

**Comment by wongma7** [comment]
Sorry, it's just `type`, not `volumeType`

**Comment by Chili-Man** [comment]
@wongma7 thanks! For me in particular, I did explicitly set the Storage class to gp2; Assuming that I do convert the underlying volume type from gp2 to gp3 through the AWS console; I wouldn't need to modify any of the Kubernetes PVC/sPVs to let it know that the type has changed?

**Comment by wongma7** [comment]
OK, I think you will have to recreate the StorageClass.

> I wouldn't need to modify any of the Kubernetes PVC/sPVs to let it know that the type has changed?
Correct, from the Kubernetes PVC/PV point of view there is no such thing as volume type.

**Comment by Chili-Man** [comment]
I see, thanks, that helps

**Comment by hussainsaify** [comment]
@Chili-Man Were you able to successfully migrate existing volumes from gp2 to gp3 just by modifying volume type from console?

**Comment by Chili-Man** [comment]
@hussainsaify I was indeed able to do so successfully without issue.

**Comment by hussainsaify** [comment]
@Chili-Man Thanks a lot for the swift response.
