### ISSUE TITLE
Helm chart doesn't apply node selectors to snapshot controller

### ISSUE THREAD

**Issue by ScottKGregory** [kubernetes-sigs/aws-ebs-csi-driver#681]
/kind bug

**What happened?**
When deploying on a mixed cluster use nodeSelectors, none get applied to the snapshot controller. This can cause it to get scheduled on Windows nodes where it won't function properly

**What you expected to happen?**
NodeSelector should be set on the statefulset so it only schedules on compatible nodes.

**How to reproduce it (as minimally and precisely as possible)?**
1. Create a cluster with at least one Windows node
2. Deploy the driver via the helm chart with `enableVolumeSnapshot` set to `true`
3. Observe that the pod is sometimes scheduled on the windows node unsuccessfully

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.18
- Driver version: 0.8.0

**Comment by wongma7** [comment]
I am planning actually to remove the snapshot controller altogether https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/635. It is meant to be a generic component that can be reused by multijple drivers, so we shouldn't be installing it...
