### ISSUE TITLE
Prow test jobs status

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-ebs-csi-driver#696]
| Internal/External | arch | Migration   | Status | Details |
|-------------------|------|-------------|--------|--------|
| Internal          | x86  | OFF         | ✅ | | |
| External          | x86  | ON          | ✅ ||
| External          | x86  | ON+Complete | ❌ | |
| External          | x86  | OFF         | ✅ | Not on by default yet |
| Internal          | arm  | OFF         | ❌ | |
| External          | arm  | ON          | ❌ | |
| External          | arm  | ON+Complete | ❌ | |
| External          | arm  | OFF         | ❌ | |

Internal meaning tests under this repo's tests/e2e for exercising EBS or driver specific functionality.
External meaning tests under kubernetes/kubernetes test/e2e for exercising generic/"conformant" CSI functionality. To run them with migration OFF: https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external https://kubernetes-csi.github.io/docs/functional-testing.html. To run with migration ON, "trick" the test by passing the in-tree DriverInfo https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/tests/e2e-migration/e2e_test.go#L93.

**Comment by ayberk** [comment]
External migration is green: https://testgrid.k8s.io/provider-aws-ebs-csi-driver#migration-test-latest
