### ISSUE TITLE
static provisoning example is missing allowed topologies 

### ISSUE THREAD

**Issue by yanivpaz** [kubernetes-sigs/aws-ebs-csi-driver#701]
/kind bug

**What happened?**
When I run this demo :
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/examples/kubernetes/static-provisioning/specs/example.yaml

new pod created in another AZ and therefore new volume is created.
the provided volume is ignored ( volumeHandle: vol-05786ec9ec9526b67 in the example ) 

**What you expected to happen?**
I expected that the pod will be created in the same AZ as the EBS volume

**How to reproduce it (as minimally and precisely as possible)?**
Run the example several times, in some of the cases the pod will be created in another zone and a new EBS will be created.

**Anything else we need to know?**:
Yes
I solved the problem by adding the following to sc:
```
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values:
    - <relevant zone>
```

**Environment**
- Kubernetes version (use `kubectl version`):
- 1.16
- Driver version:
./aws-ebs-csi-driver --version
{
  "driverVersion": "v0.8.0",
  "gitCommit": "",
  "buildDate": "2020-12-09T20:54:37Z",
  "goVersion": "go1.14.1",
  "compiler": "gc",
  "platform": "linux/amd64"
}

**Comment by yanivpaz** [comment]
maybe NoVolumeZoneConflict should be defined in scheduler policy?

**Comment by wongma7** [comment]
Yes, you need NoVolumeZoneConflict (one of the default predicates) so that scheduler respects WaitForFirstConsumer which is intended to save you from having to specify allowedTopologies https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies
