### ISSUE TITLE
x509 error when attempting to helm chart

### ISSUE THREAD

**Issue by bsakweson** [kubernetes-sigs/aws-ebs-csi-driver#706]
/kind bug

**What happened?**
Ran helm command to install `aws-ebs-csi-driver` using terraform scripts and go this error
`looks like "https://kubernetes-sigs.github.io/aws-ebs-csi-driver" is not a valid chart repository or cannot be reached: Get "https://kubernetes-sigs.github.io/aws-ebs-csi-driver/index.yaml": x509: certificate signed by unknown authority`

I can run the same commands locally targeting the same cluster successfully.

**What you expected to happen?**
Expected a successful installation
**How to reproduce it (as minimally and precisely as possible)?**
User terraform's helm_release to deploy this chart.
**Anything else we need to know?**:
`version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}`
**Environment**
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
- Driver version:

**Comment by wongma7** [comment]
The cert is GitHub's, is it possible the location you are running the helm chart from doesn't trust it

```
~ $ nmap -p 443 --script ssl-cert kubernetes-sigs.github.io
Starting Nmap 7.80 ( https://nmap.org ) at 2021-01-26 13:57 PST
Nmap scan report for kubernetes-sigs.github.io (185.199.111.153)
Host is up (0.0035s latency).
Other addresses for kubernetes-sigs.github.io (not scanned): 185.199.110.153 185.199.109.153 185.199.108.153

PORT    STATE SERVICE
443/tcp open  https
| ssl-cert: Subject: commonName=www.github.com/organizationName=GitHub, Inc./stateOrProvinceName=California/countryName=US
| Subject Alternative Name: DNS:www.github.com, DNS:*.github.com, DNS:github.com, DNS:*.github.io, DNS:github.io, DNS:*.githubusercontent.com, DNS:githubusercontent.com
| Issuer: commonName=DigiCert SHA2 High Assurance Server CA/organizationName=DigiCert Inc/countryName=US
| Public Key type: rsa
| Public Key bits: 2048
| Signature Algorithm: sha256WithRSAEncryption
| Not valid before: 2020-05-06T00:00:00
| Not valid after:  2022-04-14T12:00:00
| MD5:   120f 9db4 e44e cc8a 9f75 affd 436e c5d0
|_SHA-1: 7094 dedd e6c4 6948 3a92 70a1 4856 782d 1864 e0b7

Nmap done: 1 IP address (1 host up) scanned in 0.27 seconds
```

**Comment by bsakweson** [comment]
I do not think so because I can access Github from the same laptop and can also get the chart when using helm on terminal. I experience this issue only when running terraform helm provider.

**Comment by krmichel** [comment]
This is basically a restatement of what @wongma7 said above.  The cert on that chart repo is the same cert you will see used for a number of github addresses.  It is issued by the `DigiCert SHA2 High Assurance Server CA intermediate` with `DigiCert High Assurance EV Root CA as the root CA`.  It isn't special to this project.  Here are a list of the subject alternative names for the cert:
DNS Name=www.github.com
DNS Name=*.github.com
DNS Name=github.com
DNS Name=*.github.io
DNS Name=github.io
DNS Name=*.githubusercontent.com
DNS Name=githubusercontent.com

Where is terraform running and what CA cert bundle is being used?  That is likely the path of questions that will lead you to getting this working.  This project has no control over the certificate in use; it is managed by github.

You may need to set this on your helm_release in your terraform resource.
https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#repository_ca_file
