### ISSUE TITLE
AWS EBS CSI Driver Helm chart to inject environment variables

### ISSUE THREAD

**Issue by barric1** [kubernetes-sigs/aws-ebs-csi-driver#722]
We’d like the AWS EBS CSI Driver Helm chart to have an option to inject environment variables to pods, so that we can set AWS_STS_REGIONAL_ENDPOINTS=regional and use the Helm chart as-is without patching it after the deployment to a private VPC. 

Alternatives considered aren't considered workable for deployments at scale as we want to deploy at scale and keep our configurations as simple as possible.

**Comment by georambo** [comment]
I need this as well.  ebs-plugin only works for me when we make the calls through an proxy, so need to drop in 
```
ENV:
  - name: https_proxy
    value: xxxxxx
```


This is pretty common feature in most charts though, to drop in additional environment variables.

**Comment by ayberk** [comment]
related #765

**Comment by ayberk** [comment]
/close 

see #817
