### ISSUE TITLE
Helm chart should default enableVolumeScheduling: true

### ISSUE THREAD

**Issue by aaroniscode** [kubernetes-sigs/aws-ebs-csi-driver#727]
/kind bug

**What happened?**
Deployed the default helm chart and topology aware dynamic provisioning did not work. The kustomize based manifest default to true: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/values/controller.yaml#L4

**What you expected to happen?**
With the CSI Topology sub-feature at GA status, I would expect this feature gate to default to true.

Thoughts on this?  Is there still a good reason to default the Helm chart to not use the Topology feature?

**Comment by ayberk** [comment]
Agreed we can default to true.

/good-first-issue
