### ISSUE TITLE
Cannode Deploy the EBS CSI driver in cn-north-1 and cn-northwest-1

### ISSUE THREAD

**Issue by arestuzi** [kubernetes-sigs/aws-ebs-csi-driver#743]
According to the public document, I should run following command to deploy ebs csi in cn-north-1 and cn-northwest-1, but it returns following errors,
```
kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable-cn/?ref=master"
error: evalsymlink failure on '/tmp/kustomize-337273498/deploy/kubernetes/overlays/stable-cn' : lstat /tmp/kustomize-337273498/deploy/kubernetes/overlays/stable-cn: no such file or directory
```
I cannot pull images from k8s.gcr.io repository from the instances deployed in China region, any workaround?
```
Events:
  Type     Reason     Age   From                                                   Message
  ----     ------     ----  ----                                                   -------
  Normal   Scheduled  35s   default-scheduler                                      Successfully assigned kube-system/ebs-csi-controller-69db74bbbd-5rfww to ip-192-168-48-73.cn-north-1.compute.internal
  Normal   Pulling    34s   kubelet, ip-192-168-48-73.cn-north-1.compute.internal  Pulling image "k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.9.0"
  Warning  Failed     19s   kubelet, ip-192-168-48-73.cn-north-1.compute.internal  Failed to pull image "k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.9.0": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     19s   kubelet, ip-192-168-48-73.cn-north-1.compute.internal  Error: ErrImagePull
  Normal   Pulling    19s   kubelet, ip-192-168-48-73.cn-north-1.compute.internal  Pulling image "k8s.gcr.io/sig-storage/csi-provisioner:v2.0.2"
  Warning  Failed     4s    kubelet, ip-192-168-48-73.cn-north-1.compute.internal  Failed to pull image "k8s.gcr.io/sig-storage/csi-provisioner:v2.0.2": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     4s    kubelet, ip-192-168-48-73.cn-north-1.compute.internal  Error: ErrImagePull
  Normal   Pulling    4s    kubelet, ip-192-168-48-73.cn-north-1.compute.internal  Pulling image "k8s.gcr.io/sig-storage/csi-attacher:v3.0.0"
```

**Comment by ayberk** [comment]
Can you try pulling `918309763551.dkr.ecr.cn-north-1.amazonaws.com.cn/eks/aws-ebs-csi-driver:v0.9.0`?

**Comment by arestuzi** [comment]
thanks, I can pull this image from instances launched in China region. I tried other images, seems that they are not existed yet.
like 
918309763551.dkr.ecr.cn-north-1.amazonaws.com.cn/eks/csi-provisioner:v2.0.2
918309763551.dkr.ecr.cn-north-1.amazonaws.com.cn/eks/csi-attacher:v3.0.0

**Comment by ayberk** [comment]
Those sidecar images are available in the [public ECR gallery](https://gallery.ecr.aws/?searchTerm=csi). I just launched an instance in BJS and verified that they can be pulled. 

The workaround I can think of is using the [ECR overlay](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/overlays/stable/ecr/kustomization.yaml) after updating the driver image. So it should look like this:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../base
images:
- name: k8s.gcr.io/provider-aws/aws-ebs-csi-driver
  newName: 918309763551.dkr.ecr.cn-north-1.amazonaws.com.cn/eks/aws-ebs-csi-driver
  newTag: v0.9.0
- name: quay.io/k8scsi/csi-provisioner
  newName: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
  newTag: v2.0.3-eks-1-18-1
- name: quay.io/k8scsi/csi-attacher
  newName: public.ecr.aws/eks-distro/kubernetes-csi/external-attacher
  newTag: v3.0.1-eks-1-18-1
- name: quay.io/k8scsi/livenessprobe
  newName: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
  newTag: v2.1.0-eks-1-18-1
- name: quay.io/k8scsi/csi-node-driver-registrar
  newName: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
  newTag: v2.0.1-eks-1-18-1
```

If you then apply this via `kubectl apply -k`, you should be able to pull all images. This should unblock you until we push those images.

**Comment by ConnorJC3** [comment]
Hello! AWS China users may not be able to install the EBS CSI Driver via the helm chart because ECR Public may be inaccessible in China. However, the EBS CSI Driver is available as an EKS Addon in AWS China, which is fully featured and works exactly the same as the EKS Addon in other regions. AWS China users can install the CSI driver through the EKS Addon. Documentation is available in [English](https://docs.amazonaws.cn/en_us/eks/latest/userguide/ebs-csi.html) or [Mandarin](https://docs.amazonaws.cn/eks/latest/userguide/ebs-csi.html) on the installation and usage of the EKS Addon for AWS China regions.
