### ISSUE TITLE
node-driver-registrar preStop fails because /bin/sh doesn't exist

### ISSUE THREAD

**Issue by kgtw** [kubernetes-sigs/aws-ebs-csi-driver#747]
/kind bug

**What happened?**

preStop lifecycle hook isn't executed because `/bin/sh` doesn't exist within the registrar docker image.

See: https://github.com/kubernetes-csi/node-driver-registrar/blob/v2.0.1/Dockerfile

**What you expected to happen?**

lifecycle hook to execute successfully.

**How to reproduce it (as minimally and precisely as possible)?**

Deploy latest manifests with registrar version `v2.0.1` and observe when the pod/container is shutting down the preStop command fails to execute.

```
Exec lifecycle hook ([/bin/sh -c rm -rf /registration/ebs.csi.aws.com-reg.sock /csi/csi.sock]) for Container "node-driver-registrar" in Pod "ebs-csi-node-96jbk_ebs-csi(a82c6d41-bd2b-42dd-b092-e3acd4c43b62)" failed - error: command '/bin/sh -c rm -rf /registration/ebs.csi.aws.com-reg.sock /csi/csi.sock' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: \"/bin/sh\": stat /bin/sh: no such file or directory: unknown\r\n"
```

See: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/base/node.yaml#L71-L80

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.19.7
- Driver version:

provider-aws/aws-ebs-csi-driver:v0.9.0
k8scsi/csi-node-driver-registrar:v2.0.1
k8scsi/livenessprobe:v2.1.0

**Comment by tsunny** [comment]
We are seeing the same issue on our clusters too.

**Comment by wongma7** [comment]
LEt's remove the hook, node driver registrar already does this by itself https://github.com/kubernetes-csi/node-driver-registrar/pull/61

**Comment by tsunny** [comment]
@wongma7 - thanks for the response. This should be updated in the helm templates in the repo right? https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/747#issuecomment-790968689

**Comment by wongma7** [comment]
Yes, (and the kustomize via `make generate-kustomize`

**Comment by tsunny** [comment]
@wongma7 - PR for this - https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/778. 
TIA

**Comment by krmichel** [comment]
@wongma7 Looks like this didn't get linked to PR #778 and therefore didn't get closed.
