### ISSUE TITLE
Upgrade livenessprobe to patch memory leak

### ISSUE THREAD

**Issue by unixninja92** [kubernetes-sigs/aws-ebs-csi-driver#749]
/kind bug

**What happened?**
livenessprobe v2.1.0 has a memory leak causing it use way more ram than needed. This is patched in [livenessprobe v2.2.0
](https://github.com/kubernetes-csi/livenessprobe/blob/master/CHANGELOG/CHANGELOG-2.2.md#bug-or-regression)
**What you expected to happen?**
livenessprobe containers usually use ~5MB of ram. 

**How to reproduce it (as minimally and precisely as possible)?**
Let livenessprobe run for a while and watch ram usage.

**Comment by ayberk** [comment]
We're already using v2 so this should be a simple change. Thanks for the report!

/good-first-issue

**Comment by mowangdk** [comment]
@ayberk  If you don't mind, I would like to take up this issue~
