### ISSUE TITLE
Multiarch image was not uploaded on k8s.gcr.io/provider-aws/aws-ebs-csi-driver

### ISSUE THREAD

**Issue by DingGGu** [kubernetes-sigs/aws-ebs-csi-driver#757]
/kind bug

**What happened?**
`image: k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.9.0`
was not compatibility with arm64.

```
kubectl -n kube-system logs ebs-csi-node-56hf2 --all-containers
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
```

However, ebs-csi-driver already support multiarch using arm64
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/.github/workflows/container-image.yaml

I try to using dockerhub `image: amazon/aws-ebs-csi-driver:v0.9.0` was work properly.

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by wongma7** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/aws-ebs-csi-driver-push-images/1360032576340758528 succeeded, will check the image in staging repo...

**Comment by wongma7** [comment]
For me there appears to be an aarch64 image published at k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.9.0, I am not sure why in your case kubelet is not pulling it . I'll have to try to reproduce on my cluster


# file /bin/aws-ebs-csi-driver
/bin/aws-ebs-csi-driver: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=sb6zFW7URrvDtpRWYvI6/nGz0qTeA2RKrMeGzDbTj/bbz0_nxDjMaJL5K2sDX6/FYCLNEasQlHaPE8RR44A, stripped

**Comment by DingGGu** [comment]
I think I was mistaken. I just tested it and it works.

**Comment by giuscri** [comment]
can reproduce with `v2.1.1-eksbuild.1`:
```
efs-plugin exec /bin/aws-efs-csi-driver: exec format error
```

**Comment by torredil** [comment]
Hi there @giuscri, issues related to the `aws-efs-csi-driver` should be reported here: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/new
