### ISSUE TITLE
Dynamic-provisioning of EBS Volume is failing :  NoCredentialProviders: no valid providers in chain caused by: EnvAccessKeyNotFound: failed to find credentials in the environment 

### ISSUE THREAD

**Issue by shivani-hotstar** [kubernetes-sigs/aws-ebs-csi-driver#763]
/kind bug
Hello 
So As mentioned under [https://github.com/kubernetes-sigs/aws-ebs-csi-driver#set-up-driver-permission](url)
we can either use secret option or iam policy attached to all worker nodes .
So i went with 2nd option and attached [https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/example-iam-policy.json](url) same policy to my all cluster nodes (master and worker node role).

Application deployed this --> [https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/dynamic-provisioning/specs](url)

After **
i have attached access policy to all worker nodes 

Error :

```
I0223 14:57:28.570589       1 connection.go:185] GRPC response: {}
I0223 14:57:28.570641       1 connection.go:186] GRPC error: rpc error: code = Internal desc = NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: EC2MetadataError: failed to make EC2Metadata request
	status code: 404, request id:
caused by: empty role
I0223 14:57:28.570665       1 controller.go:645] CreateVolume failed, supports topology = true, node selected true => may reschedule = true => state = Finished: rpc error: code = Internal desc = NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: EC2MetadataError: failed to make EC2Metadata request
	status code: 404, request id:
caused by: empty role
I0223 14:57:28.570701       1 controller.go:1084] Final error received, removing PVC b6811715-aa76-4cbc-8a5b-29b9864dea69 from claims in progress
W0223 14:57:28.570713       1 controller.go:943] Retrying syncing claim "b6811715-aa76-4cbc-8a5b-29b9864dea69", failure 6
E0223 14:57:28.570731       1 controller.go:966] error syncing claim "b6811715-aa76-4cbc-8a5b-29b9864dea69": failed to provision volume with StorageClass "ebs-sc": rpc error: code = Internal desc = NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: EC2MetadataError: failed to make EC2Metadata request
	status code: 404, request id:

```

I have removed env from deployment  ebs-csi-controller spec as well :

```
- name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: key_id
              name: aws-secret
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: access_key
              name: aws-secret
              optional: true
```
Still facing the same above error.

2). I tried deploying via secret as well but in this case i am facing below error .

Error :

```
I0223 15:01:51.550753       1 connection.go:185] GRPC response: {}
I0223 15:01:51.550803       1 connection.go:186] GRPC error: rpc error: code = Internal desc = AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: f9ff2f59-7901-425c-8471-665a0c02ce6b
I0223 15:01:51.550843       1 controller.go:645] CreateVolume failed, supports topology = true, node selected true => may reschedule = true => state = Finished: rpc error: code = Internal desc = AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: f9ff2f59-7901-425c-8471-665a0c02ce6b
I0223 15:01:51.550913       1 controller.go:1084] Final error received, removing PVC b6811715-aa76-4cbc-8a5b-29b9864dea69 from claims in progress
W0223 15:01:51.550938       1 controller.go:943] Retrying syncing claim "b6811715-aa76-4cbc-8a5b-29b9864dea69", failure 6
E0223 15:01:51.550962       1 controller.go:966] error syncing claim "b6811715-aa76-4cbc-8a5b-29b9864dea69": failed to provision volume with StorageClass "ebs-sc": rpc error: code = Internal desc = AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: f9ff2f59-7901-425c-8471-665a0c02ce6b
I0223 15:01:51.551005       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"test-remove-spike", Name:"ebs-claim", UID:"b6811715-aa76-4cbc-8a5b-29b9864dea69", APIVersion:"v1", ResourceVersion:"279454308", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "ebs-sc": rpc error: code = Internal desc = AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: f9ff2f59-7901-425c-8471-665a0c02ce6b

```

Lemme clarify one thing here that after making above changes i only rotated these pods  .
`ebs-csi-controller-6ddc68647d-lxztd                                   6/6     Running            0          24m
ebs-csi-controller-6ddc68647d-nvcm4                                   6/6     Running            0          24m`

Kubernetes version (use kubectl version): k8s version i have --> v1.17.12
Driver version: k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.9.0

Any idea what is missing here ?

_Originally posted by @shivani-hotstar in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/714#issuecomment-784281594_

**Comment by khushboo121** [comment]
@shivani-hotstar I am also facing same issue while provisioning EBS volume. 
Did you get any solution to resolve the issue?

**Comment by bala-gif** [comment]
Facing same issue... Why no one responds ?

**Comment by ConnorJC3** [comment]
@bala-gif (as well as anyone else having this issue), could you please:

1. Provide the driver version (as well as helm chart version if you are installing via helm)
2. Confirm that your driver log contains lines that look like `EC2MetadataError: failed to make EC2Metadata request status code: 404`
3. Identify which of the three methods to setup permissions for the driver you used and describe how you did so

**Comment by arnoldokoth** [comment]
Hi, I'm facing the same issue. I installed the driver as an EKS add-on.
 
Version: v1.17.0-eksbuild.1

Logs from Deployment:
`E0427 09:39:36.961718       1 driver.go:120] "GRPC error" err=<
	rpc error: code = Internal desc = Could not create volume "pvc-5ff07536-2d78-40aa-b393-308867a30c4e": could not create volume in EC2: NoCredentialProviders: no valid providers in chain
	caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
	SharedCredsLoad: failed to load profile, .
	EC2RoleRequestError: no EC2 instance role found
	caused by: RequestError: send request failed
	caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
 >`

Logs from DaemonSet:
`Found 10 pods, using pod/ebs-csi-node-5s29g
I0421 13:57:18.530579       1 driver.go:73] "Driver Information" Driver="ebs.csi.aws.com" Version="v1.17.0"
I0421 13:57:18.530677       1 node.go:81] "regionFromSession Node service" region=""
I0421 13:57:18.530691       1 metadata.go:85] "retrieving instance data from ec2 metadata"
I0421 13:57:18.532983       1 metadata.go:92] "ec2 metadata is available"
I0421 13:57:18.534121       1 metadata_ec2.go:25] "Retrieving EC2 instance identity metadata" regionFromSession=""
`

**Comment by ConnorJC3** [comment]
Hi @arnoldokoth , this is likely an issue with your cluster's networking setup, the EBS CSI Controller pod is unable to reach IMDS.

If IMDS is your intended method of supplying the credentials (i.e. you did *not* provide a role when installing the EKS-managed addon), please fix your cluster such that the driver is able to reach IMDS.

If IMDS is _not_ your intended method of supplying the credentials (i.e. you have configured IRSA and supplyed a role when installing the driver), please reach out to AWS support for debugging why your IRSA is not working.

**Comment by arnoldokoth** [comment]
Hi @ConnorJC3 

I had initially configured the add-on to inherit the node role but after running into this issue I changed it to using a service account and IAM role but the issue persisted. Is there something else I need to do on the cluster after updating the permissions? 

I went through this troubleshooting guide and everything checks out fine: https://repost.aws/knowledge-center/eks-troubleshoot-ebs-volume-mounts

**Comment by arnoldokoth** [comment]
I updated the plugin and it seems to be working now.
