### ISSUE TITLE
Deploying using helm chart with snapshot enabled cause error in snapshot controller

### ISSUE THREAD

**Issue by JonathanLachapelle** [kubernetes-sigs/aws-ebs-csi-driver#798]
/kind bug

**What happened?**
Following error in ebs-snapshot-controller : 
I0316 14:58:34.096981       1 reflector.go:243] Listing and watching *v1beta1.VolumeSnapshotContent from github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117
E0316 14:58:34.099121       1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotContent: failed to list *v1beta1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)

**What you expected to happen?**
No error

**How to reproduce it (as minimally and precisely as possible)?**
Deploy via helm chart in a 1.17 kubernetes cluster with the following parameters : 

enableVolumeScheduling: true
enableVolumeResizing: true
enableVolumeSnapshot: true

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Driver version: v0.9.0

**Comment by wongma7** [comment]
the helm chart is missing the CRD. related: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/536 https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/797

Please install them https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd

**Comment by krmichel** [comment]
This issue is related to issue #635

**Comment by krmichel** [comment]
Version 2.0.0 of the helm chart no longer installs the snapshot controller or its CRDs.  The [snapshot controller](https://github.com/kubernetes-csi/external-snapshotter) is now listed as a pre-req if you want to use snapshot functionality.  The `enableVolumeSnapshot` value no longer exists and the sidecar is enabled based on whether the snapshot API is available in the target cluster.
