### ISSUE TITLE
EBS GP3 driver is not tagging volumes or naming volumes.

### ISSUE THREAD

**Issue by joshi55** [kubernetes-sigs/aws-ebs-csi-driver#800]
When deploying EBS volumes using GP3 CSI driver, it is not giving any name to EBS volumes. Volume names appear empty.
Also, it is not adding any information related to application or cluster in Tags.

We are using EKS v1.17.12 and are deploying the CSI with the command :
```
kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-0.8"
```
and then we added gp3 storage class

```
kubectl get sc
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   true                   320d
gp3             ebs.csi.aws.com         Delete          WaitForFirstConsumer   true                   50d
```

Then we deployed a simple stateful set which uses gp3 driver.  When we list its volume, it shows as
```
kubectl get pvc

NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
myappvol-myapp-0   Bound    pvc-9d466654-ab1a-4ed9-b6c0-1d544937485f   1Gi        RWO            gp3            20s
```
But it is not tagging the volume with any application related information or naming the volume (as it does with gp2)

![image](https://user-images.githubusercontent.com/30019842/111646419-a28c0f00-87cf-11eb-99dc-2e21446f9552.png)

**Same application deployed in same cluster using GP2**

But in the same EKS cluster, if i deploy same application using gp2 driver, it tags the volume properly with all information as shown below: 
```
kubectl get pvc
NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
myappvol-myapp-0   Bound    pvc-306e2076-d96e-4aef-ba12-5d494de5c5dc   1Gi        RWO            gp2            8s
```
![image](https://user-images.githubusercontent.com/30019842/111658626-86419f80-87da-11eb-89ab-401ee1dc5f4e.png)

We tried with CSI driver 0.9 too for gp3. But the issue was the same.

May we know how to resolve this issue ?

**Comment by AndyXiangLi** [comment]
@joshi55 Looks like the gp3 volume is provisioned by ebs-csi-driver and your gp2 volume is provisioned by k8s in-tree driver.
ebs-csi-driver will only add CSIVolumeName by default. If you need to add  one of these tags ("kubernetes.io/created-for/pvc/namespace", "kubernetes.io/created-for/pv/name", "kubernetes.io/created-for/pvc/name" ) to your volume when using ebs-csi-driver, you can specify the key and value in the storageclass, but please not both key and value are static. 
storageclass example:
```kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: io1
  iopsPerGB: "50"
  encrypted: "true"
  kubernetes.io/created-for/pvc/namespace: namespaceName
  kubernetes.io/created-for/pvc/name: pvcName
  kubernetes.io/created-for/pv/namespace: pvName
```

**Comment by joshi55** [comment]
>  kubernetes.io/created-for/pvc/namespace: namespaceName
>   kubernetes.io/created-for/pvc/name: pvcName
>   kubernetes.io/created-for/pv/namespace: pvName

@AndyXiangLi This is not going to work... as we volumes are provisioned dynamically, how can we have that static information for application name ? Also, there can be hundreds and hundreds of such volumes..

**Comment by AndyXiangLi** [comment]
@joshi55 Understand that, those are most FYI. CSI driver is adding the dynamic volume name under CSIVolumeName tag, let me re-phrase the previous statement to reduce confusion.

**Comment by AndyXiangLi** [comment]
There is an on-going tag discussion in #180. We definitely need to provide ability to add tags on demand.

**Comment by mapdegree** [comment]
Hi @AndyXiangLi ,
Is the functionality for adding tags on demand via CSI already introduced?
