### ISSUE TITLE
unable to get the pvs attached on ebs volumes on faragte eks cluster

### ISSUE THREAD

**Issue by daparthi001** [kubernetes-sigs/aws-ebs-csi-driver#810]
We are not able to bring the volumes up with CSI driver .

Warning  FailedScheduling  58m   fargate-scheduler  Pod not supported on Fargate: volumes not supported: storage-volume not supported because: PVC prometheus-server bound to invalid PV pvc-a996c34f-eba8-45d1-9820-e5bc19ce325c with CSI Driver: ebs.csi.aws.com

**Environment**
- Driver version:0.9.0

**Comment by ayberk** [comment]
EBS is not supported on fargate, only EFS. 

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-task-storage.html

**Comment by ayberk** [comment]
I've found [this](https://aws.amazon.com/blogs/aws/new-aws-fargate-for-amazon-eks-now-supports-amazon-efs/), hope it helps!
