### ISSUE TITLE
gp3 volumes not detected by kubelet metrics

### ISSUE THREAD

**Issue by joshi55** [kubernetes-sigs/aws-ebs-csi-driver#816]
/kind bug

GP3 volumes provisioned using this CSI driver are not detected by kublets. Thus prometheus is not able to detect these volumes and alert if they are almost full.

kubelet_volume_stats_available_bytes doesn't list those volumes at all in prometheus, but it lists all other volumes provisioned using io1 or gp2 drivers

We are using EBS CSI v0.8.1 driver.

EKS Kubernetes version : v1.17.12

NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   true                   164d
gp3             ebs.csi.aws.com         Delete          WaitForFirstConsumer   true                   39h

**Comment by wongma7** [comment]
to be clear you mean gp2 provisioned by csi has metrics but not gp3 provisioned by csi? do you have driver logs by any chance ? Are there any mentions of 'NodeGetVolumeStats' errors?

**Comment by Firaenix** [comment]
Bump
