### ISSUE TITLE
IOPS Change

### ISSUE THREAD

**Issue by srfaytkn** [kubernetes-sigs/aws-ebs-csi-driver#818]
Hello, i created a storageclass with iopsPerGB value 10 and I have a 100 gb pvc.

1-Does it cause any bug if it dynamically increases and decreases the io value from the aws console?
2-After dynamically changing the iops value from the aws console, does a size update from the csi driver cause a bug?
3-If these are causing the problem, how can I dynamically update the iops value regardless of the volume size

thanks

/triage support

**Comment by wongma7** [comment]
1. No, you should be able to update iops after the fact, driver won't try to 'reconcile' it back or anything like that.
2. No, resize won't affect iops, the " ModifyVolume" API call only includes a size arg, no iops arg.

**Comment by srfaytkn** [comment]
thank you for help @wongma7

**Comment by wongma7** [comment]
@carloruiz I didn't think of that but it makes sense.

@ayberk what do you think, should resize also update iops?

**Comment by ayberk** [comment]
Yeah I think that makes sense in this case. Since iopsPerGB is set, it really isn't a surprise bill situation.

**Comment by srfaytkn** [comment]
After this changes, can I still dynamically update the iops value regardless of the volume size from the aws console? Sometimes iops increase may be required without the need for a larger disk size.

**Comment by yuha0** [comment]
Hi, I came across this issue and wanted to second @carloruiz 's proposal. 

When I saw a configuration key "iopsPerGB", I didn't expect it to mean "iopsPerGB at volume creation time only". Shouldn't the desired IOPS always be set based on `iopsPerGB` and the actual size of the volume? 

This gives the users ability to (indirectly) change IOPS from the PVC API and I think it makes sens since they can use volume expansion API on the PVC to resize the volume already. 

@wongma7 @ayberk  what do you think?

**Comment by wongma7** [comment]
/reopen

Yeah I do still agree it makes sense. If we are worried about deviating from how this has functioned historically/in in-tree driver or surprise bill situations then it could be behind a flag but it could be the default behavior

we would need CSI changes https://github.com/container-storage-interface/spec/issues/491 to directly change IOPS so until then this seems the best we can do

**Comment by luanguimaraesla** [comment]
Hi folks, anything new on this front? This change would be precious to make it easier when migrating from `gp2` to `gp3` without impacting users expecting the old behavior. This would allow a seamless migration, without the necessity to update all Helm charts and controllers at the first moment.

**Comment by kevincantu** [comment]
Can the behavior here be documented?
