### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by pjajootibco** [kubernetes-sigs/aws-ebs-csi-driver#837]
I have a question regarding EBS Driver for Windows? Is https://github.com/kubernetes-sigs/aws-ebs-csi-driver this driver supported for Windows? If yes, how can enable it, I could not find examples or any documentation on the Github project. But I found an open ticket for windows support https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/243, hence wanted to check if it is supported at all?
If it's not supported, what are the workarounds? Do I still need to use the in-tree support?

**Comment by AndyXiangLi** [comment]
Hi @pjajootibco, windows is not supported for current version, you will need to use in-tree driver for windows nodes. 
We are working on this and you can track the status in PR #823
