### ISSUE TITLE
[node] Is hostNetwork:true mandatory?

### ISSUE THREAD

**Issue by dntosas** [kubernetes-sigs/aws-ebs-csi-driver#839]
Hello team!

A quick one, is `hostNetwork: true` mandatory for node daemonSet? Check in here --> https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/61d72fc8b1bc9ebcbc78288d9a07dc08db91be59/charts/aws-ebs-csi-driver/templates/node.yaml#L36

We manage to run the Driver successfully without this and wonder if we miss something in here.

/triage support

**Comment by wongma7** [comment]
The reason it is there is because driver needs access to instance metadata. we are working on removing this requirement https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/474 by falling back to other means of getting info if instance metadata is unavailable

**Comment by dntosas** [comment]
thanx @wongma7 makes sense :)

**Comment by groodt** [comment]
Now that https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/474 has been resolved, does the DaemonSet still require access to the `hostNetwork`? The YAML is currently still specifying it.
