### ISSUE TITLE
Reduce default log verbosity 

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-ebs-csi-driver#854]
/kind bug

**What happened?** the verbosity is set to 5 by default, https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/node.yaml#L64 . see the description of levels here : 4/5 are meant for debugging  https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md 

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by wongma7** [comment]
see also efs equivalent https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/426

**Comment by dorroddorrod** [comment]
Any updates on this ? 
The controller basically bombarding our logging database (ES) with lots of `info` messages

**Comment by wongma7** [comment]
@dorroddorrod you may manually edit the controller deployment yaml or node daemonset --v arg as shown in the patch https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/903/files 

After the patch gets merged verbosity 2 will be default

**Comment by dorroddorrod** [comment]
Can we set the verbosity level using helm ? 
for example
```
extraArgs:
  v: 0
```
