### ISSUE TITLE
WaitForAttach even when device is already assigned

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#86]
/kind bug

Inside `AttachDisk` [call](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/cloud/cloud.go#L303), `c.waitForAttachmentState` is called even when the device is already assigned. We should only call it when device is not attached.

**Comment by bertinatto** [comment]
This is similar to the in-tree implementation and I think it's not a bug actually.

If `AttachDisk` is called when the device is already marked as "attaching", we want it to wait until it becomes "attached".

**Comment by leakingtapan** [comment]
You're right. I didn't realized that the same `AttachDisk` call could be called by CO again while one is already in progress.

/close
