### ISSUE TITLE
Fast Snapshot Restore Support

### ISSUE THREAD

**Issue by timmyers** [kubernetes-sigs/aws-ebs-csi-driver#869]
**Describe the solution you'd like in detail**
I would like a way (potentially via a parameter of the `VolumeSnapshotClass`) for EBS snapshots to have Fast Snapshot Restore (FSR) enabled https://aws.amazon.com/blogs/aws/new-amazon-ebs-fast-snapshot-restore-fsr/.

**Describe alternatives you've considered**
Enabling FSR on snapshots outside the loop of the EBS CSI driver.

**Comment by abatilo** [comment]
This would actually be incredibly useful.

**Comment by AndyXiangLi** [comment]
Hi @timmyers , Do you just want FSR enabled or want driver to enable it upon snapshot creation? You can always enable the FSR on EBS console and driver will take advantages of that when restore volume from snapshot.  [ref](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-fast-snapshot-restore.html)

**Comment by timmyers** [comment]
I am ideally looking for the ability of the driver to enable it upon snapshot creation.  I think the UX of having a `VolumeSnapshotClass` that specifies this as a parameter would make sense.

**Comment by aayushrangwala** [comment]
I would like to work on this

/assign

**Comment by abencomoc** [comment]
/reopen

There is an increased interest of users to have this feature available. Reopening the request...
