### ISSUE TITLE
EBS CSI Driver of alpha driver does not allow for EBS volume resize due to change in the clusterrolebinding subject serviceaccount that is pointing to default namespace

### ISSUE THREAD

**Issue by gowthams316** [kubernetes-sigs/aws-ebs-csi-driver#872]
/kind bug

**What happened?**
EBS CSI Driver of alpha driver does not allow for EBS volume resize due to change in the clusterrolebinding subjects serviceaccount `ebs-csi-controller-sa` that is pointing to `default` namespace instead of `kube-system` namespace. 

**What you expected to happen?**
When I use the alpha version of EBS csi driver by `kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/alpha/?ref=master"` and try to resize the EBS volume by following the resize example and it throws the following error messages:
```
  Warning  ExternalExpanding      12s                  volume_expand                                                                             Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
```

On checking the EBS CSI controller pod logs could see below error messages:
```
I0506 02:52:51.916175       1 controller.go:281] Started PVC processing "default/ebs-claim"
E0506 02:52:51.918341       1 controller.go:272] Error syncing PVC: marking pvc "default/ebs-claim" as resizing failed: can't patch status of  PVC default/ebs-claim with persistentvolumeclaims "ebs-claim" is forbidden: User "system:serviceaccount:kube-system:ebs-csi-controller-sa" cannot patch resource "persistentvolumeclaims/status" in API group "" in the namespace "default"
I0506 02:53:23.918689       1 controller.go:281] Started PVC processing "default/ebs-claim"
E0506 02:53:23.920605       1 controller.go:272] Error syncing PVC: marking pvc "default/ebs-claim" as resizing failed: can't patch status of  PVC default/ebs-claim with persistentvolumeclaims "ebs-claim" is forbidden: User "system:serviceaccount:kube-system:ebs-csi-controller-sa" cannot patch resource "persistentvolumeclaims/status" in API group "" in the namespace "default"
```

**How to reproduce it (as minimally and precisely as possible)?**
- Use the alpha version of EBS csi driver with below command. 
 ```
   kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/alpha/?ref=master"
```
   -  Follow the [volume resize](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/examples/kubernetes/resizing#volume-resizing) example.
   -  The EBS volume will not be resized and you can see the error messages same as the mentioned above.

**Anything else we need to know?**:
- On reviewing the [clusterrolebinding yaml files](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/deploy/kubernetes/overlays/alpha) could see a commit made 28 days ago and changes performed by replacing the clusterrolebinding RBAC subjects of service account namespace to `default` from `kube-system` [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/6c6a3c9a55b26794ec27fd5f8f2d94237de76f42#diff-eff4ef07242ae1a6f34870736c28b4530653acc4cc502a2b3f08f508fa4291ef). 

**Environment**
- Kubernetes version (use `kubectl version`): Client Version: v1.19.6-eks-49a6c0
- Driver version: 
```
      image: k8s.gcr.io/sig-storage/csi-resizer:v1.0.0
      image: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
      image: k8s.gcr.io/provider-aws/aws-ebs-csi-driver:latest
      image: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.1
      image: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
      image: k8s.gcr.io/sig-storage/livenessprobe:v2.2.0
      image: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
```

**Comment by AndyXiangLi** [comment]
/close
Thank you for bring this up! Recent [PR](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/879) fixed this issue, I will close this.
