### ISSUE TITLE
add e2e tests for multi-arch support

### ISSUE THREAD

**Issue by vdhanan** [kubernetes-sigs/aws-ebs-csi-driver#875]
**Is your feature request related to a problem?/Why is this needed**
at the moment we only run e2e tests on x86 architecture. we should ensure that the tests also pass on arm.

/feature

**Describe the solution you'd like in detail**
create arm nodes via kops, execute the existing tests on these nodes (assuming test containers support multi-arch)

**Comment by wongma7** [comment]
keep this open ,but i created a table a while back https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/696 just to visualize we need arm equivalent of every test suite
