### ISSUE TITLE
Support for Velero

### ISSUE THREAD

**Issue by chaospuppy** [kubernetes-sigs/aws-ebs-csi-driver#880]
**Is your feature request related to a problem?/Why is this needed**
Velero currently cannot create snapshots of EBS volumes provisioned by the `ebs.csi.aws.com` provisioner due to a missing (or more accurately, renamed) field in the created PV's `spec.csi` map.

/feature

**Describe the solution you'd like in detail**
Adding a `spec.csi.volumeID` to the PV spec generated by the `ebs.csi.aws.com` provisioner so that Velero can properly ingest the volumeID
 [here](https://github.com/vmware-tanzu/velero/blob/4d173d725c3f20a0772e189249f385641d464a16/pkg/plugin/framework/volume_snapshotter_client.go#L174) would solve the issue.  The added `spec.ElasticBlockStore.volumeID` would contain a value in the format of `aws://<aws-region-and-zone>/<volume-id>` e.g. `aws://us-west-1b/vol-087f5dbbcc4f1000d`.  This is slightly redundant given the existing `spec.csi.volumeHandle` attribute that's already in place, but this seems like a lightweight change to make.

**Describe alternatives you've considered**
I have also [requested](https://github.com/vmware-tanzu/velero/issues/3341#issuecomment-837536617) an update on Velero's end to see if they could accommodate an update, but I think making this change from the awsebscsiprovisioner side would be simpler.

**Additional context**
Not having this attribute present request in the following Velero logs:

```
time="2021-05-10T23:19:28Z" level=info msg="Executing takePVSnapshot" backup=velero/test logSource="pkg/backup/item_backupper.go:405" name=pvc-e503ba8c-89db-45b1-bd5a-0ee4f08a53bf namespace= resource=persistentvolumes
time="2021-05-10T23:19:28Z" level=info msg="label \"topology.kubernetes.io/zone\" is not present on PersistentVolume, checking deprecated label..." backup=velero/test logSource="pkg/backup/item_backupper.go:432" name=pvc-e503ba8c-89db-45b1-bd5a-0ee4f08a53bf namespace= persistentVolume=pvc-e503ba8c-89db-45b1-bd5a-0ee4f08a53bf resource=persistentvolumes
time="2021-05-10T23:19:28Z" level=info msg="label \"failure-domain.beta.kubernetes.io/zone\" is not present on PersistentVolume" backup=velero/test logSource="pkg/backup/item_backupper.go:435" name=pvc-e503ba8c-89db-45b1-bd5a-0ee4f08a53bf namespace= persistentVolume=pvc-e503ba8c-89db-45b1-bd5a-0ee4f08a53bf resource=persistentvolumes
time="2021-05-10T23:19:28Z" level=info msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/test logSource="pkg/backup/item_backupper.go:458" name=pvc-e503ba8c-89db-45b1-bd5a-0ee4f08a53bf namespace= persistentVolume=pvc-e503ba8c-89db-45b1-bd5a-0ee4f08a53bf resource=persistentvolumes volumeSnapshotLocation=default
time="2021-05-10T23:19:28Z" level=info msg="Persistent volume is not a supported volume type for snapshots, skipping." backup=velero/test logSource="pkg/backup/item_backupper.go:469" name=pvc-e503ba8c-89db-45b1-bd5a-0ee4f08a53bf namespace= persistentVolume=pvc-e503ba8c-89db-45b1-bd5a-0ee4f08a53bf resource=persistentvolumes
```

with the result being no snapshots created by Velero.  For further context into exactly where the issue lies on the Velero side, please see the comment on the Velero issue I linked above.

For comparison, this is what the relevant parts of a standard `kubernetes.io/aws-ebs` provisioner-created PersistentVolume spec looks like:

```yaml
spec:
  awsElasticBlockStore:
    volumeID: aws://us-gov-west-1b/vol-087f5dbbcc4f1000d
```

I also notice that the map names differ between the `ebs.csi.aws.com` provisioner and the `kubernetes.io/aws-ebs` provisioner differ (one is `spec.csi` and the other is `spec.awsElasticBlockStore`.

I'm happy to be schooled as to why these specs are different and also why my request is totally off-base :).

**Comment by chaospuppy** [comment]
Closing this because the [csi plugin](https://github.com/vmware-tanzu/velero-plugin-for-csi) exists, so my issue it totally resolved already.

**Comment by RomanGrekov** [comment]
Hi @chaospuppy. I have the same problem. I am trying to use Velero to backup EKS cluster volumes based on ebs.csi.aws.com and it failed with the same errors you got. As I understand you did manage somehow to do it with csi plugin. But I can't find any information how can to do it. I installed Velero helm chart with such config:
`configuration:
  provider: aws
  backupStorageLocation:
    bucket: {{ bucket }}
  volumeSnapshotLocation:
    name: aws
    config:
      region: "default"
  features: EnableCSI
credentials:
  useSecret: false
initContainers:
- name: velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:v{{ velero_init_version }}
  volumeMounts:
  - mountPath: /target
    name: plugins
- name: velero-plugin-for-csi
  image: velero/velero-plugin-for-csi:v0.2.0
  imagePullPolicy: IfNotPresent
  volumeMounts:
    - mountPath: /target
      name: plugins
serviceAccount:
  server:
    create: true
    name: {{ service_account }}
    annotations:
      eks.amazonaws.com/role-arn: "{{ velero_role_arn }}"
`
but it doesn't work.
I getting error: "The 'EnableCSI' feature flag was specified, but CSI API group [snapshot.storage.k8s.io/v1beta1] was not found".
Could you tell me how did you fix it?

**Comment by dsu-igeek** [comment]
This was fixed in velero-plugin-for aws (https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/93).  CSI support is still beta in Velero.
