### ISSUE TITLE
Please allow me to set other fields in custom storage class in the helm chart

### ISSUE THREAD

**Issue by kli-abine** [kubernetes-sigs/aws-ebs-csi-driver#885]
Please allow me to set other fields in custom storage class in the helm chart

**Is your feature request related to a problem?/Why is this needed**

I have a use case where custom storage class will be created by helm chart. I need to set the allowVolumeExpansion and ReclaimPolicy fields on the storage class.
In the helm chart.

/feature

**Describe the solution you'd like in detail**

Allow me to set `allowVolumeExpansion` and `reclaimPolicy` fields in custom storage classes created by the helm chart.

**Describe alternatives you've considered**

Users can modify the storage class after helm install, but not a good experience.

**Comment by krmichel** [comment]
/remove-kind feature
/kind support

You can already do this.  The [example in the charts values file](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L177) already shows how to set the `reclaimPolicy` and the `allowVolumeExpansion` can be set the same way.

**Comment by kli-abine** [comment]
it's working, thanks!
