### ISSUE TITLE
CSIDriver v1 is not available in 1.17

### ISSUE THREAD

**Issue by arcivanov** [kubernetes-sigs/aws-ebs-csi-driver#887]
/kind bug

The chart indicates >=1.17 compatibility. And yet in 1.17 in storage v1 CSIDriver is not available.
Either discontinue support for 1.17 and bump the chart to 1.18 minimum or bust down  resource version to v1beta1

The incoming fix will do the latter.

**Comment by wd** [comment]
I was just about to post the same issue. Can't deploy v1.0.0 to kubernetes 1.17. 
```
Error: unable to recognize "": no matches for kind "CSIDriver" in version "storage.k8s.io/v1"
```
