### ISSUE TITLE
Avoid using root user in the csi-controller image

### ISSUE THREAD

**Issue by xposix** [kubernetes-sigs/aws-ebs-csi-driver#892]
We are deploying the EBS CSI driver in a very secure environment so we need to do a scan of every image that goes into the environment. 

We saw that the ebs-csi-controller image uses the root user inside and that doesn't go well with our security rules. 

Do you guys know if this is something done like that by design? or it's just something that can be improved?

**Comment by AndyXiangLi** [comment]
Hi @xposix, what do you mean use root user inside, can you provide more info? You can setup driver permission [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver#set-up-driver-permission) Thanks!

**Comment by xposix** [comment]
sorry, the user inside the OS in the container is root:

```
xposix@myhost:> kubectl exec -it ebs-csi-controller-7ccf67cbbc-jdxqx -- /bin/bash
Defaulting container name to ebs-plugin.
Use 'kubectl describe pod/ebs-csi-controller-7ccf67cbbc-jdxqx -n kube-system' to see all of the containers in this pod.
bash-4.2# id
uid=0(root) gid=0(root) groups=0(root)
bash-4.2#
```
Security best practises advise to avoid this scenario and encourage using any other OS users with uid different to 0.

Does it make sense?

**Comment by wongma7** [comment]
can you try changing  securityContext: runAsUser: of the controller? The controller should not need to be root, you are right. But the node does. They are based on the same image, so unless we start distributing different images, the image exec user will be root

**Comment by xposix** [comment]
Thanks for the information.
Closing ticket.
