### ISSUE TITLE
NodeUnpublishVolume doesn't appear to flush the volume cache

### ISSUE THREAD

**Issue by huffmanca** [kubernetes-sigs/aws-ebs-csi-driver#893]
/kind bug

**What happened?**
We're seeing repeated failures in the snapshot tests when using the AWS EBS CSI Driver. See https://github.com/kubernetes/kubernetes/issues/101279 for full details.

However, even after merging https://github.com/kubernetes/kubernetes/pull/101280 it seems that these tests continue to fail. Any of the following (inside of k8s/k8s) resolves the issue:

* Adding a `sync` to the first exec where we create the file initially.
* Waiting for 5 or more seconds before leaving the `init` function
* Waiting for VolumeAttachment instances to be removed.

It seems that even after unmounting the volume in NodeUnpublishVolume the cache isn't guaranteed to be flushed. Is this a known limitation of AWS EBS volumes?

**What you expected to happen?**
When NodeUnpublishVolume completes the volume cache is flushed.

**How to reproduce it (as minimally and precisely as possible)?**
Run any of the following tests:
* External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic Snapshot (delete policy)] snapshottable[Feature:VolumeSnapshotDataSource] volume snapshot controller  should check snapshot fields, check restore correctly works after modifying source data, check deletion
* External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic Snapshot (retain policy)] snapshottable[Feature:VolumeSnapshotDataSource] volume snapshot controller  should check snapshot fields, check restore correctly works after modifying source data, check deletion
* External Storage [Driver: ebs.csi.aws.com] [Testpattern: Pre-provisioned Snapshot (delete policy)] snapshottable[Feature:VolumeSnapshotDataSource] volume snapshot controller  should check snapshot fields, check restore correctly works after modifying source data, check deletion
* External Storage [Driver: ebs.csi.aws.com] [Testpattern: Pre-provisioned Snapshot (retain policy)] snapshottable[Feature:VolumeSnapshotDataSource] volume snapshot controller  should check snapshot fields, check restore correctly works after modifying source data, check deletion

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.21
- Driver version: 1.0.0

**Comment by huffmanca** [comment]
@AndyXiangLi and @vdhanan ,

I spoke to @wongma7 about this issue, and he mentioned that either of you may be able to provide a bit more information on why this may be occurring. Tagging you here.

**Comment by jsafrane** [comment]
I think it's `NodeUnstage` that does not flush the caches - `NodeUnpublish` just removes a bind mount. When `NodeUnstage` finishes (i.e. all volume mounts are unmounted), we expect all caches are written to the backend volume and user / test can safely take a snapshot of the volume, expecting to have all data in the snapshot.

**Comment by jsafrane** [comment]
Just an idea: would it help if the driver called `blockdev --flushbufs <device>` on NodeUnstage? How else we can we ensure that data are really written to the backend volume?

**Comment by wongma7** [comment]
btw how come our CI is not catching this, is it new to 1.21?

**Comment by msau42** [comment]
What puzzles me is `unmount` should flush the filesystem before returning success.

**Comment by wongma7** [comment]
is the nodesInUse check working, https://github.com/kubernetes/kubernetes/blame/82d8d08c7871d2a3efbe532da284a211c2b985dd/test/e2e/storage/testsuites/snapshottable.go#L194, I don't think the volume name there will contain the PV name. https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/volume/csi/csi_plugin.go#L324 I will double check myself but I'm just throwing this out there in case you have the repro setup still around.

**Comment by wongma7** [comment]
volumesInUse looks like this:

```
  volumesInUse:
  - kubernetes.io/csi/ebs.csi.aws.com^vol-0791440a47bbb12c0
```

so I think/hope it's an easy fix in the test to search for volumeHandle instead of pv.Name

**Comment by wongma7** [comment]
one issue, I assume the test is not CSI specific and in-tree plugins have their own way of coming up with volumeName...

**Comment by huffmanca** [comment]
It looks like @wongma7 is correct, and I foolishly assumed that we were using pv.Name regardless of source. With CSI volumes we're using the volumeHandle, meaning that we're not guaranteed to wait for NodeUnpublish to be called in this case. It seems that simply adding a couple more steps was enough to let NodeUnpublish complete (over the course of my tests it seems this typically completes in 2-4 seconds).

I'll update my kubernetes PR.
