### ISSUE TITLE
Create volumes with one topology label, not both

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-ebs-csi-driver#899]
/kind bug

**What happened?** https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/driver/controller.go#L658 Details: https://github.com/kubernetes/kubernetes/issues/102248

The expressions are ANDED, meaning a provisioned PV will only land on nodes that have BOTH labels. this was not the intention, we want it to be able to land on nodes with one or the other.

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by jsafrane** [comment]
> we want it to be able to land on nodes with one or the other.

Why? When the CSI driver returns only `topology.ebs.csi.aws.com/zone` label for a volume, we can be sure that a pod that uses the CSI volume will land on a node that has both the CSI driver (i.e. it has the label) and is in the right zone.

Translation we use for CSI migration will make sure that the label is translated from CSI `topology.ebs.csi.aws.com/zone` to in-tree `topology.kubernetes.io/zone` & `topology.kubernetes.io/region` and the other way around. IMO the driver should not worry about the CSI migration, as long as there is 1:1 mapping between in-tree and csi labels.

**Comment by wongma7** [comment]
I thought the NodeGetInfo response for topology labels doesn't get translated, so if we only return topology.ebs.csi.aws.com/zone then translated PVs with topology.kubernetes.io/zone won't get scheduled . That's why I thought we need to add both labels in NodeGetInfo response. Let me verify. (BTW we are lacking a migration topology e2e, I'll create issue/add it soon).

I agree with you that driver should not worry about the label. But we weren't originally thinking about topology.ebs.csi.aws.com/zone being a 1:1 mapping to topology.kubernetes.io/zone, rather we were thinking that we should try to use topology.kubernetes.io/zone as a replacement of topology.ebs.csi.aws.com/zone. Since there already exists PVs out there with topology.ebs.csi.aws.com/zone, I don't think we can ever remove it without breaking change, but IIRC we wanted to at least deprecate it and someday remove it.

cc @ayberk (he is out right now but knows more than me,i'm throwing him under the bus.)

**Comment by wongma7** [comment]
@himanshu-kun

The fallback he is referring to in that comment is in the driver controller when it is deciding in which zone to create a volume, but the scheduler doesn't have such a fallback, the scheduler is doing the AND and potentially blocking PVs/Pods from getting scheduled

this issue is fixed by https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/912 released in 1.1.0, from tha tversion on PVs and CSINode will have topology.ebs.csi.aws.com/zone topology label
