### ISSUE TITLE
Consider releasing kustomize archives

### ISSUE THREAD

**Issue by akhilles** [kubernetes-sigs/aws-ebs-csi-driver#909]
**Is your feature request related to a problem?/Why is this needed**
`kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-0.10"` takes a long time.

/feature

**Describe the solution you'd like in detail**
Publish zip, tarball archives with just the `deploy/` files.

**Describe alternatives you've considered**
Publish a tag with just the `deploy/` files.

**Additional context**
The main reason for `kubectl apply -k` being slow is it's downloading ~68 MB of files. The `deploy/` dir can be just a 44 KB archive instead.

**Comment by wongma7** [comment]
good idea, after we started checking in vendor dir the repo size has ballooned.

**Comment by nirmalaagash** [comment]
@wongma7 What are your thoughts on ignoring the vendor folder in upcoming commits?

**Comment by wongma7** [comment]
I think we should keep vendor dir checked in because in past CI has been flaky/slow to download dependencies but a github action could prepare a kustomize archive w/o vendor dir
