### ISSUE TITLE
e2e " volume snapshot controller should check snapshot fields, check restore correctly works after modifying source data, check deletion" flakes

### ISSUE THREAD

**Issue by olemarkus** [kubernetes-sigs/aws-ebs-csi-driver#911]
/kind bug

**What happened?**

kOps started running the aws cbs csi driver e2e suite and shows some tests are flaking.

All of them are variants of "volume snapshot controller should check snapshot fields, check restore correctly works after modifying source data, check deletion".

See https://k8s-testgrid.appspot.com/kops-misc#kops-scenario-aws-ebs-csi-driver
We were wondering if these were known flakes and should be filtered or if this is worth looking into.

I am aware these are tagged with Feature, but we still wanted to run tests related to the snapshot controller as well.

Note that these run against v1.0.0 and not master.

**Environment**
- Kubernetes version (use `kubectl version`): 1.21
- Driver version: v1.0.0

**Comment by wongma7** [comment]
it should be fixed by a change in the test https://github.com/kubernetes/kubernetes/pull/102021

**Comment by olemarkus** [comment]
Thanks. We'll just monitor the situation then.
