### ISSUE TITLE
Missing enableVolumeScheduling and enableVolumeResizing?

### ISSUE THREAD

**Issue by tanvp112** [kubernetes-sigs/aws-ebs-csi-driver#934]
/kind bug

**What happened?**

Latest release helm-chart-aws-ebs-csi-driver-1.2.2 has the enableVolumeScheduling and enableVolumeResizing removed from values.yaml and there is no documentation about it. Do we still need to --set enableVolumeScheduling=true while installing the driver to support dynamic provisioning? Same question goes to enableVolumeResizing, does this affect allowVolumeExpansion?

**What you expected to happen?**

Kindly clarify if this is a bug in the helm chart or intended changes.

**Environment**

EKS

- Driver version:

helm-chart-aws-ebs-csi-driver-1.2.2

**Comment by krmichel** [comment]
Those features have moved to stable and are just enabled now.

**Comment by tanvp112** [comment]
Noted with thanks.
