### ISSUE TITLE
Track volumes provisioned by the in-tree EBS plugin

### ISSUE THREAD

**Issue by nicholasmhughes** [kubernetes-sigs/aws-ebs-csi-driver#939]
**Is your feature request related to a problem? Please describe.**
To my knowledge, [EKS not yet supporting the CSIMigrationAWS feature gate](https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/kubernetes-versions.md#kubernetes-117) (I'm happy to be proven wrong here). Due to this fact, I can't perform a full migration from the in-tree EBS plugin to the EBS CSI Driver.

Since some older volumes were created by the in-tree provisioner and new volumes are being created by the CSI provisioner, we're finding that the Kubernetes scheduler is unaware when a node has reached its attachment limit.

**Describe the solution you'd like in detail**
If the CSI Driver tracked the in-tree provisioned volumes, even just the quantity of them, then it could provide an actual count of attached volumes via CSINodeInfo to the scheduler and prevent scheduling on saturated nodes.

**Describe alternatives you've considered**
I'm unaware of any way to force this behavior in EKS. If there is a way to force the CSI Driver to take full ownership of in-tree provisioned volumes through manual tag and/or annotation modifications, then I could perform a manual migration without needing the CSIMigrationAWS feature gate.

**Additional context**
N/A

**Comment by froblesmartin** [comment]
As it is said here: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/480#issuecomment-845588464, EKS won't enable it until, at least, it becomes enabled by default in K8s.

**Comment by nicholasmhughes** [comment]
this will probably be OBE from a 1.22 release of EKS before anyone implements this...
/close
