### ISSUE TITLE
Helm "mustAppend" not defined when upgrading helm chart to v1.1.x or 1.2.x from v1.0.3

### ISSUE THREAD

**Issue by TheBaus** [kubernetes-sigs/aws-ebs-csi-driver#943]
/kind bug

**What happened?**
Trying to upgrade helm chart to version 1.1.0 from version 1.0.3, Helm then throws a mustAppend error:
`Error: parse error in "aws-ebs-csi-driver/templates/controller.yaml": template: aws-ebs-csi-driver/templates/controller.yaml:54: function "mustAppend" not defined`

**What you expected to happen?**
Helm chart to upgrade to new targetRevision with no problems.

**How to reproduce it (as minimally and precisely as possible)?**
Install helm chart on any version below 1.1.x then try upgrade to v1.1.0

**Anything else we need to know?**:
Helm is deployed using ArgoCD on EKS

**Environment**
- Kubernetes version (use `kubectl version`): 
`Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T10:03:32Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}`

- Driver version:
1.0.3

**Comment by krmichel** [comment]
What version of helm is being used?

**Comment by TheBaus** [comment]
Ah sorry all, I only thought of Argo's version of Helm being the issue. 

Upgraded Argo from v1.8.4 to v2.0.2 and now the upgrade proceeds. 

Apologies for this and closing.

**Comment by TheBaus** [comment]
> What version of helm is being used?

Thanks for asking so quick @krmichel.
