### ISSUE TITLE
Provide an example of "parameters" usage in docs or tests

### ISSUE THREAD

**Issue by longrunningprocess** [kubernetes-sigs/aws-ebs-csi-driver#956]
**Is your feature request related to a problem?/Why is this needed**
I was hoping to find an example of a recurring schedule for snapshots in the https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/examples/kubernetes/snapshot/specs/classes/snapshotclass.yaml file but did not see a `"parameters"` implementation there.

**Describe the solution you'd like in detail**
I'd like to to see an example of how to establish a recurring schedule for snapshots similar to longhorn's `StorageClass` example: https://longhorn.io/docs/1.1.0/snapshots-and-backups/scheduling-backups-and-snapshots/#set-up-recurring-jobs-using-a-storageclass

**Describe alternatives you've considered**
n/a

**Additional context**
I'm just looking for the full list of options to use for this driver.

Thank you

**Comment by wongma7** [comment]
Currently the driver doesn't accept any SnapshotClass parameters.

The EBS API doesn't provide us an easy/first-class way to implement support for a parameter equivalent to longhorn's `recurringSnapshot`.

I don't know how longhorn implements their snapshotting but for EBS, under the hood our implementation of "CreateSnapshot" is  simple, the driver just calls EBS API's CreateSnapshot with the provided volume ID. Setting up a schedule would need to involve other non-EBS AWS APIs like CloudWatch https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/TakeScheduledSnapshot.html and that is out of scope of the driver.

There might be a kubernetes-native solution out there that knows how to periodically create a PVC to trigger a snapshot, which could achieve what you want, without requiring any support from the EBS driver.

**Comment by longrunningprocess** [comment]
gotcha, that's sort of what I was afraid might be the case.  I was hoping the idea of establishing a schedule for these was an abstract k8s concept that would be implemented be each platform but what you said confirms that recurring schedules is going to depend on the runtime, thanks again!
