### ISSUE TITLE
Configurable topology labels

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-ebs-csi-driver#962]
/kind bug

**What happened?**

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/729 <- autoscaler reads the in-tree topology labels
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/899 <- csi migration translation reads in-tree topology labels and our ebs-specific topology label  and translates both to normal topology label which results in PV having duplicate labels

to solve 899 we started to only put the ebs-specific topology label on csinode and on PVs.
but that breaks 729 in case migration is off which expects to read in-tree topology labels.

Moreover, if there exist PVs with both labels and users upgrade to version with only one label, then scheduler won't be able to schedule PVs with both labels to nodes with just one label, we may already have users who ran into this bug

To fix, we might need to default to having both labels on CSINode again, but still just have one label on PV. The csi translation duplicate label issue will be fixed ,but it'ps unclear at this time whether we should be using the in-tree topology label in CSINode or not, or if that label being kubernetes-specific should be reserved for in-tree kubernetes usage, etc, or if topology labels should be configurable so that by default we include the kubernetes-specific label but (totally hypothetical) non-kubernetes users can omit it.

<placeholder link to upstream issue when xists>

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by jbg** [comment]
The current status is that nodes have both labels but PVs select only on the old non-standardised label (`topology.ebs.csi.aws.com/zone`). This means scale-up-from-zero with cluster-autoscaler requires manually tagging ASGs if EBS volumes are used. Switching to the new label would make this work without the manual tagging.

I have written a patch to provide a command-line option, disabled by default (as I'm not sure if enabling it by default may break some setups), to make PVs select on the standardised label (`topology.kubernetes.io/zone`) instead. I'm testing it at the moment and am happy to send a PR if this apprach is acceptable.

Can this issue be re-opened?

**Comment by ConnorJC3** [comment]
/close

The original reason for customization of the topology labels (using the k8s standardized default) is no longer necessary as of `v1.33.0` - the driver now uses the standard label for all new volumes (see #729 for more info). We have decided not to allow other customization at this time due to the significant footgun it presents.

If you have a specific need for customization other than using the standardized label, please open a new issue so that it can be evaluated.
