### ISSUE TITLE
Driver app status and ebs-claim 'pending' indefinitely 

### ISSUE THREAD

**Issue by riturajx** [kubernetes-sigs/aws-ebs-csi-driver#963]
/kind bug

**What happened?**
I followed the steps on this page: [https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html)

**What you expected to happen?**
After running the command 'kubectl get pods', I expected to see STATUS as 'running'. However, it remains 'pending' indefinitely (waited 4+ hours).

**How to reproduce it (as minimally and precisely as possible)?**
Exactly followed: `https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html`

**Anything else we need to know?**:
On running `kubectl get events`, I get
`status code: 403, request id: xyz         Warning   ProvisioningFailed     persistentvolumeclaim/ebs-claim   failed to provision volume with StorageClass "ebs-sc": rpc error: code = Internal desc = Could not create volume "pvc-xyz": could not create volume in EC2: UnauthorizedOperation: You are not authorized to perform this operation.`

In addition, on decoding the encrypted error messaage it seems that ec2:CreateVolume policy is not attached to the concerned IAM role.

**Environment**
- Kubernetes version (use `kubectl version`):
v1.20

- Driver version:
aws-ebs-csi-driver:v1.1.0

**Comment by KqLLL** [comment]
I have the same problem.

**Comment by riturajx** [comment]
Attaching the relevant policies solved the issue.
