### ISSUE TITLE
EFS/FSx helm chart value inconsistencies

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-ebs-csi-driver#974]
/kind cleanup

I would like all AWS CSI maintained helm charts to be consistent. I am currently working on the FSx helm chart. Most inconsistencies require breaking changes (must release a major helm chart version) to fix. We recently released v2 of the EBS helm chart and it fixed a lot of inconsistencies but some remain that I didn't catch. I will use this issue to track inconsistencies that can be fixed in next major version bump. (Inconsistencies are bound to happen despite the overlap in maintainers for both repos because it's easy to accept/make contributions... and a bit tedious to cross check every change with the charts in 2-3 different repos to ensure consistency, but I'll try to do that!)

- EBS has controller.replicaCount https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L86, EFS has top-level replicaCount https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml#L8
  - Resolution: prefer controller.replicaCount
  - Breaking change? yes, need to deprecate the top-level one
- file names are inconsistent (e.g. EBS node.yaml https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/node.yaml vs EFS node-daemonset.yaml https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/charts/aws-efs-csi-driver/templates)
  - Resolution: prefer EFS more detailed naming that includes object Kind
  - Breaking change? no 
- EBS sidecars.provisioner https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L11 vs EFS sidecar.csiProvisioner https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml#L28
  - Resolution: prefer sidecars.provisioner
  - Breaking change? yes, need to deprecate sidecar.csiProvisioner
- Order of stuff like imagePullSecrets is different for EBS https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/controller.yaml#L243 vs EFS https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/templates/controller-deployment.yaml#L28
  - Resolution: pick whatever, order doesn't matter as long as it's consistent so that reviewing is easier. 
  - Breaking change? no
- EBS has readinessProbe https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/controller.yaml#L125, EFS not
  - Resolution: prefer having readinessProbe
  - Breaking change? no
- EFS still has beta node OS label https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/templates/node-daemonset.yaml#L39
  - Resolution: use GA one
  - Breaking change? no
- EBS controller and EFS node have fargate anti affinity
  - Resolution: give everything fargate anti affinity
  - Breaking change? no
- EFS sets app.kubernetes.io/name and app.kubernetes.io/instance explicitly https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/templates/node-daemonset.yaml#L12, EBS uses {{- include "aws-ebs-csi-driver.labels" . | nindent 8 }}
  - Resolution: prefer include statement 
  - Breaking change? no
- EFS calls registrar container csi-driver-registrar https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/templates/node-daemonset.yaml#L102, EBS node-driver-registrar. https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/node.yaml#L105 
  - Resolution: prefer node-driver-registrar
  - Breaking change? no

**Comment by krmichel** [comment]
@wongma7 Let me know if you need any help with this and I will do what I can.

**Comment by vdhanan** [comment]
same, happy to help

**Comment by wongma7** [comment]
reviews on the fsx chart are welcome ;) https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/194/files

I didn't mark anywhere whether a change would be breaking or not, that would make it easier for people to help out since they don't need to worry about chart versioning if they submit a nonbreaking PR change.

**Comment by wongma7** [comment]
/lifecycle frozen

still relevant

**Comment by ConnorJC3** [comment]
/close

(closing out old issues)

At this point, the EBS CSI Driver has too many customers to modify its Helm chart for the sake of consistency. Additionally, it is the most developed AWS-related CSI Driver, so any consistency-related changes should happen on the FSx/EFS side.
