### ISSUE TITLE
Helm chart needs an option to disable Windows support

### ISSUE THREAD

**Issue by tyrken** [kubernetes-sigs/aws-ebs-csi-driver#975]
Currently the helm chart **always** deploys a Windows DaemonSet `ebs-csi-node-windows` with node selector `kubernetes.io/os=windows`.

This is perfectly valid & does nothing on our linux-only EKS cluster, but is annoying clutter & we never intend to add Windows nodes.

Would you accept a PR to tidy things up by introducing a `{{- if .Values.node.windowsEnabled }}` statement around the whole of the unwanted https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/node-windows.yaml ?

Happy for it to default to `true` though I suspect Windows clusters are pretty rare.

**Comment by wongma7** [comment]
Yes I would accept it, and I wouldn't mind defaulting it false either, EKS+Windows is indeed  pretty rare. Of course you can delete the daemonset but an upgrade would install it again so I understand the annoyance

**Comment by tyrken** [comment]
@nirmalaagash happy for you to go ahead (the CLA is holding me up for now), but thinking `enableWindows` might be more in keeping with the boolean convention this project used in the past, compared to what I suggested above.
