### ISSUE TITLE
Implement NodeGetVolumeStat

### ISSUE THREAD

**Issue by akaroth** [kubernetes-sigs/aws-ebs-csi-driver#983]
**Is your feature request related to a problem?/Why is this needed**
Our project deals with a lot of statefulset and has underlying PVC's which needs to be upgraded for volume . To automate this process there are dynamic PVC resizer's available , however they depend on the ```NodeGetVolumeStat``` function to get the stats from the PVC .
/feature

**Describe the solution you'd like in detail**

I would like the resizer to work utilizing the function ```NodeGetVolumeStat```

**Describe alternatives you've considered**

**Additional context**

**Comment by AndyXiangLi** [comment]
Hi @akaroth, what version of driver are you using? We already have NodeGetVolumeStat implemented in version 0.9.0
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/release-0.9/pkg/driver/node.go#L387
