### ISSUE TITLE
CSI driver unable to provision volume with instance profile.

### ISSUE THREAD

**Issue by khushboo121** [kubernetes-sigs/aws-ebs-csi-driver#984]
/kind bug
Issue started happing once we move to aws.ebs.csi driver from v0.8.1 to v0.10.1.
eks version: v1.18.9

```
Events:
  Type     Reason                Age                   From                                                                                      Message
  ----     ------                ----                  ----                                                                                      -------
  Normal   WaitForFirstConsumer  2m1s (x26 over 8m1s)  persistentvolume-controller                                                               waiting for first consumer to be created before binding
  Normal   Provisioning          20s (x7 over 83s)     ebs.csi.aws.com_ebs-csi-controller-67cb5bb848-4t4h9_9db1a096-d0d7-43de-9801-456c9614ceb9  External provisioner is provisioning volume for claim "default/claim1"
  Warning  ProvisioningFailed    20s (x7 over 83s)     ebs.csi.aws.com_ebs-csi-controller-67cb5bb848-4t4h9_9db1a096-d0d7-43de-9801-456c9614ceb9  failed to provision volume with StorageClass "csi-sc": rpc error: code = Internal desc = NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EmptyEC2RoleList: empty EC2 Role list
```

Created the role  for required permission to. created volume and attached to ec2-instance as instance profile, with 0.8.1 version everything is working fine driver can create both static and dynamic volume but when we move to version 0.10.1 it starting giving the above error.

Do I need to add any addition permission.

IAM policy used:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:AttachVolume",
                "ec2:CreateSnapshot",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:DeleteSnapshot",
                "ec2:DeleteTags",
                "ec2:DeleteVolume",
                "ec2:DescribeAvailabilityZones",
                "ec2:DescribeInstances",
                "ec2:DescribeSnapshots",
                "ec2:DescribeTags",
                "ec2:DescribeVolumes",
                "ec2:DescribeVolumesModifications",
                "ec2:DetachVolume",
                "ec2:ModifyVolume"
            ],
            "Resource": "*"
        }
    ]
}
```

Installed aws.ebs.csi driver using terraform with helm:
```
resource "helm_release" "aws-ebs-csi-driver" {
  name       = "aws-ebs-csi-driver"
  repository = "https://kubernetes-sigs.github.io/aws-ebs-csi-driver"
  chart      = "aws-ebs-csi-driver"
  namespace  = "kube-system"
  version = "0.10.1"

  values = [
    <<EOF
enableVolumeScheduling: true
enableVolumeResizing: true
enableVolumeSnapshot: true
EOF
  ]
}```

**Comment by AndyXiangLi** [comment]
@khushboo121 Since you are on EKS, can you try this [page](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html) to setup trust-policy for the cluster?

**Comment by Zhenye-Na** [comment]
> @khushboo121 Since you are on EKS, can you try this [page](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html) to setup trust-policy for the cluster?

Sorry to revive this thread, but does this mean that EBS CSI Driver with Instance Profile also need OIDC Identity in the Trust Policy ?

**Comment by Zhenye-Na** [comment]
> > @khushboo121 Since you are on EKS, can you try this [page](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html) to setup trust-policy for the cluster?
> 
> Sorry to make update in this thread, but does this mean that EBS CSI Driver with Instance Profile also need OIDC Identity in the Trust Policy ?

Answering my own question here. Got experiment results from the [issue #1468](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1468) I created.

It turns out that if you wanna use InstanceProfile as the configuration for EBS CSi Driver permission, we should select the IAM role to inherit from node, instead of passing InstanceProfile again. At least this solved my use case and I can see EBS Volume is created and claimed by one of my created pods

**Comment by protosam** [comment]
Thanks @Zhenye-Na. We updated from from 1.21 -> 1.22 and ran into issues with the EBS CSI.

1. We had to create a policy because the managed policy didn't have permissions for KMS. Example [here](https://gist.githubusercontent.com/protosam/7b66e328d837fa2a3fe1829df00774aa/raw/6012a56d69fc7d103ed709262b63eb906431f8ab/AmazonEBSCSIDriverPolicy.json).
2. We had to create a role referencing the policy, and [create a trust relationship for the master role to assume it](https://gist.githubusercontent.com/protosam/7b66e328d837fa2a3fe1829df00774aa/raw/6012a56d69fc7d103ed709262b63eb906431f8ab/RoleTrustRelationship.json).
3. Add an annotation to the pod template on the deployment: `kubectl -n kube-system edit deploy ebs-csi-controller`
```
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::<aws-acct-num>:role/ebs-csi-controller-role
```

**Comment by ismailyenigul** [comment]
```
error listing AWS instances: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
```
If you see the above error in ebs driver controller pod logs, It means your EKS worker AMI has IMDSv2 only enabled and requests without a token are not accepted.
In this case, you must create  role with  OIDC role as described here https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html and use this role in EBS driver setup.

You can check https://github.com/parjun8840/ekscsidriver/blob/main/README.md for details as well.
if your EKS worker AMI had IMDSv1 support, it would be enough to attach AmazonEBSCSIDriverPolicy to instance profile
